// Updated Patch 25.16 - 09/01/2025 12:58:59 PM CDT

export const itemsLite: ItemLite[] = [
  {
    id: 1001,
    name: 'Boots',
    cost: 300,
    maps: [11, 12, 21, 35],
    rank: 'Boots',
    stats: {
      flatMovespeed: 25,
    },
  },
  {
    id: 1004,
    name: 'Faerie Charm',
    cost: 200,
    maps: [11, 12, 21, 35],
    rank: 'Basic',
    stats: {
      manaRegen: 50,
    },
    tags: ['Mage', 'Support'],
  },
  {
    id: 1006,
    name: 'Rejuvenation Bead',
    cost: 300,
    maps: [11, 12, 21, 35],
    rank: 'Basic',
    stats: {
      healthRegen: 100,
    },
    tags: ['Tank'],
  },
  {
    id: 1011,
    name: 'Giant\'s Belt',
    cost: 900,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      health: 350,
    },
    tags: ['Fighter', 'Mage', 'Tank'],
  },
  {
    id: 1018,
    name: 'Cloak of Agility',
    cost: 600,
    maps: [11, 12, 21, 35],
    rank: 'Basic',
    stats: {
      criticalStrikeChance: 15,
    },
    tags: ['Marksman'],
  },
  {
    id: 1026,
    name: 'Blasting Wand',
    cost: 850,
    maps: [11, 12, 21, 35],
    rank: 'Basic',
    stats: {
      abilityPower: 45,
    },
    tags: ['Mage', 'Support'],
  },
  {
    id: 1027,
    name: 'Sapphire Crystal',
    aka: ['blue'],
    cost: 300,
    maps: [11, 12, 21, 35],
    rank: 'Basic',
    stats: {
      mana: 300,
    },
    tags: ['Mage', 'Tank'],
  },
  {
    id: 1028,
    name: 'Ruby Crystal',
    aka: ['red'],
    cost: 400,
    maps: [11, 12, 21, 35],
    rank: 'Basic',
    stats: {
      health: 150,
    },
    tags: ['Fighter', 'Marksman', 'Assassin', 'Mage', 'Tank', 'Support'],
  },
  {
    id: 1029,
    name: 'Cloth Armor',
    cost: 300,
    maps: [11, 12, 21, 35],
    rank: 'Basic',
    stats: {
      armor: 15,
    },
    tags: ['Fighter', 'Marksman', 'Assassin', 'Mage', 'Tank', 'Support'],
  },
  {
    id: 1031,
    name: 'Chain Vest',
    cost: 800,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      armor: 40,
    },
    tags: ['Fighter', 'Marksman', 'Assassin', 'Tank'],
  },
  {
    id: 1033,
    name: 'Null-Magic Mantle',
    cost: 400,
    maps: [11, 12, 21, 35],
    rank: 'Basic',
    stats: {
      magicResistance: 20,
    },
    tags: ['Fighter', 'Marksman', 'Assassin', 'Mage', 'Tank', 'Support'],
  },
  {
    id: 1036,
    name: 'Long Sword',
    cost: 350,
    maps: [11, 12, 21, 35],
    rank: 'Basic',
    stats: {
      attackDamage: 10,
    },
    tags: ['Fighter', 'Marksman', 'Assassin'],
  },
  {
    id: 1037,
    name: 'Pickaxe',
    cost: 875,
    maps: [11, 12, 21, 35],
    rank: 'Basic',
    stats: {
      attackDamage: 25,
    },
    tags: ['Fighter', 'Marksman', 'Assassin'],
  },
  {
    id: 1038,
    name: 'B. F. Sword',
    aka: ['bf'],
    cost: 1300,
    maps: [11, 12, 21, 35],
    rank: 'Basic',
    stats: {
      attackDamage: 40,
    },
    tags: ['Fighter', 'Marksman', 'Assassin'],
  },
  {
    id: 1042,
    name: 'Dagger',
    cost: 250,
    maps: [11, 12, 21, 35],
    rank: 'Basic',
    stats: {
      attackSpeed: 10,
    },
    tags: ['Fighter', 'Marksman', 'Assassin'],
  },
  {
    id: 1043,
    name: 'Recurve Bow',
    cost: 700,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      attackSpeed: 15,
    },
    tags: ['Fighter', 'Marksman', 'Onhit effects'],
  },
  {
    id: 1052,
    name: 'Amplifying Tome',
    aka: ['amptome', 'book'],
    cost: 400,
    maps: [11, 12, 21, 35],
    rank: 'Basic',
    stats: {
      abilityPower: 20,
    },
    tags: ['Mage', 'Support'],
  },
  {
    id: 1053,
    name: 'Vampiric Scepter',
    cost: 900,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      attackDamage: 15,
      lifesteal: 7,
    },
    tags: ['Fighter', 'Marksman', 'Assassin'],
  },
  {
    id: 1054,
    name: 'Doran\'s Shield',
    aka: ['dshield'],
    cost: 450,
    maps: [11, 12, 21],
    rank: 'Starter',
    stats: {
      health: 110,
      healthRegen: 4,
    },
    tags: ['Fighter', 'Marksman', 'Assassin', 'Mage', 'Tank', 'Onhit effects'],
  },
  {
    id: 1055,
    name: 'Doran\'s Blade',
    aka: ['dblade'],
    cost: 450,
    maps: [11, 12, 21],
    rank: 'Starter',
    stats: {
      attackDamage: 10,
      health: 80,
      lifesteal: 3,
    },
    tags: ['Fighter', 'Marksman', 'Assassin', 'Lifesteal vamp'],
  },
  {
    id: 1056,
    name: 'Doran\'s Ring',
    aka: ['dring'],
    cost: 400,
    maps: [11, 12, 21],
    rank: 'Starter',
    stats: {
      abilityPower: 18,
      health: 90,
    },
    tags: ['Mage', 'Mana and reg', 'Onhit effects'],
  },
  {
    id: 1057,
    name: 'Negatron Cloak',
    cost: 850,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      magicResistance: 45,
    },
    tags: ['Fighter', 'Tank', 'Support'],
  },
  {
    id: 1058,
    name: 'Needlessly Large Rod',
    aka: ['nlr'],
    cost: 1200,
    maps: [11, 12, 21, 35],
    rank: 'Basic',
    stats: {
      abilityPower: 65,
    },
    tags: ['Mage'],
  },
  {
    id: 1082,
    name: 'Dark Seal',
    aka: ['Noxian'],
    cost: 350,
    maps: [11],
    rank: 'Starter',
    stats: {
      abilityPower: 15,
      health: 50,
    },
    tags: ['Mage'],
  },
  {
    id: 1083,
    name: 'Cull',
    aka: ['dblade'],
    cost: 450,
    maps: [11],
    rank: 'Starter',
    stats: {
      attackDamage: 7,
    },
    tags: [
      'Fighter',
      'Marksman',
      'Assassin',
      'Lifesteal vamp',
      'Onhit effects',
    ],
  },
  {
    id: 1101,
    name: 'Scorchclaw Pup',
    aka: ['jungle'],
    cost: 450,
    maps: [11, 21],
    rank: 'Starter',
    stats: {},
    tags: ['Fighter', 'Marksman', 'Assassin', 'Mage', 'Tank', 'Lifesteal vamp'],
  },
  {
    id: 1102,
    name: 'Gustwalker Hatchling',
    aka: ['jungle'],
    cost: 450,
    maps: [11, 21],
    rank: 'Starter',
    stats: {},
    tags: ['Fighter', 'Marksman', 'Assassin', 'Mage', 'Tank', 'Lifesteal vamp'],
  },
  {
    id: 1103,
    name: 'Mosstomper Seedling',
    aka: ['jungle'],
    cost: 450,
    maps: [11, 21],
    rank: 'Starter',
    stats: {},
    tags: ['Fighter', 'Marksman', 'Assassin', 'Mage', 'Tank', 'Lifesteal vamp'],
  },
  {
    id: 1500,
    name: 'Ohmwrecker (Turret Item)',
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    purchasable: false,
    rank: 'Special',
    stats: {
      armorPenetration: 30,
    },
  },
  {
    id: 1501,
    name: 'Lane Swap Detector',
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    purchasable: false,
    rank: 'Special',
    stats: {},
  },
  {
    id: 1502,
    name: 'Reinforced Armor (Turret Item)',
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    purchasable: false,
    rank: 'Special',
    stats: {},
  },
  {
    id: 1503,
    name: 'Warden\'s Eye',
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    purchasable: false,
    rank: 'Special',
    stats: {},
  },
  {
    id: 1506,
    name: 'Base Turret Reinforced Armor (Turret Item)',
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    purchasable: false,
    rank: 'Special',
    stats: {},
  },
  {
    id: 1507,
    name: 'Overcharged',
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    purchasable: false,
    rank: 'Special',
    stats: {},
  },
  {
    id: 1508,
    name: 'Anti-Tower Socks',
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    purchasable: false,
    rank: 'Special',
    stats: {},
  },
  {
    id: 1509,
    name: 'Gusto',
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    purchasable: false,
    rank: 'Special',
    stats: {},
  },
  {
    id: 1510,
    name: 'Phreakish Gusto',
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    purchasable: false,
    rank: 'Special',
    stats: {},
  },
  {
    id: 1511,
    name: 'Super Mech Armor',
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    purchasable: false,
    rank: 'Special',
    stats: {},
  },
  {
    id: 1512,
    name: 'Super Mech Power Field',
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    purchasable: false,
    rank: 'Special',
    stats: {},
  },
  {
    id: 1515,
    name: 'Turret Plating',
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    purchasable: false,
    rank: 'Special',
    stats: {},
  },
  {
    id: 2003,
    name: 'Health Potion',
    aka: ['red'],
    cost: 50,
    maps: [11, 12, 21],
    rank: 'Consumable',
    stats: {},
    tags: ['Health and reg'],
  },
  {
    id: 2010,
    name: 'Total Biscuit of Everlasting Will',
    aka: ['kleptomancy'],
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    purchasable: false,
    rank: 'Special',
    stats: {},
  },
  {
    id: 2019,
    name: 'Steel Sigil',
    cost: 1100,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      armor: 30,
      attackDamage: 15,
    },
    tags: ['Fighter'],
  },
  {
    id: 2020,
    name: 'The Brutalizer',
    cost: 1337,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      abilityHaste: 10,
      attackDamage: 25,
      lethality: 5,
    },
    tags: ['Assassin'],
  },
  {
    id: 2021,
    name: 'Tunneler',
    cost: 1150,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      attackDamage: 15,
      health: 250,
    },
    tags: ['Fighter'],
  },
  {
    id: 2022,
    name: 'Glowing Mote',
    cost: 250,
    maps: [11, 12, 21, 35],
    rank: 'Basic',
    stats: {
      abilityHaste: 5,
    },
    tags: ['Fighter', 'Marksman', 'Assassin', 'Mage', 'Tank', 'Support'],
  },
  {
    id: 2031,
    name: 'Refillable Potion',
    aka: ['Green Potion'],
    cost: 150,
    maps: [11, 12, 21],
    rank: 'Consumable',
    stats: {},
    tags: ['Health and reg'],
  },
  {
    id: 2049,
    name: 'Guardian\'s Amulet',
    cost: 500,
    maps: [30],
    rank: 'Starter',
    stats: {
      abilityHaste: 20,
      abilityPower: 20,
      healAndShieldPower: 15,
    },
    tags: ['Support'],
  },
  {
    id: 2050,
    name: 'Guardian\'s Shroud',
    cost: 500,
    maps: [30],
    rank: 'Starter',
    stats: {
      abilityHaste: 15,
      abilityPower: 35,
      health: 300,
    },
    tags: ['Mage', 'Tank'],
  },
  {
    id: 2051,
    name: 'Guardian\'s Horn',
    aka: [
      'Golden Arm of Kobe',
      'Golden Bicep of Kobe',
      'Horn',
      'Horn of the ManWolf',
      'ManWolf',
    ],
    cost: 950,
    maps: [12, 35],
    rank: 'Starter',
    stats: {
      health: 150,
      healthRegen: 20,
    },
    tags: ['Fighter', 'Tank', 'Support'],
  },
  {
    id: 2052,
    name: 'Poro-Snax',
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    purchasable: false,
    rank: 'Special',
    stats: {},
  },
  {
    id: 2055,
    name: 'Control Ward',
    aka: ['kleptomancy', 'orange', 'red', 'pink'],
    cost: 75,
    maps: [11],
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 2065,
    name: 'Shurelya\'s Battlesong',
    aka: ['shurelya', 'reverie'],
    cost: 2200,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      abilityPower: 50,
      manaRegen: 125,
      percentMovespeed: 4,
    },
    tags: ['Support', 'Movement'],
  },
  {
    id: 2138,
    name: 'Elixir of Iron',
    aka: ['orange', 'white'],
    cost: 500,
    maps: [11, 12, 21],
    rank: 'Consumable',
    stats: {},
    tags: ['Health and reg', 'Movement'],
  },
  {
    id: 2139,
    name: 'Elixir of Sorcery',
    aka: ['blue', 'brilliance', 'illumination'],
    cost: 500,
    maps: [11, 12, 21],
    rank: 'Consumable',
    stats: {},
    tags: ['Ability power', 'Mana and reg', 'Onhit effects'],
  },
  {
    id: 2140,
    name: 'Elixir of Wrath',
    aka: ['red potion', 'fortitude', 'rage'],
    cost: 500,
    maps: [11, 12, 21],
    rank: 'Consumable',
    stats: {},
    tags: ['Attack damage', 'Lifesteal vamp'],
  },
  {
    id: 2141,
    name: 'Cappa Juice',
    cost: 300,
    maps: [11, 12],
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 2142,
    name: 'Juice of Power',
    cost: 500,
    maps: [30],
    rank: 'Consumable',
    stats: {},
    tags: ['Attack damage', 'Ability power'],
  },
  {
    id: 2143,
    name: 'Juice of Vitality',
    cost: 500,
    maps: [30],
    rank: 'Consumable',
    stats: {},
    tags: ['Health and reg'],
  },
  {
    id: 2144,
    name: 'Juice of Haste',
    cost: 500,
    maps: [30],
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 2145,
    name: 'Lucky Dice',
    cost: 0,
    maps: [30],
    purchasable: false,
    rank: 'Special',
    stats: {},
  },
  {
    id: 2150,
    name: 'Elixir of Skill',
    cost: 0,
    maps: [11, 12, 21, 35],
    purchasable: false,
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 2151,
    name: 'Elixir of Avarice',
    cost: 0,
    maps: [11, 12, 21, 35],
    purchasable: false,
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 2152,
    name: 'Elixir of Force',
    cost: 0,
    maps: [11, 12, 21, 35],
    purchasable: false,
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 2420,
    name: 'Seeker\'s Armguard',
    aka: ['zhg', 'zonyas', 'zhonyas'],
    cost: 1600,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      abilityPower: 40,
      armor: 25,
    },
    tags: ['Mage'],
  },
  {
    id: 2421,
    name: 'Shattered Armguard',
    cost: 1600,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      abilityPower: 40,
      armor: 25,
    },
  },
  {
    id: 2422,
    name: 'Slightly Magical Boots',
    cost: 0,
    maps: [11, 12, 21, 35],
    purchasable: false,
    rank: 'Special',
    stats: {
      flatMovespeed: 25,
    },
  },
  {
    id: 2501,
    name: 'Overlord\'s Bloodmail',
    cost: 3300,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackDamage: 30,
      health: 550,
    },
    tags: ['Fighter', 'Tank'],
  },
  {
    id: 2502,
    name: 'Unending Despair',
    cost: 2800,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 10,
      armor: 25,
      health: 400,
      magicResistance: 25,
    },
    tags: ['Tank'],
  },
  {
    id: 2503,
    name: 'Blackfire Torch',
    aka: ['bft'],
    cost: 2800,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 20,
      abilityPower: 80,
      mana: 600,
    },
    tags: ['Mage'],
  },
  {
    id: 2504,
    name: 'Kaenic Rookern',
    cost: 2900,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      health: 400,
      healthRegen: 100,
      magicResistance: 80,
    },
    tags: ['Tank'],
  },
  {
    id: 2508,
    name: 'Fated Ashes',
    cost: 900,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      abilityPower: 30,
    },
    tags: ['Mage'],
  },
  {
    id: 3002,
    name: 'Trailblazer',
    cost: 2400,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      armor: 40,
      health: 250,
      percentMovespeed: 4,
    },
    tags: ['Support', 'Tank'],
  },
  {
    id: 3003,
    name: 'Archangel\'s Staff',
    aka: ['aa'],
    cost: 2900,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 25,
      abilityPower: 70,
      mana: 600,
    },
    tags: ['Mage'],
  },
  {
    id: 3004,
    name: 'Manamune',
    cost: 2900,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      attackDamage: 35,
      mana: 500,
    },
    tags: ['Fighter', 'Marksman', 'Assassin', 'Onhit effects'],
  },
  {
    id: 3006,
    name: 'Berserker\'s Greaves',
    aka: ['boots', 'zerker'],
    cost: 1100,
    maps: [11, 12, 21, 35],
    rank: 'Boots',
    stats: {
      attackSpeed: 25,
      flatMovespeed: 45,
    },
  },
  {
    id: 3009,
    name: 'Boots of Swiftness',
    aka: ['swifties'],
    cost: 1000,
    maps: [11, 12, 21, 35],
    rank: 'Boots',
    stats: {
      flatMovespeed: 55,
    },
  },
  {
    id: 3010,
    name: 'Symbiotic Soles',
    aka: ['boots'],
    cost: 900,
    maps: [11, 21],
    rank: 'Boots',
    stats: {
      flatMovespeed: 40,
    },
  },
  {
    id: 3013,
    name: 'Synchronized Souls',
    aka: ['boots'],
    cost: 900,
    maps: [11, 21],
    purchasable: false,
    rank: 'Boots',
    stats: {
      flatMovespeed: 45,
    },
  },
  {
    id: 3020,
    name: 'Sorcerer\'s Shoes',
    aka: ['boots', 'sorcs'],
    cost: 1100,
    maps: [11, 12, 21, 35],
    rank: 'Boots',
    stats: {
      flatMagicPenetration: 12,
      flatMovespeed: 45,
    },
  },
  {
    id: 3024,
    name: 'Glacial Buckler',
    cost: 900,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      abilityHaste: 10,
      armor: 25,
      mana: 300,
    },
    tags: ['Tank', 'Support'],
  },
  {
    id: 3026,
    name: 'Guardian Angel',
    aka: ['ga'],
    cost: 3200,
    maps: [11],
    rank: 'Legendary',
    stats: {
      armor: 45,
      attackDamage: 55,
    },
    tags: ['Fighter', 'Marksman', 'Assassin'],
  },
  {
    id: 3031,
    name: 'Infinity Edge',
    aka: ['ie'],
    cost: 3450,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackDamage: 65,
      criticalStrikeChance: 25,
      criticalStrikeDamage: 40,
    },
    tags: ['Marksman'],
  },
  {
    id: 3032,
    name: 'Yun Tal Wildarrows',
    aka: ['arrow', 'yuntal'],
    cost: 3000,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackDamage: 55,
      attackSpeed: 35,
    },
    tags: ['Marksman'],
  },
  {
    id: 3033,
    name: 'Mortal Reminder',
    aka: ['lw', 'grievous'],
    cost: 3300,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      armorPenetration: 35,
      attackDamage: 35,
      criticalStrikeChance: 25,
    },
    tags: ['Marksman'],
  },
  {
    id: 3035,
    name: 'Last Whisper',
    aka: ['lw'],
    cost: 1450,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      armorPenetration: 18,
      attackDamage: 20,
    },
    tags: ['Fighter', 'Marksman', 'Assassin'],
  },
  {
    id: 3036,
    name: 'Lord Dominik\'s Regards',
    aka: ['lw', 'ldr', 'doms'],
    cost: 3100,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      armorPenetration: 40,
      attackDamage: 35,
      criticalStrikeChance: 25,
    },
    tags: ['Marksman'],
  },
  {
    id: 3040,
    name: 'Seraph\'s Embrace',
    cost: 2900,
    maps: [11, 12, 21, 35],
    purchasable: false,
    rank: 'Legendary',
    stats: {
      abilityHaste: 25,
      abilityPower: 70,
      mana: 1000,
    },
  },
  {
    id: 3041,
    name: 'Mejai\'s Soulstealer',
    aka: ['book'],
    cost: 1500,
    maps: [11],
    rank: 'Legendary',
    stats: {
      abilityPower: 20,
      health: 100,
    },
    tags: ['Mage', 'Movement'],
  },
  {
    id: 3042,
    name: 'Muramana',
    cost: 2900,
    maps: [11, 12, 21, 35],
    purchasable: false,
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      attackDamage: 35,
      mana: 860,
    },
    tags: ['Fighter', 'Marksman', 'Assassin', 'Onhit effects'],
  },
  {
    id: 3044,
    name: 'Phage',
    aka: ['mallet'],
    cost: 1100,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      attackDamage: 15,
      health: 200,
    },
    tags: ['Fighter', 'Tank'],
  },
  {
    id: 3046,
    name: 'Phantom Dancer',
    aka: ['pd'],
    cost: 2650,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackSpeed: 65,
      criticalStrikeChance: 25,
      percentMovespeed: 10,
    },
    tags: ['Marksman', 'Movement'],
  },
  {
    id: 3047,
    name: 'Plated Steelcaps',
    aka: ['boots', 'ninja tabi'],
    cost: 1200,
    maps: [11, 12, 21, 35],
    rank: 'Boots',
    stats: {
      armor: 25,
      flatMovespeed: 45,
    },
  },
  {
    id: 3050,
    name: 'Zeke\'s Convergence',
    aka: ['haroldandkumar'],
    cost: 2200,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 10,
      armor: 25,
      health: 300,
      magicResistance: 25,
    },
    tags: ['Tank', 'Support'],
  },
  {
    id: 3051,
    name: 'Hearthbound Axe',
    aka: ['blue arrow'],
    cost: 1200,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      attackDamage: 20,
      attackSpeed: 20,
    },
    tags: ['Fighter', 'Movement', 'Onhit effects'],
  },
  {
    id: 3053,
    name: 'Sterak\'s Gage',
    aka: ['juggernaut', 'primal', 'shield', 'sterak\'s cage'],
    cost: 3200,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      health: 400,
      tenacity: 20,
    },
    tags: ['Fighter', 'Attack damage'],
  },
  {
    id: 3057,
    name: 'Sheen',
    aka: ['jimmy neutron'],
    cost: 900,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      abilityHaste: 10,
    },
    tags: ['Fighter', 'Marksman', 'Mage', 'Onhit effects'],
  },
  {
    id: 3065,
    name: 'Spirit Visage',
    aka: ['sv'],
    cost: 2700,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 10,
      health: 400,
      healthRegen: 100,
      magicResistance: 50,
    },
    tags: ['Tank'],
  },
  {
    id: 3066,
    name: 'Winged Moonplate',
    aka: ['chaps', 'pants', 'leggings', 'zoomin'],
    cost: 800,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      health: 200,
      percentMovespeed: 4,
    },
    tags: ['Tank', 'Movement'],
  },
  {
    id: 3067,
    name: 'Kindlegem',
    cost: 800,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      abilityHaste: 10,
      health: 200,
    },
    tags: ['Fighter', 'Marksman', 'Assassin', 'Mage', 'Tank', 'Support'],
  },
  {
    id: 3068,
    name: 'Sunfire Aegis',
    aka: ['funfire', 'sunborn'],
    cost: 2700,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 10,
      armor: 50,
      health: 350,
    },
    tags: ['Tank'],
  },
  {
    id: 3070,
    name: 'Tear of the Goddess',
    cost: 400,
    maps: [11, 12, 21, 35],
    rank: 'Starter',
    stats: {
      mana: 240,
    },
    tags: ['Marksman', 'Mage'],
  },
  {
    id: 3071,
    name: 'Black Cleaver',
    aka: ['bc'],
    cost: 3000,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 20,
      attackDamage: 40,
      health: 400,
    },
    tags: ['Fighter', 'Onhit effects', 'Armor pen', 'Movement'],
  },
  {
    id: 3072,
    name: 'Bloodthirster',
    aka: ['bt', 'healsword'],
    cost: 3400,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackDamage: 80,
      lifesteal: 15,
    },
    tags: ['Marksman'],
  },
  {
    id: 3073,
    name: 'Experimental Hexplate',
    cost: 3000,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackDamage: 40,
      attackSpeed: 20,
      health: 450,
    },
    tags: ['Fighter', 'Ability haste', 'Movement'],
  },
  {
    id: 3074,
    name: 'Ravenous Hydra',
    aka: ['rav hydra'],
    cost: 3300,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      attackDamage: 65,
      lifesteal: 12,
    },
    tags: ['Fighter'],
  },
  {
    id: 3075,
    name: 'Thornmail',
    aka: ['grievous wounds'],
    cost: 2450,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      armor: 75,
      health: 150,
    },
    tags: ['Tank'],
  },
  {
    id: 3076,
    name: 'Bramble Vest',
    aka: ['grievous wounds'],
    cost: 800,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      armor: 30,
    },
    tags: ['Tank'],
  },
  {
    id: 3077,
    name: 'Tiamat',
    cost: 1200,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      attackDamage: 20,
    },
    tags: ['Fighter', 'Tank', 'Onhit effects'],
  },
  {
    id: 3078,
    name: 'Trinity Force',
    aka: ['triforce', 'tons of damage', '3333'],
    cost: 3333,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      attackDamage: 36,
      attackSpeed: 30,
      health: 333,
    },
    tags: ['Fighter', 'Marksman', 'Movement'],
  },
  {
    id: 3082,
    name: 'Warden\'s Mail',
    cost: 1000,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      armor: 40,
    },
    tags: ['Tank'],
  },
  {
    id: 3083,
    name: 'Warmog\'s Armor',
    cost: 3100,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      health: 1000,
      healthRegen: 100,
    },
    tags: ['Tank'],
  },
  {
    id: 3084,
    name: 'Heartsteel',
    cost: 3000,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      health: 900,
      healthRegen: 100,
    },
    tags: ['Tank'],
  },
  {
    id: 3085,
    name: 'Runaan\'s Hurricane',
    cost: 2650,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackSpeed: 40,
      criticalStrikeChance: 25,
      percentMovespeed: 4,
    },
    tags: ['Marksman', 'Onhit effects', 'Movement'],
  },
  {
    id: 3086,
    name: 'Zeal',
    cost: 1200,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      attackSpeed: 15,
      criticalStrikeChance: 15,
      percentMovespeed: 4,
    },
    tags: ['Marksman', 'Movement'],
  },
  {
    id: 3087,
    name: 'Statikk Shiv',
    cost: 2700,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackDamage: 45,
      attackSpeed: 30,
      percentMovespeed: 4,
    },
    tags: ['Marksman', 'Onhit effects'],
  },
  {
    id: 3089,
    name: 'Rabadon\'s Deathcap',
    aka: ['banksys', 'dc', 'dcap', 'hat'],
    cost: 3500,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityPower: 130,
    },
    tags: ['Mage'],
  },
  {
    id: 3091,
    name: 'Wit\'s End',
    cost: 2800,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackSpeed: 50,
      magicResistance: 45,
      tenacity: 20,
    },
    tags: ['Fighter', 'Marksman', 'Onhit effects'],
  },
  {
    id: 3094,
    name: 'Rapid Firecannon',
    aka: ['canon', 'gun', 'rapidfire', 'rfc'],
    cost: 2650,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackSpeed: 35,
      criticalStrikeChance: 25,
      percentMovespeed: 4,
    },
    tags: ['Marksman', 'Movement'],
  },
  {
    id: 3100,
    name: 'Lich Bane',
    cost: 2900,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 10,
      abilityPower: 100,
      percentMovespeed: 4,
    },
    tags: ['Mage', 'Onhit effects'],
  },
  {
    id: 3102,
    name: 'Banshee\'s Veil',
    aka: ['bv', 'spellshield'],
    cost: 3000,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityPower: 105,
      magicResistance: 40,
    },
    tags: ['Mage'],
  },
  {
    id: 3105,
    name: 'Aegis of the Legion',
    cost: 1100,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      abilityHaste: 10,
      armor: 25,
      magicResistance: 25,
    },
    tags: ['Tank', 'Support'],
  },
  {
    id: 3107,
    name: 'Redemption',
    cost: 2300,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      healAndShieldPower: 10,
      health: 200,
      manaRegen: 100,
    },
    tags: ['Support'],
  },
  {
    id: 3108,
    name: 'Fiendish Codex',
    aka: ['book'],
    cost: 850,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      abilityHaste: 10,
      abilityPower: 25,
    },
    tags: ['Mage'],
  },
  {
    id: 3109,
    name: 'Knight\'s Vow',
    aka: ['kv'],
    cost: 2300,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 10,
      armor: 40,
      health: 200,
      healthRegen: 100,
    },
    tags: ['Tank', 'Support'],
  },
  {
    id: 3110,
    name: 'Frozen Heart',
    aka: ['fh'],
    cost: 2500,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 20,
      armor: 75,
      mana: 400,
    },
    tags: ['Tank', 'Support'],
  },
  {
    id: 3111,
    name: 'Mercury\'s Treads',
    aka: ['boots', 'mercs'],
    cost: 1250,
    maps: [11, 12, 21, 35],
    rank: 'Boots',
    stats: {
      flatMovespeed: 45,
      magicResistance: 20,
      tenacity: 30,
    },
  },
  {
    id: 3112,
    name: 'Guardian\'s Orb',
    cost: 950,
    maps: [12, 35],
    rank: 'Starter',
    stats: {
      abilityPower: 50,
      health: 150,
    },
    tags: ['Mage', 'Tank', 'Support', 'Mana and reg'],
  },
  {
    id: 3113,
    name: 'Aether Wisp',
    aka: ['spooky ghost'],
    cost: 900,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      abilityPower: 30,
      percentMovespeed: 4,
    },
    tags: ['Mage', 'Movement'],
  },
  {
    id: 3114,
    name: 'Forbidden Idol',
    cost: 600,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      healAndShieldPower: 8,
      manaRegen: 50,
    },
    tags: ['Support'],
  },
  {
    id: 3115,
    name: 'Nashor\'s Tooth',
    aka: ['nashors'],
    cost: 2900,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      abilityPower: 80,
      attackSpeed: 50,
    },
    tags: ['Marksman', 'Mage', 'Onhit effects'],
  },
  {
    id: 3116,
    name: 'Rylai\'s Crystal Scepter',
    aka: ['rylais'],
    cost: 2600,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityPower: 65,
      health: 400,
    },
    tags: ['Mage'],
  },
  {
    id: 3118,
    name: 'Malignance',
    cost: 2700,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      abilityPower: 90,
      mana: 600,
    },
    tags: ['Mage', 'Ability haste'],
  },
  {
    id: 3119,
    name: 'Winter\'s Approach',
    cost: 2400,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      health: 550,
      mana: 500,
    },
    tags: ['Tank'],
  },
  {
    id: 3121,
    name: 'Fimbulwinter',
    cost: 2400,
    maps: [11, 12, 21, 35],
    purchasable: false,
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      health: 550,
      mana: 860,
    },
    tags: ['Tank'],
  },
  {
    id: 3123,
    name: 'Executioner\'s Calling',
    aka: ['grievous'],
    cost: 800,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      attackDamage: 15,
    },
    tags: ['Fighter', 'Marksman', 'Assassin'],
  },
  {
    id: 3124,
    name: 'Guinsoo\'s Rageblade',
    cost: 3000,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityPower: 30,
      attackDamage: 30,
      attackSpeed: 25,
    },
    tags: ['Fighter', 'Marksman', 'Onhit effects'],
  },
  {
    id: 3133,
    name: 'Caulfield\'s Warhammer',
    cost: 1050,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      abilityHaste: 10,
      attackDamage: 20,
    },
    tags: ['Fighter', 'Marksman', 'Assassin'],
  },
  {
    id: 3134,
    name: 'Serrated Dirk',
    cost: 1000,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      attackDamage: 20,
      lethality: 10,
    },
    tags: ['Assassin', 'Armor pen'],
  },
  {
    id: 3135,
    name: 'Void Staff',
    cost: 3000,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityPower: 95,
      percentMagicPenetration: 40,
    },
    tags: ['Mage'],
  },
  {
    id: 3137,
    name: 'Cryptbloom',
    cost: 3000,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 20,
      abilityPower: 75,
      percentMagicPenetration: 30,
    },
    tags: ['Mage'],
  },
  {
    id: 3139,
    name: 'Mercurial Scimitar',
    aka: ['merc scim'],
    cost: 3200,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackDamage: 40,
      lifesteal: 10,
      magicResistance: 40,
    },
    tags: ['Fighter', 'Marksman', 'Movement'],
  },
  {
    id: 3140,
    name: 'Quicksilver Sash',
    aka: ['qss'],
    cost: 1300,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      magicResistance: 30,
    },
    tags: ['Fighter', 'Marksman', 'Assassin'],
  },
  {
    id: 3142,
    name: 'Youmuu\'s Ghostblade',
    cost: 2800,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackDamage: 55,
      lethality: 18,
      percentMovespeed: 4,
    },
    tags: ['Assassin', 'Movement'],
  },
  {
    id: 3143,
    name: 'Randuin\'s Omen',
    cost: 2700,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      armor: 75,
      health: 350,
    },
    tags: ['Tank'],
  },
  {
    id: 3144,
    name: 'Scout\'s Slingshot',
    cost: 600,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      attackSpeed: 20,
    },
    tags: ['Marksman', 'Onhit effects'],
  },
  {
    id: 3145,
    name: 'Hextech Alternator',
    aka: ['revolver', 'pewpew'],
    cost: 1100,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      abilityPower: 45,
    },
    tags: ['Mage'],
  },
  {
    id: 3147,
    name: 'Haunting Guise',
    aka: ['mask'],
    cost: 1300,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      abilityPower: 30,
      health: 200,
    },
    tags: ['Mage'],
  },
  {
    id: 3152,
    name: 'Hextech Rocketbelt',
    aka: ['protobelt', 'rocket belt'],
    cost: 2650,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 20,
      abilityPower: 70,
      health: 300,
    },
    tags: ['Mage', 'Movement'],
  },
  {
    id: 3153,
    name: 'Blade of the Ruined King',
    aka: ['brk', 'bork', 'botrk', 'mist'],
    cost: 3200,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackDamage: 40,
      attackSpeed: 25,
      lifesteal: 10,
    },
    tags: ['Fighter', 'Marksman', 'Onhit effects'],
  },
  {
    id: 3155,
    name: 'Hexdrinker',
    cost: 1300,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      attackDamage: 25,
      magicResistance: 25,
    },
    tags: ['Fighter', 'Marksman', 'Assassin'],
  },
  {
    id: 3156,
    name: 'Maw of Malmortius',
    cost: 3100,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      attackDamage: 60,
      magicResistance: 40,
    },
    tags: ['Fighter', 'Marksman', 'Assassin'],
  },
  {
    id: 3157,
    name: 'Zhonya\'s Hourglass',
    aka: ['zhg', 'zonyas', 'zhonyas'],
    cost: 3250,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityPower: 105,
      armor: 50,
    },
    tags: ['Mage'],
  },
  {
    id: 3158,
    name: 'Ionian Boots of Lucidity',
    cost: 900,
    maps: [11, 12, 21, 35],
    rank: 'Boots',
    stats: {
      abilityHaste: 10,
      flatMovespeed: 45,
    },
  },
  {
    id: 3161,
    name: 'Spear of Shojin',
    cost: 3100,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackDamage: 45,
      health: 450,
    },
    tags: ['Fighter', 'Ability haste'],
  },
  {
    id: 3165,
    name: 'Morellonomicon',
    aka: ['nmst', 'grievous', 'last shadow', 'book', 'forbidden book'],
    cost: 2850,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      abilityPower: 75,
      health: 350,
    },
    tags: ['Mage', 'Support'],
  },
  {
    id: 3170,
    name: 'Swiftmarch',
    cost: 1500,
    maps: [11],
    rank: 'Boots',
    stats: {
      flatMovespeed: 65,
    },
  },
  {
    id: 3171,
    name: 'Crimson Lucidity',
    cost: 1400,
    maps: [11],
    rank: 'Boots',
    stats: {
      abilityHaste: 25,
      flatMovespeed: 50,
    },
  },
  {
    id: 3172,
    name: 'Zephyr',
    cost: 2500,
    maps: [11, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 30,
      attackSpeed: 50,
      percentMovespeed: 10,
      tenacity: 20,
    },
    tags: ['Marksman', 'Fighter'],
  },
  {
    id: 3173,
    name: 'Chainlaced Crushers',
    cost: 1750,
    maps: [11],
    rank: 'Boots',
    stats: {
      flatMovespeed: 50,
      magicResistance: 35,
      tenacity: 30,
    },
  },
  {
    id: 3174,
    name: 'Armored Advance',
    cost: 1700,
    maps: [11],
    rank: 'Boots',
    stats: {
      armor: 40,
      flatMovespeed: 50,
    },
  },
  {
    id: 3175,
    name: 'Spellslinger\'s Shoes',
    cost: 1600,
    maps: [11],
    rank: 'Boots',
    stats: {
      flatMagicPenetration: 18,
      flatMovespeed: 50,
    },
  },
  {
    id: 3176,
    name: 'Forever Forward',
    cost: 1400,
    maps: [11],
    rank: 'Boots',
    stats: {
      flatMovespeed: 55,
    },
  },
  {
    id: 3177,
    name: 'Guardian\'s Blade',
    cost: 950,
    maps: [12, 35],
    rank: 'Starter',
    stats: {
      abilityHaste: 15,
      attackDamage: 30,
      health: 150,
    },
    tags: ['Fighter', 'Marksman', 'Assassin', 'Tank'],
  },
  {
    id: 3179,
    name: 'Umbral Glaive',
    cost: 2500,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 10,
      attackDamage: 55,
      lethality: 15,
    },
    tags: ['Assassin'],
  },
  {
    id: 3181,
    name: 'Hullbreaker',
    aka: ['ahoy', 'pirate', 'yarrr'],
    cost: 3000,
    maps: [11, 12, 21],
    rank: 'Legendary',
    stats: {
      attackDamage: 40,
      health: 500,
      percentMovespeed: 4,
    },
    tags: ['Fighter'],
  },
  {
    id: 3184,
    name: 'Guardian\'s Hammer',
    cost: 950,
    maps: [12, 35],
    rank: 'Starter',
    stats: {
      attackDamage: 25,
      health: 150,
      lifesteal: 5,
    },
    tags: ['Fighter', 'Marksman', 'Assassin'],
  },
  {
    id: 3190,
    name: 'Locket of the Iron Solari',
    cost: 2200,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 10,
      armor: 25,
      health: 200,
      magicResistance: 25,
    },
    tags: ['Tank', 'Support'],
  },
  {
    id: 3211,
    name: 'Spectre\'s Cowl',
    aka: ['hat', 'ghost'],
    cost: 1250,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      health: 200,
      healthRegen: 100,
      magicResistance: 35,
    },
    tags: ['Tank'],
  },
  {
    id: 3222,
    name: 'Mikael\'s Blessing',
    aka: ['crucible', 'michael'],
    cost: 2300,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      healAndShieldPower: 12,
      health: 250,
      manaRegen: 100,
    },
    tags: ['Support'],
  },
  {
    id: 3302,
    name: 'Terminus',
    aka: ['bow', 'sentinel'],
    cost: 3000,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackDamage: 30,
      attackSpeed: 35,
    },
    tags: ['Fighter', 'Marksman', 'Onhit effects', 'Armor pen', 'Magic pen'],
  },
  {
    id: 3330,
    name: 'Scarecrow Effigy',
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 3340,
    name: 'Stealth Ward',
    aka: ['yellow', 'totem', 'trinket'],
    cost: 0,
    maps: [11, 21],
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 3348,
    name: 'Arcane Sweeper (Trinket)',
    cost: 0,
    maps: [30],
    purchasable: false,
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 3363,
    name: 'Farsight Alteration',
    aka: ['blue', 'totem', 'trinket'],
    cost: 0,
    maps: [11, 12, 21],
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 3364,
    name: 'Oracle Lens',
    aka: ['red', 'totem', 'trinket', 'sweeper', 'spinny'],
    cost: 0,
    maps: [11, 21],
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 3400,
    name: 'Your Cut',
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    purchasable: false,
    rank: 'Special',
    stats: {},
  },
  {
    id: 3430,
    name: 'Rite of Ruin',
    cost: 2500,
    maps: [30],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      abilityPower: 50,
      criticalStrikeChance: 25,
    },
    tags: ['Mage'],
  },
  {
    id: 3504,
    name: 'Ardent Censer',
    cost: 2200,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityPower: 45,
      healAndShieldPower: 10,
      manaRegen: 125,
      percentMovespeed: 4,
    },
    tags: ['Support', 'Attack speed'],
  },
  {
    id: 3508,
    name: 'Essence Reaver',
    aka: ['er', '<s>bloothirster</s>'],
    cost: 2900,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      attackDamage: 60,
      criticalStrikeChance: 25,
    },
    tags: ['Marksman', 'Mana and reg', 'Onhit effects'],
  },
  {
    id: 3513,
    name: 'Eye of the Herald',
    cost: 0,
    purchasable: false,
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 3599,
    name: 'Black Spear',
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    rank: 'Starter',
    stats: {},
  },
  {
    id: 3742,
    name: 'Dead Man\'s Plate',
    aka: ['dmp', 'gangplank', 'juggernaut', 'dreadnought'],
    cost: 2900,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      armor: 55,
      health: 350,
      percentMovespeed: 4,
    },
    tags: ['Fighter', 'Tank'],
  },
  {
    id: 3748,
    name: 'Titanic Hydra',
    aka: ['beefer', 'juggernaut'],
    cost: 3300,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackDamage: 40,
      health: 600,
    },
    tags: ['Fighter', 'Tank', 'Onhit effects'],
  },
  {
    id: 3801,
    name: 'Crystalline Bracer',
    cost: 800,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      health: 200,
      healthRegen: 100,
    },
    tags: ['Tank', 'Support'],
  },
  {
    id: 3802,
    name: 'Lost Chapter',
    aka: ['book'],
    cost: 1200,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      abilityHaste: 10,
      abilityPower: 40,
      mana: 300,
    },
    tags: ['Mage'],
  },
  {
    id: 3803,
    name: 'Catalyst of Aeons',
    cost: 1300,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      health: 350,
      mana: 375,
    },
    tags: ['Mage'],
  },
  {
    id: 3814,
    name: 'Edge of Night',
    aka: ['eon', 'spellshield', 'spell shield'],
    cost: 3000,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackDamage: 50,
      health: 250,
      lethality: 15,
    },
    tags: ['Assassin'],
  },
  {
    id: 3865,
    name: 'World Atlas',
    cost: 400,
    maps: [11],
    rank: 'Starter',
    stats: {
      goldPer10: 3,
      health: 30,
      healthRegen: 25,
      manaRegen: 25,
    },
    tags: ['Support', 'Mage'],
  },
  {
    id: 3866,
    name: 'Runic Compass',
    cost: 400,
    maps: [11],
    purchasable: false,
    rank: 'Epic',
    stats: {
      goldPer10: 5,
      health: 100,
      healthRegen: 50,
      manaRegen: 50,
    },
    tags: ['Support'],
  },
  {
    id: 3867,
    name: 'Bounty of Worlds',
    cost: 400,
    maps: [11],
    purchasable: false,
    rank: 'Legendary',
    stats: {
      goldPer10: 5,
      health: 200,
      healthRegen: 75,
      manaRegen: 75,
    },
    tags: ['Support'],
  },
  {
    id: 3869,
    name: 'Celestial Opposition',
    cost: 400,
    maps: [11],
    rank: 'Legendary',
    stats: {
      goldPer10: 5,
      health: 200,
      healthRegen: 75,
      manaRegen: 75,
    },
    tags: ['Support'],
  },
  {
    id: 3870,
    name: 'Dream Maker',
    cost: 400,
    maps: [11],
    rank: 'Legendary',
    stats: {
      goldPer10: 5,
      health: 200,
      healthRegen: 75,
      manaRegen: 75,
    },
    tags: ['Support'],
  },
  {
    id: 3871,
    name: 'Zaz\'Zak\'s Realmspike',
    cost: 400,
    maps: [11],
    rank: 'Legendary',
    stats: {
      goldPer10: 5,
      health: 200,
      healthRegen: 75,
      manaRegen: 75,
    },
    tags: ['Support'],
  },
  {
    id: 3876,
    name: 'Solstice Sleigh',
    cost: 400,
    maps: [11],
    rank: 'Legendary',
    stats: {
      goldPer10: 5,
      health: 200,
      healthRegen: 75,
      manaRegen: 75,
    },
    tags: ['Support'],
  },
  {
    id: 3877,
    name: 'Bloodsong',
    cost: 400,
    maps: [11],
    rank: 'Legendary',
    stats: {
      goldPer10: 5,
      health: 200,
      healthRegen: 75,
      manaRegen: 75,
    },
    tags: ['Support'],
  },
  {
    id: 3901,
    name: 'Fire at Will',
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    purchasable: false,
    stats: {},
  },
  {
    id: 3902,
    name: 'Death\'s Daughter',
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    purchasable: false,
    stats: {},
  },
  {
    id: 3903,
    name: 'Raise Morale',
    cost: 0,
    maps: [11, 12, 21, 30, 35],
    purchasable: false,
    stats: {},
  },
  {
    id: 3916,
    name: 'Oblivion Orb',
    aka: ['grievous'],
    cost: 800,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      abilityPower: 25,
    },
    tags: ['Mage', 'Support'],
  },
  {
    id: 4003,
    name: 'Lifeline',
    cost: 1600,
    maps: [12, 21, 35],
    rank: 'Epic',
    stats: {
      attackDamage: 25,
      lethality: 5,
      percentMovespeed: 4,
    },
    tags: ['Assassin'],
  },
  {
    id: 4005,
    name: 'Imperial Mandate',
    aka: ['banner of command', 'flag'],
    cost: 2250,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 20,
      abilityPower: 60,
      manaRegen: 125,
    },
    tags: ['Support'],
  },
  {
    id: 4011,
    name: 'Sword of Blossoming Dawn',
    cost: 2500,
    maps: [30],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      abilityPower: 45,
      healAndShieldPower: 12,
      health: 200,
    },
    tags: ['Support'],
  },
  {
    id: 4015,
    name: 'Perplexity',
    cost: 2500,
    maps: [30],
    rank: 'Legendary',
    stats: {
      abilityPower: 60,
      armorPenetration: 22,
      percentMagicPenetration: 30,
      percentMovespeed: 5,
    },
    tags: ['Mage'],
  },
  {
    id: 4016,
    name: 'Wordless Promise',
    cost: 2500,
    maps: [30],
    rank: 'Legendary',
    stats: {
      abilityHaste: 25,
      abilityPower: 50,
      healAndShieldPower: 25,
    },
    tags: ['Support'],
  },
  {
    id: 4017,
    name: 'Hellfire Hatchet',
    cost: 2500,
    maps: [30],
    rank: 'Legendary',
    stats: {
      attackDamage: 35,
      lethality: 12,
    },
    tags: ['Assassin'],
  },
  {
    id: 4401,
    name: 'Force of Nature',
    aka: ['fon'],
    cost: 2800,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      health: 400,
      magicResistance: 55,
      percentMovespeed: 4,
    },
    tags: ['Tank'],
  },
  {
    id: 4628,
    name: 'Horizon Focus',
    aka: ['snipe', 'lock on'],
    cost: 2800,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 25,
      abilityPower: 115,
    },
    tags: ['Mage'],
  },
  {
    id: 4629,
    name: 'Cosmic Drive',
    aka: ['hat'],
    cost: 3000,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 25,
      abilityPower: 70,
      health: 350,
      percentMovespeed: 4,
    },
    tags: ['Mage', 'Movement'],
  },
  {
    id: 4630,
    name: 'Blighting Jewel',
    aka: ['purple'],
    cost: 1100,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      abilityPower: 25,
      percentMagicPenetration: 13,
    },
    tags: ['Mage'],
  },
  {
    id: 4632,
    name: 'Verdant Barrier',
    aka: ['necklace'],
    cost: 1600,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      abilityPower: 40,
      magicResistance: 25,
    },
    tags: ['Mage'],
  },
  {
    id: 4633,
    name: 'Riftmaker',
    aka: ['velkoz'],
    cost: 3100,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      abilityPower: 70,
      health: 350,
    },
    tags: ['Mage', 'Lifesteal vamp'],
  },
  {
    id: 4638,
    name: 'Watchful Wardstone',
    aka: ['Support', 'Ward'],
    cost: 1100,
    maps: [11],
    rank: 'Epic',
    stats: {
      abilityHaste: 10,
      armor: 10,
      health: 150,
      magicResistance: 15,
    },
    tags: ['Support'],
  },
  {
    id: 4642,
    name: 'Bandleglass Mirror',
    aka: ['yordle'],
    cost: 900,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      abilityHaste: 10,
      abilityPower: 20,
      manaRegen: 100,
    },
    tags: ['Support'],
  },
  {
    id: 4643,
    name: 'Vigilant Wardstone',
    aka: ['Support', 'Ward', 'sightstone'],
    cost: 2300,
    maps: [11],
    rank: 'Legendary',
    stats: {
      abilityHaste: 20,
      armor: 25,
      health: 250,
      magicResistance: 30,
    },
    tags: ['Support'],
  },
  {
    id: 4645,
    name: 'Shadowflame',
    cost: 3200,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityPower: 110,
      flatMagicPenetration: 15,
    },
    tags: ['Mage'],
  },
  {
    id: 4646,
    name: 'Stormsurge',
    cost: 2800,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityPower: 90,
      flatMagicPenetration: 15,
      percentMovespeed: 6,
    },
    tags: ['Mage'],
  },
  {
    id: 6333,
    name: 'Death\'s Dance',
    aka: ['dd', '<s>Bloodbag</s>'],
    cost: 3300,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      armor: 50,
      attackDamage: 60,
    },
    tags: ['Fighter'],
  },
  {
    id: 6609,
    name: 'Chempunk Chainsword',
    aka: ['grievous'],
    cost: 3100,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      attackDamage: 45,
      health: 450,
    },
    tags: ['Fighter', 'Assassin'],
  },
  {
    id: 6610,
    name: 'Sundered Sky',
    cost: 3100,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 10,
      attackDamage: 40,
      health: 400,
    },
    tags: ['Fighter'],
  },
  {
    id: 6616,
    name: 'Staff of Flowing Water',
    aka: ['nami'],
    cost: 2250,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      abilityPower: 35,
      healAndShieldPower: 10,
      manaRegen: 125,
    },
    tags: ['Support'],
  },
  {
    id: 6617,
    name: 'Moonstone Renewer',
    aka: ['yuumi'],
    cost: 2200,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 20,
      abilityPower: 25,
      health: 200,
      manaRegen: 125,
    },
    tags: ['Support'],
  },
  {
    id: 6620,
    name: 'Echoes of Helia',
    aka: ['spooky cup'],
    cost: 2200,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 20,
      abilityPower: 35,
      health: 200,
      manaRegen: 125,
    },
    tags: ['Support'],
  },
  {
    id: 6621,
    name: 'Dawncore',
    cost: 2500,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityPower: 45,
      healAndShieldPower: 16,
      manaRegen: 100,
    },
    tags: ['Support'],
  },
  {
    id: 6631,
    name: 'Stridebreaker',
    aka: ['kneecapper', 'whipchain'],
    cost: 3300,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackDamage: 40,
      attackSpeed: 25,
      health: 450,
    },
    tags: ['Fighter', 'Movement'],
  },
  {
    id: 6653,
    name: 'Liandry\'s Torment',
    aka: ['last shadow', 'ls'],
    cost: 3000,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityPower: 60,
      health: 300,
    },
    tags: ['Mage'],
  },
  {
    id: 6655,
    name: 'Luden\'s Companion',
    aka: ['boomstick', 'gun'],
    cost: 2750,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 10,
      abilityPower: 100,
      mana: 600,
    },
    tags: ['Mage'],
  },
  {
    id: 6657,
    name: 'Rod of Ages',
    cost: 2600,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityPower: 45,
      health: 350,
      mana: 500,
    },
    tags: ['Mage'],
  },
  {
    id: 6660,
    name: 'Bami\'s Cinder',
    aka: ['fire'],
    cost: 900,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      abilityHaste: 5,
      health: 150,
    },
    tags: ['Tank'],
  },
  {
    id: 6662,
    name: 'Iceborn Gauntlet',
    cost: 2900,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      armor: 50,
      health: 300,
    },
    tags: ['Fighter', 'Tank', 'Onhit effects'],
  },
  {
    id: 6664,
    name: 'Hollow Radiance',
    cost: 2800,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 10,
      health: 400,
      healthRegen: 100,
      magicResistance: 40,
    },
    tags: ['Tank'],
  },
  {
    id: 6665,
    name: 'Jak\'Sho, The Protean',
    cost: 3200,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      armor: 45,
      health: 350,
      magicResistance: 45,
    },
    tags: ['Tank'],
  },
  {
    id: 6670,
    name: 'Noonquiver',
    cost: 1300,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      attackDamage: 15,
      criticalStrikeChance: 20,
    },
    tags: ['Marksman', 'Onhit effects'],
  },
  {
    id: 6672,
    name: 'Kraken Slayer',
    cost: 3000,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackDamage: 45,
      attackSpeed: 40,
      percentMovespeed: 4,
    },
    tags: ['Marksman'],
  },
  {
    id: 6673,
    name: 'Immortal Shieldbow',
    cost: 3000,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackDamage: 55,
      criticalStrikeChance: 25,
    },
    tags: ['Marksman', 'Health and reg'],
  },
  {
    id: 6675,
    name: 'Navori Flickerblade',
    cost: 2650,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackSpeed: 40,
      criticalStrikeChance: 25,
      percentMovespeed: 4,
    },
    tags: ['Marksman'],
  },
  {
    id: 6676,
    name: 'The Collector',
    aka: ['deathblade', 'gun'],
    cost: 3000,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackDamage: 50,
      criticalStrikeChance: 25,
      lethality: 10,
    },
    tags: ['Marksman', 'Assassin'],
  },
  {
    id: 6690,
    name: 'Rectrix',
    cost: 775,
    maps: [11, 12, 21, 35],
    rank: 'Epic',
    stats: {
      attackDamage: 15,
      percentMovespeed: 4,
    },
    tags: ['Assassin', 'Fighter'],
  },
  {
    id: 6692,
    name: 'Eclipse',
    cost: 2900,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      attackDamage: 60,
    },
    tags: ['Fighter'],
  },
  {
    id: 6694,
    name: 'Serylda\'s Grudge',
    cost: 3000,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      armorPenetration: 35,
      attackDamage: 45,
    },
    tags: ['Assassin'],
  },
  {
    id: 6695,
    name: 'Serpent\'s Fang',
    cost: 2500,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackDamage: 55,
      lethality: 15,
    },
    tags: ['Assassin'],
  },
  {
    id: 6696,
    name: 'Axiom Arc',
    cost: 3000,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 20,
      attackDamage: 55,
      lethality: 18,
    },
    tags: ['Assassin'],
  },
  {
    id: 6697,
    name: 'Hubris',
    cost: 3000,
    maps: [11, 21],
    rank: 'Legendary',
    stats: {
      abilityHaste: 10,
      attackDamage: 60,
      lethality: 18,
    },
    tags: ['Assassin'],
  },
  {
    id: 6698,
    name: 'Profane Hydra',
    cost: 3200,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 10,
      attackDamage: 60,
      lethality: 18,
    },
    tags: ['Assassin'],
  },
  {
    id: 6699,
    name: 'Voltaic Cyclosword',
    cost: 3000,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 10,
      attackDamage: 55,
      lethality: 18,
    },
    tags: ['Assassin'],
  },
  {
    id: 6701,
    name: 'Opportunity',
    cost: 2700,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      attackDamage: 55,
      lethality: 18,
    },
    tags: ['Assassin', 'Movement'],
  },
  {
    id: 8010,
    name: 'Bloodletter\'s Curse',
    cost: 2900,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      abilityPower: 65,
      health: 400,
    },
    tags: ['Mage'],
  },
  {
    id: 8020,
    name: 'Abyssal Mask',
    cost: 2650,
    maps: [11, 12, 21, 35],
    rank: 'Legendary',
    stats: {
      abilityHaste: 15,
      health: 350,
      magicResistance: 45,
    },
    tags: ['Tank', 'Support'],
  },
  {
    id: 220000,
    name: 'Stat Bonus',
    cost: 750,
    maps: [30],
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 220001,
    name: 'Legendary Fighter Item',
    cost: 2000,
    maps: [30],
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 220002,
    name: 'Legendary Marksman Item',
    cost: 2000,
    maps: [30],
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 220003,
    name: 'Legendary Assassin Item',
    cost: 2000,
    maps: [30],
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 220004,
    name: 'Legendary Mage Item',
    cost: 2000,
    maps: [30],
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 220005,
    name: 'Legendary Tank Item',
    cost: 2000,
    maps: [30],
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 220006,
    name: 'Legendary Support Item',
    cost: 2000,
    maps: [30],
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 220007,
    name: 'Prismatic Item',
    cost: 4000,
    maps: [30],
    rank: 'Consumable',
    stats: {},
  },
  {
    id: 223005,
    name: 'Ghostcrawlers',
    cost: 500,
    maps: [30],
    rank: 'Boots',
    stats: {
      flatMovespeed: 70,
    },
  },
  {
    id: 223039,
    name: 'Atma\'s Reckoning',
    aka: ['wreckoning'],
    cost: 2500,
    maps: [30],
    rank: 'Legendary',
    stats: {
      criticalStrikeChance: 20,
      health: 700,
    },
    tags: ['Fighter'],
  },
  {
    id: 223095,
    name: 'Stormrazor',
    aka: ['Windblade'],
    cost: 2500,
    maps: [30],
    rank: 'Legendary',
    stats: {
      attackDamage: 45,
      attackSpeed: 25,
      criticalStrikeChance: 25,
    },
    tags: ['Marksman', 'Onhit effects'],
  },
  {
    id: 223146,
    name: 'Hextech Gunblade',
    cost: 2500,
    maps: [30],
    rank: 'Legendary',
    stats: {
      abilityPower: 90,
      attackDamage: 45,
      omnivamp: 15,
    },
    tags: ['Mage'],
  },
  {
    id: 223185,
    name: 'Guardian\'s Dirk',
    cost: 500,
    maps: [30],
    rank: 'Starter',
    stats: {
      abilityHaste: 10,
      attackDamage: 25,
      lethality: 11,
    },
    tags: ['Fighter', 'Assassin'],
  },
  {
    id: 224004,
    name: 'Spectral Cutlass',
    cost: 2800,
    maps: [30],
    rank: 'Legendary',
    stats: {
      attackDamage: 50,
      lethality: 15,
      percentMovespeed: 4,
    },
    tags: ['Assassin'],
  },
  {
    id: 224403,
    name: 'The Golden Spatula',
    aka: ['debug'],
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 20,
      abilityPower: 125,
      armor: 40,
      attackDamage: 90,
      attackSpeed: 60,
      criticalStrikeChance: 25,
      health: 350,
      healthRegen: 200,
      lifesteal: 15,
      magicResistance: 40,
      mana: 350,
      manaRegen: 200,
      percentMovespeed: 10,
    },
  },
  {
    id: 226630,
    name: 'Goredrinker',
    aka: ['slurp'],
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 20,
      attackDamage: 55,
      health: 400,
    },
    tags: ['Fighter'],
  },
  {
    id: 228001,
    name: 'Anathema\'s Chains',
    cost: 2500,
    maps: [30],
    rank: 'Legendary',
    stats: {
      abilityHaste: 20,
      health: 650,
    },
    tags: ['Tank', 'Support'],
  },
  {
    id: 228002,
    name: 'Wooglet\'s Witchcap',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 20,
      abilityPower: 300,
      armor: 50,
    },
    tags: ['Mage'],
  },
  {
    id: 443054,
    name: 'Darksteel Talons',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      armor: 55,
      attackSpeed: 50,
      percentMovespeed: 10,
    },
    tags: ['Tank'],
  },
  {
    id: 443055,
    name: 'Fulmination',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      attackDamage: 55,
      attackSpeed: 45,
      percentMovespeed: 15,
    },
    tags: ['Marksman'],
  },
  {
    id: 443056,
    name: 'Demon King\'s Crown',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {},
  },
  {
    id: 443058,
    name: 'Shield of Molten Stone',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      armor: 100,
      health: 300,
    },
    tags: ['Tank'],
  },
  {
    id: 443059,
    name: 'Cloak of Starry Night',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      health: 300,
      magicResistance: 100,
    },
    tags: ['Tank'],
  },
  {
    id: 443060,
    name: 'Sword of the Divine',
    aka: ['sotd'],
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      criticalStrikeChance: 50,
    },
    tags: ['Assassin'],
  },
  {
    id: 443061,
    name: 'Force of Entropy',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 30,
      criticalStrikeChance: 25,
      health: 900,
    },
    tags: ['Tank'],
  },
  {
    id: 443062,
    name: 'Sanguine Gift',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 20,
      abilityPower: 80,
      healAndShieldPower: 15,
    },
    tags: ['Mage'],
  },
  {
    id: 443063,
    name: 'Eleisa\'s Miracle',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 25,
      armor: 50,
      magicResistance: 50,
    },
    tags: ['Support'],
  },
  {
    id: 443064,
    name: 'Talisman of Ascension',
    aka: ['Support', 'Economy', 'Gold'],
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {},
  },
  {
    id: 443069,
    name: 'Hamstringer',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      attackDamage: 45,
      attackSpeed: 40,
      criticalStrikeChance: 25,
    },
    tags: ['Marksman'],
  },
  {
    id: 443079,
    name: 'Turbo Chemtank',
    aka: ['catastrophe'],
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      health: 600,
    },
    tags: ['Tank'],
  },
  {
    id: 443080,
    name: 'Twin Mask',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {},
  },
  {
    id: 443081,
    name: 'Hexbolt Companion',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      attackSpeed: 75,
      health: 500,
    },
    tags: ['Tank'],
  },
  {
    id: 443090,
    name: 'Reaper\'s Toll',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      attackSpeed: 50,
      percentMovespeed: 10,
    },
    tags: ['Marksman'],
  },
  {
    id: 443193,
    name: 'Gargoyle Stoneplate',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 15,
      armor: 65,
      magicResistance: 65,
      percentMovespeed: 10,
    },
    tags: ['Tank'],
  },
  {
    id: 444636,
    name: 'Night Harvester',
    aka: ['dark', 'scythe'],
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 25,
      abilityPower: 90,
      health: 300,
    },
    tags: ['Mage'],
  },
  {
    id: 444637,
    name: 'Demonic Embrace',
    aka: ['helmet'],
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityPower: 80,
      health: 700,
    },
    tags: ['Mage'],
  },
  {
    id: 444644,
    name: 'Crown of the Shattered Queen',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 25,
      abilityPower: 85,
      health: 300,
      mana: 600,
    },
    tags: ['Mage'],
  },
  {
    id: 446632,
    name: 'Divine Sunderer',
    aka: ['devourer'],
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 20,
      attackDamage: 55,
      health: 350,
    },
    tags: ['Fighter'],
  },
  {
    id: 446656,
    name: 'Everfrost',
    aka: ['GLP', 'hose', 'supersoaker'],
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 25,
      abilityPower: 100,
      health: 250,
      mana: 600,
    },
    tags: ['Mage'],
  },
  {
    id: 446667,
    name: 'Radiant Virtue',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      armor: 35,
      healAndShieldPower: 12,
      health: 400,
      magicResistance: 35,
    },
    tags: ['Tank'],
  },
  {
    id: 446671,
    name: 'Galeforce',
    aka: ['squallrider'],
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      attackDamage: 65,
      attackSpeed: 30,
      criticalStrikeChance: 25,
      percentMovespeed: 12,
    },
    tags: ['Marksman'],
  },
  {
    id: 446691,
    name: 'Duskblade of Draktharr',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 20,
      attackDamage: 50,
      lethality: 20,
    },
    tags: ['Assassin'],
  },
  {
    id: 446693,
    name: 'Prowler\'s Claw',
    cost: 0,
    rank: 'Special',
    stats: {
      abilityHaste: 20,
      attackDamage: 55,
      lethality: 22,
    },
    tags: ['Assassin'],
  },
  {
    id: 447100,
    name: 'Mirage Blade',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      attackSpeed: 60,
      percentMovespeed: 12,
    },
  },
  {
    id: 447101,
    name: 'Gambler\'s Blade',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 40,
      attackSpeed: 70,
      percentMovespeed: 8,
    },
  },
  {
    id: 447102,
    name: 'Reality Fracture',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityPower: 80,
      attackSpeed: 40,
      health: 300,
    },
    tags: ['Mage'],
  },
  {
    id: 447103,
    name: 'Hemomancer\'s Helm',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 30,
      attackDamage: 60,
      omnivamp: 15,
    },
    tags: ['Fighter'],
  },
  {
    id: 447104,
    name: 'Innervating Locket',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 20,
      abilityPower: 70,
      health: 200,
    },
    tags: ['Mage'],
  },
  {
    id: 447105,
    name: 'Empyrean Promise',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 30,
      abilityPower: 70,
      healAndShieldPower: 18,
      manaRegen: 125,
    },
    tags: ['Mage'],
  },
  {
    id: 447106,
    name: 'Dragonheart',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {},
  },
  {
    id: 447107,
    name: 'Decapitator',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      attackSpeed: 50,
      percentMovespeed: 12,
    },
  },
  {
    id: 447108,
    name: 'Runecarver',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 20,
      abilityPower: 80,
      percentMovespeed: 8,
    },
    tags: ['Mage'],
  },
  {
    id: 447109,
    name: 'Cruelty',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityPower: 80,
      armor: 30,
      magicResistance: 30,
    },
    tags: ['Mage'],
  },
  {
    id: 447110,
    name: 'Moonflair Spellblade',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityPower: 85,
      health: 400,
      tenacity: 30,
    },
    tags: ['Mage'],
  },
  {
    id: 447112,
    name: 'Flesheater',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 20,
      health: 500,
    },
  },
  {
    id: 447113,
    name: 'Detonation Orb',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 20,
      abilityPower: 90,
      flatMagicPenetration: 12,
      mana: 600,
    },
    tags: ['Mage'],
  },
  {
    id: 447114,
    name: 'Reverberation',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      armor: 35,
      attackSpeed: 40,
      magicResistance: 35,
    },
    tags: ['Tank'],
  },
  {
    id: 447115,
    name: 'Regicide',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      attackDamage: 60,
      lethality: 15,
      percentMovespeed: 8,
    },
    tags: ['Assassin'],
  },
  {
    id: 447116,
    name: 'Kinkou Jitte',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 30,
      health: 400,
    },
    tags: ['Assassin', 'Fighter', 'Mage'],
  },
  {
    id: 447118,
    name: 'Pyromancer\'s Cloak',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 15,
      health: 400,
    },
    tags: ['Fighter', 'Marksman', 'Mage'],
  },
  {
    id: 447119,
    name: 'Lightning Rod',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      armor: 30,
      attackSpeed: 30,
      health: 500,
      magicResistance: 30,
      percentMovespeed: 8,
    },
    tags: ['Tank'],
  },
  {
    id: 447120,
    name: 'Diamond-Tipped Spear',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      attackSpeed: 30,
    },
    tags: ['Marksman', 'Mage'],
  },
  {
    id: 447121,
    name: 'Twilight\'s Edge',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityPower: 100,
      attackDamage: 70,
    },
    tags: ['Marksman', 'Mage'],
  },
  {
    id: 447122,
    name: 'Black Hole Gauntlet',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 25,
      health: 900,
    },
    tags: ['Tank'],
  },
  {
    id: 447123,
    name: 'Puppeteer',
    cost: 0,
    maps: [30],
    rank: 'Special',
    stats: {
      abilityHaste: 40,
      attackSpeed: 30,
      healAndShieldPower: 15,
      manaRegen: 150,
    },
    tags: ['Support'],
  },
]
