export * from './getWikiData';
export * from './champion/getChampsFromDatabase';
export * from './getData';
export * from './item/getItemsFromDatabase';
export * from './item/filterSR';
export * from './item/formatEffects';
export * from './item/formatItemStats';
export * from './champion/updateChampionData';
export * from './supabase';
export * from './patchNewData';
declare namespace supabase {}
