import { defineUiTheme } from "./defineUiTheme"

export const commandPaletteTheme = defineUiTheme({
  slots: {
    back: "p-0",
    close: "",
    content: "relative flex flex-col overflow-hidden",
    empty: "text-center text-n5",
    footer: "p-1",
    group: "isolate p-1",
    input: "",
    item: "group relative flex w-full items-start outline-none select-none before:absolute before:inset-px before:z-[-1] before:rounded-md data-disabled:cursor-not-allowed data-disabled:opacity-75",
    itemDescription: "truncate text-n5",
    itemLabel: "space-x-1 truncate text-n4",
    itemLabelBase: "text-pc [&>mark]:bg-n0 [&>mark]:text-nc",
    itemLabelPrefix: "text-p3",
    itemLabelSuffix: "text-n4 [&>mark]:bg-n0 [&>mark]:text-nc",
    itemLeadingAvatar: "shrink-0",
    itemLeadingAvatarSize: "",
    itemLeadingChip: "shrink-0",
    itemLeadingChipSize: "",
    itemLeadingIcon: "shrink-0",
    itemTrailing: "ms-auto inline-flex items-center",
    itemTrailingIcon: "shrink-0",
    itemTrailingKbds: "hidden shrink-0 items-center lg:inline-flex",
    itemTrailingKbdsSize: "",
    itemTrailingpcIcon:
      "hidden shrink-0 text-n4 group-data-highlighted:inline-flex",
    itemWrapper: "flex min-w-0 flex-1 flex-col text-start",
    label: "font-semibold text-pc",
    root: "flex min-h-0 min-w-0 flex-col divide-y divide-p3",
    viewport: "relative flex-1 scroll-py-1 overflow-y-auto focus:outline-none",
  },
  variants: {
    active: {
      false: {
        item: [
          "text-p3 data-highlighted:not-data-disabled:text-pc data-highlighted:not-data-disabled:before:bg-p3/50",
          "transition-colors before:transition-colors",
        ],
        itemLeadingIcon: [
          "text-n4 group-data-highlighted:not-group-data-disabled:text-p3",
          "transition-colors",
        ],
      },
      true: {
        item: "text-pc before:bg-p3",
        itemLeadingIcon: "text-p3",
      },
    },
    loading: {
      true: {
        itemLeadingIcon: "animate-spin",
      },
    },
    size: {
      lg: {
        empty: "py-7 text-sm",
        input: "[&>input]:h-13",
        item: "gap-2 p-2 text-sm",
        itemLeadingAvatarSize: "2xs",
        itemLeadingChip: "size-5",
        itemLeadingChipSize: "md",
        itemLeadingIcon: "size-5",
        itemTrailing: "gap-2",
        itemTrailingIcon: "size-5",
        itemTrailingKbds: "gap-0.5",
        itemTrailingKbdsSize: "md",
        itemTrailingpcIcon: "size-5",
        label: "gap-2 p-2 text-xs",
      },
      md: {
        empty: "py-6 text-sm",
        input: "[&_svg]:size-4! [&_svg]:text-n4 [&>input]:h-12",
        item: "gap-1.5 p-1.5 text-sm",
        itemLeadingAvatarSize: "2xs",
        itemLeadingChip: "size-5",
        itemLeadingChipSize: "md",
        itemLeadingIcon: "size-4",
        itemTrailing: "gap-1.5",
        itemTrailingIcon: "size-4",
        itemTrailingKbds: "gap-0.5",
        itemTrailingKbdsSize: "md",
        itemTrailingpcIcon: "size-5",
        label: "gap-1.5 p-1.5 text-xs",
        root: "[&_svg]:size-4! [&_svg]:text-n4",
      },
      sm: {
        empty: "py-4 text-xs",
        input: "[&>input]:h-11",
        item: "gap-1.5 p-1.5 text-xs",
        itemLeadingAvatarSize: "3xs",
        itemLeadingChip: "size-4",
        itemLeadingChipSize: "sm",
        itemLeadingIcon: "size-4",
        itemTrailing: "gap-1.5",
        itemTrailingIcon: "size-4",
        itemTrailingKbds: "gap-0.5",
        itemTrailingKbdsSize: "sm",
        itemTrailingpcIcon: "size-4",
        label: "gap-1.5 p-1.5 text-[10px]/3",
      },
      xl: {
        empty: "py-8 text-base",
        input: "[&>input]:h-14",
        item: "gap-2 p-2 text-base",
        itemLeadingAvatarSize: "xs",
        itemLeadingChip: "size-6",
        itemLeadingChipSize: "lg",
        itemLeadingIcon: "size-6",
        itemTrailing: "gap-2",
        itemTrailingIcon: "size-6",
        itemTrailingKbds: "gap-0.5",
        itemTrailingKbdsSize: "lg",
        itemTrailingpcIcon: "size-6",
        label: "gap-2 p-2 text-sm",
      },
      xs: {
        empty: "py-3 text-xs",
        input: "[&>input]:h-10",
        item: "gap-1 p-1 text-xs",
        itemLeadingAvatarSize: "3xs",
        itemLeadingChip: "size-4",
        itemLeadingChipSize: "sm",
        itemLeadingIcon: "size-4",
        itemTrailing: "gap-1",
        itemTrailingIcon: "size-4",
        itemTrailingKbds: "gap-0.5",
        itemTrailingKbdsSize: "sm",
        itemTrailingpcIcon: "size-4",
        label: "gap-1 p-1 text-[10px]/3",
      },
    },
    virtualize: {
      false: {
        viewport: "divide-y divide-p3",
      },
      true: {
        viewport: "isolate p-1",
      },
    },
  },
  defaultVariants: {
    size: "md",
  },
})

export default commandPaletteTheme
