// Updated Patch 16.9 - 05/08/2026 03:28:22 PM CDT

export const abilityIdToName: Record<string, string> = {
  "266P": "Deathbringer Stance",
  "266Q": "The Darkin Blade",
  "266W": "Infernal Chains",
  "266E": "Umbral Dash",
  "266R": "World Ender",
  "103P": "Essence Theft",
  "103Q": "Orb of Deception",
  "103W": "Fox-Fire",
  "103E": "Charm",
  "103R": "Spirit Rush",
  "84P": "Assassin's Mark",
  "84Q": "Five Point Strike",
  "84W": "Twilight Shroud",
  "84E": "Shuriken Flip",
  "84R": "Perfect Execution",
  "166P": "Dirty Fighting",
  "166Q": "Avengerang",
  "166W": "Going Rogue",
  "166E": "Heroic Swing",
  "166R": "Comeuppance",
  "12P": "Triumphant Roar",
  "12Q": "Pulverize",
  "12W": "Headbutt",
  "12E": "Trample",
  "12R": "Unbreakable Will",
  "799P": "Drakehound's Step",
  "799Q": "Sundering Slam",
  "799W": "Repudiation",
  "799E": "Lacerate",
  "799R": "Public Execution",
  "32P": "Cursed Touch",
  "32Q": "Bandage Toss",
  "32W": "Despair",
  "32E": "Tantrum",
  "32R": "Curse of the Sad Mummy",
  "34P": "Rebirth",
  "34Q": "Flash Frost",
  "34W": "Crystallize",
  "34E": "Frostbite",
  "34R": "Glacial Storm",
  "1P": "Pyromania",
  "1Q": "Disintegrate",
  "1W": "Incinerate",
  "1E": "Molten Shield",
  "1R": "Summon: Tibbers",
  "523P": "Crescendum",
  "523Q": "Sentry",
  "523W": "Phase",
  "523E": "Weapon Queue System",
  "523R": "Moonlight Vigil",
  "22P": "Frost Shot",
  "22Q": "Ranger's Focus",
  "22W": "Volley",
  "22E": "Hawkshot",
  "22R": "Enchanted Crystal Arrow",
  "136P": "Cosmic Creator",
  "136Q": "Breath of Light",
  "136W": "Astral Flight",
  "136E": "Singularity",
  "136R": "The Skies Descend",
  "893P": "Spirit Abjuration",
  "893Q": "Twofold Hex",
  "893W": "Across the Veil",
  "893E": "The Weirding",
  "893R": "Between Worlds",
  "268P": "Shurima's Legacy",
  "268Q": "Conquering Sands",
  "268W": "Arise!",
  "268E": "Shifting Sands",
  "268R": "Emperor's Divide",
  "432P": "Traveler's Call",
  "432Q": "Cosmic Binding",
  "432W": "Caretaker's Shrine",
  "432E": "Magical Journey",
  "432R": "Tempered Fate",
  "200P": "Death in Lavender",
  "200Q": "Void Surge",
  "200W": "Above and Below",
  "200E": "Royal Maelstrom",
  "200R": "Endless Banquet",
  "53P": "Mana Barrier",
  "53Q": "Rocket Grab",
  "53W": "Overdrive",
  "53E": "Power Fist",
  "53R": "Static Field",
  "63P": "Blaze",
  "63Q": "Sear",
  "63W": "Pillar of Flame",
  "63E": "Conflagration",
  "63R": "Pyroclasm",
  "201P": "Concussive Blows",
  "201Q": "Winter's Bite",
  "201W": "Stand Behind Me",
  "201E": "Unbreakable",
  "201R": "Glacial Fissure",
  "233P": "Crimson Curse",
  "233Q": "Head Rush",
  "233W": "Snack Attack",
  "233E": "Chilling Scream",
  "233R": "Certain Death",
  "51P": "Headshot",
  "51Q": "Piltover Peacemaker",
  "51W": "Yordle Snap Trap",
  "51E": "90 Caliber Net",
  "51R": "Ace in the Hole",
  "164P": "Adaptive Defenses",
  "164Q": "Precision Protocol",
  "164W": "Tactical Sweep",
  "164E": "Wall Dive",
  "164R": "The Hextech Ultimatum",
  "69P": "Serpentine Grace",
  "69Q": "Noxious Blast",
  "69W": "Miasma",
  "69E": "Twin Fang",
  "69R": "Petrifying Gaze",
  "31P": "Carnivore",
  "31Q": "Rupture",
  "31W": "Feral Scream",
  "31E": "Vorpal Spikes",
  "31R": "Feast",
  "42P": "Hextech Munitions",
  "42Q": "Phosphorus Bomb",
  "42W": "Valkyrie",
  "42E": "Gatling Gun",
  "42R": "Missile Barrage",
  "122P": "Hemorrhage",
  "122Q": "Decimate",
  "122W": "Crippling Strike",
  "122E": "Apprehend",
  "122R": "Noxian Guillotine",
  "131P": "Moonsilver Blade",
  "131Q": "Crescent Strike",
  "131W": "Pale Cascade",
  "131E": "Lunar Rush",
  "131R": "Moonfall",
  "36P": "Goes Where He Pleases",
  "36Q": "Infected Bonesaw",
  "36W": "Heart Zapper",
  "36E": "Blunt Force Trauma",
  "36R": "Maximum Dosage",
  "119P": "League of Draven",
  "119Q": "Spinning Axe",
  "119W": "Blood Rush",
  "119E": "Stand Aside",
  "119R": "Whirling Death",
  "245P": "Z-Drive Resonance",
  "245Q": "Timewinder",
  "245W": "Parallel Convergence",
  "245E": "Phase Dive",
  "245R": "Chronobreak",
  "60P": "Spider Queen",
  "60Q": "Venomous Bite",
  "60W": "Skittering Frenzy",
  "60E": "Rappel",
  "60R": "Spider Form / Human Form",
  "28P": "Demon Shade",
  "28Q": "Hate Spike",
  "28W": "Allure",
  "28E": "Empowered Whiplash",
  "28R": "Last Caress",
  "81P": "Rising Spell Force",
  "81Q": "Mystic Shot",
  "81W": "Essence Flux",
  "81E": "Arcane Shift",
  "81R": "Trueshot Barrage",
  "9P": "A Harmless Scarecrow",
  "9Q": "Terrify",
  "9W": "Bountiful Harvest",
  "9E": "Reap",
  "9R": "Crowstorm",
  "114P": "Duelist's Dance",
  "114Q": "Lunge",
  "114W": "Riposte",
  "114E": "Bladework",
  "114R": "Grand Challenge",
  "105P": "Nimble Fighter",
  "105Q": "Urchin Strike",
  "105W": "Seastone Trident",
  "105E": "Trickster",
  "105R": "Chum the Waters",
  "3P": "Colossal Smash",
  "3Q": "Winds of War",
  "3W": "Shield of Durand",
  "3E": "Justice Punch",
  "3R": "Hero's Entrance",
  "41P": "Trial by Fire",
  "41Q": "Parrrley",
  "41W": "Remove Scurvy",
  "41E": "Powder Keg",
  "41R": "Cannon Barrage",
  "86P": "Perseverance",
  "86Q": "Decisive Strike",
  "86W": "Courage",
  "86E": "Judgment",
  "86R": "Demacian Justice",
  "150P": "Rage Gene",
  "150Q": "Boulder Toss",
  "150W": "Wallop",
  "150E": "Crunch",
  "150R": "GNAR!",
  "79P": "Happy Hour",
  "79Q": "Barrel Roll",
  "79W": "Drunken Rage",
  "79E": "Body Slam",
  "79R": "Explosive Cask",
  "104P": "New Destiny",
  "104Q": "End of the Line",
  "104W": "Smoke Screen",
  "104E": "Quickdraw",
  "104R": "Collateral Damage",
  "887P": "A Thousand Cuts",
  "887Q": "Snip Snip!",
  "887W": "Hallowed Mist",
  "887E": "Skip 'n Slash",
  "887R": "Needlework",
  "120P": "Warpath",
  "120Q": "Rampage",
  "120W": "Spirit of Dread",
  "120E": "Devastating Charge",
  "120R": "Onslaught of Shadows",
  "74P": "Hextech Affinity",
  "74Q": "H-28Q Apex Turret",
  "74W": "Hextech Rocket Swarm",
  "74E": "CH-3X Lightning Grenade",
  "74R": "UPGRADE!!!",
  "910P": "Signature of the Visionary",
  "910Q": "Molten Fissure",
  "910W": "Stirring Lights",
  "910E": "Crushing Maw",
  "910R": "Wash Brush",
  "420P": "Prophet of an Elder God",
  "420Q": "Tentacle Smash",
  "420W": "Harsh Lesson",
  "420E": "Test of Spirit",
  "420R": "Leap of Faith",
  "39P": "Ionian Fervor",
  "39Q": "Bladesurge",
  "39W": "Defiant Dance",
  "39E": "Flawless Duet",
  "39R": "Vanguard's Edge",
  "427P": "Friend of the Forest",
  "427Q": "Rootcaller",
  "427W": "Brushmaker",
  "427E": "Triggerseed",
  "427R": "Daisy!",
  "40P": "Tailwind",
  "40Q": "Howling Gale",
  "40W": "Zephyr",
  "40E": "Eye of the Storm",
  "40R": "Monsoon",
  "59P": "Martial Cadence",
  "59Q": "Dragon Strike",
  "59W": "Golden Aegis",
  "59E": "Demacian Standard",
  "59R": "Cataclysm",
  "24P": "Relentless Assault",
  "24Q": "Leap Strike",
  "24W": "Empower",
  "24E": "Counter Strike",
  "24R": "Grandmaster-at-Arms",
  "126P": "Hextech Capacitor 2",
  "126Q": "Shock Blast",
  "126W": "Hyper Charge",
  "126E": "Acceleration Gate",
  "126R": "Transform Mercury Hammer",
  "202P": "Whisper",
  "202Q": "Dancing Grenade",
  "202W": "Deadly Flourish",
  "202E": "Captive Audience",
  "202R": "Curtain Call",
  "222P": "Get Excited!",
  "222Q": "Switcheroo!",
  "222W": "Zap!",
  "222E": "Flame Chompers!",
  "222R": "Super Mega Death Rocket!",
  "897P": "Dauntless Instinct",
  "897Q": "Ntofo Strikes",
  "897W": "Path Maker",
  "897E": "Footwork",
  "897R": "All Out",
  "145P": "Second Skin",
  "145Q": "Icathian Rain",
  "145W": "Void Seeker",
  "145E": "Supercharge",
  "145R": "Killer Instinct",
  "429P": "Martial Poise",
  "429Q": "Pierce",
  "429W": "Sentinel",
  "429E": "Rend",
  "429R": "Fate's Call",
  "43P": "Gathering Fire",
  "43Q": "Soulflare",
  "43W": "Renewal",
  "43E": "Defiance",
  "43R": "Mantra",
  "30P": "Death Defied",
  "30Q": "Lay Waste",
  "30W": "Wall of Pain",
  "30E": "Defile",
  "30R": "Requiem",
  "38P": "Void Stone",
  "38Q": "Null Sphere",
  "38W": "Nether Blade",
  "38E": "Force Pulse",
  "38R": "Riftwalk",
  "55P": "Voracity",
  "55Q": "Bouncing Blade",
  "55W": "Preparation",
  "55E": "Shunpo",
  "55R": "Death Lotus",
  "10P": "Divine Ascent",
  "10Q": "Radiant Blast",
  "10W": "Celestial Blessing",
  "10E": "Starfire Spellblade",
  "10R": "Divine Judgment",
  "141P": "The Darkin Scythe",
  "141Q": "Reaping Slash",
  "141W": "Blade's Reach",
  "141E": "Shadow Step",
  "141R": "Umbral Trespass",
  "85P": "Mark of the Storm",
  "85Q": "Thundering Shuriken",
  "85W": "Electrical Surge",
  "85E": "Lightning Rush",
  "85R": "Slicing Maelstrom",
  "121P": "Unseen Threat",
  "121Q": "Evolved Reaper Claws",
  "121W": "Evolved Spike Racks",
  "121E": "Evolved Wings",
  "121R": "Evolved Adaptive Cloaking",
  "203P": "Mark of the Kindred",
  "203Q": "Dance of Arrows",
  "203W": "Wolf's Frenzy",
  "203E": "Mounting Dread",
  "203R": "Lamb's Respite",
  "240P": "Dismounted Skaarl the Cowardly Lizard",
  "240Q": "Pocket Pistol",
  "240W": "Violent Tendencies",
  "240E": "Dismounted Jousting",
  "240R": "Dismounted Chaaaaaaaarge!!!",
  "96P": "Icathian Surprise",
  "96Q": "Caustic Spittle",
  "96W": "Bio-Arcane Barrage",
  "96E": "Void Ooze",
  "96R": "Living Artillery",
  "7P": "Mirror Image",
  "7Q": "Sigil of Malice",
  "7W": "Distortion",
  "7E": "Ethereal Chains",
  "7R": "Mimic",
  "64P": "Flurry",
  "64Q": "Resonating Strike",
  "64W": "Iron Will",
  "64E": "Cripple",
  "64R": "Dragon's Rage",
  "89P": "Sunlight",
  "89Q": "Shield of Daybreak",
  "89W": "Eclipse",
  "89E": "Zenith Blade",
  "89R": "Solar Flare",
  "876P": "Dream-Laden Bough",
  "876Q": "Blooming Blows",
  "876W": "Watch Out! Eep!",
  "876E": "Swirlseed",
  "876R": "Lilting Lullaby",
  "127P": "Iceborn Subjugation",
  "127Q": "Ice Shard",
  "127W": "Ring of Frost",
  "127E": "Glacial Path",
  "127R": "Frozen Tomb",
  "236P": "Lightslinger",
  "236Q": "Piercing Light",
  "236W": "Ardent Blaze",
  "236E": "Relentless Pursuit",
  "236R": "The Culling",
  "117P": "Pix, Faerie Companion",
  "117Q": "Glitterlance",
  "117W": "Whimsy",
  "117E": "Help, Pix!",
  "117R": "Wild Growth",
  "99P": "Illumination",
  "99Q": "Light Binding",
  "99W": "Prismatic Barrier",
  "99E": "Lucent Singularity",
  "99R": "Final Spark",
  "54P": "Granite Shield",
  "54Q": "Seismic Shard",
  "54W": "Thunderclap",
  "54E": "Ground Slam",
  "54R": "Unstoppable Force",
  "90P": "Void Shift",
  "90Q": "Call of the Void",
  "90W": "Void Swarm",
  "90E": "Malefic Visions",
  "90R": "Nether Grasp",
  "57P": "Sap Magic",
  "57Q": "Bramble Smash",
  "57W": "Twisted Advance",
  "57E": "Sapling Toss",
  "57R": "Nature's Grasp",
  "11P": "Double Strike",
  "11Q": "Alpha Strike",
  "11W": "Meditate",
  "11E": "Wuju Style",
  "11R": "Highlander",
  "800P": "Searing Brilliance",
  "800Q": "Radiant Volley",
  "800W": "Rebuttal",
  "800E": "Solar Snare",
  "800R": "Golden Eclipse",
  "902P": "Fired Up!",
  "902Q": "Ultra Mega Fire Kick",
  "902W": "Cozy Campfire",
  "902E": "Warm Hugs",
  "902R": "Breath of Life",
  "21P": "Love Tap",
  "21Q": "Double Up",
  "21W": "Strut",
  "21E": "Make It Rain",
  "21R": "Bullet Time",
  "82P": "Darkness Rise",
  "82Q": "Obliterate",
  "82W": "Indestructible",
  "82E": "Death's Grasp",
  "82R": "Realm of Death",
  "25P": "Soul Siphon",
  "25Q": "Dark Binding",
  "25W": "Tormented Shadow",
  "25E": "Black Shield",
  "25R": "Soul Shackles",
  "950P": "We Are More",
  "950Q": "Darkin Daggers",
  "950W": "The Call of the Pack",
  "950E": "Eviscerate",
  "950R": "Hounds' Pursuit",
  "267P": "Surging Tides",
  "267Q": "Aqua Prison",
  "267W": "Ebb and Flow",
  "267E": "Tidecaller's Blessing",
  "267R": "Tidal Wave",
  "75P": "Soul Eater",
  "75Q": "Siphoning Strike",
  "75W": "Wither",
  "75E": "Spirit Fire",
  "75R": "Fury of the Sands",
  "111P": "Staggering Blow",
  "111Q": "Dredge Line",
  "111W": "Titan's Wrath",
  "111E": "Riptide",
  "111R": "Depth Charge",
  "518P": "Inherent Glamour",
  "518Q": "Blooming Burst",
  "518W": "Shapesplitter",
  "518E": "Tangle-Barbs",
  "518R": "Pop Blossom",
  "76P": "Prowl",
  "76Q": "Takedown",
  "76W": "Pounce",
  "76E": "Swipe",
  "76R": "Aspect of the Cougar",
  "895P": "Joy Unending",
  "895Q": "Formless Blade",
  "895W": "Jubilant Veil",
  "895E": "Slipstream",
  "895R": "Apotheosis",
  "56P": "Umbra Blades",
  "56Q": "Duskbringer",
  "56W": "Shroud of Darkness",
  "56E": "Unspeakable Horror",
  "56R": "Paranoia",
  "20P": "Call of the Freljord",
  "20Q": "Consume",
  "20W": "Biggest Snowball Ever!",
  "20E": "Snowball Barrage",
  "20R": "Absolute Zero",
  "2P": "Berserker Rage",
  "2Q": "Undertow",
  "2W": "Tough It Out",
  "2E": "Reckless Swing",
  "2R": "Ragnarok",
  "61P": "Clockwork Windup",
  "61Q": "Command: Attack",
  "61W": "Command: Dissonance",
  "61E": "Command: Protect",
  "61R": "Command: Shockwave",
  "516P": "Living Forge",
  "516Q": "Volcanic Rupture",
  "516W": "Bellows Breath",
  "516E": "Searing Charge",
  "516R": "Call of the Forge God",
  "80P": "Mortal Will",
  "80Q": "Comet Spear",
  "80W": "Shield Vault",
  "80E": "Aegis Assault",
  "80R": "Grand Starfall",
  "78P": "Iron Ambassador",
  "78Q": "Hammer Shock",
  "78W": "Steadfast Presence",
  "78E": "Heroic Charge",
  "78R": "Keeper's Verdict",
  "555P": "Gift of the Drowned Ones",
  "555Q": "Bone Skewer",
  "555W": "Ghostwater Dive",
  "555E": "Phantom Undertow",
  "555R": "Death from Below",
  "246P": "Royal Privilege",
  "246Q": "Elemental Wrath",
  "246W": "Terrashape",
  "246E": "Audacity",
  "246R": "Supreme Display of Talent",
  "133P": "Harrier",
  "133Q": "Blinding Assault",
  "133W": "Heightened Senses",
  "133E": "Vault",
  "133R": "Skystrike",
  "497P": "Fey Feathers",
  "497Q": "Gleaming Quill",
  "497W": "Grand Entrance",
  "497E": "Battle Dance",
  "497R": "The Quickness",
  "33P": "Spiked Shell",
  "33Q": "Powerball",
  "33W": "Defensive Ball Curl",
  "33E": "Frenzying Taunt",
  "33R": "Soaring Slam",
  "421P": "Fury of the Xer'Sai",
  "421Q": "Prey Seeker",
  "421W": "Unburrow",
  "421E": "Tunnel",
  "421R": "Void Rush",
  "526P": "Break the Mold",
  "526Q": "Shattering Strike",
  "526W": "Ferromancy: Mount Up",
  "526E": "Full Tilt",
  "526R": "Magnet Storm",
  "888P": "Leverage",
  "888Q": "Handshake",
  "888W": "Bailout",
  "888E": "Loyalty Program",
  "888R": "Hostile Takeover",
  "58P": "Reign of Anger",
  "58Q": "Cull the Meek",
  "58W": "Ruthless Predator",
  "58E": "Slice and Dice",
  "58R": "Dominus",
  "107P": "Unseen Predator",
  "107Q": "Savagery",
  "107W": "Battle Roar",
  "107E": "Bola Strike",
  "107R": "Thrill of the Hunt",
  "92P": "Runic Blade",
  "92Q": "Broken Wings",
  "92W": "Ki Burst",
  "92E": "Valor",
  "92R": "Wind Slash",
  "68P": "Junkyard Titan",
  "68Q": "Flamespitter",
  "68W": "Scrap Shield",
  "68E": "Electro Harpoon",
  "68R": "The Equalizer",
  "13P": "Arcane Mastery",
  "13Q": "Overload",
  "13W": "Rune Prison",
  "13E": "Spell Flux",
  "13R": "Realm Warp",
  "360P": "Daredevil Impulse",
  "360Q": "Flair",
  "360W": "Blade Whirl",
  "360E": "Wild Rush",
  "360R": "Inferno Trigger",
  "113P": "Fury of the North",
  "113Q": "Arctic Assault",
  "113W": "Winter's Wrath",
  "113E": "Permafrost",
  "113R": "Glacial Prison",
  "235P": "Absolution",
  "235Q": "Piercing Darkness",
  "235W": "Last Embrace",
  "235E": "Curse of the Black Mist",
  "235R": "Dawning Shadow",
  "147P": "Stage Presence",
  "147Q": "High Note",
  "147W": "Surround Sound",
  "147E": "Beat Drop",
  "147R": "Encore",
  "875P": "Pit Grit",
  "875Q": "Knuckle Down",
  "875W": "Haymaker",
  "875E": "Facebreaker",
  "875R": "The Show Stopper",
  "35P": "Backstab",
  "35Q": "Deceive",
  "35W": "Jack in the Box",
  "35E": "Two-Shiv Poison",
  "35R": "Hallucinate",
  "98P": "Ki Barrier",
  "98Q": "Twilight Assault",
  "98W": "Spirit's Refuge",
  "98E": "Shadow Dash",
  "98R": "Stand United",
  "102P": "Scalemail",
  "102Q": "Emberstrike",
  "102W": "Inferno Aegis",
  "102E": "Molten Burst",
  "102R": "Dragon's Descent",
  "27P": "Noxious Slipstream",
  "27Q": "Poison Trail",
  "27W": "Mega Adhesive",
  "27E": "Fling",
  "27R": "Insanity Potion",
  "14P": "Death Surge",
  "14Q": "Decimating Smash",
  "14W": "Soul Furnace",
  "14E": "Roar of the Slayer",
  "14R": "Unstoppable Onslaught",
  "15P": "Fleet of Foot",
  "15Q": "Boomerang Blade",
  "15W": "Ricochet",
  "15E": "Spell Shield",
  "15R": "On the Hunt",
  "72P": "Threads of Vibration",
  "72Q": "Upheaval",
  "72W": "Seismic Bastion",
  "72E": "Ixtal's Impact",
  "72R": "Impale",
  "901P": "Dragon Practice",
  "901Q": "Super Scorcher Breath",
  "901W": "Achooo!",
  "901E": "Flap, Flap, Flap",
  "901R": "MMOOOMMMM!",
  "37P": "Power Chord",
  "37Q": "Hymn of Valor",
  "37W": "Aria of Perseverance",
  "37E": "Song of Celerity",
  "37R": "Crescendo",
  "16P": "Salvation",
  "16Q": "Starcall",
  "16W": "Astral Infusion",
  "16E": "Equinox",
  "16R": "Wish",
  "50P": "Ravenous Flock",
  "50Q": "Death's Hand",
  "50W": "Vision of Empire",
  "50E": "Nevermove",
  "50R": "Demonflare",
  "517P": "Petricite Burst",
  "517Q": "Chain Lash",
  "517W": "Kingslayer",
  "517E": "Abduct",
  "517R": "Hijack",
  "134P": "Transcendent",
  "134Q": "Dark Sphere",
  "134W": "Force of Will",
  "134E": "Scatter the Weak",
  "134R": "Unleashed Power",
  "223P": "An Acquired Taste",
  "223Q": "Tongue Lash",
  "223W": "Abyssal Dive",
  "223E": "Thick Skin",
  "223R": "Regurgitate",
  "163P": "Rock Surfing",
  "163Q": "Threaded Volley",
  "163W": "Seismic Shove",
  "163E": "Unraveled Earth",
  "163R": "Weaver's Wall",
  "91P": "Blade's End",
  "91Q": "Noxian Diplomacy",
  "91W": "Rake",
  "91E": "Assassin's Path",
  "91R": "Shadow Assault",
  "44P": "Bravado",
  "44Q": "Starlight's Touch",
  "44W": "Bastion",
  "44E": "Dazzle",
  "44R": "Cosmic Radiance",
  "17P": "Guerrilla Warfare",
  "17Q": "Blinding Dart",
  "17W": "Move Quick",
  "17E": "Toxic Shot",
  "17R": "Noxious Trap",
  "412P": "Damnation",
  "412Q": "Death Sentence",
  "412W": "Dark Passage",
  "412E": "Flay",
  "412R": "The Box",
  "18P": "Draw a Bead",
  "18Q": "Rapid Fire",
  "18W": "Rocket Jump",
  "18E": "Explosive Charge",
  "18R": "Buster Shot",
  "48P": "King's Tribute",
  "48Q": "Chomp",
  "48W": "Frozen Domain",
  "48E": "Pillar of Ice",
  "48R": "Subjugate",
  "23P": "Battle Fury",
  "23Q": "Bloodlust",
  "23W": "Mocking Shout",
  "23E": "Spinning Slash",
  "23R": "Undying Rage",
  "4P": "Loaded Dice",
  "4Q": "Wild Cards",
  "4W": "Pick a Card",
  "4E": "Stacked Deck",
  "4R": "Destiny",
  "29P": "Deadly Venom",
  "29Q": "Ambush",
  "29W": "Venom Cask",
  "29E": "Contaminate",
  "29R": "Spray and Pray",
  "77P": "Bridge Between",
  "77Q": "Wilding Claw",
  "77W": "Iron Mantle",
  "77E": "Blazing Stampede",
  "77R": "Wingborne Storm",
  "6P": "Echoing Flames",
  "6Q": "Corrosive Charge",
  "6W": "Purge",
  "6E": "Disdain",
  "6R": "Fear Beyond Death",
  "110P": "Living Vengeance",
  "110Q": "Piercing Arrow",
  "110W": "Blighted Quiver",
  "110E": "Hail of Arrows",
  "110R": "Chain of Corruption",
  "67P": "Night Hunter",
  "67Q": "Tumble",
  "67W": "Silver Bolts",
  "67E": "Condemn",
  "67R": "Final Hour",
  "45P": "Phenomenal Evil Power",
  "45Q": "Baleful Strike",
  "45W": "Dark Matter",
  "45E": "Event Horizon",
  "45R": "Primordial Burst",
  "161P": "Organic Deconstruction",
  "161Q": "Plasma Fission",
  "161W": "Void Rift",
  "161E": "Tectonic Disruption",
  "161R": "Life Form Disintegration Ray",
  "711P": "Doom 'n Gloom",
  "711Q": "Mistral Bolt",
  "711W": "Personal Space",
  "711E": "Looming Darkness",
  "711R": "Shadow Surge",
  "254P": "Blast Shield",
  "254Q": "Vault Breaker",
  "254W": "Denting Blows",
  "254E": "Relentless Force",
  "254R": "Cease and Desist",
  "234P": "Sovereign's Domination",
  "234Q": "Blade of the Ruined King",
  "234W": "Spectral Maw",
  "234E": "Harrowed Path",
  "234R": "Heartbreaker",
  "112P": "Glorious Evolution",
  "112Q": "Siphon Power",
  "112W": "Gravity Field",
  "112E": "Hextech Ray",
  "112R": "Arcane Storm",
  "8P": "Crimson Pact",
  "8Q": "Transfusion",
  "8W": "Sanguine Pool",
  "8E": "Tides of Blood",
  "8R": "Hemoplague",
  "106P": "The Relentless Storm",
  "106Q": "Thundering Smash",
  "106W": "Frenzied Maul",
  "106E": "Sky Splitter",
  "106R": "Stormbringer",
  "19P": "Eternal Hunger",
  "19Q": "Jaws of the Beast",
  "19W": "Blood Hunt",
  "19E": "Primal Howl",
  "19R": "Infinite Duress",
  "62P": "Stone Skin",
  "62Q": "Crushing Blow",
  "62W": "Warrior Trickster",
  "62E": "Nimbus Strike",
  "62R": "Cyclone",
  "498P": "Clean Cuts",
  "498Q": "Double Daggers",
  "498W": "Deadly Plumage",
  "498E": "Bladecaller",
  "498R": "Featherstorm",
  "101P": "Mana Surge",
  "101Q": "Arcanopulse",
  "101W": "Eye of Destruction",
  "101E": "Shocking Orb",
  "101R": "Rite of the Arcane",
  "5P": "Determination",
  "5Q": "Three Talon Strike",
  "5W": "Wind Becomes Lightning",
  "5E": "Audacious Charge",
  "5R": "Crescent Guard",
  "157P": "Way of the Wanderer",
  "157Q": "Steel Tempest",
  "157W": "Wind Wall",
  "157E": "Sweeping Blade",
  "157R": "Last Breath",
  "777P": "Way of the Hunter",
  "777Q": "Mortal Steel",
  "777W": "Spirit Cleave",
  "777E": "Soul Unbound",
  "777R": "Fate Sealed",
  "83P": "Shepherd of Souls",
  "83Q": "Awakening",
  "83W": "Dark Procession",
  "83E": "Mourning Mist",
  "83R": "Eulogy of the Isles",
  "804P": "Vow of the First Lands",
  "804Q": "Cultivation of Spirit",
  "804W": "Arc of Ruin",
  "804E": "Untouchable Shadow",
  "804R": "Transcend One's Self",
  "350P": "Feline Friendship",
  "350Q": "Prowling Projectile",
  "350W": "You and Me!",
  "350E": "Zoomies",
  "350R": "Final Chapter",
  "904P": "Cultivation of War",
  "904Q": "The Darkin Glaive",
  "904W": "Dreaded Return",
  "904E": "Aureate Rush",
  "904R": "Grim Deliverance",
  "154P": "Cell Division",
  "154Q": "Stretching Strikes",
  "154W": "Unstable Matter",
  "154E": "Elastic Slingshot",
  "154R": "Let's Bounce!",
  "238P": "Contempt for the Weak",
  "238Q": "Razor Shuriken",
  "238W": "Living Shadow",
  "238E": "Shadow Slash",
  "238R": "Death Mark",
  "221P": "Living Battery",
  "221Q": "Burst Fire",
  "221W": "Ultrashock Laser",
  "221E": "Spark Surge",
  "221R": "Lightning Crash",
  "115P": "Short Fuse",
  "115Q": "Bouncing Bomb",
  "115W": "Satchel Charge",
  "115E": "Hexplosive Minefield",
  "115R": "Mega Inferno Bomb",
  "26P": "Time in a Bottle",
  "26Q": "Time Bomb",
  "26W": "Rewind",
  "26E": "Time Warp",
  "26R": "Chronoshift",
  "142P": "More Sparkles!",
  "142Q": "Paddle Star!",
  "142W": "Spell Thief",
  "142E": "Sleepy Trouble Bubble",
  "142R": "Portal Jump",
  "143P": "Garden of Thorns",
  "143Q": "Deadly Spines",
  "143W": "Rampant Growth",
  "143E": "Grasping Roots",
  "143R": "Stranglethorns"
}