// Updated Patch 16.12 - 06/25/2026 10:32:45 PM CDT

export const championToTitle: Record<string, string> = {
  "Aatrox": "The Darkin Blade",
  "Ahri": "The Nine-Tailed Fox",
  "Akali": "The Rogue Assassin",
  "Akshan": "The Rogue Sentinel",
  "Alistar": "The Minotaur",
  "Ambessa": "Matriarch of War",
  "Amumu": "The Sad Mummy",
  "Anivia": "The Cryophoenix",
  "Annie": "The Dark Child",
  "Aphelios": "The Weapon of the Faithful",
  "Ashe": "The Frost Archer",
  "AurelionSol": "The Star Forger",
  "Aurora": "The Witch Between Worlds",
  "Azir": "The Emperor of the Sands",
  "Bard": "The Wandering Caretaker",
  "Belveth": "The Empress of the Void",
  "Blitzcrank": "The Great Steam Golem",
  "Brand": "The Burning Vengeance",
  "Braum": "The Heart of the Freljord",
  "Briar": "The Restrained Hunger",
  "Caitlyn": "The Sheriff of Piltover",
  "Camille": "The Steel Shadow",
  "Cassiopeia": "The Serpent's Embrace",
  "Chogath": "The Terror of the Void",
  "Corki": "The Daring Bombardier",
  "Darius": "The Hand of Noxus",
  "Diana": "Scorn of the Moon",
  "DrMundo": "The Madman of Zaun",
  "Draven": "The Glorious Executioner",
  "Ekko": "The Boy Who Shattered Time",
  "Elise": "The Spider Queen",
  "Evelynn": "Agony's Embrace",
  "Ezreal": "The Prodigal Explorer",
  "Fiddlesticks": "The Ancient Fear",
  "Fiora": "The Grand Duelist",
  "Fizz": "The Tidal Trickster",
  "Galio": "The Colossus",
  "Gangplank": "The Saltwater Scourge",
  "Garen": "The Might of Demacia",
  "Gnar": "The Missing Link",
  "Gragas": "The Rabble Rouser",
  "Graves": "The Outlaw",
  "Gwen": "The Hallowed Seamstress",
  "Hecarim": "The Shadow of War",
  "Heimerdinger": "The Revered Inventor",
  "Hwei": "The Visionary",
  "Illaoi": "The Kraken Priestess",
  "Irelia": "The Blade Dancer",
  "Ivern": "The Green Father",
  "Janna": "The Storm's Fury",
  "JarvanIV": "The Exemplar of Demacia",
  "Jax": "Grandmaster at Arms",
  "Jayce": "The Defender of Tomorrow",
  "Jhin": "The Virtuoso",
  "Jinx": "The Loose Cannon",
  "KSante": "The Pride of Nazumah",
  "Kaisa": "Daughter of the Void",
  "Kalista": "The Spear of Vengeance",
  "Karma": "The Enlightened One",
  "Karthus": "The Deathsinger",
  "Kassadin": "The Void Walker",
  "Katarina": "The Sinister Blade",
  "Kayle": "The Righteous",
  "Kayn": "The Shadow Reaper",
  "Kennen": "The Heart of the Tempest",
  "Khazix": "The Voidreaver",
  "Kindred": "The Eternal Hunters",
  "Kled": "The Cantankerous Cavalier",
  "KogMaw": "The Mouth of the Abyss",
  "Leblanc": "The Deceiver",
  "LeeSin": "The Blind Monk",
  "Leona": "The Radiant Dawn",
  "Lillia": "The Bashful Bloom",
  "Lissandra": "The Ice Witch",
  "Lucian": "The Purifier",
  "Lulu": "The Fae Sorceress",
  "Lux": "The Lady of Luminosity",
  "Malphite": "Shard of the Monolith",
  "Malzahar": "The Prophet of the Void",
  "Maokai": "The Twisted Treant",
  "MasterYi": "The Wuju Bladesman",
  "Mel": "The Soul's Reflection",
  "Milio": "The Gentle Flame",
  "MissFortune": "The Bounty Hunter",
  "Mordekaiser": "The Iron Revenant",
  "Morgana": "The Fallen",
  "Naafiri": "The Hound of a Hundred Bites",
  "Nami": "The Tidecaller",
  "Nasus": "The Curator of the Sands",
  "Nautilus": "The Titan of the Depths",
  "Neeko": "The Curious Chameleon",
  "Nidalee": "The Bestial Huntress",
  "Nilah": "The Joy Unbound",
  "Nocturne": "The Eternal Nightmare",
  "Nunu": "The Boy and His Yeti",
  "Olaf": "The Berserker",
  "Orianna": "The Lady of Clockwork",
  "Ornn": "The Fire Below the Mountain",
  "Pantheon": "The Unbreakable Spear",
  "Poppy": "Keeper of the Hammer",
  "Pyke": "The Bloodharbor Ripper",
  "Qiyana": "Empress of the Elements",
  "Quinn": "Demacia's Wings",
  "Rakan": "The Charmer",
  "Rammus": "The Armordillo",
  "RekSai": "The Void Burrower",
  "Rell": "The Iron Maiden",
  "Renata": "The Chem-Baroness",
  "Renekton": "The Butcher of the Sands",
  "Rengar": "The Pridestalker",
  "Riven": "The Exile",
  "Rumble": "The Mechanized Menace",
  "Ryze": "The Rune Mage",
  "Samira": "The Desert Rose",
  "Sejuani": "Fury of the North",
  "Senna": "The Redeemer",
  "Seraphine": "The Starry-Eyed Songstress",
  "Sett": "The Boss",
  "Shaco": "The Demon Jester",
  "Shen": "The Eye of Twilight",
  "Shyvana": "The Half-Dragon",
  "Singed": "The Mad Chemist",
  "Sion": "The Undead Juggernaut",
  "Sivir": "The Battle Mistress",
  "Skarner": "The Primordial Sovereign",
  "Smolder": "The Fiery Fledgling",
  "Sona": "Maven of the Strings",
  "Soraka": "The Starchild",
  "Swain": "The Noxian Grand General",
  "Sylas": "The Unshackled",
  "Syndra": "The Dark Sovereign",
  "TahmKench": "The River King",
  "Taliyah": "The Stoneweaver",
  "Talon": "The Blade's Shadow",
  "Taric": "The Shield of Valoran",
  "Teemo": "The Swift Scout",
  "Thresh": "The Chain Warden",
  "Tristana": "The Yordle Gunner",
  "Trundle": "The Troll King",
  "Tryndamere": "The Barbarian King",
  "TwistedFate": "The Card Master",
  "Twitch": "The Plague Rat",
  "Udyr": "The Spirit Walker",
  "Urgot": "The Dreadnought",
  "Varus": "The Arrow of Retribution",
  "Vayne": "The Night Hunter",
  "Veigar": "The Tiny Master of Evil",
  "Velkoz": "The Eye of the Void",
  "Vex": "The Gloomist",
  "Vi": "The Piltover Enforcer",
  "Viego": "The Ruined King",
  "Viktor": "The Herald of the Arcane",
  "Vladimir": "The Crimson Reaper",
  "Volibear": "The Relentless Storm",
  "Warwick": "The Uncaged Wrath of Zaun",
  "MonkeyKing": "The Monkey King",
  "Xayah": "The Rebel",
  "Xerath": "The Magus Ascendant",
  "XinZhao": "The Seneschal of Demacia",
  "Yasuo": "The Unforgiven",
  "Yone": "The Unforgotten",
  "Yorick": "Shepherd of Souls",
  "Yunara": "The Unbroken Faith",
  "Yuumi": "The Magical Cat",
  "Zaahen": "The Unsundered",
  "Zac": "The Secret Weapon",
  "Zed": "The Master of Shadows",
  "Zeri": "The Spark of Zaun",
  "Ziggs": "The Hexplosives Expert",
  "Zilean": "The Chronokeeper",
  "Zoe": "The Aspect of Twilight",
  "Zyra": "Rise of the Thorns"
}
