// Updated Patch 16.6 - 03/30/2026 12:54:59 PM CDT
import type { Skin } from "#shared/types"

type CompactSkin = readonly [
  id: string,
  name: string,
  keyOverride?: string,
  loadOverride?: string,
]

function defaultSkinKey(champion: string, id: string): string {
  return `${champion.toLowerCase()}_splash_<type>_${id}`
}

function defaultLoadKey(champion: string, id: string): string {
  const base = `${champion.toLowerCase()}loadscreen`
  return id === "0" ? base : `${base}_${id}`
}

function buildSkinIndex(compact: Record<string, readonly CompactSkin[]>): Record<string, Skin[]> {
  return Object.fromEntries(
    Object.entries(compact).map(([champion, skins]) => [
      champion,
      skins.map(([id, name, keyOverride, loadOverride]) => ({
        id,
        name,
        key: keyOverride ?? defaultSkinKey(champion, id),
        load: loadOverride ?? defaultLoadKey(champion, id),
      })),
    ]),
  )
}

const compactSkinIndex = {
  Aatrox: [
    ["0", "Original"],
    ["1", "Justicar"],
    ["2", "Mecha"],
    ["3", "Sea Hunter"],
    ["7", "Blood Moon"],
    ["8", "Prestige Blood Moon"],
    ["9", "Victorious"],
    ["11", "Odyssey"],
    ["8", "Prestige Blood Moon (2022)", undefined, "aatroxloadscreen_20"],
    ["21", "Lunar Eclipse"],
    ["30", "DRX"],
    ["31", "Prestige DRX"],
    ["33", "Primordian", "aatrox_splash_<type>_33.skins_aatrox_skin33", "aatroxloadscreen_33.skins_aatrox_skin33"],
  ],
  Ahri: [
    ["0", "Original", undefined, "ahriloadscreen_0"],
    ["1", "Dynasty"],
    ["2", "Midnight"],
    ["3", "Foxfire"],
    ["4", "Popstar"],
    ["5", "Challenger"],
    ["6", "Academy"],
    ["7", "Arcade"],
    ["14", "Star Guardian"],
    ["15", "KDA"],
    ["16", "Prestige KDA", undefined, "ahriloadscreen_16_le"],
    ["17", "Elderwood"],
    ["27", "Spirit Blossom"],
    ["28", "KDA ALL OUT"],
    ["42", "Coven"],
    ["65", "Prestige KDA (2022)", undefined, "ahriloadscreen_65_le"],
    ["66", "Arcana"],
    ["76", "Snow Moon"],
    ["85", "Risen Legend", "ahri_splash_<type>_85.skins_ahri_hol", "ahriloadscreen_85.skins_ahri_hol"],
    ["88", "Spirit Blossom Springs", "ahri_splash_<type>_88.skins_ahri_skin88", "ahriloadscreen_88.skins_ahri_skin88"],
    ["89", "After Hours Spirit Blossom Springs", "ahri_splash_<type>_89.skins_ahri_skin89", "ahriloadscreen_89.skins_ahri_skin89"],
  ],
  Akali: [
    ["0", "Original"],
    ["1", "Stinger"],
    ["2", "Infernal"],
    ["3", "All-star"],
    ["4", "Nurse"],
    ["5", "Blood Moon"],
    ["6", "Silverfang"],
    ["7", "Headhunter"],
    ["8", "Sashimi"],
    ["9", "KDA"],
    ["13", "Prestige KDA"],
    ["14", "PROJECT"],
    ["15", "True Damage"],
    ["32", "KDA ALL OUT"],
    ["50", "Crime City Nightmare"],
    ["13", "Prestige KDA (2022)", undefined, "akaliloadscreen_60"],
    ["61", "Star Guardian"],
    ["68", "DRX"],
    ["70", "Coven"],
    ["71", "Prestige Coven"],
    ["82", "Empyrean"],
    ["92", "Spirit Blossom", "akali_splash_<type>_92.skins_akali_skin92", "akaliloadscreen_92.skins_akali_skin92"],
  ],
  Akshan: [
    ["0", "Original"],
    ["1", "Cyber Pop"],
    ["10", "Crystal Rose"],
    ["20", "Three Honors"],
  ],
  Alistar: [
    ["0", "Original"],
    ["1", "Black"],
    ["2", "Golden"],
    ["4", "Longhorn"],
    ["3", "Matador"],
    ["5", "Unchained"],
    ["6", "Infernal"],
    ["7", "Sweeper"],
    ["8", "Marauder"],
    ["9", "SKT T1"],
    ["10", "Moo Cow"],
    ["19", "Hextech"],
    ["20", "Conqueror"],
    ["22", "Blackfrost"],
    ["29", "Lunar Beast"],
    ["40", "Elderwood", "alistar_splash_<type>_40.skins_alistar_skin40", "alistarloadscreen_40.skins_alistar_skin40"],
  ],
  Ambessa: [
    ["0", "Original", "ambessa_splash_<type>_0.domina", "ambessaloadscreen_0.domina"],
    ["1", "Chosen of the Wolf", "ambessa_splash_<type>_1.matcha_ambessa", "ambessaloadscreen_1.matcha_ambessa"],
  ],
  Amumu: [
    ["0", "Original"],
    ["1", "Pharaoh"],
    ["2", "Vancouver"],
    ["3", "Emumu"],
    ["4", "Re-Gifted"],
    ["5", "Almost-Prom King"],
    ["6", "Little Knight"],
    ["7", "Sad Robot"],
    ["8", "Surprise Party"],
    ["17", "Infernal"],
    ["23", "Hextech"],
    ["24", "Pumpkin Prince"],
    ["34", "Porcelain"],
    ["44", "Heartache"],
    ["53", "Dumpling Darlings", "amumu_splash_<type>_53.skins_amumu_skin53", "amumuloadscreen_53.skins_amumu_skin53"],
  ],
  Anivia: [
    ["0", "Original"],
    ["1", "Team Spirit"],
    ["2", "Bird of Prey"],
    ["3", "Noxus Hunter"],
    ["4", "Hextech"],
    ["5", "Blackfrost"],
    ["6", "Prehistoric"],
    ["7", "Festival Queen"],
    ["8", "Papercraft"],
    ["17", "Cosmic Flight"],
    ["27", "Divine Phoenix"],
    ["37", "Bewitching Batnivia"],
    ["46", "Victorious"],
  ],
  Annie: [
    ["0", "Original"],
    ["1", "Goth"],
    ["2", "Red Riding"],
    ["3", "Annie in Wonderland"],
    ["4", "Prom Queen"],
    ["6", "Reverse"],
    ["5", "Frostfire"],
    ["7", "FrankenTibbers"],
    ["8", "Panda"],
    ["9", "Sweetheart"],
    ["10", "Hextech"],
    ["11", "Super Galaxy"],
    ["12", "Annie-Versary"],
    ["13", "Lunar Beast"],
    ["22", "Cafe Cuties"],
    ["31", "Fright Night"],
    ["40", "Winterblessed"],
    ["50", "Battle Princess", "annie_splash_<type>_50.skins_annie_skin50", "annieloadscreen_50.skins_annie_skin50"],
  ],
  Aphelios: [
    ["0", "Original"],
    ["1", "Nightbringer"],
    ["9", "Lunar Beast"],
    ["18", "EDG"],
    ["20", "Spirit Blossom"],
    ["30", "HEARTSTEEL"],
    ["40", "Prestige Spirit Blossom Springs", "aphelios_splash_<type>_40.prestige2_onsen_aphelios", "apheliosloadscreen_40.prestige2_onsen_aphelios"],
  ],
  Ashe: [
    ["0", "Original"],
    ["1", "Freljord"],
    ["2", "Sherwood Forest"],
    ["3", "Woad"],
    ["4", "Queen"],
    ["5", "Amethyst"],
    ["6", "Heartseeker"],
    ["7", "Marauder"],
    ["8", "PROJECT"],
    ["9", "Worlds 2017"],
    ["11", "Cosmic Queen"],
    ["17", "High Noon"],
    ["23", "Fae Dragon"],
    ["32", "Coven"],
    ["43", "Ocean Song"],
    ["52", "Lunar Empress"],
    ["63", "DRX"],
    ["65", "Crystalis Motus"],
    ["67", "Infernal", "ashe_splash_<type>_67.skins_ashe_skin67", "asheloadscreen_67.skins_ashe_skin67"],
    ["76", "Spirit Blossom", "ashe_splash_<type>_76.skins_ashe_skin76", "asheloadscreen_76.skins_ashe_skin76"],
    ["84", "Firecracker", "ashe_splash_<type>_84.skins_ashe_skin84", "asheloadscreen_84.skins_ashe_skin84"],
  ],
  AurelionSol: [
    ["0", "Original"],
    ["1", "Ashen Lord"],
    ["2", "Mecha"],
    ["11", "Storm Dragon"],
    ["21", "Inkshadow"],
    ["31", "Porcelain Protector"],
    ["38", "Divine Architect Porcelain", "aurelionsol_splash_<type>_38.skins_aurelionsol_skin38", "aurelionsolloadscreen_38.skins_aurelionsol_skin38"],
  ],
  Aurora: [
    ["0", "Original", "aurora_splash_<type>_0.aurora", "auroraloadscreen_0.aurora"],
    ["1", "Battle Bunny", "aurora_splash_<type>_1.aurora", "auroraloadscreen_1.aurora"],
    ["11", "Arcana", "aurora_splash_<type>_11.skins_aurora_skin11", "auroraloadscreen_11.skins_aurora_skin11"],
  ],
  Azir: [
    ["0", "Original"],
    ["1", "Galactic"],
    ["2", "Gravelord"],
    ["3", "SKT T1"],
    ["4", "Warring Kingdoms"],
    ["5", "Elderwood"],
    ["14", "Worlds 2022"],
    ["19", "Attorney", "azir_splash_<type>_19.skins_azir_skin19", "azirloadscreen_19.skins_azir_skin19"],
  ],
  Bard: [
    ["0", "Original"],
    ["1", "Elderwood"],
    ["5", "Snow Day"],
    ["6", "Bard Bard"],
    ["8", "Astronaut"],
    ["17", "Cafe Cuties"],
    ["26", "Shan Hai Scrolls"],
    ["35", "T1", "bard_splash_<type>_35.skins_bard_skin35", "bardloadscreen_35.skins_bard_skin35"],
    ["37", "Spirit Blossom", "bard_splash_<type>_37.skins_bard_skin37", "bardloadscreen_37.skins_bard_skin37"],
  ],
  Belveth: [
    ["0", "Original", undefined, "belvethloadscreen_0"],
    ["1", "Battle Boss"],
    ["10", "Cosmic Matriarch"],
    ["19", "Primordian", "belveth_splash_<type>_19.skins_belveth_skin19", "belvethloadscreen_19.skins_belveth_skin19"],
  ],
  Blitzcrank: [
    ["0", "Original"],
    ["1", "Rusty"],
    ["2", "Goalkeeper"],
    ["3", "Boom Boom"],
    ["4", "Piltover Customs"],
    ["5", "Definitely Not"],
    ["6", "iBlitzcrank"],
    ["7", "Riot"],
    ["11", "Battle Boss"],
    ["21", "Lancer Paragon"],
    ["20", "Lancer Rogue"],
    ["22", "Witch's Brew"],
    ["29", "Space Groove"],
    ["36", "Victorious"],
    ["47", "Zenith Games"],
    ["56", "Beezcrank"],
    ["66", "Bubble Bash", "blitzcrank_splash_<type>_66.skins_blitzcrank_skin66", "blitzcrankloadscreen_66.skins_blitzcrank_skin66"],
  ],
  Brand: [
    ["0", "Original"],
    ["1", "Apocalyptic"],
    ["2", "Vandal"],
    ["3", "Cryocore"],
    ["4", "Zombie"],
    ["5", "Spirit Fire"],
    ["6", "Battle Boss"],
    ["7", "Arclight"],
    ["8", "Eternal Dragon"],
    ["21", "Debonair"],
    ["22", "Prestige Debonair"],
    ["33", "Street Demons"],
    ["42", "Empyrean"],
  ],
  Braum: [
    ["0", "Original"],
    ["1", "Dragonslayer"],
    ["2", "El Tigre"],
    ["3", "Braum Lionheart"],
    ["10", "Santa"],
    ["11", "Crime City"],
    ["24", "Sugar Rush"],
    ["33", "Pool Party"],
    ["42", "Grill Master", "braum_splash_<type>_42.skins_braum_skin42", "braumloadscreen_42.skins_braum_skin42"],
  ],
  Briar: [
    ["0", "Original", undefined, "briarloadscreen_0"],
    ["1", "Street Demons"],
    ["10", "Primordian", "briar_splash_<type>_10.skins_briar_skin10", "briarloadscreen_10.skins_briar_skin10"],
    ["20", "Battle Academia", "briar_splash_<type>_20.skins_briar_skin20", "briarloadscreen_20.skins_briar_skin20"],
  ],
  Caitlyn: [
    ["0", "Original", undefined, "caitlynloadscreen_0"],
    ["1", "Resistance"],
    ["2", "Sheriff"],
    ["3", "Safari"],
    ["5", "Officer"],
    ["4", "Arctic Warfare"],
    ["6", "Headhunter"],
    ["10", "Lunar Wraith"],
    ["11", "Pulsefire"],
    ["13", "Pool Party"],
    ["19", "Arcade"],
    ["20", "Prestige Arcade", undefined, "caitlynloadscreen_20_le"],
    ["22", "Battle Academia"],
    ["28", "Arcane Enforcer"],
    ["20", "Prestige Arcade (2022)", undefined, "caitlynloadscreen_29"],
    ["30", "Snow Moon"],
    ["39", "Heartthrob"],
    ["48", "DRX"],
    ["50", "Arcane Commander", "caitlyn_splash_<type>_50.skins_caitlyn_skin50", "caitlynloadscreen_50.skins_caitlyn_skin50"],
    ["51", "Prestige Arcane Commander", "caitlyn_splash_<type>_51.skins_caitlyn_skin51", "caitlynloadscreen_51.skins_caitlyn_skin51"],
    ["54", "Firecracker", "caitlyn_splash_<type>_54.skins_caitlyn_skin54", "caitlynloadscreen_54.skins_caitlyn_skin54"],
  ],
  Camille: [
    ["0", "Original"],
    ["1", "Program"],
    ["2", "Coven"],
    ["10", "iG"],
    ["11", "Arcana"],
    ["21", "Strike Commander"],
    ["31", "Winterblessed"],
    ["32", "Prestige Winterblessed"],
    ["44", "Petals of Spring", "camille_splash_<type>_44.skins_camille_skin44", "camilleloadscreen_44.skins_camille_skin44"],
  ],
  Cassiopeia: [
    ["0", "Original"],
    ["1", "Desperada"],
    ["2", "Siren"],
    ["3", "Mythic"],
    ["4", "Jade Fang"],
    ["8", "Eternum"],
    ["9", "Spirit Blossom"],
    ["18", "Coven"],
    ["28", "Bewitching"],
    ["38", "Prestige Mythmaker", "cassiopeia_splash_<type>_38.skins_cassiopeia_skin38", "cassiopeialoadscreen_38.skins_cassiopeia_skin38"],
  ],
  Chogath: [
    ["0", "Original"],
    ["1", "Nightmare"],
    ["2", "Gentleman"],
    ["3", "Loch Ness"],
    ["4", "Jurassic"],
    ["5", "Battlecast Prime"],
    ["6", "Prehistoric"],
    ["7", "Dark Star"],
    ["14", "Shan Hai Scrolls"],
    ["23", "Broken Covenant"],
    ["32", "Toy Terror"],
    ["41", "Petricite", "chogath_splash_<type>_41.skins_chogath_skin41", "chogathloadscreen_41.skins_chogath_skin41"],
  ],
  Corki: [
    ["0", "Original"],
    ["1", "UFO"],
    ["2", "Ice Toboggan"],
    ["3", "Red Baron"],
    ["4", "Hot Rod"],
    ["5", "Urfrider"],
    ["6", "Dragonwing"],
    ["7", "Fnatic"],
    ["8", "Arcade"],
    ["18", "Corgi"],
    ["26", "Astronaut"],
    ["36", "Brick Toy", "corki_splash_<type>_36.skins_corki_skin36", "corkiloadscreen_36.skins_corki_skin36"],
  ],
  Darius: [
    ["0", "Original"],
    ["1", "Lord"],
    ["2", "Bioforge"],
    ["3", "Woad King"],
    ["4", "Dunkmaster"],
    ["8", "Academy"],
    ["14", "Dreadnova"],
    ["15", "God-King"],
    ["16", "High Noon"],
    ["24", "Lunar Beast"],
    ["33", "Crime City Nightmare"],
    ["43", "Spirit Blossom"],
    ["54", "Porcelain"],
    ["64", "Divine God-King", "darius_splash_<type>_64.skins_darius_skin64", "dariusloadscreen_64.skins_darius_skin64"],
    ["65", "Prestige Triumphant General", "darius_splash_<type>_65.skins_darius_skin65", "dariusloadscreen_65.skins_darius_skin65"],
    ["67", "Mecha Kingdoms", "darius_splash_<type>_67.skins_darius_skin67", "dariusloadscreen_67.skins_darius_skin67"],
  ],
  Diana: [
    ["0", "Original"],
    ["1", "Dark Valkyrie"],
    ["2", "Lunar Goddess"],
    ["3", "Infernal"],
    ["11", "Blood Moon"],
    ["12", "Dark Waters"],
    ["18", "Dragonslayer"],
    ["25", "Battle Queen"],
    ["26", "Prestige Battle Queen"],
    ["27", "Sentinel"],
    ["37", "Firecracker"],
    ["47", "Winterblessed"],
    ["54", "Heavenscale"],
    ["64", "Dark Cosmic", "diana_splash_<type>_64.skins_diana_skin64", "dianaloadscreen_64.skins_diana_skin64"],
    ["65", "Prestige Dark Cosmic", "diana_splash_<type>_65.skins_diana_skin65", "dianaloadscreen_65.skins_diana_skin65"],
  ],
  DrMundo: [
    ["0", "Original", undefined, "drmundoloadscreen_0"],
    ["1", "Toxic"],
    ["2", "Mr. Mundoverse"],
    ["3", "Corporate Mundo"],
    ["4", "Mundo Mundo"],
    ["5", "Executioner Mundo"],
    ["6", "Rageborn Mundo"],
    ["7", "TPA Mundo"],
    ["8", "Pool Party Mundo"],
    ["9", "El Macho Mundo"],
    ["10", "Frozen Prince Mundo"],
    ["21", "Street Demons"],
  ],
  Draven: [
    ["0", "Original"],
    ["1", "Soul Reaver"],
    ["2", "Gladiator"],
    ["3", "Primetime"],
    ["4", "Pool Party"],
    ["5", "Beast Hunter"],
    ["6", "Draven Draven"],
    ["12", "Santa"],
    ["13", "Mecha Kingdoms"],
    ["20", "Ruined"],
    ["29", "Debonair"],
    ["39", "Fright Night"],
    ["48", "La Ilusión"],
    ["58", "Grand Reckoning", "draven_splash_<type>_58.skins_draven_skin58", "dravenloadscreen_58.skins_draven_skin58"],
    ["68", "Victorious", "draven_splash_<type>_68.skins_draven_skin68", "dravenloadscreen_68.skins_draven_skin68"],
  ],
  Ekko: [
    ["0", "Original"],
    ["1", "Sandstorm"],
    ["2", "Academy"],
    ["3", "PROJECT"],
    ["11", "SKT T1"],
    ["12", "Trick or Treat"],
    ["19", "True Damage"],
    ["28", "Pulsefire"],
    ["36", "Arcane Firelight"],
    ["45", "Star Guardian"],
    ["46", "Prestige Star Guardian"],
    ["56", "Breakout True Damage"],
    ["57", "Arcane Last Stand", "ekko_splash_<type>_57.skins_ekko_skin57", "ekkoloadscreen_57.skins_ekko_skin57"],
  ],
  Elise: [
    ["0", "Original"],
    ["1", "Death Blossom"],
    ["2", "Victorious"],
    ["3", "Blood Moon"],
    ["4", "SKT T1"],
    ["5", "Super Galaxy"],
    ["6", "Bewitching"],
    ["15", "Withered Rose"],
    ["24", "Coven"],
    ["34", "Masque of the Black Rose", "elise_splash_<type>_34.skins_elise_care_skin34", "eliseloadscreen_34.skins_elise_care_skin34"],
  ],
  Evelynn: [
    ["0", "Original"],
    ["1", "Shadow"],
    ["2", "Masquerade"],
    ["3", "Tango"],
    ["4", "Safecracker"],
    ["5", "Blood Moon"],
    ["6", "KDA"],
    ["7", "Prestige KDA"],
    ["8", "Sugar Rush"],
    ["15", "KDA ALL OUT"],
    ["24", "Coven"],
    ["7", "Prestige KDA (2022)", undefined, "evelynnloadscreen_31"],
    ["32", "Spirit Blossom"],
    ["42", "Soul Fighter"],
    ["52", "High Noon"],
    ["53", "Prestige High Noon"],
    ["64", "Nightbringer", "evelynn_splash_<type>_64.skins_evelynn_skin64", "evelynnloadscreen_64.skins_evelynn_skin64"],
  ],
  Ezreal: [
    ["0", "Original"],
    ["1", "Nottingham"],
    ["2", "Striker"],
    ["3", "Frosted"],
    ["4", "Explorer"],
    ["5", "Pulsefire"],
    ["6", "TPA"],
    ["7", "Debonair"],
    ["8", "Ace of Spades"],
    ["9", "Arcade"],
    ["18", "Star Guardian"],
    ["19", "SSG"],
    ["20", "Pajama Guardian"],
    ["21", "Battle Academia"],
    ["22", "PsyOps"],
    ["23", "Prestige PsyOps"],
    ["25", "Porcelain Protector"],
    ["33", "Faerie Court"],
    ["43", "HEARTSTEEL"],
    ["44", "Heavenscale"],
    ["54", "Prestige Heavenscale"],
    ["65", "Masque of the Black Rose", "ezreal_splash_<type>_65.skins_ezreal_skin65", "ezrealloadscreen_65.skins_ezreal_skin65"],
  ],
  Fiddlesticks: [
    ["0", "Original"],
    ["2", "Union Jack"],
    ["1", "Spectral"],
    ["5", "Fiddle Me Timbers"],
    ["3", "Bandito"],
    ["4", "Pumpkinhead"],
    ["6", "Surprise Party"],
    ["7", "Dark Candy"],
    ["8", "Risen"],
    ["9", "Praetorian"],
    ["27", "Star Nemesis"],
    ["37", "Blood Moon"],
    ["46", "Flora Fatalis", "fiddlesticks_splash_<type>_46.skins_fiddlesticks_skin46", "fiddlesticksloadscreen_46.skins_fiddlesticks_skin46"],
  ],
  Fiora: [
    ["0", "Original"],
    ["1", "Royal Guard"],
    ["2", "Nightraven"],
    ["3", "Headmistress"],
    ["4", "PROJECT"],
    ["5", "Pool Party"],
    ["22", "Soaring Sword"],
    ["23", "Heartpiercer"],
    ["31", "iG"],
    ["41", "Pulsefire"],
    ["50", "Lunar Beast"],
    ["51", "Prestige Lunar Beast"],
    ["60", "Bewitching"],
    ["69", "Faerie Court"],
    ["80", "Dragonmancer"],
    ["89", "Battle Queen", "fiora_splash_<type>_89.skins_fiora_skin89", "fioraloadscreen_89.skins_fiora_skin89"],
    ["98", "Victorious", "fiora_splash_<type>_98.skins_fiora_skin98", "fioraloadscreen_98.skins_fiora_skin98"],
  ],
  Fizz: [
    ["0", "Original"],
    ["1", "Atlantean"],
    ["2", "Tundra"],
    ["3", "Fisherman"],
    ["4", "Void"],
    ["8", "Cottontail"],
    ["9", "Super Galaxy"],
    ["10", "Omega Squad"],
    ["14", "Fuzz"],
    ["15", "Prestige Fuzz"],
    ["16", "Little Devil"],
    ["15", "Prestige Fuzz (2022)", undefined, "fizzloadscreen_25"],
    ["26", "Astronaut"],
    ["35", "Rain Shepherd", "fizz_splash_<type>_35.skins_fizz_skin35", "fizzloadscreen_35.skins_fizz_skin35"],
  ],
  Galio: [
    ["0", "Original"],
    ["1", "Enchanted"],
    ["2", "Hextech"],
    ["3", "Commando"],
    ["4", "Gatekeeper"],
    ["5", "Debonair"],
    ["6", "Birdio"],
    ["13", "Infernal"],
    ["19", "Dragon Guardian"],
    ["28", "Mythmaker"],
    ["40", "Aegis Frame", "galio_splash_<type>_40.skins_galio_skin40", "galioloadscreen_40.skins_galio_skin40"],
  ],
  Gangplank: [
    ["0", "Original"],
    ["1", "Spooky"],
    ["2", "Minuteman"],
    ["3", "Sailor"],
    ["4", "Toy Soldier"],
    ["5", "Special Forces"],
    ["6", "Sultan"],
    ["7", "Captain"],
    ["8", "Dreadnova"],
    ["14", "Pool Party"],
    ["21", "FPX"],
    ["23", "Gangplank the Betrayer"],
    ["33", "PROJECT"],
  ],
  Garen: [
    ["0", "Original"],
    ["1", "Sanguine"],
    ["2", "Desert Trooper"],
    ["3", "Commando"],
    ["4", "Dreadknight"],
    ["5", "Rugged"],
    ["6", "Steel Legion"],
    ["10", "Rogue Admiral"],
    ["11", "Warring Kingdoms"],
    ["13", "God-King"],
    ["14", "Demacia Vice"],
    ["22", "Mecha Kingdoms"],
    ["23", "Prestige Mecha Kingdoms"],
    ["24", "Battle Academia"],
    ["33", "Mythmaker"],
    ["44", "Fallen God-King", "garen_splash_<type>_44.skins_garen_skin44", "garenloadscreen_44.skins_garen_skin44"],
    ["43", "Pengu", "garen_splash_<type>_43.pengugaren", "garenloadscreen_43.pengugaren"],
    ["46", "Visions of the Fallen", "garen_splash_<type>_46.skins_garen_skin46", "garenloadscreen_46.skins_garen_skin46"],
  ],
  Gnar: [
    ["0", "Original"],
    ["1", "Dino"],
    ["2", "Gentleman"],
    ["3", "Snow Day"],
    ["4", "El León"],
    ["13", "Super Galaxy"],
    ["14", "SSG"],
    ["15", "Astronaut"],
    ["22", "Elderwood"],
    ["31", "La Ilusión"],
    ["41", "T1", "gnar_splash_<type>_41.skins_gnar_skin41", "gnarloadscreen_41.skins_gnar_skin41"],
  ],
  Gragas: [
    ["0", "Original"],
    ["1", "Scuba"],
    ["2", "Hillbilly"],
    ["3", "Santa"],
    ["4", "Gragas, Esq."],
    ["5", "Vandal"],
    ["6", "Oktoberfest"],
    ["7", "Superfan"],
    ["8", "Fnatic"],
    ["9", "Gragas Caskbreaker"],
    ["10", "Arctic Ops"],
    ["11", "Warden"],
    ["20", "Space Groove"],
    ["29", "High Noon"],
    ["39", "Music Fan", "gragas_splash_<type>_39.skins_gragas_skin39", "gragasloadscreen_39.skins_gragas_skin39"],
  ],
  Graves: [
    ["0", "Original"],
    ["1", "Hired Gun"],
    ["2", "Jailbreak"],
    ["3", "Crime City"],
    ["4", "Riot"],
    ["5", "Pool Party"],
    ["6", "Cutthroat"],
    ["7", "Snow Day"],
    ["14", "Victorious"],
    ["18", "Praetorian"],
    ["25", "Battle Professor"],
    ["35", "Sentinel"],
    ["42", "EDG"],
    ["45", "Porcelain"],
  ],
  Gwen: [
    ["0", "Original", undefined, "gwenloadscreen_0"],
    ["1", "Space Groove"],
    ["11", "Cafe Cuties"],
    ["20", "Soul Fighter"],
    ["30", "Battle Queen", "gwen_splash_<type>_30.skins_gwen_skin30", "gwenloadscreen_30.skins_gwen_skin30"],
    ["39", "Rain Shepherd", "gwen_splash_<type>_39.skins_gwen_skin39", "gwenloadscreen_39.skins_gwen_skin39"],
  ],
  Hecarim: [
    ["0", "Original", undefined, "hecarimloadscreen_0"],
    ["1", "Blood Knight"],
    ["2", "Reaper"],
    ["3", "Headless"],
    ["4", "Arcade"],
    ["5", "Elderwood"],
    ["6", "Worldbreaker"],
    ["7", "Lancer Zero"],
    ["8", "High Noon"],
    ["14", "Cosmic Charger"],
    ["22", "Arcana"],
    ["31", "Winterblessed"],
    ["41", "Nightbringer", "hecarim_splash_<type>_41.skins_hecarim_skin41", "hecarimloadscreen_41.skins_hecarim_skin41"],
  ],
  Heimerdinger: [
    ["0", "Original"],
    ["2", "Blast Zone"],
    ["1", "Alien Invader"],
    ["3", "Piltover Customs"],
    ["4", "Snowmerdinger"],
    ["5", "Hazmat"],
    ["6", "Dragon Trainer"],
    ["15", "Pool Party"],
    ["24", "Heimerstinger"],
    ["33", "Arcane Professor", "heimerdinger_splash_<type>_33.skins_heimerdinger_skin33", "heimerdingerloadscreen_33.skins_heimerdinger_skin33"],
  ],
  Hwei: [
    ["0", "Original", undefined, "hweiloadscreen_0"],
    ["1", "Winterblessed"],
    ["11", "Spirit Blossom", "hwei_splash_<type>_11.skins_hwei_skin11", "hweiloadscreen_11.skins_hwei_skin11"],
  ],
  Illaoi: [
    ["0", "Original"],
    ["1", "Void Bringer"],
    ["2", "Resistance"],
    ["10", "Cosmic Invoker"],
    ["18", "Snow Moon"],
    ["27", "Battle Bear", "illaoi_splash_<type>_27.skins_illaoi_skin27", "illaoiloadscreen_27.skins_illaoi_skin27"],
  ],
  Irelia: [
    ["0", "Original"],
    ["2", "Aviator"],
    ["1", "Nightblade"],
    ["3", "Infiltrator"],
    ["4", "Frostblade"],
    ["5", "Order of the Lotus"],
    ["6", "Divine Sword"],
    ["15", "iG"],
    ["16", "PROJECT"],
    ["17", "Prestige PROJECT"],
    ["18", "High Noon"],
    ["26", "Sentinel"],
    ["17", "Prestige PROJECT (2022)", undefined, "irelialoadscreen_36"],
    ["37", "Mythmaker"],
    ["45", "Porcelain"],
    ["55", "Spirit Blossom", "irelia_splash_<type>_55.skins_irelia_skin55", "irelialoadscreen_55.skins_irelia_skin55"],
  ],
  Ivern: [
    ["0", "Original"],
    ["1", "Candy King"],
    ["2", "Dunkmaster"],
    ["11", "Old God"],
    ["20", "Astronaut"],
    ["30", "Spirit Blossom", "ivern_splash_<type>_30.skins_ivern_skin30", "ivernloadscreen_30.skins_ivern_skin30"],
  ],
  Janna: [
    ["0", "Original"],
    ["1", "Tempest"],
    ["2", "Hextech"],
    ["3", "Frost Queen"],
    ["4", "Victorious"],
    ["5", "Forecast"],
    ["6", "Fnatic"],
    ["7", "Star Guardian"],
    ["8", "Sacred Sword"],
    ["13", "Bewitching"],
    ["20", "Guardian of the Sands"],
    ["27", "Battle Queen"],
    ["36", "Crystal Rose"],
    ["45", "Cyber Halo"],
    ["46", "Prestige Cyber Halo"],
    ["56", "Heavenscale"],
    ["66", "Dawnbringer", "janna_splash_<type>_66.skins_janna_skin66", "jannaloadscreen_66.skins_janna_skin66"],
  ],
  JarvanIV: [
    ["0", "Original"],
    ["1", "Commando"],
    ["2", "Dragonslayer"],
    ["3", "Darkforge"],
    ["4", "Victorious"],
    ["5", "Warring Kingdoms"],
    ["6", "Fnatic"],
    ["7", "Dark Star"],
    ["8", "SSG"],
    ["9", "Hextech"],
    ["11", "Pool Party"],
    ["21", "Lunar Beast"],
    ["30", "Worlds 2021"],
    ["35", "Nightbringer"],
    ["44", "Mythmaker", "jarvaniv_splash_<type>_44.skins_jarvaniv_skin44", "jarvanivloadscreen_44.skins_jarvaniv_skin44"],
    ["54", "Prestige Visions of the Fallen", "jarvaniv_splash_<type>_54.skins_jarvaniv_skin54", "jarvanivloadscreen_54.skins_jarvaniv_skin54"],
  ],
  Jax: [
    ["0", "Original", undefined, "jaxloadscreen_0"],
    ["1", "The Mighty"],
    ["2", "Vandal"],
    ["4", "PAX"],
    ["3", "Angler"],
    ["5", "Jaximus"],
    ["6", "Temple"],
    ["7", "Nemesis"],
    ["8", "SKT T1"],
    ["12", "Warden"],
    ["13", "God Staff"],
    ["14", "Mecha Kingdoms"],
    ["20", "Conqueror"],
    ["21", "Prestige Conqueror"],
    ["22", "Empyrean"],
    ["32", "Neo PAX"],
    ["33", "PROJECT"],
  ],
  Jayce: [
    ["0", "Original"],
    ["1", "Full Metal"],
    ["2", "Debonair"],
    ["3", "Forsaken"],
    ["4", "Jayce Brighthammer"],
    ["5", "Battle Academia"],
    ["15", "Resistance"],
    ["24", "Arcane Inventor"],
    ["25", "Zenith Games"],
    ["34", "T1", "jayce_splash_<type>_34.skins_jayce_skin34", "jayceloadscreen_34.skins_jayce_skin34"],
    ["36", "Prestige T1", "jayce_splash_<type>_36.prestige2_worldswinners_jayce", "jayceloadscreen_36.prestige2_worldswinners_jayce"],
    ["35", "Arcane Survivor", "jayce_splash_<type>_35.skins_jayce_skin35", "jayceloadscreen_35.skins_jayce_skin35"],
    ["38", "Petals of Spring", "jayce_splash_<type>_38.skins_jayce_skin38", "jayceloadscreen_38.skins_jayce_skin38"],
  ],
  Jhin: [
    ["0", "Original"],
    ["1", "High Noon"],
    ["2", "Blood Moon"],
    ["3", "SKT T1"],
    ["4", "PROJECT"],
    ["5", "Dark Cosmic"],
    ["14", "Shan Hai Scrolls"],
    ["23", "DWG"],
    ["25", "Empyrean"],
    ["36", "Soul Fighter"],
    ["37", "Dark Cosmic Erasure"],
    ["47", "Mythmaker", "jhin_splash_<type>_47.skins_jhin_skin47", "jhinloadscreen_47.skins_jhin_skin47"],
    ["55", "Arcana", "jhin_splash_<type>_55.skins_jhin_skin55", "jhinloadscreen_55.skins_jhin_skin55"],
  ],
  Jinx: [
    ["0", "Original"],
    ["1", "Crime City"],
    ["2", "Firecracker"],
    ["3", "Zombie Slayer"],
    ["4", "Star Guardian"],
    ["12", "Ambitious Elf"],
    ["13", "Odyssey"],
    ["20", "PROJECT"],
    ["29", "Heartseeker"],
    ["37", "Arcane Enemy"],
    ["38", "Battle Cat"],
    ["40", "Prestige Battle Cat"],
    ["51", "Cafe Cuties"],
    ["62", "T1", "jinx_splash_<type>_62.skins_jinx_skin62", "jinxloadscreen_62.skins_jinx_skin62"],
    ["60", "Arcane Fractured", "jinx_splash_<type>_60.skins_jinx_skin60_projectcare", "jinxloadscreen_60.skins_jinx_skin60_projectcare"],
  ],
  KSante: [
    ["0", "Original", undefined, "ksanteloadscreen_0"],
    ["1", "Empyrean"],
    ["2", "Prestige Empyrean"],
    ["8", "HEARTSTEEL"],
  ],
  Kaisa: [
    ["0", "Original"],
    ["1", "Bullet Angel"],
    ["14", "KDA"],
    ["15", "Prestige KDA"],
    ["16", "iG"],
    ["17", "Arcade"],
    ["26", "KDA ALL OUT"],
    ["27", "Prestige KDA ALL OUT"],
    ["29", "Lagoon Dragon"],
    ["15", "Prestige KDA (2022)", undefined, "kaisaloadscreen_39"],
    ["40", "Star Guardian"],
    ["48", "Inkshadow"],
    ["59", "Heavenscale"],
    ["69", "Dark Star", "kaisa_splash_<type>_69.skins_kaisa_skin69", "kaisaloadscreen_69.skins_kaisa_skin69"],
    ["70", "Risen Legend", "kaisa_splash_<type>_70.skins_kaisa_hol", "kaisaloadscreen_70.skins_kaisa_hol"],
  ],
  Kalista: [
    ["0", "Original"],
    ["1", "Blood Moon"],
    ["2", "Worlds 2015"],
    ["3", "SKT T1"],
    ["5", "Marauder"],
    ["14", "Faerie Court"],
    ["24", "Dawnbringer", "kalista_splash_<type>_24.skins_kalista_skin24", "kalistaloadscreen_24.skins_kalista_skin24"],
  ],
  Karma: [
    ["0", "Original"],
    ["2", "Sakura"],
    ["1", "Sun Goddess"],
    ["3", "Traditional"],
    ["4", "Order of the Lotus"],
    ["5", "Warden"],
    ["6", "Winter Wonder"],
    ["7", "Conqueror"],
    ["8", "Dark Star"],
    ["19", "Dawnbringer"],
    ["26", "Odyssey"],
    ["27", "Ruined"],
    ["44", "Tranquility Dragon"],
    ["54", "Faerie Queen"],
    ["61", "Infernal", "karma_splash_<type>_61.skins_karma_skin61", "karmaloadscreen_61.skins_karma_skin61"],
    ["70", "Spirit Blossom", "karma_splash_<type>_70.skins_karma_skin70", "karmaloadscreen_70.skins_karma_skin70"],
  ],
  Karthus: [
    ["0", "Original"],
    ["1", "Phantom"],
    ["2", "Statue of Karthus"],
    ["3", "Grim Reaper"],
    ["4", "Pentakill"],
    ["5", "Fnatic"],
    ["9", "Karthus Lightsbane"],
    ["10", "Infernal"],
    ["17", "Pentakill Lost Chapter"],
    ["26", "Elderwood"],
    ["35", "Arcana", "karthus_splash_<type>_35.skins_karthus_skin35", "karthusloadscreen_35.skins_karthus_skin35"],
  ],
  Kassadin: [
    ["0", "Original", undefined, "kassadinloadscreen_0"],
    ["1", "Festival"],
    ["2", "Deep One"],
    ["3", "Pre-Void"],
    ["4", "Harbinger"],
    ["5", "Cosmic Reaver"],
    ["6", "Count"],
    ["14", "Hextech"],
    ["15", "Shockblade"],
    ["24", "Dragonmancer"],
  ],
  Katarina: [
    ["0", "Original"],
    ["1", "Mercenary"],
    ["2", "Red Card"],
    ["3", "Bilgewater"],
    ["4", "Kitty Cat"],
    ["5", "High Command"],
    ["6", "Sandstorm"],
    ["7", "Slay Belle"],
    ["8", "Warring Kingdoms"],
    ["9", "PROJECT"],
    ["10", "Death Sworn"],
    ["12", "Battle Academia"],
    ["21", "Blood Moon"],
    ["29", "Battle Queen"],
    ["37", "High Noon"],
    ["47", "Faerie Court"],
    ["48", "Prestige Faerie Court"],
    ["59", "Chosen of the Wolf", "katarina_splash_<type>_59.skins_katarina_skin59", "katarinaloadscreen_59.skins_katarina_skin59"],
    ["60", "Prestige Masque of the Black Rose", "katarina_splash_<type>_60.skins_katarina_skin60", "katarinaloadscreen_60.skins_katarina_skin60"],
    ["70", "Petals of Spring", "katarina_splash_<type>_70.skins_katarina_skin70", "katarinaloadscreen_70.skins_katarina_skin70"],
  ],
  Kayle: [
    ["0", "Original"],
    ["1", "Silver"],
    ["2", "Viridian"],
    ["3", "Transcended"],
    ["4", "Battleborn"],
    ["5", "Judgment"],
    ["6", "Aether Wing"],
    ["7", "Riot"],
    ["8", "Iron Inquisitor"],
    ["9", "Pentakill"],
    ["15", "PsyOps"],
    ["24", "Dragonslayer"],
    ["33", "Pentakill Lost Chapter"],
    ["42", "Sun-Eater"],
    ["57", "Immortal Journey"],
    ["66", "Empyrean"],
    ["67", "Prestige Empyrean"],
    ["78", "Spirit Blossom", "kayle_splash_<type>_78.skins_kayle_skin78", "kayleloadscreen_78.skins_kayle_skin78"],
  ],
  Kayn: [
    ["0", "Original"],
    ["1", "Soulhunter"],
    ["2", "Odyssey"],
    ["8", "Nightbringer"],
    ["9", "Prestige Nightbringer"],
    ["15", "Snow Moon"],
    ["20", "HEARTSTEEL"],
    ["26", "Battle Academia", "kayn_splash_<type>_26.skins_kayn_skin26", "kaynloadscreen_26.skins_kayn_skin26"],
  ],
  Kennen: [
    ["0", "Original"],
    ["1", "Deadly"],
    ["2", "Swamp Master"],
    ["3", "Karate"],
    ["4", "Kennen M.D."],
    ["5", "Arctic Ops"],
    ["6", "Blood Moon"],
    ["7", "Super"],
    ["8", "Infernal"],
    ["23", "DWG"],
    ["25", "Astronaut"],
  ],
  Khazix: [
    ["0", "Original"],
    ["1", "Mecha"],
    ["2", "Guardian of the Sands"],
    ["3", "Death Blossom"],
    ["4", "Dark Star"],
    ["11", "Worlds 2018"],
    ["60", "Odyssey"],
    ["69", "Lunar Guardian"],
    ["79", "Crystalis Indomitus"],
  ],
  Kindred: [
    ["0", "Original"],
    ["1", "Shadowfire"],
    ["2", "Super Galaxy"],
    ["3", "Spirit Blossom"],
    ["12", "Porcelain"],
    ["22", "Woof and Lamb"],
    ["23", "DRX"],
    ["33", "Prestige Porcelain"],
    ["34", "Chosen of the Wolf", "kindred_splash_<type>_34.skins_kindred_skin34", "kindredloadscreen_34.skins_kindred_skin34"],
  ],
  Kled: [
    ["0", "Original"],
    ["1", "Sir"],
    ["2", "Count Kledula"],
    ["9", "Marauder"],
    ["18", "Kibble-Head"],
  ],
  KogMaw: [
    ["0", "Original"],
    ["1", "Caterpillar"],
    ["2", "Sonoran"],
    ["3", "Monarch"],
    ["4", "Reindeer"],
    ["5", "Lion Dance"],
    ["6", "Deep Sea"],
    ["7", "Jurassic"],
    ["8", "Battlecast"],
    ["9", "Pug'Maw"],
    ["10", "Hextech"],
    ["19", "Arcanist"],
    ["28", "Bee'Maw"],
    ["37", "Zap'Maw"],
    ["46", "Shan Hai Scrolls"],
    ["55", "Victorious", "kogmaw_splash_<type>_55.skins_kogmaw_skin55", "kogmawloadscreen_55.skins_kogmaw_skin55"],
  ],
  Leblanc: [
    ["0", "Original", "leblanc_splash_<type>_0.leblanc_rework", "leblancloadscreen_0.leblanc_rework"],
    ["2", "Prestigious", "leblanc_splash_<type>_2.leblanc_rework", "leblancloadscreen_2.leblanc_rework"],
    ["1", "Wicked", "leblanc_splash_<type>_1.leblanc_rework", "leblancloadscreen_1.leblanc_rework"],
    ["3", "Mistletoe", "leblanc_splash_<type>_3.leblanc_rework", "leblancloadscreen_3.leblanc_rework"],
    ["4", "Ravenborn", "leblanc_splash_<type>_4.leblanc_rework", "leblancloadscreen_4.leblanc_rework"],
    ["5", "Elderwood", "leblanc_splash_<type>_5.leblanc_rework", "leblancloadscreen_5.leblanc_rework"],
    ["12", "Program", "leblanc_splash_<type>_12.leblanc_rework", "leblancloadscreen_12.leblanc_rework"],
    ["19", "iG", "leblanc_splash_<type>_19.leblanc_rework", "leblancloadscreen_19.leblanc_rework"],
    ["20", "Coven", "leblanc_splash_<type>_20.leblanc_rework", "leblancloadscreen_20.leblanc_rework"],
    ["29", "Worlds 2020", "leblanc_splash_<type>_29.leblanc_rework", "leblancloadscreen_29.leblanc_rework"],
    ["33", "Prestige Coven", "leblanc_splash_<type>_33.leblanc_rework", "leblancloadscreen_33.leblanc_rework"],
    ["35", "Debonair", "leblanc_splash_<type>_35.leblanc_rework", "leblancloadscreen_35.leblanc_rework"],
    ["45", "Bewitching", "leblanc_splash_<type>_45.leblanc_rework", "leblancloadscreen_45.leblanc_rework"],
    ["55", "Risen Legend", "leblanc_splash_<type>_55.leblanc_rework", "leblancloadscreen_55.leblanc_rework"],
  ],
  LeeSin: [
    ["0", "Original", undefined, "leesinloadscreen_0"],
    ["2", "Acolyte"],
    ["1", "Traditional"],
    ["3", "Dragon Fist"],
    ["4", "Muay Thai"],
    ["5", "Pool Party"],
    ["6", "SKT T1"],
    ["10", "Knockout"],
    ["11", "God Fist"],
    ["12", "Playmaker"],
    ["27", "Nightbringer"],
    ["28", "Prestige Nightbringer", undefined, "leesinloadscreen_28_le"],
    ["29", "FPX"],
    ["31", "Storm Dragon"],
    ["39", "Prestige Nightbringer (2022)", undefined, "leesinloadscreen_39_le"],
    ["41", "Zenith Games"],
    ["51", "Heavenscale"],
    ["52", "Divine Heavenscale"],
    ["68", "T1", "leesin_splash_<type>_68.skins_leesin_skin68", "leesinloadscreen_68.skins_leesin_skin68"],
    ["72", "Inkshadow", "leesin_splash_<type>_72.skins_leesin_skin72", "leesinloadscreen_72.skins_leesin_skin72"],
  ],
  Leona: [
    ["0", "Original"],
    ["1", "Valkyrie"],
    ["2", "Defender"],
    ["3", "Iron Solari"],
    ["4", "Pool Party"],
    ["8", "PROJECT"],
    ["9", "Barbecue"],
    ["10", "Solar Eclipse"],
    ["11", "Lunar Eclipse"],
    ["12", "Mecha Kingdoms"],
    ["21", "Battle Academia"],
    ["23", "Prestige Battle Academia"],
    ["22", "DWG"],
    ["33", "Debonair"],
    ["34", "High Noon"],
    ["50", "Crystalis Motus"],
    ["52", "Battle Lion", "leona_splash_<type>_52.skins_leona_skin52", "leonaloadscreen_52.skins_leona_skin52"],
    ["53", "Prestige Battle Lion", "leona_splash_<type>_53.prestige2_animasquad_leona", "leonaloadscreen_53.prestige2_animasquad_leona"],
  ],
  Lillia: [
    ["0", "Original"],
    ["1", "Spirit Blossom"],
    ["10", "Nightbringer"],
    ["19", "Shan Hai Scrolls"],
    ["28", "Faerie Court"],
    ["37", "Bowling League", "lillia_splash_<type>_37.skins_lillia_skin37", "lillialoadscreen_37.skins_lillia_skin37"],
    ["46", "Petals of Spring", "lillia_splash_<type>_46.skins_lillia_skin46", "lillialoadscreen_46.skins_lillia_skin46"],
  ],
  Lissandra: [
    ["0", "Original"],
    ["1", "Bloodstone"],
    ["2", "Blade Queen"],
    ["3", "Program"],
    ["4", "Coven"],
    ["12", "Dark Cosmic"],
    ["23", "Porcelain"],
    ["34", "Space Groove"],
    ["33", "Prestige Porcelain"],
    ["43", "Flora Fatalis", "lissandra_splash_<type>_43.skins_lissandra_skin43", "lissandraloadscreen_43.skins_lissandra_skin43"],
  ],
  Lucian: [
    ["0", "Original"],
    ["1", "Hired Gun"],
    ["2", "Striker"],
    ["6", "PROJECT"],
    ["7", "Heartseeker"],
    ["8", "High Noon"],
    ["9", "Demacia Vice"],
    ["18", "Pulsefire"],
    ["19", "Prestige Pulsefire"],
    ["25", "Victorious"],
    ["31", "Arcana"],
    ["40", "Strike Paladin"],
    ["52", "Winterblessed"],
    ["62", "Masked Justice", "lucian_splash_<type>_62.skins_lucian_skin62", "lucianloadscreen_62.skins_lucian_skin62"],
    ["72", "Sunken Shadows", "lucian_splash_<type>_72.skins_lucian_skin72", "lucianloadscreen_72.skins_lucian_skin72"],
  ],
  Lulu: [
    ["0", "Original"],
    ["1", "Bittersweet"],
    ["2", "Wicked"],
    ["3", "Dragon Trainer"],
    ["4", "Winter Wonder"],
    ["5", "Pool Party"],
    ["6", "Star Guardian"],
    ["14", "Cosmic Enchantress"],
    ["15", "Pajama Guardian"],
    ["26", "Space Groove"],
    ["27", "Prestige Space Groove"],
    ["37", "Monster Tamer"],
    ["46", "Cafe Cuties"],
    ["55", "Arcana", "lulu_splash_<type>_55.skins_lulu_skin55", "lululoadscreen_55.skins_lulu_skin55"],
  ],
  Lux: [
    ["0", "Original"],
    ["1", "Sorceress"],
    ["2", "Spellthief"],
    ["3", "Commando"],
    ["4", "Imperial"],
    ["5", "Steel Legion"],
    ["6", "Star Guardian"],
    ["7", "Elementalist"],
    ["8", "Lunar Empress"],
    ["14", "Pajama Guardian"],
    ["15", "Battle Academia"],
    ["16", "Prestige Battle Academia"],
    ["17", "Dark Cosmic"],
    ["18", "Cosmic"],
    ["19", "Space Groove"],
    ["29", "Porcelain"],
    ["40", "Prestige Porcelain"],
    ["16", "Prestige Battle Academia (2022)", undefined, "luxloadscreen_39"],
    ["42", "Empyrean"],
    ["38", "Soul Fighter"],
    ["61", "Faerie Court"],
    ["70", "Prestige Spirit Blossom", "lux_splash_<type>_70.skins_lux_skin70", "luxloadscreen_70.skins_lux_skin70"],
    ["72", "Panda Pal", "lux_splash_<type>_72.skins_lux_skin72", "luxloadscreen_72.skins_lux_skin72"],
  ],
  Malphite: [
    ["0", "Original"],
    ["1", "Shamrock"],
    ["2", "Coral Reef"],
    ["3", "Marble"],
    ["4", "Obsidian"],
    ["5", "Glacial"],
    ["6", "Mecha"],
    ["7", "Ironside"],
    ["16", "Odyssey"],
    ["23", "Dark Star"],
    ["24", "Prestige Dark Star"],
    ["25", "FPX"],
    ["27", "Old God"],
    ["37", "Lunar Guardian"],
    ["48", "Pool Party", "malphite_splash_<type>_48.skins_malphite_skin48", "malphiteloadscreen_48.skins_malphite_skin48"],
  ],
  Malzahar: [
    ["0", "Original"],
    ["1", "Vizier"],
    ["2", "Shadow Prince"],
    ["3", "Djinn"],
    ["4", "Overlord"],
    ["5", "Snow Day"],
    ["6", "Battle Boss"],
    ["7", "Hextech"],
    ["9", "Worldbreaker"],
    ["18", "Beezahar"],
    ["28", "Debonair"],
    ["38", "Three Honors"],
    ["39", "Empyrean"],
    ["49", "Fatebreaker", "malzahar_splash_<type>_49.skins_malzahar_skin49", "malzaharloadscreen_49.skins_malzahar_skin49"],
  ],
  Maokai: [
    ["0", "Original"],
    ["1", "Charred"],
    ["2", "Totemic"],
    ["3", "Festive"],
    ["4", "Haunted"],
    ["5", "Goalkeeper"],
    ["6", "Meowkai"],
    ["7", "Victorious"],
    ["16", "Worldbreaker"],
    ["24", "Astronaut"],
    ["33", "DRX"],
    ["35", "Corrupted Petricite", "maokai_splash_<type>_35.skins_maokai_skin35", "maokailoadscreen_35.skins_maokai_skin35"],
  ],
  MasterYi: [
    ["0", "Original"],
    ["1", "Assassin"],
    ["2", "Chosen"],
    ["3", "Ionia"],
    ["4", "Samurai Yi"],
    ["5", "Headhunter"],
    ["9", "PROJECT Yi"],
    ["10", "Cosmic Blade"],
    ["11", "Eternal Sword Yi"],
    ["17", "Snow Man Yi"],
    ["24", "Blood Moon"],
    ["33", "PsyOps"],
    ["42", "Debonair"],
    ["52", "Spirit Blossom"],
    ["53", "Prestige Spirit Blossom"],
    ["89", "Inkshadow"],
    ["96", "Heavenscale"],
    ["106", "Victorious", "masteryi_splash_<type>_106.skins_masteryi_skin106", "masteryiloadscreen_106.skins_masteryi_skin106"],
  ],
  Mel: [
    ["0", "Original", "mel_splash_<type>_0.mel", "melloadscreen_0.mel"],
    ["1", "Arcane Councilor", "mel_splash_<type>_1.mel", "melloadscreen_1.mel"],
    ["10", "Prestige Winterblessed", "mel_splash_<type>_10.skins_mel_skin10", "melloadscreen_10.skins_mel_skin10"],
  ],
  Milio: [
    ["0", "Original", undefined, "milioloadscreen_0"],
    ["1", "Faerie Court"],
    ["11", "Rain Shepherd", "milio_splash_<type>_11.skins_milio_skin11", "milioloadscreen_11.skins_milio_skin11"],
    ["20", "Winter Wonder", "milio_splash_<type>_20.skins_milio_skin20", "milioloadscreen_20.skins_milio_skin20"],
  ],
  MissFortune: [
    ["0", "Original"],
    ["1", "Cowgirl"],
    ["2", "Waterloo"],
    ["3", "Secret Agent"],
    ["4", "Candy Cane"],
    ["5", "Road Warrior"],
    ["6", "Crime City"],
    ["7", "Arcade"],
    ["8", "Captain Fortune"],
    ["9", "Pool Party"],
    ["15", "Star Guardian"],
    ["16", "Gun Goddess"],
    ["17", "Pajama Guardian"],
    ["18", "Bewitching"],
    ["20", "Prestige Bewitching"],
    ["21", "Ruined"],
    ["31", "Battle Bunny"],
    ["20", "Prestige Bewitching (2022)", undefined, "missfortuneloadscreen_33"],
    ["40", "Broken Covenant"],
    ["41", "Prestige Broken Covenant"],
    ["50", "Porcelain"],
    ["32", "Admiral Battle Bunny", "missfortune_splash_<type>_32.skins_missfortune_skin32", "missfortuneloadscreen_32.skins_missfortune_skin32"],
    ["60", "Battle Queen", "missfortune_splash_<type>_60.skins_missfortune_skin60", "missfortuneloadscreen_60.skins_missfortune_skin60"],
  ],
  Mordekaiser: [
    ["0", "Original"],
    ["1", "Dragon Knight"],
    ["2", "Infernal"],
    ["3", "Pentakill"],
    ["4", "Lord"],
    ["5", "King of Clubs"],
    ["6", "Dark Star"],
    ["13", "PROJECT"],
    ["23", "Pentakill Lost Chapter"],
    ["32", "High Noon"],
    ["42", "Ashen Graveknight"],
    ["44", "Old God"],
    ["54", "Sahn-Uzal", "mordekaiser_splash_<type>_54.skins_mordekaiser_skin54", "mordekaiserloadscreen_54.skins_mordekaiser_skin54"],
    ["55", "Prestige Money Miser", "mordekaiser_splash_<type>_55.skins_mordekaiser_skin55", "mordekaiserloadscreen_55.skins_mordekaiser_skin55"],
  ],
  Morgana: [
    ["0", "Original"],
    ["1", "Exiled"],
    ["2", "Sinful Succulence"],
    ["3", "Blade Mistress"],
    ["4", "Blackthorn"],
    ["5", "Ghost Bride"],
    ["6", "Victorious"],
    ["10", "Lunar Wraith"],
    ["11", "Bewitching"],
    ["17", "Majestic Empress"],
    ["26", "Coven"],
    ["39", "Dawnbringer"],
    ["41", "Prestige Bewitching"],
    ["50", "Star Nemesis"],
    ["60", "Snow Moon"],
    ["70", "Porcelain"],
    ["80", "Spirit Blossom", "morgana_splash_<type>_80.skins_morgana_skin80", "morganaloadscreen_80.skins_morgana_skin80"],
    ["81", "Prestige Veiled Lady", "morgana_splash_<type>_81.skins_morgana_skin81", "morganaloadscreen_81.skins_morgana_skin81"],
  ],
  Naafiri: [
    ["0", "Original", undefined, "naafiriloadscreen_0"],
    ["1", "Soul Fighter"],
    ["11", "PROJECT"],
    ["20", "Glizzy", "naafiri_splash_<type>_20.skins_naafiri_skin20", "naafiriloadscreen_20.skins_naafiri_skin20"],
    ["29", "Warhound", "naafiri_splash_<type>_29.skins_naafiri_skin29", "naafiriloadscreen_29.skins_naafiri_skin29"],
  ],
  Nami: [
    ["0", "Original"],
    ["1", "Koi"],
    ["2", "River Spirit"],
    ["3", "Urf the Nami-tee"],
    ["7", "Deep Sea"],
    ["8", "SKT T1"],
    ["9", "Program"],
    ["15", "Splendid Staff"],
    ["24", "Cosmic Destiny"],
    ["32", "Bewitching"],
    ["41", "Space Groove"],
    ["42", "Prestige Space Groove"],
    ["51", "Coven"],
    ["58", "Mythmaker", "nami_splash_<type>_58.skins_nami_skin58", "namiloadscreen_58.skins_nami_skin58"],
    ["68", "Sunken Shadows", "nami_splash_<type>_68.skins_nami_skin68", "namiloadscreen_68.skins_nami_skin68"],
  ],
  Nasus: [
    ["0", "Original"],
    ["1", "Galactic"],
    ["2", "Pharaoh"],
    ["3", "Dreadknight"],
    ["4", "Riot K-9"],
    ["5", "Infernal"],
    ["6", "Archduke"],
    ["10", "Worldbreaker"],
    ["11", "Lunar Guardian"],
    ["16", "Battlecast"],
    ["25", "Space Groove"],
    ["35", "Armored Titan"],
    ["45", "Nightbringer"],
    ["54", "Fatemaker", "nasus_splash_<type>_54.skins_nasus_skin54", "nasusloadscreen_54.skins_nasus_skin54"],
  ],
  Nautilus: [
    ["0", "Original"],
    ["1", "Abyssal"],
    ["2", "Subterranean"],
    ["3", "AstroNautilus"],
    ["4", "Warden"],
    ["5", "Worldbreaker"],
    ["6", "Conqueror"],
    ["9", "Shan Hai Scrolls"],
    ["18", "Fright Night"],
    ["27", "Cosmic Paladin"],
    ["36", "Crystalis Indomitus", "nautilus_splash_<type>_36.skins_nautilus_skin36", "nautilusloadscreen_36.skins_nautilus_skin36"],
    ["39", "Petricite", "nautilus_splash_<type>_39.skins_nautilus_skin39", "nautilusloadscreen_39.skins_nautilus_skin39"],
  ],
  Neeko: [
    ["0", "Original"],
    ["1", "Winter Wonder"],
    ["10", "Star Guardian"],
    ["11", "Prestige Star Guardian"],
    ["12", "Shan Hai Scrolls"],
    ["11", "Prestige Star Guardian (2022)", undefined, "neekoloadscreen_21"],
    ["22", "Bewitching"],
    ["31", "Street Demons"],
    ["40", "Cosplayer", "neeko_splash_<type>_40.skins_neeko_skin40", "neekoloadscreen_40.skins_neeko_skin40"],
    ["49", "Beeko", "neeko_splash_<type>_49.skins_neeko_skin49", "neekoloadscreen_49.skins_neeko_skin49"],
  ],
  Nidalee: [
    ["0", "Original"],
    ["1", "Snow Bunny"],
    ["2", "Leopard"],
    ["3", "French Maid"],
    ["4", "Pharaoh"],
    ["5", "Bewitching"],
    ["6", "Headhunter"],
    ["7", "Warring Kingdoms"],
    ["8", "Challenger"],
    ["9", "Super Galaxy"],
    ["11", "Dawnbringer"],
    ["18", "Cosmic Huntress"],
    ["27", "DWG"],
    ["29", "Ocean Song"],
    ["39", "Kittalee"],
    ["48", "La Ilusión"],
    ["58", "Spirit Blossom", "nidalee_splash_<type>_58.skins_nidalee_skin58", "nidaleeloadscreen_58.skins_nidalee_skin58"],
  ],
  Nilah: [
    ["0", "Original", undefined, "nilahloadscreen_0"],
    ["1", "Star Guardian"],
    ["11", "Coven"],
    ["21", "Inkshadow", "nilah_splash_<type>_21.skins_nilah_skin21", "nilahloadscreen_21.skins_nilah_skin21"],
  ],
  Nocturne: [
    ["0", "Original"],
    ["1", "Frozen Terror"],
    ["2", "Void"],
    ["3", "Ravager"],
    ["4", "Haunting"],
    ["5", "Eternum"],
    ["6", "Cursed Revenant"],
    ["7", "Old God"],
    ["16", "Hextech"],
    ["17", "Broken Covenant"],
    ["26", "Empyrean"],
  ],
  Nunu: [
    ["0", "Original"],
    ["1", "Sasquatch"],
    ["2", "Workshop"],
    ["3", "Grungy"],
    ["4", "Nunu Bot"],
    ["5", "Demolisher"],
    ["6", "TPA"],
    ["7", "Zombie"],
    ["8", "Papercraft"],
    ["16", "Space Groove"],
    ["26", "Nunu & Beelump"],
    ["35", "Cosmic Paladins"],
    ["44", "Fright Night", "nunu_splash_<type>_44.skins_nunu_skin44", "nunuloadscreen_44.skins_nunu_skin44"],
  ],
  Olaf: [
    ["0", "Original"],
    ["1", "Forsaken"],
    ["2", "Glacial"],
    ["3", "Brolaf"],
    ["4", "Pentakill"],
    ["5", "Marauder"],
    ["6", "Butcher"],
    ["15", "SKT T1"],
    ["16", "Dragonslayer"],
    ["25", "Sentinel"],
    ["35", "Pentakill Lost Chapter"],
    ["44", "Infernal", "olaf_splash_<type>_44.skins_olaf_skin44", "olafloadscreen_44.skins_olaf_skin44"],
  ],
  Orianna: [
    ["0", "Original"],
    ["1", "Gothic"],
    ["2", "Sewn Chaos"],
    ["3", "Bladecraft"],
    ["4", "TPA"],
    ["5", "Winter Wonder"],
    ["6", "Heartseeker"],
    ["7", "Dark Star"],
    ["8", "Victorious"],
    ["11", "Pool Party"],
    ["20", "Orbeeanna"],
    ["29", "Star Guardian"],
    ["38", "T1", "orianna_splash_<type>_38.skins_orianna_skin38", "oriannaloadscreen_38.skins_orianna_skin38"],
  ],
  Ornn: [
    ["0", "Original"],
    ["1", "Thunder Lord"],
    ["2", "Elderwood"],
    ["11", "Space Groove"],
    ["20", "Choo-Choo"],
    ["29", "Aegis Frame", "ornn_splash_<type>_29.skins_ornn_skin29", "ornnloadscreen_29.skins_ornn_skin29"],
  ],
  Pantheon: [
    ["0", "Original"],
    ["1", "Myrmidon"],
    ["2", "Ruthless"],
    ["3", "Perseus"],
    ["4", "Full Metal"],
    ["5", "Glaive Warrior"],
    ["6", "Dragonslayer"],
    ["7", "Zombie Slayer"],
    ["8", "Baker"],
    ["16", "Pulsefire"],
    ["25", "Ruined"],
    ["26", "Prestige Ascended"],
    ["36", "Ashen Conqueror"],
    ["38", "Chosen of the Wolf", "pantheon_splash_<type>_38.skins_pantheon_skin38", "pantheonloadscreen_38.skins_pantheon_skin38"],
  ],
  Poppy: [
    ["0", "Original"],
    ["1", "Noxus"],
    ["3", "Blacksmith"],
    ["2", "Lollipoppy"],
    ["4", "Ragdoll"],
    ["5", "Battle Regalia"],
    ["6", "Scarlet Hammer"],
    ["7", "Star Guardian"],
    ["14", "Snow Fawn"],
    ["15", "Hextech"],
    ["16", "Astronaut"],
    ["24", "Bewitching"],
    ["33", "Cafe Cuties"],
    ["42", "Firecracker", "poppy_splash_<type>_42.skins_poppy_skin42", "poppyloadscreen_42.skins_poppy_skin42"],
  ],
  Pyke: [
    ["0", "Original"],
    ["1", "Sand Wraith"],
    ["9", "Blood Moon"],
    ["16", "PROJECT"],
    ["25", "PsyOps"],
    ["34", "Sentinel"],
    ["44", "Ashen Knight"],
    ["45", "Empyrean"],
    ["53", "Soul Fighter"],
    ["54", "Prestige Soul Fighter"],
    ["64", "Fright Night", "pyke_splash_<type>_64.skins_pyke_skin64", "pykeloadscreen_64.skins_pyke_skin64"],
    ["74", "Inkshadow", "pyke_splash_<type>_74.skins_pyke_skin74", "pykeloadscreen_74.skins_pyke_skin74"],
    ["75", "T1", "pyke_splash_<type>_75.skins_pyke_skin75", "pykeloadscreen_75.skins_pyke_skin75"],
  ],
  Qiyana: [
    ["0", "Original"],
    ["1", "Battle Boss"],
    ["2", "True Damage"],
    ["10", "Prestige True Damage"],
    ["11", "Battle Queen"],
    ["20", "Shockblade"],
    ["10", "Prestige True Damage (2022)", undefined, "qiyanaloadscreen_21"],
    ["30", "Lunar Empress"],
    ["40", "La Ilusión"],
    ["50", "Prestige Battle Academia", "qiyana_splash_<type>_50.skins_qiyana_skin50", "qiyanaloadscreen_50.skins_qiyana_skin50"],
  ],
  Quinn: [
    ["0", "Original"],
    ["1", "Phoenix"],
    ["2", "Woad Scout"],
    ["3", "Corsair"],
    ["4", "Heartseeker"],
    ["5", "Warden"],
    ["14", "Star Guardian"],
  ],
  Rakan: [
    ["0", "Original"],
    ["1", "Cosmic Dawn"],
    ["2", "Sweetheart"],
    ["3", "SSG"],
    ["4", "iG"],
    ["5", "Star Guardian"],
    ["9", "Elderwood"],
    ["18", "Arcana"],
    ["27", "Broken Covenant"],
    ["36", "Redeemed Star Guardian"],
    ["37", "Dragonmancer"],
    ["38", "Prestige Dragonmancer"],
    ["47", "Battle Academia", "rakan_splash_<type>_47.skins_rakan_skin47", "rakanloadscreen_47.skins_rakan_skin47"],
  ],
  Rammus: [
    ["0", "Original"],
    ["1", "King"],
    ["2", "Chrome"],
    ["3", "Molten"],
    ["4", "Freljord"],
    ["5", "Ninja"],
    ["6", "Full Metal"],
    ["7", "Guardian of the Sands"],
    ["8", "Sweeper"],
    ["16", "Hextech"],
    ["17", "Astronaut"],
    ["26", "Durian Defender"],
  ],
  RekSai: [
    ["0", "Original"],
    ["1", "Eternum"],
    ["2", "Pool Party"],
    ["9", "Blackfrost"],
    ["17", "Elderwood"],
    ["26", "Primordian", "reksai_splash_<type>_26.skins_reksai_skin26", "reksailoadscreen_26.skins_reksai_skin26"],
  ],
  Rell: [
    ["0", "Original"],
    ["1", "Battle Queen"],
    ["10", "Star Guardian"],
    ["20", "High Noon"],
    ["30", "Grand Reckoning", "rell_splash_<type>_30.skins_rell_skin30", "rellloadscreen_30.skins_rell_skin30"],
  ],
  Renata: [
    ["0", "Original", undefined, "renataloadscreen_0"],
    ["1", "Admiral Glasc"],
    ["10", "Fright Night"],
    ["20", "La Ilusión"],
    ["21", "Prestige La Ilusión"],
    ["31", "Masque of the Black Rose", "renata_splash_<type>_31.skins_renata_care_skin31", "renataloadscreen_31.skins_renata_care_skin31"],
  ],
  Renekton: [
    ["0", "Original"],
    ["1", "Galactic"],
    ["2", "Outback"],
    ["3", "Bloodfury"],
    ["4", "Rune Wars"],
    ["6", "Pool Party"],
    ["5", "Scorched Earth"],
    ["7", "Prehistoric"],
    ["8", "SKT T1"],
    ["9", "Renektoy"],
    ["17", "Hextech"],
    ["18", "Blackfrost"],
    ["26", "PROJECT"],
    ["33", "Dawnbringer"],
    ["42", "Worlds 2023"],
    ["48", "Inkshadow", "renekton_splash_<type>_48.skins_renekton_skin48", "renektonloadscreen_48.skins_renekton_skin48"],
  ],
  Rengar: [
    ["0", "Original"],
    ["1", "Headhunter"],
    ["2", "Night Hunter"],
    ["3", "SSW"],
    ["8", "Mecha"],
    ["15", "Pretty Kitty"],
    ["23", "Guardian of the Sands"],
    ["30", "Sentinel"],
    ["40", "Street Demons"],
  ],
  Riven: [
    ["0", "Original"],
    ["1", "Redeemed"],
    ["2", "Crimson Elite"],
    ["3", "Battle Bunny"],
    ["4", "Worlds 2012"],
    ["5", "Dragonblade"],
    ["6", "Arcade"],
    ["7", "Reignited Worlds 2012"],
    ["16", "Dawnbringer"],
    ["18", "Pulsefire"],
    ["20", "Valiant Sword"],
    ["22", "Prestige Valiant Sword"],
    ["23", "Spirit Blossom"],
    ["34", "Sentinel"],
    ["44", "Battle Bunny Prime"],
    ["22", "Prestige Valiant Sword (2022)", undefined, "rivenloadscreen_45"],
    ["55", "Broken Covenant"],
    ["63", "Primal Ambush"],
  ],
  Rumble: [
    ["0", "Original"],
    ["2", "Bilgerat"],
    ["1", "Rumble in the Jungle"],
    ["3", "Super Galaxy"],
    ["4", "Badlands Baron"],
    ["13", "Space Groove"],
    ["23", "Cafe Cuties"],
  ],
  Ryze: [
    ["0", "Original"],
    ["1", "Young"],
    ["2", "Tribal"],
    ["3", "Uncle"],
    ["4", "Triumphant"],
    ["5", "Professor"],
    ["6", "Zombie"],
    ["7", "Dark Crystal"],
    ["8", "Pirate"],
    ["9", "Ryze Whitebeard"],
    ["10", "SKT T1"],
    ["11", "Worlds 2019"],
    ["13", "Guardian of the Sands"],
    ["20", "Arcana"],
    ["29", "Blood Moon", "ryze_splash_<type>_29.skins_ryze_skin29", "ryzeloadscreen_29.skins_ryze_skin29"],
  ],
  Samira: [
    ["0", "Original"],
    ["1", "PsyOps"],
    ["10", "Space Groove"],
    ["20", "High Noon"],
    ["30", "Soul Fighter"],
    ["33", "Masque of the Black Rose", "samira_splash_<type>_33.skins_samira_care_skin33", "samiraloadscreen_33.skins_samira_care_skin33"],
    ["35", "Battle Professor", "samira_splash_<type>_35.skins_samira_skin35", "samiraloadscreen_35.skins_samira_skin35"],
  ],
  Sejuani: [
    ["0", "Original"],
    ["1", "Sabretusk"],
    ["2", "Darkrider"],
    ["3", "Traditional"],
    ["4", "Bear Cavalry"],
    ["5", "Poro Rider"],
    ["6", "Beast Hunter"],
    ["7", "Sejuani Dawnchaser"],
    ["8", "Firecracker"],
    ["15", "Hextech"],
    ["16", "PROJECT"],
    ["26", "Solar Eclipse"],
    ["36", "Victorious"],
    ["48", "Pug Trainer", "sejuani_splash_<type>_48.skins_sejuani_skin48", "sejuaniloadscreen_48.skins_sejuani_skin48"],
  ],
  Senna: [
    ["0", "Original"],
    ["1", "True Damage"],
    ["9", "Prestige True Damage"],
    ["10", "High Noon"],
    ["16", "PROJECT"],
    ["26", "Lunar Eclipse"],
    ["27", "Prestige Lunar Eclipse"],
    ["36", "Bewitching"],
    ["46", "Star Guardian"],
    ["56", "Winterblessed"],
    ["63", "Masked Justice", "senna_splash_<type>_63.skins_senna_skin63", "sennaloadscreen_63.skins_senna_skin63"],
    ["72", "Warhound", "senna_splash_<type>_72.skins_senna_skin72", "sennaloadscreen_72.skins_senna_skin72"],
  ],
  Seraphine: [
    ["0", "Original"],
    ["1", "KDA ALL OUT Indie"],
    ["4", "Graceful Phoenix"],
    ["14", "Ocean Song"],
    ["15", "Prestige Ocean Song"],
    ["24", "Faerie Court"],
    ["34", "Star Guardian"],
    ["43", "Battle Dove", "seraphine_splash_<type>_43.skins_seraphine_skin43", "seraphineloadscreen_43.skins_seraphine_skin43"],
    ["50", "Dumpling Darlings", "seraphine_splash_<type>_50.skins_seraphine_skin50", "seraphineloadscreen_50.skins_seraphine_skin50"],
    ["59", "Firecracker", "seraphine_splash_<type>_59.skins_seraphine_skin59", "seraphineloadscreen_59.skins_seraphine_skin59"],
  ],
  Sett: [
    ["0", "Original"],
    ["1", "Mecha Kingdoms"],
    ["8", "Obsidian Dragon"],
    ["9", "Prestige Obsidian Dragon"],
    ["10", "Pool Party"],
    ["19", "Firecracker"],
    ["38", "Spirit Blossom"],
    ["45", "Soul Fighter"],
    ["56", "HEARTSTEEL"],
    ["66", "Radiant Serpent", "sett_splash_<type>_66.skins_sett_skin66", "settloadscreen_66.skins_sett_skin66"],
    ["67", "Spirit Blossom Springs", "sett_splash_<type>_67.skins_sett_skin67", "settloadscreen_67.skins_sett_skin67"],
  ],
  Shaco: [
    ["0", "Original"],
    ["1", "Mad Hatter"],
    ["2", "Royal"],
    ["3", "Nutcracko"],
    ["4", "Workshop"],
    ["5", "Asylum"],
    ["6", "Masked"],
    ["7", "Wild Card"],
    ["8", "Dark Star"],
    ["15", "Arcanist"],
    ["23", "Crime City Nightmare"],
    ["33", "Winterblessed"],
    ["43", "Soul Fighter"],
    ["44", "Prestige Soul Fighter"],
    ["54", "Fright Night", "shaco_splash_<type>_54.skins_shaco_skin54", "shacoloadscreen_54.skins_shaco_skin54"],
    ["64", "Cat-in-the-Box", "shaco_splash_<type>_64.skins_shaco_skin64", "shacoloadscreen_64.skins_shaco_skin64"],
  ],
  Shen: [
    ["0", "Original"],
    ["1", "Frozen"],
    ["2", "Yellow Jacket"],
    ["3", "Surgeon"],
    ["4", "Blood Moon"],
    ["5", "Warlord"],
    ["6", "TPA"],
    ["15", "Pulsefire"],
    ["16", "Infernal"],
    ["22", "PsyOps"],
    ["40", "Shockblade"],
    ["49", "Ashen Guardian"],
    ["51", "Three Honors", "shen_splash_<type>_51.skins_shen_skin51", "shenloadscreen_51.skins_shen_skin51"],
  ],
  Shyvana: [
    ["0", "Original", "shyvana_splash_<type>_0.shyvana_rework", "shyvanaloadscreen_0.shyvana_rework"],
    ["1", "Shyvana Ironscale", "shyvana_splash_<type>_1.shyvana_rework", "shyvanaloadscreen_1.shyvana_rework"],
    ["2", "Boneclaw", "shyvana_splash_<type>_2.shyvana_rework", "shyvanaloadscreen_2.shyvana_rework"],
    ["3", "Darkflame", "shyvana_splash_<type>_3.shyvana_rework", "shyvanaloadscreen_3.shyvana_rework"],
    ["4", "Ice Drake", "shyvana_splash_<type>_4.shyvana_rework", "shyvanaloadscreen_4.shyvana_rework"],
    ["5", "Worlds 2014", "shyvana_splash_<type>_5.shyvana_rework", "shyvanaloadscreen_5.shyvana_rework"],
    ["6", "Super Galaxy", "shyvana_splash_<type>_6.shyvana_rework", "shyvanaloadscreen_6.shyvana_rework"],
    ["8", "Ruined", "shyvana_splash_<type>_8.shyvana_rework", "shyvanaloadscreen_8.shyvana_rework"],
    ["17", "Immortal Journey", "shyvana_splash_<type>_17.shyvana_rework", "shyvanaloadscreen_17.shyvana_rework"],
  ],
  Singed: [
    ["0", "Original"],
    ["1", "Riot Squad"],
    ["2", "Hextech"],
    ["3", "Surfer"],
    ["4", "Mad Scientist"],
    ["5", "Augmented"],
    ["6", "Snow Day"],
    ["7", "SSW"],
    ["8", "Black Scourge"],
    ["9", "Beekeeper"],
    ["10", "Resistance"],
    ["19", "Astronaut"],
    ["28", "Arcane Shimmer Lab", "singed_splash_<type>_28.skins_singed_skin28", "singedloadscreen_28.skins_singed_skin28"],
  ],
  Sion: [
    ["0", "Original"],
    ["1", "Hextech"],
    ["2", "Barbarian"],
    ["3", "Lumberjack"],
    ["4", "Warmonger"],
    ["5", "Mecha Zero"],
    ["14", "Worldbreaker"],
    ["22", "Blackfrost"],
    ["30", "High Noon"],
    ["40", "Cosmic Paladin"],
    ["49", "Grand Reckoning", "sion_splash_<type>_49.skins_sion_skin49", "sionloadscreen_49.skins_sion_skin49"],
  ],
  Sivir: [
    ["0", "Original", undefined, "sivirloadscreen_0"],
    ["1", "Warrior Princess"],
    ["2", "Spectacular"],
    ["3", "Huntress"],
    ["4", "Bandit"],
    ["5", "PAX"],
    ["6", "Snowstorm"],
    ["7", "Warden"],
    ["8", "Victorious"],
    ["9", "Neo PAX"],
    ["10", "Pizza Delivery"],
    ["16", "Blood Moon"],
    ["25", "Odyssey"],
    ["34", "Cafe Cuties"],
    ["43", "Solar Eclipse"],
    ["50", "Mythmaker"],
    ["51", "Prestige Mythmaker"],
    ["61", "Primal Ambush"],
    ["70", "Ann-Sivir-sary", "sivir_splash_<type>_70.skins_sivir_skin70", "sivirloadscreen_70.skins_sivir_skin70"],
  ],
  Skarner: [
    ["0", "Original", undefined, "skarnerloadscreen_0"],
    ["1", "Sandscourge"],
    ["2", "Earthrune"],
    ["3", "Battlecast Alpha"],
    ["4", "Guardian of the Sands"],
    ["5", "Cosmic Sting"],
    ["14", "Mecha Kingdoms", "skarner_splash_<type>_14.skins_skarner_skin14", "skarnerloadscreen_14.skins_skarner_skin14"],
  ],
  Smolder: [
    ["0", "Original", undefined, "smolderloadscreen_0"],
    ["1", "Heavenscale"],
    ["11", "Reindeer", "smolder_splash_<type>_11.skins_smolder_skin11", "smolderloadscreen_11.skins_smolder_skin11"],
  ],
  Sona: [
    ["0", "Original"],
    ["1", "Muse"],
    ["2", "Pentakill"],
    ["3", "Silent Night"],
    ["4", "Guqin"],
    ["5", "Arcade"],
    ["6", "DJ"],
    ["7", "Sweetheart"],
    ["9", "Odyssey"],
    ["17", "PsyOps"],
    ["26", "Pentakill Lost Chapter"],
    ["35", "Star Guardian"],
    ["45", "Immortal Journey"],
    ["46", "Prestige Immortal Journey"],
    ["56", "Victorious", "sona_splash_<type>_56.skins_sona_skin56", "sonaloadscreen_56.skins_sona_skin56"],
    ["66", "Spirit Blossom Springs", "sona_splash_<type>_66.skins_sona_skin66", "sonaloadscreen_66.skins_sona_skin66"],
    ["75", "Prestige Requiem", "sona_splash_<type>_75.skins_sona_skin75", "sonaloadscreen_75.skins_sona_skin75"],
  ],
  Soraka: [
    ["0", "Original"],
    ["1", "Dryad"],
    ["2", "Divine"],
    ["3", "Celestine"],
    ["4", "Reaper"],
    ["5", "Order of the Banana"],
    ["6", "Program"],
    ["7", "Star Guardian"],
    ["8", "Pajama Guardian"],
    ["9", "Winter Wonder"],
    ["15", "Dawnbringer"],
    ["16", "Nightbringer"],
    ["17", "Prestige Star Guardian"],
    ["18", "Cafe Cuties"],
    ["27", "Spirit Blossom"],
    ["37", "Immortal Journey"],
    ["44", "Faerie Court", "soraka_splash_<type>_44.skins_soraka_skin44", "sorakaloadscreen_44.skins_soraka_skin44"],
    ["53", "Flora Fatalis", "soraka_splash_<type>_53.skins_soraka_skin53", "sorakaloadscreen_53.skins_soraka_skin53"],
  ],
  Swain: [
    ["0", "Original"],
    ["2", "Bilgewater"],
    ["1", "Northern Front"],
    ["3", "Tyrant"],
    ["4", "Dragon Master"],
    ["11", "Hextech"],
    ["12", "Crystal Rose"],
    ["21", "Winterblessed"],
    ["32", "Chosen of the Wolf", "swain_splash_<type>_32.skins_swain_skin32", "swainloadscreen_32.skins_swain_skin32"],
    ["33", "Prestige Chosen of the Wolf", "swain_splash_<type>_33.prestige2_matcha_swain", "swainloadscreen_33.prestige2_matcha_swain"],
    ["42", "Fried Chicken King", "swain_splash_<type>_42.skins_swain_skin42", "swainloadscreen_42.skins_swain_skin42"],
  ],
  Sylas: [
    ["0", "Original"],
    ["1", "Lunar Wraith"],
    ["8", "Freljord"],
    ["13", "PROJECT"],
    ["14", "Prestige PROJECT"],
    ["24", "Battle Wolf"],
    ["34", "Ashen Slayer"],
    ["36", "Winterblessed"],
    ["46", "Dark Star", "sylas_splash_<type>_46.skins_sylas_skin46", "sylasloadscreen_46.skins_sylas_skin46"],
    ["53", "Prestige T1", "sylas_splash_<type>_53.skins_sylas_skin53", "sylasloadscreen_53.skins_sylas_skin53"],
  ],
  Syndra: [
    ["0", "Original", undefined, "syndraloadscreen_0"],
    ["1", "Justicar"],
    ["2", "Atlantean"],
    ["3", "Queen of Diamonds"],
    ["4", "Snow Day"],
    ["5", "SKT T1"],
    ["6", "Star Guardian"],
    ["7", "Pool Party"],
    ["16", "Withered Rose"],
    ["25", "Bewitching"],
    ["34", "Prestige Star Guardian"],
    ["44", "Spirit Blossom"],
    ["54", "Coven"],
    ["65", "Dumpling Darlings", "syndra_splash_<type>_65.skins_syndra_skin65", "syndraloadscreen_65_2.skins_syndra_skin65"],
  ],
  TahmKench: [
    ["0", "Original"],
    ["1", "Master Chef"],
    ["2", "Urf Kench"],
    ["3", "Coin Emperor"],
    ["11", "Arcana"],
    ["20", "High Noon"],
    ["30", "Shan Hai Scrolls"],
    ["39", "Choncc Kench", "tahmkench_splash_<type>_39.skins_tahmkench_skin39", "tahmkenchloadscreen_39.skins_tahmkench_skin39"],
  ],
  Taliyah: [
    ["0", "Original"],
    ["1", "Freljord"],
    ["2", "SSG"],
    ["3", "Pool Party"],
    ["11", "Star Guardian"],
    ["21", "Crystalis Motus"],
    ["24", "Durand's Legacy", "taliyah_splash_<type>_24.skins_taliyah_skin24", "taliyahloadscreen_24.skins_taliyah_skin24"],
  ],
  Talon: [
    ["0", "Original"],
    ["1", "Renegade"],
    ["2", "Crimson Elite"],
    ["3", "Dragonblade"],
    ["4", "SSW"],
    ["5", "Blood Moon"],
    ["12", "Enduring Sword"],
    ["20", "Talon Blackwood"],
    ["29", "Withered Rose"],
    ["38", "High Noon"],
    ["39", "Prestige High Noon"],
    ["49", "Primal Ambush"],
    ["59", "Grand Reckoning", "talon_splash_<type>_59.skins_talon_skin59", "talonloadscreen_59.skins_talon_skin59"],
  ],
  Taric: [
    ["0", "Original"],
    ["1", "Emerald"],
    ["2", "Armor of the Fifth Age"],
    ["3", "Bloodstone"],
    ["4", "Pool Party"],
    ["9", "Taric Luminshield"],
    ["18", "Space Groove"],
    ["27", "Fatebreaker", "taric_splash_<type>_27.skins_taric_skin27", "taricloadscreen_27.skins_taric_skin27"],
  ],
  Teemo: [
    ["0", "Original", "teemo_splash_<type>_0.asu_teemo", "teemoloadscreen_0.asu_teemo"],
    ["1", "Happy Elf", "teemo_splash_<type>_1.asu_teemo", "teemoloadscreen_1.asu_teemo"],
    ["2", "Recon", "teemo_splash_<type>_2.asu_teemo", "teemoloadscreen_2.asu_teemo"],
    ["3", "Badger", "teemo_splash_<type>_3.asu_teemo", "teemoloadscreen_3.asu_teemo"],
    ["4", "Astronaut", "teemo_splash_<type>_4.asu_teemo", "teemoloadscreen_4.asu_teemo"],
    ["5", "Cottontail", "teemo_splash_<type>_5.asu_teemo", "teemoloadscreen_5.asu_teemo"],
    ["6", "Super", "teemo_splash_<type>_6.asu_teemo", "teemoloadscreen_6.asu_teemo"],
    ["7", "Panda", "teemo_splash_<type>_7.asu_teemo", "teemoloadscreen_7.asu_teemo"],
    ["8", "Omega Squad"],
    ["14", "Little Devil", "teemo_splash_<type>_14.asu_teemo", "teemoloadscreen_14.asu_teemo"],
    ["18", "Beemo", "teemo_splash_<type>_18.asu_teemo", "teemoloadscreen_18.asu_teemo"],
    ["25", "Spirit Blossom", "teemo_splash_<type>_25.asu_teemo", "teemoloadscreen_25.asu_teemo"],
    ["27", "Prestige Spirit Blossom", "teemo_splash_<type>_27.asu_teemo", "teemoloadscreen_27.asu_teemo"],
    ["37", "Firecracker", "teemo_splash_<type>_37.asu_teemo", "teemoloadscreen_37.asu_teemo"],
    ["47", "Space Groove"],
    ["54", "Spirit Blossom Springs", "teemo_splash_<type>_54.skins_teemo_skin54", "teemoloadscreen_54.skins_teemo_skin54"],
  ],
  Thresh: [
    ["0", "Original"],
    ["1", "Deep Terror"],
    ["2", "Worlds 2013"],
    ["3", "Blood Moon"],
    ["4", "SSW"],
    ["5", "Dark Star"],
    ["6", "High Noon"],
    ["13", "Pulsefire"],
    ["14", "Prestige Pulsefire"],
    ["15", "FPX"],
    ["17", "Spirit Blossom"],
    ["27", "Unbound"],
    ["28", "Steel Dragon"],
    ["14", "Prestige Pulsefire (2022)", undefined, "threshloadscreen_38"],
    ["39", "Lunar Emperor"],
    ["49", "Winterblessed"],
    ["59", "Janitor", "thresh_splash_<type>_59.skins_thresh_skin59", "threshloadscreen_59.skins_thresh_skin59"],
  ],
  Tristana: [
    ["0", "Original"],
    ["1", "Riot Girl"],
    ["2", "Earnest Elf"],
    ["3", "Firefighter"],
    ["4", "Guerilla"],
    ["5", "Buccaneer"],
    ["6", "Rocket Girl"],
    ["10", "Dragon Trainer"],
    ["11", "Bewitching"],
    ["12", "Omega Squad"],
    ["24", "Little Demon"],
    ["33", "Pengu Cosplay"],
    ["40", "Hextech"],
    ["41", "Firecracker"],
    ["51", "Spirit Blossom"],
    ["61", "Faerie Court", "tristana_splash_<type>_61.skins_tristana_skin61", "tristanaloadscreen_61.skins_tristana_skin61"],
    ["70", "Rain Shepherd", "tristana_splash_<type>_70.skins_tristana_skin70", "tristanaloadscreen_70.skins_tristana_skin70"],
  ],
  Trundle: [
    ["0", "Original"],
    ["2", "Junkyard"],
    ["1", "Lil' Slugger"],
    ["3", "Traditional"],
    ["4", "Constable"],
    ["5", "Worldbreaker"],
    ["6", "Dragonslayer"],
    ["12", "Fright Night"],
    ["21", "Esports Fan", "trundle_splash_<type>_21.skins_trundle_skin21", "trundleloadscreen_21.skins_trundle_skin21"],
  ],
  Tryndamere: [
    ["0", "Original"],
    ["1", "Highland"],
    ["2", "King"],
    ["3", "Viking"],
    ["4", "Demonblade"],
    ["5", "Sultan"],
    ["6", "Warring Kingdoms"],
    ["7", "Nightmare"],
    ["8", "Beast Hunter"],
    ["9", "Chemtech"],
    ["10", "Blood Moon"],
    ["18", "Nightbringer"],
    ["27", "Victorious"],
    ["37", "Visions of the Fallen", "tryndamere_splash_<type>_37.skins_tryndamere_skin37", "tryndamereloadscreen_37.skins_tryndamere_skin37"],
  ],
  TwistedFate: [
    ["0", "Original"],
    ["1", "PAX"],
    ["2", "Jack of Hearts"],
    ["3", "The Magnificent"],
    ["4", "Tango"],
    ["5", "High Noon"],
    ["6", "Musketeer"],
    ["7", "Underworld"],
    ["8", "Red Card"],
    ["9", "Cutpurse"],
    ["10", "Blood Moon"],
    ["11", "Pulsefire"],
    ["13", "Odyssey"],
    ["23", "DWG"],
    ["25", "Crime City Nightmare"],
    ["36", "Space Groove"],
    ["45", "Victorious", "twistedfate_splash_<type>_45.skins_twistedfate_skin45", "twistedfateloadscreen_45.skins_twistedfate_skin45"],
  ],
  Twitch: [
    ["0", "Original"],
    ["1", "Kingpin"],
    ["3", "Medieval"],
    ["2", "Whistler Village"],
    ["4", "Crime City"],
    ["5", "Vandal"],
    ["6", "Pickpocket"],
    ["7", "SSW"],
    ["8", "Omega Squad"],
    ["12", "Ice King"],
    ["27", "Twitch Shadowfoot"],
    ["36", "Dragonslayer"],
    ["45", "High Noon"],
    ["55", "Cheddar Chief"],
    ["64", "Pool Party", "twitch_splash_<type>_64.skins_twitch_skin64", "twitchloadscreen_64.skins_twitch_skin64"],
  ],
  Udyr: [
    ["0", "Original", undefined, "udyrloadscreen_0"],
    ["1", "Black Belt"],
    ["2", "Primal"],
    ["3", "Spirit Guard"],
    ["4", "Definitely Not"],
    ["5", "Dragon Oracle"],
    ["6", "Inkshadow"],
  ],
  Urgot: [
    ["0", "Original"],
    ["2", "Butcher"],
    ["1", "Giant Enemy Crabgot"],
    ["3", "Battlecast"],
    ["9", "High Noon"],
    ["15", "Pajama Guardian Cosplay"],
    ["23", "Fright Night"],
    ["32", "Urgot the Clogfather", "urgot_splash_<type>_32.skins_urgot_skin32", "urgotloadscreen_32.skins_urgot_skin32"],
  ],
  Varus: [
    ["0", "Original"],
    ["1", "Blight Crystal"],
    ["2", "Arclight"],
    ["3", "Arctic Ops"],
    ["4", "Heartseeker"],
    ["5", "Varus Swiftbolt"],
    ["6", "Dark Star"],
    ["7", "Conqueror"],
    ["9", "Infernal"],
    ["17", "Cosmic Hunter"],
    ["16", "PROJECT"],
    ["34", "High Noon"],
    ["44", "Snow Moon"],
    ["53", "Empyrean"],
    ["60", "Spirit Blossom", "varus_splash_<type>_60.skins_varus_skin60", "varusloadscreen_60.skins_varus_skin60"],
    ["69", "T1", "varus_splash_<type>_69.skins_varus_skin69", "varusloadscreen_69.skins_varus_skin69"],
  ],
  Vayne: [
    ["0", "Original"],
    ["2", "Aristocrat"],
    ["1", "Vindicator"],
    ["3", "Dragonslayer"],
    ["4", "Heartseeker"],
    ["5", "SKT T1"],
    ["6", "Arclight"],
    ["10", "Soulstealer"],
    ["11", "PROJECT"],
    ["12", "Firecracker"],
    ["13", "Prestige Firecracker"],
    ["15", "FPX"],
    ["14", "Spirit Blossom"],
    ["25", "Sentinel"],
    ["32", "Battle Bat"],
    ["13", "Prestige Firecracker (2022)", undefined, "vayneloadscreen_33"],
    ["44", "Dawnbringer"],
    ["55", "Dragonmancer"],
    ["64", "Risen Legend", "vayne_splash_<type>_64.skins_vayne_skin64", "vayneloadscreen_64.skins_vayne_skin64"],
  ],
  Veigar: [
    ["0", "Original"],
    ["1", "White Mage"],
    ["2", "Curling"],
    ["3", "Veigar Greybeard"],
    ["4", "Leprechaun"],
    ["5", "Baron Von"],
    ["6", "Superb Villain"],
    ["7", "Bad Santa"],
    ["8", "Final Boss"],
    ["9", "Omega Squad"],
    ["13", "Elderwood"],
    ["23", "Furyhorn Cosplay"],
    ["32", "Astronaut"],
    ["41", "Monster Tamer"],
    ["51", "King Beegar"],
    ["60", "Fright Night", "veigar_splash_<type>_60.skins_veigar_skin60", "veigarloadscreen_60.skins_veigar_skin60"],
  ],
  Velkoz: [
    ["0", "Original"],
    ["1", "Battlecast"],
    ["2", "Arclight"],
    ["3", "Definitely Not"],
    ["4", "Infernal"],
    ["11", "Blackfrost"],
    ["20", "Bee'Koz"],
  ],
  Vex: [
    ["0", "Original", undefined, "vexloadscreen_0"],
    ["1", "Dawnbringer"],
    ["10", "Empyrean"],
    ["20", "Stargazer", "vex_splash_<type>_20.skins_vex_skin20", "vexloadscreen_20.skins_vex_skin20"],
    ["29", "Surprise Party", "vex_splash_<type>_29.skins_vex_skin29", "vexloadscreen_29.skins_vex_skin29"],
  ],
  Vi: [
    ["0", "Original"],
    ["1", "Neon Strike"],
    ["2", "Officer"],
    ["3", "Debonair"],
    ["4", "Demon"],
    ["5", "Warring Kingdoms"],
    ["11", "PROJECT"],
    ["12", "Heartbreaker"],
    ["20", "PsyOps"],
    ["29", "Arcane Undercity"],
    ["30", "Heartache"],
    ["39", "Primal Ambush"],
    ["48", "Arcane Brawler", "vi_splash_<type>_48.skins_vi_skin48", "viloadscreen_48.skins_vi_skin48"],
    ["49", "T1", "vi_splash_<type>_49.skins_vi_skin49", "viloadscreen_49.skins_vi_skin49"],
  ],
  Viego: [
    ["0", "Original"],
    ["1", "Lunar Beast"],
    ["10", "Dissonance of Pentakill"],
    ["19", "EDG"],
    ["21", "King"],
    ["30", "Soul Fighter"],
    ["37", "Worlds 2024", "viego_splash_<type>_37.skins_viego_skin37", "viegoloadscreen_37.skins_viego_skin37"],
    ["43", "Revenant Reign", "viego_splash_<type>_43.skins_viego_skin43", "viegoloadscreen_43.skins_viego_skin43"],
  ],
  Viktor: [
    ["0", "Original", "viktor_splash_<type>_0.viktorvgu", "viktorloadscreen_0.viktorvgu"],
    ["1", "Full Machine", "viktor_splash_<type>_1.viktorvgu", "viktorloadscreen_1.viktorvgu"],
    ["2", "Prototype", "viktor_splash_<type>_2.viktorvgu", "viktorloadscreen_2.viktorvgu"],
    ["3", "Creator", "viktor_splash_<type>_3.viktorvgu", "viktorloadscreen_3.viktorvgu"],
    ["4", "Death Sworn", "viktor_splash_<type>_4.viktorvgu", "viktorloadscreen_4.viktorvgu"],
    ["5", "PsyOps", "viktor_splash_<type>_5.viktorvgu", "viktorloadscreen_5.viktorvgu"],
    ["14", "High Noon", "viktor_splash_<type>_14.viktorvgu", "viktorloadscreen_14.viktorvgu"],
    ["24", "Arcane Savior", "viktor_splash_<type>_24.skins_viktorrework_skin24", "viktorloadscreen_24.skins_viktorrework_skin24"],
    ["25", "Machine Herald", "viktor_splash_<type>_25.skins_viktor_skin25", "viktorloadscreen_25.skins_viktor_skin25"],
  ],
  Vladimir: [
    ["0", "Original"],
    ["1", "Count"],
    ["2", "Marquis"],
    ["3", "Nosferatu"],
    ["4", "Vandal"],
    ["5", "Blood Lord"],
    ["6", "Soulstealer"],
    ["7", "Academy"],
    ["8", "Dark Waters"],
    ["14", "Nightbringer"],
    ["21", "Cosmic Devourer"],
    ["30", "Cafe Cuties"],
    ["39", "Broken Covenant"],
    ["48", "Masque of the Black Rose", "vladimir_splash_<type>_48.skins_vladimir_care_skin48", "vladimirloadscreen_48.skins_vladimir_care_skin48"],
  ],
  Volibear: [
    ["0", "Original"],
    ["1", "Thunder Lord"],
    ["2", "Northern Storm"],
    ["3", "Runeguard"],
    ["4", "Captain"],
    ["5", "El Rayo"],
    ["6", "The Thousand-Pierced Bear"],
    ["7", "Duality Dragon"],
    ["9", "Prestige Duality Dragon"],
    ["19", "Inkshadow"],
    ["29", "Spirit Blossom Springs", "volibear_splash_<type>_29.skins_volibear_skin29", "volibearloadscreen_29.skins_volibear_skin29"],
  ],
  Warwick: [
    ["0", "Original"],
    ["2", "Urf the Manatee"],
    ["3", "Big Bad"],
    ["1", "Grey"],
    ["4", "Tundra Hunter"],
    ["5", "Feral"],
    ["6", "Firefang"],
    ["7", "Hyena"],
    ["8", "Marauder"],
    ["9", "Urfwick"],
    ["10", "Lunar Guardian"],
    ["16", "PROJECT"],
    ["35", "Old God"],
    ["45", "Winterblessed"],
    ["46", "Prestige Winterblessed"],
    ["56", "Arcane Vander", "warwick_splash_<type>_56.skins_warwick_skin56", "warwickloadscreen_56.skins_warwick_skin56"],
    ["58", "Warhound", "warwick_splash_<type>_58.skins_warwick_skin58", "warwickloadscreen_58.skins_warwick_skin58"],
  ],
  MonkeyKing: [
    ["0", "Original"],
    ["2", "General"],
    ["1", "Volcanic"],
    ["3", "Jade Dragon"],
    ["4", "Underworld"],
    ["5", "Radiant"],
    ["6", "Lancer Stratus"],
    ["7", "Battle Academia"],
    ["16", "Elderwood"],
    ["26", "Mecha Kingdoms", "monkeyking_splash_<type>_26.skins_monkeyking_skin26", "monkeykingloadscreen_26.skins_monkeyking_skin26"],
  ],
  Xayah: [
    ["0", "Original"],
    ["1", "Cosmic Dusk"],
    ["2", "Sweetheart"],
    ["3", "SSG"],
    ["4", "Star Guardian"],
    ["8", "Elderwood"],
    ["17", "Brave Phoenix"],
    ["26", "Prestige Brave Phoenix"],
    ["28", "Arcana"],
    ["37", "Broken Covenant"],
    ["38", "Redeemed Star Guardian"],
    ["47", "Battle Bat", "xayah_splash_<type>_47.skins_xayah_skin47", "xayahloadscreen_47.skins_xayah_skin47"],
    ["57", "Battle Academia", "xayah_splash_<type>_57.skins_xayah_skin57", "xayahloadscreen_57.skins_xayah_skin57"],
  ],
  Xerath: [
    ["0", "Original"],
    ["1", "Runeborn"],
    ["2", "Battlecast"],
    ["3", "Scorched Earth"],
    ["4", "Guardian of the Sands"],
    ["5", "Dark Star"],
    ["12", "Arcana"],
    ["21", "Astronaut"],
    ["30", "Crystalis Indomitus", "xerath_splash_<type>_30.skins_xerath_skin30", "xerathloadscreen_30.skins_xerath_skin30"],
    ["32", "Corrupted Petricite", "xerath_splash_<type>_32.skins_xerath_skin32", "xerathloadscreen_32.skins_xerath_skin32"],
  ],
  XinZhao: [
    ["0", "Original", "xinzhaorework_splash_<type>_0.xinzhaorework", "xinzhaoreworkloadscreen_0.xinzhaorework"],
    ["1", "Commando", "xinzhaorework_splash_<type>_1.xinzhaorework", "xinzhaoreworkloadscreen_1.xinzhaorework"],
    ["2", "Imperial", "xinzhao_splash_<type>_2.xinzhaorework", "xinzhaoloadscreen_2.xinzhaorework"],
    ["3", "Viscero", "xinzhaorework_splash_<type>_3.xinzhaorework", "xinzhaoreworkloadscreen_3.xinzhaorework"],
    ["4", "Winged Hussar", "xinzhao_splash_<type>_4.xinzhaorework", "xinzhaoloadscreen_4.xinzhaorework"],
    ["5", "Warring Kingdoms", "xinzhaorework_splash_<type>_5.xinzhaorework", "xinzhaoreworkloadscreen_5.xinzhaorework"],
    ["6", "Secret Agent", "xinzhaorework_splash_<type>_6.xinzhaorework", "xinzhaoreworkloadscreen_6.xinzhaorework"],
    ["13", "Dragonslayer", "xinzhaorework_splash_<type>_13.xinzhaorework", "xinzhaoreworkloadscreen_13.xinzhaorework"],
    ["20", "Cosmic Defender", "xinzhaorework_splash_<type>_20.xinzhaorework", "xinzhaoreworkloadscreen_20.xinzhaorework"],
    ["27", "Marauder", "xinzhaorework_splash_<type>_27.xinzhaorework", "xinzhaoreworkloadscreen_27.xinzhaorework"],
    ["36", "Firecracker", "xinzhaorework_splash_<type>_36.xinzhaorework", "xinzhaoreworkloadscreen_36.xinzhaorework"],
    ["47", "Trials of Twilight", "xinzhao_splash_<type>_47.skins_xinzhaorework_skin47", "xinzhaoloadscreen_47.skins_xinzhaorework_skin47"],
  ],
  Yasuo: [
    ["0", "Original"],
    ["1", "High Noon"],
    ["2", "PROJECT"],
    ["3", "Blood Moon"],
    ["9", "Nightbringer"],
    ["10", "Odyssey"],
    ["17", "Battle Boss"],
    ["18", "True Damage"],
    ["36", "Spirit Blossom"],
    ["35", "Prestige True Damage"],
    ["54", "Truth Dragon"],
    ["55", "Dream Dragon"],
    ["45", "Sea Dog"],
    ["56", "Inkshadow"],
    ["57", "Prestige Inkshadow"],
    ["68", "Foreseen"],
    ["77", "Battle Wolf", "yasuo_splash_<type>_77.skins_yasuo_skin77", "yasuoloadscreen_77.skins_yasuo_skin77"],
    ["87", "Genesis Nightbringer", "yasuo_splash_<type>_87.skins_yasuo_skin87", "yasuoloadscreen_87.skins_yasuo_skin87"],
    ["88", "Petals of Spring", "yasuo_splash_<type>_88.skins_yasuo_skin88", "yasuoloadscreen_88.skins_yasuo_skin88"],
  ],
  Yone: [
    ["0", "Original"],
    ["1", "Spirit Blossom"],
    ["10", "Battle Academia"],
    ["19", "Dawnbringer"],
    ["26", "Ocean Song"],
    ["35", "Inkshadow"],
    ["45", "HEARTSTEEL"],
    ["46", "Prestige HEARTSTEEL"],
    ["55", "High Noon"],
    ["58", "Peacemaker High Noon"],
    ["65", "Masked Justice", "yone_splash_<type>_65.skins_yone_skin65", "yoneloadscreen_65.skins_yone_skin65"],
    ["74", "T1", "yone_splash_<type>_74.skins_yone_skin74", "yoneloadscreen_74.skins_yone_skin74"],
  ],
  Yorick: [
    ["0", "Original"],
    ["1", "Undertaker"],
    ["2", "Pentakill"],
    ["3", "Arclight"],
    ["4", "Meowrick"],
    ["12", "Resistance"],
    ["21", "Pentakill Lost Chapter"],
    ["30", "Spirit Blossom"],
    ["40", "Dark Star", "yorick_splash_<type>_40.skins_yorick_skin40", "yorickloadscreen_40.skins_yorick_skin40"],
    ["50", "High Noon", "yorick_splash_<type>_50.skins_yorick_skin50", "yorickloadscreen_50.skins_yorick_skin50"],
  ],
  Yunara: [
    ["0", "Original", "yunara_splash_<type>_0.yunara", "yunaraloadscreen_0.yunara"],
    ["1", "Spirit Blossom Springs", "yunara_splash_<type>_1.yunara", "yunaraloadscreen_1.yunara"],
  ],
  Yuumi: [
    ["0", "Original"],
    ["1", "Battle Principal"],
    ["11", "Heartseeker"],
    ["19", "Yuubee"],
    ["28", "Bewitching"],
    ["37", "EDG"],
    ["39", "Shiba"],
    ["49", "Cyber Cat", "yuumi_splash_<type>_49.skins_yuumi_skin49", "yuumiloadscreen_49.skins_yuumi_skin49"],
    ["50", "Prestige Cyber Cat", "yuumi_splash_<type>_50.skins_yuumi_skin50", "yuumiloadscreen_50.skins_yuumi_skin50"],
    ["61", "Nightbringer", "yuumi_splash_<type>_61.skins_yuumi_skin61", "yuumiloadscreen_61.skins_yuumi_skin61"],
    ["70", "Firecracker", "yuumi_splash_<type>_70.skins_yuumi_skin70", "yuumiloadscreen_70.skins_yuumi_skin70"],
  ],
  Zaahen: [
    ["0", "Original", "zaahen_splash_<type>_0.zaahen", "zaahenloadscreen_0.zaahen"],
    ["1", "Immortal Journey", "zaahen_splash_<type>_1.zaahen", "zaahenloadscreen_1.zaahen"],
  ],
  Zac: [
    ["0", "Original"],
    ["1", "Special Weapon"],
    ["2", "Pool Party"],
    ["6", "SKT T1"],
    ["7", "Battlecast"],
    ["14", "Empyrean"],
    ["24", "Zesty Dip"],
  ],
  Zed: [
    ["0", "Original"],
    ["1", "Shockblade"],
    ["2", "SKT T1"],
    ["3", "PROJECT"],
    ["10", "Worlds 2016"],
    ["11", "Death Sworn"],
    ["13", "Galaxy Slayer"],
    ["15", "PsyOps"],
    ["30", "Prestige PROJECT"],
    ["31", "Debonair"],
    ["38", "Empyrean"],
    ["49", "Immortal Journey"],
    ["58", "Blood Moon"],
    ["68", "Quantum Galaxy Slayer", "zed_splash_<type>_68.skins_zed_skin68", "zedloadscreen_68.skins_zed_skin68"],
    ["69", "Prestige Spirit Blossom", "zed_splash_<type>_69.skins_zed_skin69", "zedloadscreen_69.skins_zed_skin69"],
  ],
  Zeri: [
    ["0", "Original", undefined, "zeriloadscreen_0"],
    ["1", "Withered Rose"],
    ["10", "Ocean Song"],
    ["19", "Immortal Journey"],
    ["28", "Fright Night", "zeri_splash_<type>_28.skins_zeri_skin28", "zeriloadscreen_28.skins_zeri_skin28"],
    ["29", "Prestige Fright Night", "zeri_splash_<type>_29.skins_zeri_skin29", "zeriloadscreen_29.skins_zeri_skin29"],
    ["40", "Winter Wonder", "zeri_splash_<type>_40.skins_zeri_skin40", "zeriloadscreen_40.skins_zeri_skin40"],
  ],
  Ziggs: [
    ["0", "Original"],
    ["1", "Mad Scientist"],
    ["2", "Major"],
    ["3", "Pool Party"],
    ["4", "Snow Day"],
    ["5", "Master Arcanist"],
    ["6", "Battle Boss"],
    ["7", "Odyssey"],
    ["14", "Sugar Rush"],
    ["23", "Hextech"],
    ["24", "BZZZiggs"],
    ["33", "La Ilusión"],
    ["43", "Firecracker", "ziggs_splash_<type>_43.skins_ziggs_skin43", "ziggsloadscreen_43.skins_ziggs_skin43"],
  ],
  Zilean: [
    ["0", "Original"],
    ["1", "Old Saint"],
    ["2", "Groovy"],
    ["3", "Shurima Desert"],
    ["4", "Time Machine"],
    ["5", "Blood Moon"],
    ["6", "Sugar Rush"],
    ["14", "Winterblessed"],
    ["24", "Arcana", "zilean_splash_<type>_24.skins_zilean_skin24", "zileanloadscreen_24.skins_zilean_skin24"],
  ],
  Zoe: [
    ["0", "Original"],
    ["1", "Cyber Pop"],
    ["2", "Pool Party"],
    ["9", "Star Guardian"],
    ["18", "Arcanist"],
    ["19", "Prestige Arcanist"],
    ["20", "EDG"],
    ["22", "Winterblessed"],
    ["33", "Dark Star", "zoe_splash_<type>_33.skins_zoe_skin33", "zoeloadscreen_33.skins_zoe_skin33"],
    ["43", "Prestige Eternal Aspect", "zoe_splash_<type>_43.skins_zoe_skin43", "zoeloadscreen_43.skins_zoe_skin43"],
  ],
  Zyra: [
    ["0", "Original"],
    ["1", "Wildfire"],
    ["2", "Haunted"],
    ["3", "SKT T1"],
    ["4", "Dragon Sorceress"],
    ["5", "Coven"],
    ["6", "Prestige Coven"],
    ["7", "Crystal Rose"],
    ["16", "Crime City Nightmare"],
    ["36", "Mythmaker"],
    ["46", "Street Demons"],
    ["55", "Blood Moon"],
    ["64", "Spirit Blossom", "zyra_splash_<type>_64.skins_zyra_skin64", "zyraloadscreen_64.skins_zyra_skin64"],
  ],
} as const satisfies Record<string, readonly CompactSkin[]>

export const skinIndex: Record<string, Skin[]> = buildSkinIndex(compactSkinIndex)
