// Updated Patch 16.5 - 03/10/2026 04:23:16 PM CDT
import type { Skin } from "#shared/types"

type CompactSkin = readonly [
  id: string,
  name: string,
  keyOverride?: string,
  loadOverride?: string,
]

function defaultSkinKey(champion: string, id: string): string {
  return `${champion.toLowerCase()}_splash_<type>_${id}`
}

function defaultLoadKey(champion: string, id: string): string {
  const base = `${champion.toLowerCase()}loadscreen`
  return id === "0" ? base : `${base}_${id}`
}

function buildSkinIndex(compact: Record<string, readonly CompactSkin[]>): Record<string, Skin[]> {
  return Object.fromEntries(
    Object.entries(compact).map(([champion, skins]) => [
      champion,
      skins.map(([id, name, keyOverride, loadOverride]) => ({
        id,
        name,
        key: keyOverride ?? defaultSkinKey(champion, id),
        load: loadOverride ?? defaultLoadKey(champion, id),
      })),
    ]),
  )
}

const compactSkinIndex = {
  Aatrox: [
    ["0", "Original"],
    ["1", "Justicar Aatrox"],
    ["2", "Mecha Aatrox"],
    ["3", "Sea Hunter Aatrox"],
    ["7", "Blood Moon Aatrox"],
    ["8", "Prestige Blood Moon Aatrox"],
    ["9", "Victorious Aatrox"],
    ["11", "Odyssey Aatrox"],
    ["20", "Prestige Blood Moon Aatrox (2022)"],
    ["21", "Lunar Eclipse Aatrox"],
    ["30", "DRX Aatrox"],
    ["31", "Prestige DRX Aatrox"],
    ["33", "Primordian Aatrox"],
    ["8", "Prestige Blood Moon (2022)", undefined, "aatroxloadscreen_20"],
  ],
  Ahri: [
    ["0", "Original", undefined, "ahriloadscreen_0"],
    ["1", "Dynasty Ahri"],
    ["2", "Midnight Ahri"],
    ["3", "Foxfire Ahri"],
    ["4", "Popstar Ahri"],
    ["5", "Challenger Ahri"],
    ["6", "Academy Ahri"],
    ["7", "Arcade Ahri"],
    ["14", "Star Guardian Ahri"],
    ["15", "K/DA Ahri"],
    ["16", "Prestige K/DA Ahri"],
    ["17", "Elderwood Ahri"],
    ["27", "Spirit Blossom Ahri"],
    ["28", "K/DA ALL OUT Ahri"],
    ["42", "Coven Ahri"],
    ["65", "Prestige K/DA Ahri (2022)"],
    ["66", "Arcana Ahri"],
    ["76", "Snow Moon Ahri"],
    ["85", "Risen Legend Ahri"],
    ["86", "Immortalized Legend Ahri"],
    ["88", "Spirit Blossom Springs Ahri"],
    ["89", "After Hours Spirit Blossom Springs Ahri"],
    ["16", "Prestige KDA", undefined, "ahriloadscreen_16_le"],
    ["65", "Prestige KDA (2022)", undefined, "ahriloadscreen_65_le"],
  ],
  Akali: [
    ["0", "Original"],
    ["1", "Stinger Akali"],
    ["2", "Infernal Akali"],
    ["3", "All-star Akali"],
    ["4", "Nurse Akali"],
    ["5", "Blood Moon Akali"],
    ["6", "Silverfang Akali"],
    ["7", "Headhunter Akali"],
    ["8", "Sashimi Akali"],
    ["9", "K/DA Akali"],
    ["13", "Prestige K/DA Akali"],
    ["14", "PROJECT: Akali"],
    ["15", "True Damage Akali"],
    ["32", "K/DA ALL OUT Akali"],
    ["50", "Crime City Nightmare Akali"],
    ["60", "Prestige K/DA Akali (2022)"],
    ["61", "Star Guardian Akali"],
    ["68", "DRX Akali"],
    ["70", "Coven Akali"],
    ["71", "Prestige Coven Akali"],
    ["82", "Empyrean Akali"],
    ["92", "Spirit Blossom Akali"],
    ["13", "Prestige KDA (2022)", undefined, "akaliloadscreen_60"],
  ],
  Akshan: [
    ["0", "Original"],
    ["1", "Cyber Pop Akshan"],
    ["10", "Crystal Rose Akshan"],
    ["20", "Three Honors Akshan"],
  ],
  Alistar: [
    ["0", "Original"],
    ["1", "Black Alistar"],
    ["2", "Golden Alistar"],
    ["3", "Matador Alistar"],
    ["4", "Longhorn Alistar"],
    ["5", "Unchained Alistar"],
    ["6", "Infernal Alistar"],
    ["7", "Sweeper Alistar"],
    ["8", "Marauder Alistar"],
    ["9", "SKT T1 Alistar"],
    ["10", "Moo Cow Alistar"],
    ["19", "Hextech Alistar"],
    ["20", "Conqueror Alistar"],
    ["22", "Blackfrost Alistar"],
    ["29", "Lunar Beast Alistar"],
    ["40", "Elderwood Alistar"],
  ],
  Ambessa: [
    ["0", "Original"],
    ["1", "Chosen of the Wolf Ambessa"],
  ],
  Amumu: [
    ["0", "Original"],
    ["1", "Pharaoh Amumu"],
    ["2", "Vancouver Amumu"],
    ["3", "Emumu"],
    ["4", "Re-Gifted Amumu"],
    ["5", "Almost-Prom King Amumu"],
    ["6", "Little Knight Amumu"],
    ["7", "Sad Robot Amumu"],
    ["8", "Surprise Party Amumu"],
    ["17", "Infernal Amumu"],
    ["23", "Hextech Amumu"],
    ["24", "Pumpkin Prince Amumu"],
    ["34", "Porcelain Amumu"],
    ["44", "Heartache Amumu"],
    ["53", "Dumpling Darlings Amumu"],
  ],
  Anivia: [
    ["0", "Original"],
    ["1", "Team Spirit Anivia"],
    ["2", "Bird of Prey Anivia"],
    ["3", "Noxus Hunter Anivia"],
    ["4", "Hextech Anivia"],
    ["5", "Blackfrost Anivia"],
    ["6", "Prehistoric Anivia"],
    ["7", "Festival Queen Anivia"],
    ["8", "Papercraft Anivia"],
    ["17", "Cosmic Flight Anivia"],
    ["27", "Divine Phoenix Anivia"],
    ["37", "Bewitching Batnivia"],
    ["46", "Victorious Anivia"],
  ],
  Annie: [
    ["0", "Original"],
    ["1", "Goth Annie"],
    ["2", "Red Riding Annie"],
    ["3", "Annie in Wonderland"],
    ["4", "Prom Queen Annie"],
    ["5", "Frostfire Annie"],
    ["6", "Reverse Annie"],
    ["7", "FrankenTibbers Annie"],
    ["8", "Panda Annie"],
    ["9", "Sweetheart Annie"],
    ["10", "Hextech Annie"],
    ["11", "Super Galaxy Annie"],
    ["12", "Annie-Versary"],
    ["13", "Lunar Beast Annie"],
    ["22", "Cafe Cuties Annie"],
    ["31", "Fright Night Annie"],
    ["40", "Winterblessed Annie"],
    ["50", "Battle Princess Annie"],
  ],
  Aphelios: [
    ["0", "Original"],
    ["1", "Nightbringer Aphelios"],
    ["9", "Lunar Beast Aphelios"],
    ["18", "EDG Aphelios"],
    ["20", "Spirit Blossom Aphelios"],
    ["30", "HEARTSTEEL Aphelios"],
    ["40", "Prestige Spirit Blossom Springs Aphelios"],
  ],
  Ashe: [
    ["0", "Original"],
    ["1", "Freljord Ashe"],
    ["2", "Sherwood Forest Ashe"],
    ["3", "Woad Ashe"],
    ["4", "Queen Ashe"],
    ["5", "Amethyst Ashe"],
    ["6", "Heartseeker Ashe"],
    ["7", "Marauder Ashe"],
    ["8", "PROJECT: Ashe"],
    ["9", "Worlds 2017 Ashe"],
    ["11", "Cosmic Queen Ashe"],
    ["17", "High Noon Ashe"],
    ["23", "Fae Dragon Ashe"],
    ["32", "Coven Ashe"],
    ["43", "Ocean Song Ashe"],
    ["52", "Lunar Empress Ashe"],
    ["63", "DRX Ashe"],
    ["65", "Crystalis Motus Ashe"],
    ["67", "Infernal Ashe"],
    ["76", "Spirit Blossom Ashe"],
    ["84", "Firecracker Ashe"],
  ],
  AurelionSol: [
    ["0", "Original"],
    ["1", "Ashen Lord Aurelion Sol"],
    ["2", "Mecha Aurelion Sol"],
    ["11", "Storm Dragon Aurelion Sol"],
    ["21", "Inkshadow Aurelion Sol"],
    ["31", "Porcelain Protector Aurelion Sol"],
    ["38", "Divine Architect Porcelain Aurelion Sol"],
  ],
  Aurora: [
    ["0", "Original"],
    ["1", "Battle Bunny Aurora"],
    ["11", "Arcana Aurora"],
  ],
  Azir: [
    ["0", "Original"],
    ["1", "Galactic Azir"],
    ["2", "Gravelord Azir"],
    ["3", "SKT T1 Azir"],
    ["4", "Warring Kingdoms Azir"],
    ["5", "Elderwood Azir"],
    ["14", "Worlds 2022 Azir"],
    ["19", "Attorney Azir"],
  ],
  Bard: [
    ["0", "Original"],
    ["1", "Elderwood Bard"],
    ["5", "Snow Day Bard"],
    ["6", "Bard Bard"],
    ["8", "Astronaut Bard"],
    ["17", "Cafe Cuties Bard"],
    ["26", "Shan Hai Scrolls Bard"],
    ["35", "T1 Bard"],
    ["37", "Spirit Blossom Bard"],
  ],
  Belveth: [
    ["0", "Original", undefined, "belvethloadscreen_0"],
    ["1", "Battle Boss Bel'Veth"],
    ["10", "Cosmic Matriarch Bel'Veth"],
    ["19", "Primordian Bel'Veth"],
  ],
  Blitzcrank: [
    ["0", "Original"],
    ["1", "Rusty Blitzcrank"],
    ["2", "Goalkeeper Blitzcrank"],
    ["3", "Boom Boom Blitzcrank"],
    ["4", "Piltover Customs Blitzcrank"],
    ["5", "Definitely Not Blitzcrank"],
    ["6", "iBlitzcrank"],
    ["7", "Riot Blitzcrank"],
    ["11", "Battle Boss Blitzcrank"],
    ["20", "Lancer Rogue Blitzcrank"],
    ["21", "Lancer Paragon Blitzcrank"],
    ["22", "Witch's Brew Blitzcrank"],
    ["29", "Space Groove Blitz & Crank"],
    ["36", "Victorious Blitzcrank"],
    ["47", "Zenith Games Blitzcrank"],
    ["56", "Beezcrank"],
  ],
  Brand: [
    ["0", "Original"],
    ["1", "Apocalyptic Brand"],
    ["2", "Vandal Brand"],
    ["3", "Cryocore Brand"],
    ["4", "Zombie Brand"],
    ["5", "Spirit Fire Brand"],
    ["6", "Battle Boss Brand"],
    ["7", "Arclight Brand"],
    ["8", "Eternal Dragon Brand"],
    ["21", "Debonair Brand"],
    ["22", "Prestige Debonair Brand"],
    ["33", "Street Demons Brand"],
    ["42", "Empyrean Brand"],
  ],
  Braum: [
    ["0", "Original"],
    ["1", "Dragonslayer Braum"],
    ["2", "El Tigre Braum"],
    ["3", "Braum Lionheart"],
    ["10", "Santa Braum"],
    ["11", "Crime City Braum"],
    ["24", "Sugar Rush Braum"],
    ["33", "Pool Party Braum"],
    ["42", "Grill Master Braum"],
  ],
  Briar: [
    ["0", "Original", undefined, "briarloadscreen_0"],
    ["1", "Street Demons Briar"],
    ["10", "Primordian Briar"],
    ["20", "Battle Academia Briar"],
  ],
  Caitlyn: [
    ["0", "Original", undefined, "caitlynloadscreen_0"],
    ["1", "Resistance Caitlyn"],
    ["2", "Sheriff Caitlyn"],
    ["3", "Safari Caitlyn"],
    ["4", "Arctic Warfare Caitlyn"],
    ["5", "Officer Caitlyn"],
    ["6", "Headhunter Caitlyn"],
    ["10", "Lunar Wraith Caitlyn"],
    ["11", "Pulsefire Caitlyn"],
    ["13", "Pool Party Caitlyn"],
    ["19", "Arcade Caitlyn"],
    ["20", "Prestige Arcade Caitlyn"],
    ["22", "Battle Academia Caitlyn"],
    ["28", "Arcane Enforcer Caitlyn"],
    ["29", "Prestige Arcade Caitlyn (2022)"],
    ["30", "Snow Moon Caitlyn"],
    ["39", "Heartthrob Caitlyn"],
    ["48", "DRX Caitlyn"],
    ["50", "Arcane Commander Caitlyn"],
    ["51", "Prestige Arcane Commander Caitlyn"],
    ["54", "Firecracker Caitlyn"],
    ["20", "Prestige Arcade", undefined, "caitlynloadscreen_20_le"],
    ["20", "Prestige Arcade (2022)", undefined, "caitlynloadscreen_29"],
  ],
  Camille: [
    ["0", "Original"],
    ["1", "Program Camille"],
    ["2", "Coven Camille"],
    ["10", "iG Camille"],
    ["11", "Arcana Camille"],
    ["21", "Strike Commander Camille"],
    ["31", "Winterblessed Camille"],
    ["32", "Prestige Winterblessed Camille"],
    ["44", "Petals of Spring Camille"],
  ],
  Cassiopeia: [
    ["0", "Original"],
    ["1", "Desperada Cassiopeia"],
    ["2", "Siren Cassiopeia"],
    ["3", "Mythic Cassiopeia"],
    ["4", "Jade Fang Cassiopeia"],
    ["8", "Eternum Cassiopeia"],
    ["9", "Spirit Blossom Cassiopeia"],
    ["18", "Coven Cassiopeia"],
    ["28", "Bewitching Cassiopeia"],
    ["38", "Prestige Mythmaker Cassiopeia"],
  ],
  Chogath: [
    ["0", "Original"],
    ["1", "Nightmare Cho'Gath"],
    ["2", "Gentleman Cho'Gath"],
    ["3", "Loch Ness Cho'Gath"],
    ["4", "Jurassic Cho'Gath"],
    ["5", "Battlecast Prime Cho'Gath"],
    ["6", "Prehistoric Cho'Gath"],
    ["7", "Dark Star Cho'Gath"],
    ["14", "Shan Hai Scrolls Cho'Gath"],
    ["23", "Broken Covenant Cho'Gath"],
    ["32", "Toy Terror Cho'Gath"],
    ["41", "Petricite Cho'Gath"],
  ],
  Corki: [
    ["0", "Original"],
    ["1", "UFO Corki"],
    ["2", "Ice Toboggan Corki"],
    ["3", "Red Baron Corki"],
    ["4", "Hot Rod Corki"],
    ["5", "Urfrider Corki"],
    ["6", "Dragonwing Corki"],
    ["7", "Fnatic Corki"],
    ["8", "Arcade Corki"],
    ["18", "Corgi Corki"],
    ["26", "Astronaut Corki"],
    ["36", "Brick Toy Corki"],
  ],
  Darius: [
    ["0", "Original"],
    ["1", "Lord Darius"],
    ["2", "Bioforge Darius"],
    ["3", "Woad King Darius"],
    ["4", "Dunkmaster Darius"],
    ["8", "Academy Darius"],
    ["14", "Dreadnova Darius"],
    ["15", "God-King Darius"],
    ["16", "High Noon Darius"],
    ["24", "Lunar Beast Darius"],
    ["33", "Crime City Nightmare Darius"],
    ["43", "Spirit Blossom Darius"],
    ["54", "Porcelain Darius"],
    ["64", "Divine God-King Darius"],
    ["65", "Prestige Triumphant General Darius"],
    ["67", "Mecha Kingdoms Darius"],
  ],
  Diana: [
    ["0", "Original"],
    ["1", "Dark Valkyrie Diana"],
    ["2", "Lunar Goddess Diana"],
    ["3", "Infernal Diana"],
    ["11", "Blood Moon Diana"],
    ["12", "Dark Waters Diana"],
    ["18", "Dragonslayer Diana"],
    ["25", "Battle Queen Diana"],
    ["26", "Prestige Battle Queen Diana"],
    ["27", "Sentinel Diana"],
    ["37", "Firecracker Diana"],
    ["47", "Winterblessed Diana"],
    ["54", "Heavenscale Diana"],
    ["64", "Dark Cosmic Diana"],
    ["65", "Prestige Dark Cosmic Diana"],
  ],
  Draven: [
    ["0", "Original"],
    ["1", "Soul Reaver Draven"],
    ["2", "Gladiator Draven"],
    ["3", "Primetime Draven"],
    ["4", "Pool Party Draven"],
    ["5", "Beast Hunter Draven"],
    ["6", "Draven Draven"],
    ["12", "Santa Draven"],
    ["13", "Mecha Kingdoms Draven"],
    ["20", "Ruined Draven"],
    ["29", "Debonair Draven"],
    ["39", "Fright Night Draven"],
    ["48", "La Ilusión Draven"],
    ["58", "Grand Reckoning Draven"],
    ["68", "Victorious Draven"],
  ],
  DrMundo: [
    ["0", "Original", undefined, "drmundoloadscreen_0"],
    ["1", "Toxic Dr. Mundo"],
    ["2", "Mr. Mundoverse"],
    ["3", "Corporate Mundo"],
    ["4", "Mundo Mundo"],
    ["5", "Executioner Mundo"],
    ["6", "Rageborn Mundo"],
    ["7", "TPA Mundo"],
    ["8", "Pool Party Mundo"],
    ["9", "El Macho Mundo"],
    ["10", "Frozen Prince Mundo"],
    ["21", "Street Demons Dr. Mundo"],
  ],
  Ekko: [
    ["0", "Original"],
    ["1", "Sandstorm Ekko"],
    ["2", "Academy Ekko"],
    ["3", "PROJECT: Ekko"],
    ["11", "SKT T1 Ekko"],
    ["12", "Trick or Treat Ekko"],
    ["19", "True Damage Ekko"],
    ["28", "Pulsefire Ekko"],
    ["36", "Arcane Firelight Ekko"],
    ["45", "Star Guardian Ekko"],
    ["46", "Prestige Star Guardian Ekko"],
    ["56", "Breakout True Damage Ekko"],
    ["57", "Arcane Last Stand Ekko"],
  ],
  Elise: [
    ["0", "Original"],
    ["1", "Death Blossom Elise"],
    ["2", "Victorious Elise"],
    ["3", "Blood Moon Elise"],
    ["4", "SKT T1 Elise"],
    ["5", "Super Galaxy Elise"],
    ["6", "Bewitching Elise"],
    ["15", "Withered Rose Elise"],
    ["24", "Coven Elise"],
    ["34", "Masque of the Black Rose Elise"],
  ],
  Evelynn: [
    ["0", "Original"],
    ["1", "Shadow Evelynn"],
    ["2", "Masquerade Evelynn"],
    ["3", "Tango Evelynn"],
    ["4", "Safecracker Evelynn"],
    ["5", "Blood Moon Evelynn"],
    ["6", "K/DA Evelynn"],
    ["7", "Prestige K/DA Evelynn"],
    ["8", "Sugar Rush Evelynn"],
    ["15", "K/DA ALL OUT Evelynn"],
    ["24", "Coven Evelynn"],
    ["31", "Prestige K/DA Evelynn (2022)"],
    ["32", "Spirit Blossom Evelynn"],
    ["42", "Soul Fighter Evelynn"],
    ["52", "High Noon Evelynn"],
    ["53", "Prestige High Noon Evelynn"],
    ["64", "Nightbringer Evelynn"],
    ["7", "Prestige KDA (2022)", undefined, "evelynnloadscreen_31"],
  ],
  Ezreal: [
    ["0", "Original"],
    ["1", "Nottingham Ezreal"],
    ["2", "Striker Ezreal"],
    ["3", "Frosted Ezreal"],
    ["4", "Explorer Ezreal"],
    ["5", "Pulsefire Ezreal"],
    ["6", "TPA Ezreal"],
    ["7", "Debonair Ezreal"],
    ["8", "Ace of Spades Ezreal"],
    ["9", "Arcade Ezreal"],
    ["18", "Star Guardian Ezreal"],
    ["19", "SSG Ezreal"],
    ["20", "Pajama Guardian Ezreal"],
    ["21", "Battle Academia Ezreal"],
    ["22", "PsyOps Ezreal"],
    ["23", "Prestige PsyOps Ezreal"],
    ["25", "Porcelain Protector Ezreal"],
    ["33", "Faerie Court Ezreal"],
    ["43", "HEARTSTEEL Ezreal"],
    ["44", "Heavenscale Ezreal"],
    ["54", "Prestige Heavenscale Ezreal"],
    ["65", "Masque of the Black Rose Ezreal"],
  ],
  Fiddlesticks: [
    ["0", "Original"],
    ["1", "Spectral Fiddlesticks"],
    ["2", "Union Jack Fiddlesticks"],
    ["3", "Bandito Fiddlesticks"],
    ["4", "Pumpkinhead Fiddlesticks"],
    ["5", "Fiddle Me Timbers"],
    ["6", "Surprise Party Fiddlesticks"],
    ["7", "Dark Candy Fiddlesticks"],
    ["8", "Risen Fiddlesticks"],
    ["9", "Praetorian Fiddlesticks"],
    ["27", "Star Nemesis Fiddlesticks"],
    ["37", "Blood Moon Fiddlesticks"],
    ["46", "Flora Fatalis Fiddlesticks"],
  ],
  Fiora: [
    ["0", "Original"],
    ["1", "Royal Guard Fiora"],
    ["2", "Nightraven Fiora"],
    ["3", "Headmistress Fiora"],
    ["4", "PROJECT: Fiora"],
    ["5", "Pool Party Fiora"],
    ["22", "Soaring Sword Fiora"],
    ["23", "Heartpiercer Fiora"],
    ["31", "iG Fiora"],
    ["41", "Pulsefire Fiora"],
    ["50", "Lunar Beast Fiora"],
    ["51", "Prestige Lunar Beast Fiora"],
    ["60", "Bewitching Fiora"],
    ["69", "Faerie Court Fiora"],
    ["80", "Dragonmancer Fiora"],
    ["89", "Battle Queen Fiora"],
    ["98", "Victorious Fiora"],
  ],
  Fizz: [
    ["0", "Original"],
    ["1", "Atlantean Fizz"],
    ["2", "Tundra Fizz"],
    ["3", "Fisherman Fizz"],
    ["4", "Void Fizz"],
    ["8", "Cottontail Fizz"],
    ["9", "Super Galaxy Fizz"],
    ["10", "Omega Squad Fizz"],
    ["14", "Fuzz Fizz"],
    ["15", "Prestige Fuzz Fizz"],
    ["16", "Little Devil Fizz"],
    ["25", "Prestige Fuzz Fizz (2022)"],
    ["26", "Astronaut Fizz"],
    ["35", "Rain Shepherd Fizz"],
    ["15", "Prestige Fuzz (2022)", undefined, "fizzloadscreen_25"],
  ],
  Galio: [
    ["0", "Original"],
    ["1", "Enchanted Galio"],
    ["2", "Hextech Galio"],
    ["3", "Commando Galio"],
    ["4", "Gatekeeper Galio"],
    ["5", "Debonair Galio"],
    ["6", "Birdio"],
    ["13", "Infernal Galio"],
    ["19", "Dragon Guardian Galio"],
    ["28", "Mythmaker Galio"],
    ["40", "Aegis Frame Galio"],
  ],
  Gangplank: [
    ["0", "Original"],
    ["1", "Spooky Gangplank"],
    ["2", "Minuteman Gangplank"],
    ["3", "Sailor Gangplank"],
    ["4", "Toy Soldier Gangplank"],
    ["5", "Special Forces Gangplank"],
    ["6", "Sultan Gangplank"],
    ["7", "Captain Gangplank"],
    ["8", "Dreadnova Gangplank"],
    ["14", "Pool Party Gangplank"],
    ["21", "FPX Gangplank"],
    ["23", "Gangplank the Betrayer"],
    ["33", "PROJECT: Gangplank"],
  ],
  Garen: [
    ["0", "Original"],
    ["1", "Sanguine Garen"],
    ["2", "Desert Trooper Garen"],
    ["3", "Commando Garen"],
    ["4", "Dreadknight Garen"],
    ["5", "Rugged Garen"],
    ["6", "Steel Legion Garen"],
    ["10", "Rogue Admiral Garen"],
    ["11", "Warring Kingdoms Garen"],
    ["13", "God-King Garen"],
    ["14", "Demacia Vice Garen"],
    ["22", "Mecha Kingdoms Garen"],
    ["23", "Prestige Mecha Kingdoms Garen"],
    ["24", "Battle Academia Garen"],
    ["33", "Mythmaker Garen"],
    ["44", "Fallen God-King Garen"],
    ["46", "Visions of the Fallen Garen"],
  ],
  Gnar: [
    ["0", "Original"],
    ["1", "Dino Gnar"],
    ["2", "Gentleman Gnar"],
    ["3", "Snow Day Gnar"],
    ["4", "El León Gnar"],
    ["13", "Super Galaxy Gnar"],
    ["14", "SSG Gnar"],
    ["15", "Astronaut Gnar"],
    ["22", "Elderwood Gnar"],
    ["31", "La Ilusión Gnar"],
    ["41", "T1 Gnar"],
  ],
  Gragas: [
    ["0", "Original"],
    ["1", "Scuba Gragas"],
    ["2", "Hillbilly Gragas"],
    ["3", "Santa Gragas"],
    ["4", "Gragas, Esq."],
    ["5", "Vandal Gragas"],
    ["6", "Oktoberfest Gragas"],
    ["7", "Superfan Gragas"],
    ["8", "Fnatic Gragas"],
    ["9", "Gragas Caskbreaker"],
    ["10", "Arctic Ops Gragas"],
    ["11", "Warden Gragas"],
    ["20", "Space Groove Gragas"],
    ["29", "High Noon Gragas"],
    ["39", "Music Fan Gragas"],
  ],
  Graves: [
    ["0", "Original"],
    ["1", "Hired Gun Graves"],
    ["2", "Jailbreak Graves"],
    ["3", "Crime City Graves"],
    ["4", "Riot Graves"],
    ["5", "Pool Party Graves"],
    ["6", "Cutthroat Graves"],
    ["7", "Snow Day Graves"],
    ["14", "Victorious Graves"],
    ["18", "Praetorian Graves"],
    ["25", "Battle Professor Graves"],
    ["35", "Sentinel Graves"],
    ["42", "EDG Graves"],
    ["45", "Porcelain Graves"],
  ],
  Gwen: [
    ["0", "Original", undefined, "gwenloadscreen_0"],
    ["1", "Space Groove Gwen"],
    ["11", "Cafe Cuties Gwen"],
    ["20", "Soul Fighter Gwen"],
    ["30", "Battle Queen Gwen"],
    ["39", "Rain Shepherd Gwen"],
  ],
  Hecarim: [
    ["0", "Original", undefined, "hecarimloadscreen_0"],
    ["1", "Blood Knight Hecarim"],
    ["2", "Reaper Hecarim"],
    ["3", "Headless Hecarim"],
    ["4", "Arcade Hecarim"],
    ["5", "Elderwood Hecarim"],
    ["6", "Worldbreaker Hecarim"],
    ["7", "Lancer Zero Hecarim"],
    ["8", "High Noon Hecarim"],
    ["14", "Cosmic Charger Hecarim"],
    ["22", "Arcana Hecarim"],
    ["31", "Winterblessed Hecarim"],
    ["41", "Nightbringer Hecarim"],
  ],
  Heimerdinger: [
    ["0", "Original"],
    ["1", "Alien Invader Heimerdinger"],
    ["2", "Blast Zone Heimerdinger"],
    ["3", "Piltover Customs Heimerdinger"],
    ["4", "Snowmerdinger"],
    ["5", "Hazmat Heimerdinger"],
    ["6", "Dragon Trainer Heimerdinger"],
    ["15", "Pool Party Heimerdinger"],
    ["24", "Heimerstinger"],
    ["33", "Arcane Professor Heimerdinger"],
  ],
  Hwei: [
    ["0", "Original", undefined, "hweiloadscreen_0"],
    ["1", "Winterblessed Hwei"],
    ["11", "Spirit Blossom Hwei"],
  ],
  Illaoi: [
    ["0", "Original"],
    ["1", "Void Bringer Illaoi"],
    ["2", "Resistance Illaoi"],
    ["10", "Cosmic Invoker Illaoi"],
    ["18", "Snow Moon Illaoi"],
    ["27", "Battle Bear Illaoi"],
  ],
  Irelia: [
    ["0", "Original"],
    ["1", "Nightblade Irelia"],
    ["2", "Aviator Irelia"],
    ["3", "Infiltrator Irelia"],
    ["4", "Frostblade Irelia"],
    ["5", "Order of the Lotus Irelia"],
    ["6", "Divine Sword Irelia"],
    ["15", "iG Irelia"],
    ["16", "PROJECT: Irelia"],
    ["17", "Prestige PROJECT: Irelia"],
    ["18", "High Noon Irelia"],
    ["26", "Sentinel Irelia"],
    ["36", "Prestige PROJECT: Irelia (2022)"],
    ["37", "Mythmaker Irelia"],
    ["45", "Porcelain Irelia"],
    ["55", "Spirit Blossom Irelia"],
    ["17", "Prestige PROJECT (2022)", undefined, "irelialoadscreen_36"],
  ],
  Ivern: [
    ["0", "Original"],
    ["1", "Candy King Ivern"],
    ["2", "Dunkmaster Ivern"],
    ["11", "Old God Ivern"],
    ["20", "Astronaut Ivern"],
    ["30", "Spirit Blossom Ivern"],
  ],
  Janna: [
    ["0", "Original"],
    ["1", "Tempest Janna"],
    ["2", "Hextech Janna"],
    ["3", "Frost Queen Janna"],
    ["4", "Victorious Janna"],
    ["5", "Forecast Janna"],
    ["6", "Fnatic Janna"],
    ["7", "Star Guardian Janna"],
    ["8", "Sacred Sword Janna"],
    ["13", "Bewitching Janna"],
    ["20", "Guardian of the Sands Janna"],
    ["27", "Battle Queen Janna"],
    ["36", "Crystal Rose Janna"],
    ["45", "Cyber Halo Janna"],
    ["46", "Prestige Cyber Halo Janna"],
    ["56", "Heavenscale Janna"],
    ["66", "Dawnbringer Janna"],
  ],
  JarvanIV: [
    ["0", "Original"],
    ["1", "Commando Jarvan IV"],
    ["2", "Dragonslayer Jarvan IV"],
    ["3", "Darkforge Jarvan IV"],
    ["4", "Victorious Jarvan IV"],
    ["5", "Warring Kingdoms Jarvan IV"],
    ["6", "Fnatic Jarvan IV"],
    ["7", "Dark Star Jarvan IV"],
    ["8", "SSG Jarvan IV"],
    ["9", "Hextech Jarvan IV"],
    ["11", "Pool Party Jarvan IV"],
    ["21", "Lunar Beast Jarvan IV"],
    ["30", "Worlds 2021 Jarvan IV"],
    ["35", "Nightbringer Jarvan IV"],
    ["44", "Mythmaker Jarvan IV"],
    ["54", "Prestige Visions of the Fallen Jarvan IV"],
  ],
  Jax: [
    ["0", "Original", undefined, "jaxloadscreen_0"],
    ["1", "The Mighty Jax"],
    ["2", "Vandal Jax"],
    ["3", "Angler Jax"],
    ["4", "PAX Jax"],
    ["5", "Jaximus"],
    ["6", "Temple Jax"],
    ["7", "Nemesis Jax"],
    ["8", "SKT T1 Jax"],
    ["12", "Warden Jax"],
    ["13", "God Staff Jax"],
    ["14", "Mecha Kingdoms Jax"],
    ["20", "Conqueror Jax"],
    ["21", "Prestige Conqueror Jax"],
    ["22", "Empyrean Jax"],
    ["32", "Neo PAX Jax"],
    ["33", "PROJECT: Jax"],
  ],
  Jayce: [
    ["0", "Original"],
    ["1", "Full Metal Jayce"],
    ["2", "Debonair Jayce"],
    ["3", "Forsaken Jayce"],
    ["4", "Jayce Brighthammer"],
    ["5", "Battle Academia Jayce"],
    ["15", "Resistance Jayce"],
    ["24", "Arcane Inventor Jayce"],
    ["25", "Zenith Games Jayce"],
    ["34", "T1 Jayce"],
    ["35", "Arcane Survivor Jayce"],
    ["36", "Prestige T1 Jayce"],
    ["38", "Petals of Spring Jayce"],
  ],
  Jhin: [
    ["0", "Original"],
    ["1", "High Noon Jhin"],
    ["2", "Blood Moon Jhin"],
    ["3", "SKT T1 Jhin"],
    ["4", "PROJECT: Jhin"],
    ["5", "Dark Cosmic Jhin"],
    ["14", "Shan Hai Scrolls Jhin"],
    ["23", "DWG Jhin"],
    ["25", "Empyrean Jhin"],
    ["36", "Soul Fighter Jhin"],
    ["37", "Dark Cosmic Erasure Jhin"],
    ["47", "Mythmaker Jhin"],
    ["55", "Arcana Jhin"],
  ],
  Jinx: [
    ["0", "Original"],
    ["1", "Crime City Jinx"],
    ["2", "Firecracker Jinx"],
    ["3", "Zombie Slayer Jinx"],
    ["4", "Star Guardian Jinx"],
    ["12", "Ambitious Elf Jinx"],
    ["13", "Odyssey Jinx"],
    ["20", "PROJECT: Jinx"],
    ["29", "Heartseeker Jinx"],
    ["37", "Arcane Enemy Jinx"],
    ["38", "Battle Cat Jinx"],
    ["40", "Prestige Battle Cat Jinx"],
    ["51", "Cafe Cuties Jinx"],
    ["60", "Arcane Fractured Jinx"],
    ["62", "T1 Jinx"],
  ],
  Kaisa: [
    ["0", "Original"],
    ["1", "Bullet Angel Kai'Sa"],
    ["14", "K/DA Kai'Sa"],
    ["15", "Prestige K/DA Kai'Sa"],
    ["16", "iG Kai'Sa"],
    ["17", "Arcade Kai'Sa"],
    ["26", "K/DA ALL OUT Kai'Sa"],
    ["27", "Prestige K/DA ALL OUT Kai'Sa"],
    ["29", "Lagoon Dragon Kai'Sa"],
    ["39", "Prestige K/DA Kai'Sa (2022)"],
    ["40", "Star Guardian Kai'Sa"],
    ["48", "Inkshadow Kai'Sa"],
    ["59", "Heavenscale Kai'Sa"],
    ["69", "Dark Star Kai'Sa"],
    ["70", "Risen Legend Kai'Sa"],
    ["71", "Immortalized Legend Kai'Sa"],
    ["15", "Prestige KDA (2022)", undefined, "kaisaloadscreen_39"],
  ],
  Kalista: [
    ["0", "Original"],
    ["1", "Blood Moon Kalista"],
    ["2", "Worlds 2015 Kalista"],
    ["3", "SKT T1 Kalista"],
    ["5", "Marauder Kalista"],
    ["14", "Faerie Court Kalista"],
    ["24", "Dawnbringer Kalista"],
  ],
  Karma: [
    ["0", "Original"],
    ["1", "Sun Goddess Karma"],
    ["2", "Sakura Karma"],
    ["3", "Traditional Karma"],
    ["4", "Order of the Lotus Karma"],
    ["5", "Warden Karma"],
    ["6", "Winter Wonder Karma"],
    ["7", "Conqueror Karma"],
    ["8", "Dark Star Karma"],
    ["19", "Dawnbringer Karma"],
    ["26", "Odyssey Karma"],
    ["27", "Ruined Karma"],
    ["44", "Tranquility Dragon Karma"],
    ["54", "Faerie Queen Karma"],
    ["61", "Infernal Karma"],
    ["70", "Spirit Blossom Karma"],
  ],
  Karthus: [
    ["0", "Original"],
    ["1", "Phantom Karthus"],
    ["2", "Statue of Karthus"],
    ["3", "Grim Reaper Karthus"],
    ["4", "Pentakill Karthus"],
    ["5", "Fnatic Karthus"],
    ["9", "Karthus Lightsbane"],
    ["10", "Infernal Karthus"],
    ["17", "Pentakill III: Lost Chapter Karthus"],
    ["26", "Elderwood Karthus"],
    ["35", "Arcana Karthus"],
  ],
  Kassadin: [
    ["0", "Original", undefined, "kassadinloadscreen_0"],
    ["1", "Festival Kassadin"],
    ["2", "Deep One Kassadin"],
    ["3", "Pre-Void Kassadin"],
    ["4", "Harbinger Kassadin"],
    ["5", "Cosmic Reaver Kassadin"],
    ["6", "Count Kassadin"],
    ["14", "Hextech Kassadin"],
    ["15", "Shockblade Kassadin"],
    ["24", "Dragonmancer Kassadin"],
  ],
  Katarina: [
    ["0", "Original"],
    ["1", "Mercenary Katarina"],
    ["2", "Red Card Katarina"],
    ["3", "Bilgewater Katarina"],
    ["4", "Kitty Cat Katarina"],
    ["5", "High Command Katarina"],
    ["6", "Sandstorm Katarina"],
    ["7", "Slay Belle Katarina"],
    ["8", "Warring Kingdoms Katarina"],
    ["9", "PROJECT: Katarina"],
    ["10", "Death Sworn Katarina"],
    ["12", "Battle Academia Katarina"],
    ["21", "Blood Moon Katarina"],
    ["29", "Battle Queen Katarina"],
    ["37", "High Noon Katarina"],
    ["47", "Faerie Court Katarina"],
    ["48", "Prestige Faerie Court Katarina"],
    ["59", "Chosen of the Wolf Katarina"],
    ["60", "Prestige Masque of the Black Rose Katarina"],
    ["70", "Petals of Spring Katarina"],
  ],
  Kayle: [
    ["0", "Original"],
    ["1", "Silver Kayle"],
    ["2", "Viridian Kayle"],
    ["3", "Transcended Kayle"],
    ["4", "Battleborn Kayle"],
    ["5", "Judgment Kayle"],
    ["6", "Aether Wing Kayle"],
    ["7", "Riot Kayle"],
    ["8", "Iron Inquisitor Kayle"],
    ["9", "Pentakill Kayle"],
    ["15", "PsyOps Kayle"],
    ["24", "Dragonslayer Kayle"],
    ["33", "Pentakill III: Lost Chapter Kayle"],
    ["42", "Sun-Eater Kayle"],
    ["57", "Immortal Journey Kayle"],
    ["66", "Empyrean Kayle"],
    ["67", "Prestige Empyrean Kayle"],
    ["78", "Spirit Blossom Kayle"],
  ],
  Kayn: [
    ["0", "Original"],
    ["1", "Soulhunter Kayn"],
    ["2", "Odyssey Kayn"],
    ["8", "Nightbringer Kayn"],
    ["9", "Prestige Nightbringer Kayn"],
    ["15", "Snow Moon Kayn"],
    ["20", "HEARTSTEEL Kayn"],
    ["26", "Battle Academia Kayn"],
  ],
  Kennen: [
    ["0", "Original"],
    ["1", "Deadly Kennen"],
    ["2", "Swamp Master Kennen"],
    ["3", "Karate Kennen"],
    ["4", "Kennen M.D."],
    ["5", "Arctic Ops Kennen"],
    ["6", "Blood Moon Kennen"],
    ["7", "Super Kennen"],
    ["8", "Infernal Kennen"],
    ["23", "DWG Kennen"],
    ["25", "Astronaut Kennen"],
  ],
  Khazix: [
    ["0", "Original"],
    ["1", "Mecha Kha'Zix"],
    ["2", "Guardian of the Sands Kha'Zix"],
    ["3", "Death Blossom Kha'Zix"],
    ["4", "Dark Star Kha'Zix"],
    ["11", "Worlds 2018 Kha'Zix"],
    ["60", "Odyssey Kha'Zix"],
    ["69", "Lunar Guardian Kha'Zix"],
    ["79", "Crystalis Indomitus Kha'Zix"],
  ],
  Kindred: [
    ["0", "Original"],
    ["1", "Shadowfire Kindred"],
    ["2", "Super Galaxy Kindred"],
    ["3", "Spirit Blossom Kindred"],
    ["12", "Porcelain Kindred"],
    ["22", "Woof and Lamb Kindred"],
    ["23", "DRX Kindred"],
    ["33", "Prestige Porcelain Kindred"],
    ["34", "Chosen of the Wolf Kindred"],
  ],
  Kled: [
    ["0", "Original"],
    ["1", "Sir Kled"],
    ["2", "Count Kledula"],
    ["9", "Marauder Kled"],
    ["18", "Kibble-Head Kled"],
  ],
  KogMaw: [
    ["0", "Original"],
    ["1", "Caterpillar Kog'Maw"],
    ["2", "Sonoran Kog'Maw"],
    ["3", "Monarch Kog'Maw"],
    ["4", "Reindeer Kog'Maw"],
    ["5", "Lion Dance Kog'Maw"],
    ["6", "Deep Sea Kog'Maw"],
    ["7", "Jurassic Kog'Maw"],
    ["8", "Battlecast Kog'Maw"],
    ["9", "Pug'Maw"],
    ["10", "Hextech Kog'Maw"],
    ["19", "Arcanist Kog'Maw"],
    ["28", "Bee'Maw"],
    ["37", "Zap'Maw"],
    ["46", "Shan Hai Scrolls Kog'Maw"],
    ["55", "Victorious Kog'Maw"],
  ],
  KSante: [
    ["0", "Original", undefined, "ksanteloadscreen_0"],
    ["1", "Empyrean K'Sante"],
    ["2", "Prestige Empyrean K'Sante"],
    ["8", "HEARTSTEEL K'Sante"],
  ],
  Leblanc: [
    ["0", "Original"],
    ["1", "Wicked LeBlanc"],
    ["2", "Prestigious LeBlanc"],
    ["3", "Mistletoe LeBlanc"],
    ["4", "Ravenborn LeBlanc"],
    ["5", "Elderwood LeBlanc"],
    ["12", "Program LeBlanc"],
    ["19", "iG LeBlanc"],
    ["20", "Coven LeBlanc"],
    ["29", "Worlds 2020 LeBlanc"],
    ["33", "Prestige Coven LeBlanc"],
    ["35", "Debonair LeBlanc"],
    ["45", "Bewitching LeBlanc"],
    ["55", "Risen Legend LeBlanc"],
  ],
  LeeSin: [
    ["0", "Original", undefined, "leesinloadscreen_0"],
    ["1", "Traditional Lee Sin"],
    ["2", "Acolyte Lee Sin"],
    ["3", "Dragon Fist Lee Sin"],
    ["4", "Muay Thai Lee Sin"],
    ["5", "Pool Party Lee Sin"],
    ["6", "SKT T1 Lee Sin"],
    ["10", "Knockout Lee Sin"],
    ["11", "God Fist Lee Sin"],
    ["12", "Playmaker Lee Sin"],
    ["27", "Nightbringer Lee Sin"],
    ["28", "Prestige Nightbringer Lee Sin"],
    ["29", "FPX Lee Sin"],
    ["31", "Storm Dragon Lee Sin"],
    ["39", "Prestige Nightbringer Lee Sin (2022)"],
    ["41", "Zenith Games Lee Sin"],
    ["51", "Heavenscale Lee Sin"],
    ["52", "Divine Heavenscale Lee Sin"],
    ["68", "T1 Lee Sin"],
    ["72", "Inkshadow Lee Sin"],
    ["28", "Prestige Nightbringer", undefined, "leesinloadscreen_28_le"],
    ["39", "Prestige Nightbringer (2022)", undefined, "leesinloadscreen_39_le"],
  ],
  Leona: [
    ["0", "Original"],
    ["1", "Valkyrie Leona"],
    ["2", "Defender Leona"],
    ["3", "Iron Solari Leona"],
    ["4", "Pool Party Leona"],
    ["8", "PROJECT: Leona"],
    ["9", "Barbecue Leona"],
    ["10", "Solar Eclipse Leona"],
    ["11", "Lunar Eclipse Leona"],
    ["12", "Mecha Kingdoms Leona"],
    ["21", "Battle Academia Leona"],
    ["22", "DWG Leona"],
    ["23", "Prestige Battle Academia Leona"],
    ["33", "Debonair Leona"],
    ["34", "High Noon Leona"],
    ["50", "Crystalis Motus Leona"],
    ["52", "Battle Lion Leona"],
    ["53", "Prestige Battle Lion Leona"],
  ],
  Lillia: [
    ["0", "Original"],
    ["1", "Spirit Blossom Lillia"],
    ["10", "Nightbringer Lillia"],
    ["19", "Shan Hai Scrolls Lillia"],
    ["28", "Faerie Court Lillia"],
    ["37", "Bowling League Lillia"],
    ["46", "Petals of Spring Lillia"],
  ],
  Lissandra: [
    ["0", "Original"],
    ["1", "Bloodstone Lissandra"],
    ["2", "Blade Queen Lissandra"],
    ["3", "Program Lissandra"],
    ["4", "Coven Lissandra"],
    ["12", "Dark Cosmic Lissandra"],
    ["23", "Porcelain Lissandra"],
    ["33", "Prestige Porcelain Lissandra"],
    ["34", "Space Groove Lissandra"],
    ["43", "Flora Fatalis Lissandra"],
  ],
  Lucian: [
    ["0", "Original"],
    ["1", "Hired Gun Lucian"],
    ["2", "Striker Lucian"],
    ["6", "PROJECT: Lucian"],
    ["7", "Heartseeker Lucian"],
    ["8", "High Noon Lucian"],
    ["9", "Demacia Vice Lucian"],
    ["18", "Pulsefire Lucian"],
    ["19", "Prestige Pulsefire Lucian"],
    ["25", "Victorious Lucian"],
    ["31", "Arcana Lucian"],
    ["40", "Strike Paladin Lucian"],
    ["52", "Winterblessed Lucian"],
    ["62", "Masked Justice Lucian"],
    ["72", "Sunken Shadows Lucian"],
  ],
  Lulu: [
    ["0", "Original"],
    ["1", "Bittersweet Lulu"],
    ["2", "Wicked Lulu"],
    ["3", "Dragon Trainer Lulu"],
    ["4", "Winter Wonder Lulu"],
    ["5", "Pool Party Lulu"],
    ["6", "Star Guardian Lulu"],
    ["14", "Cosmic Enchantress Lulu"],
    ["15", "Pajama Guardian Lulu"],
    ["26", "Space Groove Lulu"],
    ["27", "Prestige Space Groove Lulu"],
    ["37", "Monster Tamer Lulu"],
    ["46", "Cafe Cuties Lulu"],
    ["55", "Arcana Lulu"],
  ],
  Lux: [
    ["0", "Original"],
    ["1", "Sorceress Lux"],
    ["2", "Spellthief Lux"],
    ["3", "Commando Lux"],
    ["4", "Imperial Lux"],
    ["5", "Steel Legion Lux"],
    ["6", "Star Guardian Lux"],
    ["7", "Elementalist Lux"],
    ["8", "Lunar Empress Lux"],
    ["14", "Pajama Guardian Lux"],
    ["15", "Battle Academia Lux"],
    ["16", "Prestige Battle Academia Lux"],
    ["17", "Dark Cosmic Lux"],
    ["18", "Cosmic Lux"],
    ["19", "Space Groove Lux"],
    ["29", "Porcelain Lux"],
    ["38", "Soul Fighter Lux"],
    ["39", "Prestige Battle Academia Lux (2022)"],
    ["40", "Prestige Porcelain Lux"],
    ["42", "Empyrean Lux"],
    ["61", "Faerie Court Lux"],
    ["70", "Prestige Spirit Blossom Lux"],
    ["72", "Panda Pal Lux"],
    ["16", "Prestige Battle Academia (2022)", undefined, "luxloadscreen_39"],
  ],
  Malphite: [
    ["0", "Original"],
    ["1", "Shamrock Malphite"],
    ["2", "Coral Reef Malphite"],
    ["3", "Marble Malphite"],
    ["4", "Obsidian Malphite"],
    ["5", "Glacial Malphite"],
    ["6", "Mecha Malphite"],
    ["7", "Ironside Malphite"],
    ["16", "Odyssey Malphite"],
    ["23", "Dark Star Malphite"],
    ["24", "Prestige Dark Star Malphite"],
    ["25", "FPX Malphite"],
    ["27", "Old God Malphite"],
    ["37", "Lunar Guardian Malphite"],
    ["48", "Pool Party Malphite"],
  ],
  Malzahar: [
    ["0", "Original"],
    ["1", "Vizier Malzahar"],
    ["2", "Shadow Prince Malzahar"],
    ["3", "Djinn Malzahar"],
    ["4", "Overlord Malzahar"],
    ["5", "Snow Day Malzahar"],
    ["6", "Battle Boss Malzahar"],
    ["7", "Hextech Malzahar"],
    ["9", "Worldbreaker Malzahar"],
    ["18", "Beezahar"],
    ["28", "Debonair Malzahar"],
    ["38", "Three Honors Malzahar"],
    ["39", "Empyrean Malzahar"],
    ["49", "Fatebreaker Malzahar"],
  ],
  Maokai: [
    ["0", "Original"],
    ["1", "Charred Maokai"],
    ["2", "Totemic Maokai"],
    ["3", "Festive Maokai"],
    ["4", "Haunted Maokai"],
    ["5", "Goalkeeper Maokai"],
    ["6", "Meowkai"],
    ["7", "Victorious Maokai"],
    ["16", "Worldbreaker Maokai"],
    ["24", "Astronaut Maokai"],
    ["33", "DRX Maokai"],
    ["35", "Corrupted Petricite Maokai"],
  ],
  MasterYi: [
    ["0", "Original"],
    ["1", "Assassin Master Yi"],
    ["2", "Chosen Master Yi"],
    ["3", "Ionia Master Yi"],
    ["4", "Samurai Yi"],
    ["5", "Headhunter Master Yi"],
    ["9", "PROJECT: Yi"],
    ["10", "Cosmic Blade Master Yi"],
    ["11", "Eternal Sword Yi"],
    ["17", "Snow Man Yi"],
    ["24", "Blood Moon Master Yi"],
    ["33", "PsyOps Master Yi"],
    ["42", "Debonair Master Yi"],
    ["52", "Spirit Blossom Master Yi"],
    ["53", "Prestige Spirit Blossom Master Yi"],
    ["89", "Inkshadow Master Yi"],
    ["96", "Heavenscale Master Yi"],
    ["106", "Victorious Master Yi"],
  ],
  Mel: [
    ["0", "Original"],
    ["1", "Arcane Councilor Mel"],
    ["10", "Prestige Winterblessed Mel"],
  ],
  Milio: [
    ["0", "Original", undefined, "milioloadscreen_0"],
    ["1", "Faerie Court Milio"],
    ["11", "Rain Shepherd Milio"],
    ["20", "Winter Wonder Milio"],
  ],
  MissFortune: [
    ["0", "Original"],
    ["1", "Cowgirl Miss Fortune"],
    ["2", "Waterloo Miss Fortune"],
    ["3", "Secret Agent Miss Fortune"],
    ["4", "Candy Cane Miss Fortune"],
    ["5", "Road Warrior Miss Fortune"],
    ["6", "Crime City Miss Fortune"],
    ["7", "Arcade Miss Fortune"],
    ["8", "Captain Fortune"],
    ["9", "Pool Party Miss Fortune"],
    ["15", "Star Guardian Miss Fortune"],
    ["16", "Gun Goddess Miss Fortune"],
    ["17", "Pajama Guardian Miss Fortune"],
    ["18", "Bewitching Miss Fortune"],
    ["20", "Prestige Bewitching Miss Fortune"],
    ["21", "Ruined Miss Fortune"],
    ["31", "Battle Bunny Miss Fortune"],
    ["32", "Admiral Battle Bunny Miss Fortune"],
    ["33", "Prestige Bewitching Miss Fortune (2022)"],
    ["40", "Broken Covenant Miss Fortune"],
    ["41", "Prestige Broken Covenant Miss Fortune"],
    ["50", "Porcelain Miss Fortune"],
    ["60", "Battle Queen Miss Fortune"],
    ["20", "Prestige Bewitching (2022)", undefined, "missfortuneloadscreen_33"],
  ],
  MonkeyKing: [
    ["0", "Original"],
    ["1", "Volcanic Wukong"],
    ["2", "General Wukong"],
    ["3", "Jade Dragon Wukong"],
    ["4", "Underworld Wukong"],
    ["5", "Radiant Wukong"],
    ["6", "Lancer Stratus Wukong"],
    ["7", "Battle Academia Wukong"],
    ["16", "Elderwood Wukong"],
    ["26", "Mecha Kingdoms Wukong"],
  ],
  Mordekaiser: [
    ["0", "Original"],
    ["1", "Dragon Knight Mordekaiser"],
    ["2", "Infernal Mordekaiser"],
    ["3", "Pentakill Mordekaiser"],
    ["4", "Lord Mordekaiser"],
    ["5", "King of Clubs Mordekaiser"],
    ["6", "Dark Star Mordekaiser"],
    ["13", "PROJECT: Mordekaiser"],
    ["23", "Pentakill III: Lost Chapter Mordekaiser"],
    ["32", "High Noon Mordekaiser"],
    ["42", "Ashen Graveknight Mordekaiser"],
    ["44", "Old God Mordekaiser"],
    ["54", "Sahn-Uzal Mordekaiser"],
  ],
  Morgana: [
    ["0", "Original"],
    ["1", "Exiled Morgana"],
    ["2", "Sinful Succulence Morgana"],
    ["3", "Blade Mistress Morgana"],
    ["4", "Blackthorn Morgana"],
    ["5", "Ghost Bride Morgana"],
    ["6", "Victorious Morgana"],
    ["10", "Lunar Wraith Morgana"],
    ["11", "Bewitching Morgana"],
    ["17", "Majestic Empress Morgana"],
    ["26", "Coven Morgana"],
    ["39", "Dawnbringer Morgana"],
    ["41", "Prestige Bewitching Morgana"],
    ["50", "Star Nemesis Morgana"],
    ["60", "Snow Moon Morgana"],
    ["70", "Porcelain Morgana"],
    ["80", "Spirit Blossom Morgana"],
    ["81", "Prestige Veiled Lady Morgana"],
  ],
  Naafiri: [
    ["0", "Original", undefined, "naafiriloadscreen_0"],
    ["1", "Soul Fighter Naafiri"],
    ["11", "PROJECT: Naafiri"],
    ["20", "Glizzy Naafiri"],
  ],
  Nami: [
    ["0", "Original"],
    ["1", "Koi Nami"],
    ["2", "River Spirit Nami"],
    ["3", "Urf the Nami-tee"],
    ["7", "Deep Sea Nami"],
    ["8", "SKT T1 Nami"],
    ["9", "Program Nami"],
    ["15", "Splendid Staff Nami"],
    ["24", "Cosmic Destiny Nami"],
    ["32", "Bewitching Nami"],
    ["41", "Space Groove Nami"],
    ["42", "Prestige Space Groove Nami"],
    ["51", "Coven Nami"],
    ["58", "Mythmaker Nami"],
    ["68", "Sunken Shadows Nami"],
  ],
  Nasus: [
    ["0", "Original"],
    ["1", "Galactic Nasus"],
    ["2", "Pharaoh Nasus"],
    ["3", "Dreadknight Nasus"],
    ["4", "Riot K-9 Nasus"],
    ["5", "Infernal Nasus"],
    ["6", "Archduke Nasus"],
    ["10", "Worldbreaker Nasus"],
    ["11", "Lunar Guardian Nasus"],
    ["16", "Battlecast Nasus"],
    ["25", "Space Groove Nasus"],
    ["35", "Armored Titan Nasus"],
    ["45", "Nightbringer Nasus"],
    ["54", "Fatemaker Nasus"],
  ],
  Nautilus: [
    ["0", "Original"],
    ["1", "Abyssal Nautilus"],
    ["2", "Subterranean Nautilus"],
    ["3", "AstroNautilus"],
    ["4", "Warden Nautilus"],
    ["5", "Worldbreaker Nautilus"],
    ["6", "Conqueror Nautilus"],
    ["9", "Shan Hai Scrolls Nautilus"],
    ["18", "Fright Night Nautilus"],
    ["27", "Cosmic Paladin Nautilus"],
    ["36", "Crystalis Indomitus Nautilus"],
    ["39", "Petricite Nautilus"],
  ],
  Neeko: [
    ["0", "Original"],
    ["1", "Winter Wonder Neeko"],
    ["10", "Star Guardian Neeko"],
    ["11", "Prestige Star Guardian Neeko"],
    ["12", "Shan Hai Scrolls Neeko"],
    ["21", "Prestige Star Guardian Neeko (2022)"],
    ["22", "Bewitching Neeko"],
    ["31", "Street Demons Neeko"],
    ["40", "Cosplayer Neeko"],
    ["49", "Beeko"],
    ["11", "Prestige Star Guardian (2022)", undefined, "neekoloadscreen_21"],
  ],
  Nidalee: [
    ["0", "Original"],
    ["1", "Snow Bunny Nidalee"],
    ["2", "Leopard Nidalee"],
    ["3", "French Maid Nidalee"],
    ["4", "Pharaoh Nidalee"],
    ["5", "Bewitching Nidalee"],
    ["6", "Headhunter Nidalee"],
    ["7", "Warring Kingdoms Nidalee"],
    ["8", "Challenger Nidalee"],
    ["9", "Super Galaxy Nidalee"],
    ["11", "Dawnbringer Nidalee"],
    ["18", "Cosmic Huntress Nidalee"],
    ["27", "DWG Nidalee"],
    ["29", "Ocean Song Nidalee"],
    ["39", "Kittalee"],
    ["48", "La Ilusión Nidalee"],
    ["58", "Spirit Blossom Nidalee"],
  ],
  Nilah: [
    ["0", "Original", undefined, "nilahloadscreen_0"],
    ["1", "Star Guardian Nilah"],
    ["11", "Coven Nilah"],
    ["21", "Inkshadow Nilah"],
  ],
  Nocturne: [
    ["0", "Original"],
    ["1", "Frozen Terror Nocturne"],
    ["2", "Void Nocturne"],
    ["3", "Ravager Nocturne"],
    ["4", "Haunting Nocturne"],
    ["5", "Eternum Nocturne"],
    ["6", "Cursed Revenant Nocturne"],
    ["7", "Old God Nocturne"],
    ["16", "Hextech Nocturne"],
    ["17", "Broken Covenant Nocturne"],
    ["26", "Empyrean Nocturne"],
  ],
  Nunu: [
    ["0", "Original"],
    ["1", "Sasquatch Nunu & Willump"],
    ["2", "Workshop Nunu & Willump"],
    ["3", "Grungy Nunu & Willump"],
    ["4", "Nunu & Willump Bot"],
    ["5", "Demolisher Nunu & Willump"],
    ["6", "TPA Nunu & Willump"],
    ["7", "Zombie Nunu & Willump"],
    ["8", "Papercraft Nunu & Willump"],
    ["16", "Space Groove Nunu & Willump"],
    ["26", "Nunu & Beelump"],
    ["35", "Cosmic Paladins Nunu & Willump"],
    ["44", "Fright Night Nunu & Willump"],
  ],
  Olaf: [
    ["0", "Original"],
    ["1", "Forsaken Olaf"],
    ["2", "Glacial Olaf"],
    ["3", "Brolaf"],
    ["4", "Pentakill Olaf"],
    ["5", "Marauder Olaf"],
    ["6", "Butcher Olaf"],
    ["15", "SKT T1 Olaf"],
    ["16", "Dragonslayer Olaf"],
    ["25", "Sentinel Olaf"],
    ["35", "Pentakill III: Lost Chapter Olaf"],
    ["44", "Infernal Olaf"],
  ],
  Orianna: [
    ["0", "Original"],
    ["1", "Gothic Orianna"],
    ["2", "Sewn Chaos Orianna"],
    ["3", "Bladecraft Orianna"],
    ["4", "TPA Orianna"],
    ["5", "Winter Wonder Orianna"],
    ["6", "Heartseeker Orianna"],
    ["7", "Dark Star Orianna"],
    ["8", "Victorious Orianna"],
    ["11", "Pool Party Orianna"],
    ["20", "Orbeeanna"],
    ["29", "Star Guardian Orianna"],
    ["38", "T1 Orianna"],
  ],
  Ornn: [
    ["0", "Original"],
    ["1", "Thunder Lord Ornn"],
    ["2", "Elderwood Ornn"],
    ["11", "Space Groove Ornn"],
    ["20", "Choo-Choo Ornn"],
    ["29", "Aegis Frame Ornn"],
  ],
  Pantheon: [
    ["0", "Original"],
    ["1", "Myrmidon Pantheon"],
    ["2", "Ruthless Pantheon"],
    ["3", "Perseus Pantheon"],
    ["4", "Full Metal Pantheon"],
    ["5", "Glaive Warrior Pantheon"],
    ["6", "Dragonslayer Pantheon"],
    ["7", "Zombie Slayer Pantheon"],
    ["8", "Baker Pantheon"],
    ["16", "Pulsefire Pantheon"],
    ["25", "Ruined Pantheon"],
    ["26", "Prestige Ascended Pantheon"],
    ["36", "Ashen Conqueror Pantheon"],
    ["38", "Chosen of the Wolf Pantheon"],
  ],
  Poppy: [
    ["0", "Original"],
    ["1", "Noxus Poppy"],
    ["2", "Lollipoppy"],
    ["3", "Blacksmith Poppy"],
    ["4", "Ragdoll Poppy"],
    ["5", "Battle Regalia Poppy"],
    ["6", "Scarlet Hammer Poppy"],
    ["7", "Star Guardian Poppy"],
    ["14", "Snow Fawn Poppy"],
    ["15", "Hextech Poppy"],
    ["16", "Astronaut Poppy"],
    ["24", "Bewitching Poppy"],
    ["33", "Cafe Cuties Poppy"],
    ["42", "Firecracker Poppy"],
  ],
  Pyke: [
    ["0", "Original"],
    ["1", "Sand Wraith Pyke"],
    ["9", "Blood Moon Pyke"],
    ["16", "PROJECT: Pyke"],
    ["25", "PsyOps Pyke"],
    ["34", "Sentinel Pyke"],
    ["44", "Ashen Knight Pyke"],
    ["45", "Empyrean Pyke"],
    ["53", "Soul Fighter Pyke"],
    ["54", "Prestige Soul Fighter Pyke"],
    ["64", "Fright Night Pyke"],
    ["74", "Inkshadow Pyke"],
    ["75", "T1 Pyke"],
  ],
  Qiyana: [
    ["0", "Original"],
    ["1", "Battle Boss Qiyana"],
    ["2", "True Damage Qiyana"],
    ["10", "Prestige True Damage Qiyana"],
    ["11", "Battle Queen Qiyana"],
    ["20", "Shockblade Qiyana"],
    ["21", "Prestige True Damage Qiyana (2022)"],
    ["30", "Lunar Empress Qiyana"],
    ["40", "La Ilusión Qiyana"],
    ["50", "Prestige Battle Academia Qiyana"],
    ["10", "Prestige True Damage (2022)", undefined, "qiyanaloadscreen_21"],
  ],
  Quinn: [
    ["0", "Original"],
    ["1", "Phoenix Quinn"],
    ["2", "Woad Scout Quinn"],
    ["3", "Corsair Quinn"],
    ["4", "Heartseeker Quinn"],
    ["5", "Warden Quinn"],
    ["14", "Star Guardian Quinn"],
  ],
  Rakan: [
    ["0", "Original"],
    ["1", "Cosmic Dawn Rakan"],
    ["2", "Sweetheart Rakan"],
    ["3", "SSG Rakan"],
    ["4", "iG Rakan"],
    ["5", "Star Guardian Rakan"],
    ["9", "Elderwood Rakan"],
    ["18", "Arcana Rakan"],
    ["27", "Broken Covenant Rakan"],
    ["36", "Redeemed Star Guardian Rakan"],
    ["37", "Dragonmancer Rakan"],
    ["38", "Prestige Dragonmancer Rakan"],
    ["47", "Battle Academia Rakan"],
  ],
  Rammus: [
    ["0", "Original"],
    ["1", "King Rammus"],
    ["2", "Chrome Rammus"],
    ["3", "Molten Rammus"],
    ["4", "Freljord Rammus"],
    ["5", "Ninja Rammus"],
    ["6", "Full Metal Rammus"],
    ["7", "Guardian of the Sands Rammus"],
    ["8", "Sweeper Rammus"],
    ["16", "Hextech Rammus"],
    ["17", "Astronaut Rammus"],
    ["26", "Durian Defender Rammus"],
  ],
  RekSai: [
    ["0", "Original"],
    ["1", "Eternum Rek'Sai"],
    ["2", "Pool Party Rek'Sai"],
    ["9", "Blackfrost Rek'Sai"],
    ["17", "Elderwood Rek'Sai"],
    ["26", "Primordian Rek'Sai"],
  ],
  Rell: [
    ["0", "Original"],
    ["1", "Battle Queen Rell"],
    ["10", "Star Guardian Rell"],
    ["20", "High Noon Rell"],
    ["30", "Grand Reckoning Rell"],
  ],
  Renata: [
    ["0", "Original", undefined, "renataloadscreen_0"],
    ["1", "Admiral Glasc"],
    ["10", "Fright Night Renata Glasc"],
    ["20", "La Ilusión Renata Glasc"],
    ["21", "Prestige La Ilusión Renata Glasc"],
    ["31", "Masque of the Black Rose Renata Glasc"],
  ],
  Renekton: [
    ["0", "Original"],
    ["1", "Galactic Renekton"],
    ["2", "Outback Renekton"],
    ["3", "Bloodfury Renekton"],
    ["4", "Rune Wars Renekton"],
    ["5", "Scorched Earth Renekton"],
    ["6", "Pool Party Renekton"],
    ["7", "Prehistoric Renekton"],
    ["8", "SKT T1 Renekton"],
    ["9", "Renektoy"],
    ["17", "Hextech Renekton"],
    ["18", "Blackfrost Renekton"],
    ["26", "PROJECT: Renekton"],
    ["33", "Dawnbringer Renekton"],
    ["42", "Worlds 2023 Renekton"],
    ["48", "Inkshadow Renekton"],
  ],
  Rengar: [
    ["0", "Original"],
    ["1", "Headhunter Rengar"],
    ["2", "Night Hunter Rengar"],
    ["3", "SSW Rengar"],
    ["8", "Mecha Rengar"],
    ["15", "Pretty Kitty Rengar"],
    ["23", "Guardian of the Sands Rengar"],
    ["30", "Sentinel Rengar"],
    ["40", "Street Demons Rengar"],
  ],
  Riven: [
    ["0", "Original"],
    ["1", "Redeemed Riven"],
    ["2", "Crimson Elite Riven"],
    ["3", "Battle Bunny Riven"],
    ["4", "Worlds 2012 Riven"],
    ["5", "Dragonblade Riven"],
    ["6", "Arcade Riven"],
    ["7", "Reignited Worlds 2012 Riven"],
    ["16", "Dawnbringer Riven"],
    ["18", "Pulsefire Riven"],
    ["20", "Valiant Sword Riven"],
    ["22", "Prestige Valiant Sword Riven"],
    ["23", "Spirit Blossom Riven"],
    ["34", "Sentinel Riven"],
    ["44", "Battle Bunny Prime Riven"],
    ["45", "Prestige Valiant Sword Riven (2022)"],
    ["55", "Broken Covenant Riven"],
    ["63", "Primal Ambush Riven"],
    ["22", "Prestige Valiant Sword (2022)", undefined, "rivenloadscreen_45"],
  ],
  Rumble: [
    ["0", "Original"],
    ["1", "Rumble in the Jungle"],
    ["2", "Bilgerat Rumble"],
    ["3", "Super Galaxy Rumble"],
    ["4", "Badlands Baron Rumble"],
    ["13", "Space Groove Rumble"],
    ["23", "Cafe Cuties Rumble"],
  ],
  Ryze: [
    ["0", "Original"],
    ["1", "Young Ryze"],
    ["2", "Tribal Ryze"],
    ["3", "Uncle Ryze"],
    ["4", "Triumphant Ryze"],
    ["5", "Professor Ryze"],
    ["6", "Zombie Ryze"],
    ["7", "Dark Crystal Ryze"],
    ["8", "Pirate Ryze"],
    ["9", "Ryze Whitebeard"],
    ["10", "SKT T1 Ryze"],
    ["11", "Worlds 2019 Ryze"],
    ["13", "Guardian of the Sands Ryze"],
    ["20", "Arcana Ryze"],
    ["29", "Blood Moon Ryze"],
  ],
  Samira: [
    ["0", "Original"],
    ["1", "PsyOps Samira"],
    ["10", "Space Groove Samira"],
    ["20", "High Noon Samira"],
    ["30", "Soul Fighter Samira"],
    ["33", "Masque of the Black Rose Samira"],
    ["35", "Battle Professor Samira"],
  ],
  Sejuani: [
    ["0", "Original"],
    ["1", "Sabretusk Sejuani"],
    ["2", "Darkrider Sejuani"],
    ["3", "Traditional Sejuani"],
    ["4", "Bear Cavalry Sejuani"],
    ["5", "Poro Rider Sejuani"],
    ["6", "Beast Hunter Sejuani"],
    ["7", "Sejuani Dawnchaser"],
    ["8", "Firecracker Sejuani"],
    ["15", "Hextech Sejuani"],
    ["16", "PROJECT: Sejuani"],
    ["26", "Solar Eclipse Sejuani"],
    ["36", "Victorious Sejuani"],
  ],
  Senna: [
    ["0", "Original"],
    ["1", "True Damage Senna"],
    ["9", "Prestige True Damage Senna"],
    ["10", "High Noon Senna"],
    ["16", "PROJECT: Senna"],
    ["26", "Lunar Eclipse Senna"],
    ["27", "Prestige Lunar Eclipse Senna"],
    ["36", "Bewitching Senna"],
    ["46", "Star Guardian Senna"],
    ["56", "Winterblessed Senna"],
    ["63", "Masked Justice Senna"],
  ],
  Seraphine: [
    ["0", "Original"],
    ["1", "K/DA ALL OUT Seraphine Indie"],
    ["2", "K/DA ALL OUT Seraphine Rising Star"],
    ["3", "K/DA ALL OUT Seraphine Superstar"],
    ["4", "Graceful Phoenix Seraphine"],
    ["14", "Ocean Song Seraphine"],
    ["15", "Prestige Ocean Song Seraphine"],
    ["24", "Faerie Court Seraphine"],
    ["34", "Star Guardian Seraphine"],
    ["43", "Battle Dove Seraphine"],
    ["50", "Dumpling Darlings Seraphine"],
    ["59", "Firecracker Seraphine"],
  ],
  Sett: [
    ["0", "Original"],
    ["1", "Mecha Kingdoms Sett"],
    ["8", "Obsidian Dragon Sett"],
    ["9", "Prestige Obsidian Dragon Sett"],
    ["10", "Pool Party Sett"],
    ["19", "Firecracker Sett"],
    ["38", "Spirit Blossom Sett"],
    ["45", "Soul Fighter Sett"],
    ["56", "HEARTSTEEL Sett"],
    ["66", "Radiant Serpent Sett"],
    ["67", "Spirit Blossom Springs Sett"],
  ],
  Shaco: [
    ["0", "Original"],
    ["1", "Mad Hatter Shaco"],
    ["2", "Royal Shaco"],
    ["3", "Nutcracko"],
    ["4", "Workshop Shaco"],
    ["5", "Asylum Shaco"],
    ["6", "Masked Shaco"],
    ["7", "Wild Card Shaco"],
    ["8", "Dark Star Shaco"],
    ["15", "Arcanist Shaco"],
    ["23", "Crime City Nightmare Shaco"],
    ["33", "Winterblessed Shaco"],
    ["43", "Soul Fighter Shaco"],
    ["44", "Prestige Soul Fighter Shaco"],
    ["54", "Fright Night Shaco"],
    ["64", "Cat-in-the-Box Shaco"],
  ],
  Shen: [
    ["0", "Original"],
    ["1", "Frozen Shen"],
    ["2", "Yellow Jacket Shen"],
    ["3", "Surgeon Shen"],
    ["4", "Blood Moon Shen"],
    ["5", "Warlord Shen"],
    ["6", "TPA Shen"],
    ["15", "Pulsefire Shen"],
    ["16", "Infernal Shen"],
    ["22", "PsyOps Shen"],
    ["40", "Shockblade Shen"],
    ["49", "Ashen Guardian Shen"],
    ["51", "Three Honors Shen"],
  ],
  Shyvana: [
    ["0", "Original"],
    ["1", "Ironscale Shyvana"],
    ["2", "Boneclaw Shyvana"],
    ["3", "Darkflame Shyvana"],
    ["4", "Ice Drake Shyvana"],
    ["5", "Worlds 2014 Shyvana"],
    ["6", "Super Galaxy Shyvana"],
    ["8", "Ruined Shyvana"],
    ["17", "Immortal Journey Shyvana"],
  ],
  Singed: [
    ["0", "Original"],
    ["1", "Riot Squad Singed"],
    ["2", "Hextech Singed"],
    ["3", "Surfer Singed"],
    ["4", "Mad Scientist Singed"],
    ["5", "Augmented Singed"],
    ["6", "Snow Day Singed"],
    ["7", "SSW Singed"],
    ["8", "Black Scourge Singed"],
    ["9", "Beekeeper Singed"],
    ["10", "Resistance Singed"],
    ["19", "Astronaut Singed"],
    ["28", "Arcane Shimmer Lab Singed"],
  ],
  Sion: [
    ["0", "Original"],
    ["1", "Hextech Sion"],
    ["2", "Barbarian Sion"],
    ["3", "Lumberjack Sion"],
    ["4", "Warmonger Sion"],
    ["5", "Mecha Zero Sion"],
    ["14", "Worldbreaker Sion"],
    ["22", "Blackfrost Sion"],
    ["30", "High Noon Sion"],
    ["40", "Cosmic Paladin Sion"],
    ["49", "Grand Reckoning Sion"],
  ],
  Sivir: [
    ["0", "Original", undefined, "sivirloadscreen_0"],
    ["1", "Warrior Princess Sivir"],
    ["2", "Spectacular Sivir"],
    ["3", "Huntress Sivir"],
    ["4", "Bandit Sivir"],
    ["5", "PAX Sivir"],
    ["6", "Snowstorm Sivir"],
    ["7", "Warden Sivir"],
    ["8", "Victorious Sivir"],
    ["9", "Neo PAX Sivir"],
    ["10", "Pizza Delivery Sivir"],
    ["16", "Blood Moon Sivir"],
    ["25", "Odyssey Sivir"],
    ["34", "Cafe Cuties Sivir"],
    ["43", "Solar Eclipse Sivir"],
    ["50", "Mythmaker Sivir"],
    ["51", "Prestige Mythmaker Sivir"],
    ["61", "Primal Ambush Sivir"],
    ["70", "Ann-Sivir-sary"],
  ],
  Skarner: [
    ["0", "Original", undefined, "skarnerloadscreen_0"],
    ["1", "Sandscourge Skarner"],
    ["2", "Earthrune Skarner"],
    ["3", "Battlecast Alpha Skarner"],
    ["4", "Guardian of the Sands Skarner"],
    ["5", "Cosmic Sting Skarner"],
    ["14", "Mecha Kingdoms Skarner"],
  ],
  Smolder: [
    ["0", "Original", undefined, "smolderloadscreen_0"],
    ["1", "Heavenscale Smolder"],
    ["11", "Reindeer Smolder"],
  ],
  Sona: [
    ["0", "Original"],
    ["1", "Muse Sona"],
    ["2", "Pentakill Sona"],
    ["3", "Silent Night Sona"],
    ["4", "Guqin Sona"],
    ["5", "Arcade Sona"],
    ["6", "DJ Sona"],
    ["7", "Sweetheart Sona"],
    ["9", "Odyssey Sona"],
    ["17", "PsyOps Sona"],
    ["26", "Pentakill III: Lost Chapter Sona"],
    ["35", "Star Guardian Sona"],
    ["45", "Immortal Journey Sona"],
    ["46", "Prestige Immortal Journey Sona"],
    ["56", "Victorious Sona"],
    ["66", "Spirit Blossom Springs Sona"],
    ["75", "Prestige Requiem Sona"],
  ],
  Soraka: [
    ["0", "Original"],
    ["1", "Dryad Soraka"],
    ["2", "Divine Soraka"],
    ["3", "Celestine Soraka"],
    ["4", "Reaper Soraka"],
    ["5", "Order of the Banana Soraka"],
    ["6", "Program Soraka"],
    ["7", "Star Guardian Soraka"],
    ["8", "Pajama Guardian Soraka"],
    ["9", "Winter Wonder Soraka"],
    ["15", "Dawnbringer Soraka"],
    ["16", "Nightbringer Soraka"],
    ["17", "Prestige Star Guardian Soraka"],
    ["18", "Cafe Cuties Soraka"],
    ["27", "Spirit Blossom Soraka"],
    ["37", "Immortal Journey Soraka"],
    ["44", "Faerie Court Soraka"],
    ["53", "Flora Fatalis Soraka"],
  ],
  Swain: [
    ["0", "Original"],
    ["1", "Northern Front Swain"],
    ["2", "Bilgewater Swain"],
    ["3", "Tyrant Swain"],
    ["4", "Dragon Master Swain"],
    ["11", "Hextech Swain"],
    ["12", "Crystal Rose Swain"],
    ["21", "Winterblessed Swain"],
    ["32", "Chosen of the Wolf Swain"],
    ["33", "Prestige Chosen of the Wolf Swain"],
  ],
  Sylas: [
    ["0", "Original"],
    ["1", "Lunar Wraith Sylas"],
    ["8", "Freljord Sylas"],
    ["13", "PROJECT: Sylas"],
    ["14", "Prestige PROJECT: Sylas"],
    ["24", "Battle Wolf Sylas"],
    ["34", "Ashen Slayer Sylas"],
    ["36", "Winterblessed Sylas"],
    ["46", "Dark Star Sylas"],
    ["53", "Prestige T1 Sylas"],
  ],
  Syndra: [
    ["0", "Original", undefined, "syndraloadscreen_0"],
    ["1", "Justicar Syndra"],
    ["2", "Atlantean Syndra"],
    ["3", "Queen of Diamonds Syndra"],
    ["4", "Snow Day Syndra"],
    ["5", "SKT T1 Syndra"],
    ["6", "Star Guardian Syndra"],
    ["7", "Pool Party Syndra"],
    ["16", "Withered Rose Syndra"],
    ["25", "Bewitching Syndra"],
    ["34", "Prestige Star Guardian Syndra"],
    ["44", "Spirit Blossom Syndra"],
    ["54", "Coven Syndra"],
    ["65", "Dumpling Darlings Syndra"],
    ["65", "Dumpling Darlings", undefined, "syndraloadscreen_65_2.skins_syndra_skin65"],
  ],
  TahmKench: [
    ["0", "Original"],
    ["1", "Master Chef Tahm Kench"],
    ["2", "Urf Kench"],
    ["3", "Coin Emperor Tahm Kench"],
    ["11", "Arcana Tahm Kench"],
    ["20", "High Noon Tahm Kench"],
    ["30", "Shan Hai Scrolls Tahm Kench"],
  ],
  Taliyah: [
    ["0", "Original"],
    ["1", "Freljord Taliyah"],
    ["2", "SSG Taliyah"],
    ["3", "Pool Party Taliyah"],
    ["11", "Star Guardian Taliyah"],
    ["21", "Crystalis Motus Taliyah"],
    ["24", "Durand's Legacy Taliyah"],
  ],
  Talon: [
    ["0", "Original"],
    ["1", "Renegade Talon"],
    ["2", "Crimson Elite Talon"],
    ["3", "Dragonblade Talon"],
    ["4", "SSW Talon"],
    ["5", "Blood Moon Talon"],
    ["12", "Enduring Sword Talon"],
    ["20", "Talon Blackwood"],
    ["29", "Withered Rose Talon"],
    ["38", "High Noon Talon"],
    ["39", "Prestige High Noon Talon"],
    ["49", "Primal Ambush Talon"],
    ["59", "Grand Reckoning Talon"],
  ],
  Taric: [
    ["0", "Original"],
    ["1", "Emerald Taric"],
    ["2", "Armor of the Fifth Age Taric"],
    ["3", "Bloodstone Taric"],
    ["4", "Pool Party Taric"],
    ["9", "Taric Luminshield"],
    ["18", "Space Groove Taric"],
    ["27", "Fatebreaker Taric"],
  ],
  Teemo: [
    ["0", "Original"],
    ["1", "Happy Elf Teemo"],
    ["2", "Recon Teemo"],
    ["3", "Badger Teemo"],
    ["4", "Astronaut Teemo"],
    ["5", "Cottontail Teemo"],
    ["6", "Super Teemo"],
    ["7", "Panda Teemo"],
    ["8", "Omega Squad Teemo"],
    ["14", "Little Devil Teemo"],
    ["18", "Beemo"],
    ["25", "Spirit Blossom Teemo"],
    ["27", "Prestige Spirit Blossom Teemo"],
    ["37", "Firecracker Teemo"],
    ["47", "Space Groove Teemo"],
    ["54", "Spirit Blossom Springs Teemo"],
  ],
  Thresh: [
    ["0", "Original"],
    ["1", "Deep Terror Thresh"],
    ["2", "Worlds 2013 Thresh"],
    ["3", "Blood Moon Thresh"],
    ["4", "SSW Thresh"],
    ["5", "Dark Star Thresh"],
    ["6", "High Noon Thresh"],
    ["13", "Pulsefire Thresh"],
    ["14", "Prestige Pulsefire Thresh"],
    ["15", "FPX Thresh"],
    ["17", "Spirit Blossom Thresh"],
    ["27", "Unbound Thresh"],
    ["28", "Steel Dragon Thresh"],
    ["38", "Prestige Pulsefire Thresh (2022)"],
    ["39", "Lunar Emperor Thresh"],
    ["49", "Winterblessed Thresh"],
    ["59", "Janitor Thresh"],
    ["14", "Prestige Pulsefire (2022)", undefined, "threshloadscreen_38"],
  ],
  Tristana: [
    ["0", "Original"],
    ["1", "Riot Girl Tristana"],
    ["2", "Earnest Elf Tristana"],
    ["3", "Firefighter Tristana"],
    ["4", "Guerilla Tristana"],
    ["5", "Buccaneer Tristana"],
    ["6", "Rocket Girl Tristana"],
    ["10", "Dragon Trainer Tristana"],
    ["11", "Bewitching Tristana"],
    ["12", "Omega Squad Tristana"],
    ["24", "Little Demon Tristana"],
    ["33", "Pengu Cosplay Tristana"],
    ["40", "Hextech Tristana"],
    ["41", "Firecracker Tristana"],
    ["51", "Spirit Blossom Tristana"],
    ["61", "Faerie Court Tristana"],
    ["70", "Rain Shepherd Tristana"],
  ],
  Trundle: [
    ["0", "Original"],
    ["1", "Lil' Slugger Trundle"],
    ["2", "Junkyard Trundle"],
    ["3", "Traditional Trundle"],
    ["4", "Constable Trundle"],
    ["5", "Worldbreaker Trundle"],
    ["6", "Dragonslayer Trundle"],
    ["12", "Fright Night Trundle"],
    ["21", "Esports Fan Trundle"],
  ],
  Tryndamere: [
    ["0", "Original"],
    ["1", "Highland Tryndamere"],
    ["2", "King Tryndamere"],
    ["3", "Viking Tryndamere"],
    ["4", "Demonblade Tryndamere"],
    ["5", "Sultan Tryndamere"],
    ["6", "Warring Kingdoms Tryndamere"],
    ["7", "Nightmare Tryndamere"],
    ["8", "Beast Hunter Tryndamere"],
    ["9", "Chemtech Tryndamere"],
    ["10", "Blood Moon Tryndamere"],
    ["18", "Nightbringer Tryndamere"],
    ["27", "Victorious Tryndamere"],
    ["37", "Visions of the Fallen Tryndamere"],
  ],
  TwistedFate: [
    ["0", "Original"],
    ["1", "PAX Twisted Fate"],
    ["2", "Jack of Hearts Twisted Fate"],
    ["3", "The Magnificent Twisted Fate"],
    ["4", "Tango Twisted Fate"],
    ["5", "High Noon Twisted Fate"],
    ["6", "Musketeer Twisted Fate"],
    ["7", "Underworld Twisted Fate"],
    ["8", "Red Card Twisted Fate"],
    ["9", "Cutpurse Twisted Fate"],
    ["10", "Blood Moon Twisted Fate"],
    ["11", "Pulsefire Twisted Fate"],
    ["13", "Odyssey Twisted Fate"],
    ["23", "DWG Twisted Fate"],
    ["25", "Crime City Nightmare Twisted Fate"],
    ["36", "Space Groove Twisted Fate"],
    ["45", "Victorious Twisted Fate"],
  ],
  Twitch: [
    ["0", "Original"],
    ["1", "Kingpin Twitch"],
    ["2", "Whistler Village Twitch"],
    ["3", "Medieval Twitch"],
    ["4", "Crime City Twitch"],
    ["5", "Vandal Twitch"],
    ["6", "Pickpocket Twitch"],
    ["7", "SSW Twitch"],
    ["8", "Omega Squad Twitch"],
    ["12", "Ice King Twitch"],
    ["27", "Twitch Shadowfoot"],
    ["36", "Dragonslayer Twitch"],
    ["45", "High Noon Twitch"],
    ["55", "Cheddar Chief Twitch"],
    ["64", "Pool Party Twitch"],
  ],
  Udyr: [
    ["0", "Original", undefined, "udyrloadscreen_0"],
    ["1", "Black Belt Udyr"],
    ["2", "Primal Udyr"],
    ["3", "Spirit Guard Udyr"],
    ["4", "Definitely Not Udyr"],
    ["5", "Dragon Oracle Udyr"],
    ["6", "Inkshadow Udyr"],
  ],
  Urgot: [
    ["0", "Original"],
    ["1", "Giant Enemy Crabgot"],
    ["2", "Butcher Urgot"],
    ["3", "Battlecast Urgot"],
    ["9", "High Noon Urgot"],
    ["15", "Pajama Guardian Cosplay Urgot"],
    ["23", "Fright Night Urgot"],
    ["32", "Urgot the Clogfather"],
  ],
  Varus: [
    ["0", "Original"],
    ["1", "Blight Crystal Varus"],
    ["2", "Arclight Varus"],
    ["3", "Arctic Ops Varus"],
    ["4", "Heartseeker Varus"],
    ["5", "Varus Swiftbolt"],
    ["6", "Dark Star Varus"],
    ["7", "Conqueror Varus"],
    ["9", "Infernal Varus"],
    ["16", "PROJECT: Varus"],
    ["17", "Cosmic Hunter Varus"],
    ["34", "High Noon Varus"],
    ["44", "Snow Moon Varus"],
    ["53", "Empyrean Varus"],
    ["60", "Spirit Blossom Varus"],
    ["69", "T1 Varus"],
  ],
  Vayne: [
    ["0", "Original"],
    ["1", "Vindicator Vayne"],
    ["2", "Aristocrat Vayne"],
    ["3", "Dragonslayer Vayne"],
    ["4", "Heartseeker Vayne"],
    ["5", "SKT T1 Vayne"],
    ["6", "Arclight Vayne"],
    ["10", "Soulstealer Vayne"],
    ["11", "PROJECT: Vayne"],
    ["12", "Firecracker Vayne"],
    ["13", "Prestige Firecracker Vayne"],
    ["14", "Spirit Blossom Vayne"],
    ["15", "FPX Vayne"],
    ["25", "Sentinel Vayne"],
    ["32", "Battle Bat Vayne"],
    ["33", "Prestige Firecracker Vayne (2022)"],
    ["44", "Dawnbringer Vayne"],
    ["55", "Dragonmancer Vayne"],
    ["64", "Risen Legend Vayne"],
    ["13", "Prestige Firecracker (2022)", undefined, "vayneloadscreen_33"],
  ],
  Veigar: [
    ["0", "Original"],
    ["1", "White Mage Veigar"],
    ["2", "Curling Veigar"],
    ["3", "Veigar Greybeard"],
    ["4", "Leprechaun Veigar"],
    ["5", "Baron Von Veigar"],
    ["6", "Superb Villain Veigar"],
    ["7", "Bad Santa Veigar"],
    ["8", "Final Boss Veigar"],
    ["9", "Omega Squad Veigar"],
    ["13", "Elderwood Veigar"],
    ["23", "Furyhorn Cosplay Veigar"],
    ["32", "Astronaut Veigar"],
    ["41", "Monster Tamer Veigar"],
    ["51", "King Beegar"],
    ["60", "Fright Night Veigar"],
  ],
  Velkoz: [
    ["0", "Original"],
    ["1", "Battlecast Vel'Koz"],
    ["2", "Arclight Vel'Koz"],
    ["3", "Definitely Not Vel'Koz"],
    ["4", "Infernal Vel'Koz"],
    ["11", "Blackfrost Vel'Koz"],
    ["20", "Bee'Koz"],
  ],
  Vex: [
    ["0", "Original", undefined, "vexloadscreen_0"],
    ["1", "Dawnbringer Vex"],
    ["10", "Empyrean Vex"],
    ["20", "Stargazer Vex"],
  ],
  Vi: [
    ["0", "Original"],
    ["1", "Neon Strike Vi"],
    ["2", "Officer Vi"],
    ["3", "Debonair Vi"],
    ["4", "Demon Vi"],
    ["5", "Warring Kingdoms Vi"],
    ["11", "PROJECT: Vi"],
    ["12", "Heartbreaker Vi"],
    ["20", "PsyOps Vi"],
    ["29", "Arcane Undercity Vi"],
    ["30", "Heartache Vi"],
    ["39", "Primal Ambush Vi"],
    ["48", "Arcane Brawler Vi"],
    ["49", "T1 Vi"],
  ],
  Viego: [
    ["0", "Original"],
    ["1", "Lunar Beast Viego"],
    ["10", "Dissonance of Pentakill Viego"],
    ["19", "EDG Viego"],
    ["21", "King Viego"],
    ["30", "Soul Fighter Viego"],
    ["37", "Worlds 2024 Viego"],
    ["43", "Revenant Reign Viego"],
  ],
  Viktor: [
    ["0", "Original"],
    ["1", "Full Machine Viktor"],
    ["2", "Prototype Viktor"],
    ["3", "Creator Viktor"],
    ["4", "Death Sworn Viktor"],
    ["5", "PsyOps Viktor"],
    ["14", "High Noon Viktor"],
    ["24", "Arcane Savior Viktor"],
    ["25", "Machine Herald Viktor"],
  ],
  Vladimir: [
    ["0", "Original"],
    ["1", "Count Vladimir"],
    ["2", "Marquis Vladimir"],
    ["3", "Nosferatu Vladimir"],
    ["4", "Vandal Vladimir"],
    ["5", "Blood Lord Vladimir"],
    ["6", "Soulstealer Vladimir"],
    ["7", "Academy Vladimir"],
    ["8", "Dark Waters Vladimir"],
    ["14", "Nightbringer Vladimir"],
    ["21", "Cosmic Devourer Vladimir"],
    ["30", "Cafe Cuties Vladimir"],
    ["39", "Broken Covenant Vladimir"],
    ["48", "Masque of the Black Rose Vladimir"],
  ],
  Volibear: [
    ["0", "Original"],
    ["1", "Thunder Lord Volibear"],
    ["2", "Northern Storm Volibear"],
    ["3", "Runeguard Volibear"],
    ["4", "Captain Volibear"],
    ["5", "El Rayo Volibear"],
    ["6", "The Thousand-Pierced Bear"],
    ["7", "Duality Dragon Volibear"],
    ["9", "Prestige Duality Dragon Volibear"],
    ["19", "Inkshadow Volibear"],
    ["29", "Spirit Blossom Springs Volibear"],
  ],
  Warwick: [
    ["0", "Original"],
    ["1", "Grey Warwick"],
    ["2", "Urf the Manatee"],
    ["3", "Big Bad Warwick"],
    ["4", "Tundra Hunter Warwick"],
    ["5", "Feral Warwick"],
    ["6", "Firefang Warwick"],
    ["7", "Hyena Warwick"],
    ["8", "Marauder Warwick"],
    ["9", "Urfwick"],
    ["10", "Lunar Guardian Warwick"],
    ["16", "PROJECT: Warwick"],
    ["35", "Old God Warwick"],
    ["45", "Winterblessed Warwick"],
    ["46", "Prestige Winterblessed Warwick"],
    ["56", "Arcane Vander Warwick"],
  ],
  Xayah: [
    ["0", "Original"],
    ["1", "Cosmic Dusk Xayah"],
    ["2", "Sweetheart Xayah"],
    ["3", "SSG Xayah"],
    ["4", "Star Guardian Xayah"],
    ["8", "Elderwood Xayah"],
    ["17", "Brave Phoenix Xayah"],
    ["26", "Prestige Brave Phoenix Xayah"],
    ["28", "Arcana Xayah"],
    ["37", "Broken Covenant Xayah"],
    ["38", "Redeemed Star Guardian Xayah"],
    ["47", "Battle Bat Xayah"],
    ["57", "Battle Academia Xayah"],
  ],
  Xerath: [
    ["0", "Original"],
    ["1", "Runeborn Xerath"],
    ["2", "Battlecast Xerath"],
    ["3", "Scorched Earth Xerath"],
    ["4", "Guardian of the Sands Xerath"],
    ["5", "Dark Star Xerath"],
    ["12", "Arcana Xerath"],
    ["21", "Astronaut Xerath"],
    ["30", "Crystalis Indomitus Xerath"],
    ["32", "Corrupted Petricite Xerath"],
  ],
  XinZhao: [
    ["0", "Original", "xinzhaorework_splash_<type>_0.xinzhaorework", "xinzhaoreworkloadscreen_0.xinzhaorework"],
    ["1", "Commando Xin Zhao"],
    ["2", "Imperial Xin Zhao"],
    ["3", "Viscero Xin Zhao"],
    ["4", "Winged Hussar Xin Zhao"],
    ["5", "Warring Kingdoms Xin Zhao"],
    ["6", "Secret Agent Xin Zhao"],
    ["13", "Dragonslayer Xin Zhao"],
    ["20", "Cosmic Defender Xin Zhao"],
    ["27", "Marauder Xin Zhao"],
    ["36", "Firecracker Xin Zhao"],
    ["47", "Trials of Twilight Xin Zhao"],
    ["1", "Commando", "xinzhaorework_splash_<type>_1.xinzhaorework", "xinzhaoreworkloadscreen_1.xinzhaorework"],
    ["3", "Viscero", "xinzhaorework_splash_<type>_3.xinzhaorework", "xinzhaoreworkloadscreen_3.xinzhaorework"],
    ["5", "Warring Kingdoms", "xinzhaorework_splash_<type>_5.xinzhaorework", "xinzhaoreworkloadscreen_5.xinzhaorework"],
    ["6", "Secret Agent", "xinzhaorework_splash_<type>_6.xinzhaorework", "xinzhaoreworkloadscreen_6.xinzhaorework"],
    ["13", "Dragonslayer", "xinzhaorework_splash_<type>_13.xinzhaorework", "xinzhaoreworkloadscreen_13.xinzhaorework"],
    ["20", "Cosmic Defender", "xinzhaorework_splash_<type>_20.xinzhaorework", "xinzhaoreworkloadscreen_20.xinzhaorework"],
    ["27", "Marauder", "xinzhaorework_splash_<type>_27.xinzhaorework", "xinzhaoreworkloadscreen_27.xinzhaorework"],
    ["36", "Firecracker", "xinzhaorework_splash_<type>_36.xinzhaorework", "xinzhaoreworkloadscreen_36.xinzhaorework"],
  ],
  Yasuo: [
    ["0", "Original"],
    ["1", "High Noon Yasuo"],
    ["2", "PROJECT: Yasuo"],
    ["3", "Blood Moon Yasuo"],
    ["9", "Nightbringer Yasuo"],
    ["10", "Odyssey Yasuo"],
    ["17", "Battle Boss Yasuo"],
    ["18", "True Damage Yasuo"],
    ["35", "Prestige True Damage Yasuo"],
    ["36", "Spirit Blossom Yasuo"],
    ["45", "Sea Dog Yasuo"],
    ["54", "Truth Dragon Yasuo"],
    ["55", "Dream Dragon Yasuo"],
    ["56", "Inkshadow Yasuo"],
    ["57", "Prestige Inkshadow Yasuo"],
    ["68", "Foreseen Yasuo"],
    ["77", "Battle Wolf Yasuo"],
    ["87", "Genesis Nightbringer Yasuo"],
    ["88", "Petals of Spring Yasuo"],
  ],
  Yone: [
    ["0", "Original"],
    ["1", "Spirit Blossom Yone"],
    ["10", "Battle Academia Yone"],
    ["19", "Dawnbringer Yone"],
    ["26", "Ocean Song Yone"],
    ["35", "Inkshadow Yone"],
    ["45", "HEARTSTEEL Yone"],
    ["46", "Prestige HEARTSTEEL Yone"],
    ["55", "High Noon Yone"],
    ["58", "Peacemaker High Noon Yone"],
    ["65", "Masked Justice Yone"],
    ["74", "T1 Yone"],
  ],
  Yorick: [
    ["0", "Original"],
    ["1", "Undertaker Yorick"],
    ["2", "Pentakill Yorick"],
    ["3", "Arclight Yorick"],
    ["4", "Meowrick"],
    ["12", "Resistance Yorick"],
    ["21", "Pentakill III: Lost Chapter Yorick"],
    ["30", "Spirit Blossom Yorick"],
    ["40", "Dark Star Yorick"],
    ["50", "High Noon Yorick"],
  ],
  Yunara: [
    ["0", "Original"],
    ["1", "Spirit Blossom Springs Yunara"],
  ],
  Yuumi: [
    ["0", "Original"],
    ["1", "Battle Principal Yuumi"],
    ["11", "Heartseeker Yuumi"],
    ["19", "Yuubee"],
    ["28", "Bewitching Yuumi"],
    ["37", "EDG Yuumi"],
    ["39", "Shiba Yuumi"],
    ["49", "Cyber Cat Yuumi"],
    ["50", "Prestige Cyber Cat Yuumi"],
    ["61", "Nightbringer Yuumi"],
    ["70", "Firecracker Yuumi"],
  ],
  Zaahen: [
    ["0", "Original"],
    ["1", "Immortal Journey Zaahen"],
  ],
  Zac: [
    ["0", "Original"],
    ["1", "Special Weapon Zac"],
    ["2", "Pool Party Zac"],
    ["6", "SKT T1 Zac"],
    ["7", "Battlecast Zac"],
    ["14", "Empyrean Zac"],
    ["24", "Zesty Dip Zac"],
  ],
  Zed: [
    ["0", "Original"],
    ["1", "Shockblade Zed"],
    ["2", "SKT T1 Zed"],
    ["3", "PROJECT: Zed"],
    ["10", "Worlds 2016 Zed"],
    ["11", "Death Sworn Zed"],
    ["13", "Galaxy Slayer Zed"],
    ["15", "PsyOps Zed"],
    ["30", "Prestige PROJECT: Zed"],
    ["31", "Debonair Zed"],
    ["38", "Empyrean Zed"],
    ["49", "Immortal Journey Zed"],
    ["58", "Blood Moon Zed"],
    ["68", "Quantum Galaxy Slayer Zed"],
    ["69", "Prestige Spirit Blossom Zed"],
  ],
  Zeri: [
    ["0", "Original", undefined, "zeriloadscreen_0"],
    ["1", "Withered Rose Zeri"],
    ["10", "Ocean Song Zeri"],
    ["19", "Immortal Journey Zeri"],
    ["28", "Fright Night Zeri"],
    ["29", "Prestige Fright Night Zeri"],
    ["40", "Winter Wonder Zeri"],
  ],
  Ziggs: [
    ["0", "Original"],
    ["1", "Mad Scientist Ziggs"],
    ["2", "Major Ziggs"],
    ["3", "Pool Party Ziggs"],
    ["4", "Snow Day Ziggs"],
    ["5", "Master Arcanist Ziggs"],
    ["6", "Battle Boss Ziggs"],
    ["7", "Odyssey Ziggs"],
    ["14", "Sugar Rush Ziggs"],
    ["23", "Hextech Ziggs"],
    ["24", "BZZZiggs"],
    ["33", "La Ilusión Ziggs"],
    ["43", "Firecracker Ziggs"],
  ],
  Zilean: [
    ["0", "Original"],
    ["1", "Old Saint Zilean"],
    ["2", "Groovy Zilean"],
    ["3", "Shurima Desert Zilean"],
    ["4", "Time Machine Zilean"],
    ["5", "Blood Moon Zilean"],
    ["6", "Sugar Rush Zilean"],
    ["14", "Winterblessed Zilean"],
    ["24", "Arcana Zilean"],
  ],
  Zoe: [
    ["0", "Original"],
    ["1", "Cyber Pop Zoe"],
    ["2", "Pool Party Zoe"],
    ["9", "Star Guardian Zoe"],
    ["18", "Arcanist Zoe"],
    ["19", "Prestige Arcanist Zoe"],
    ["20", "EDG Zoe"],
    ["22", "Winterblessed Zoe"],
    ["33", "Dark Star Zoe"],
    ["43", "Prestige Eternal Aspect Zoe"],
  ],
  Zyra: [
    ["0", "Original"],
    ["1", "Wildfire Zyra"],
    ["2", "Haunted Zyra"],
    ["3", "SKT T1 Zyra"],
    ["4", "Dragon Sorceress Zyra"],
    ["5", "Coven Zyra"],
    ["6", "Prestige Coven Zyra"],
    ["7", "Crystal Rose Zyra"],
    ["16", "Crime City Nightmare Zyra"],
    ["36", "Mythmaker Zyra"],
    ["46", "Street Demons Zyra"],
    ["55", "Blood Moon Zyra"],
    ["64", "Spirit Blossom Zyra"],
  ],
} as const satisfies Record<string, readonly CompactSkin[]>

export const skinIndex: Record<string, Skin[]> = buildSkinIndex(compactSkinIndex)
