export const statTotalGold = [
  {
    id: "total",
    name: "Total Gold Cost",
    abbr: ["Total"],
    description: "",
    icon: "lp:gold",
  },
]
export const statIndex: Record<string, StatIndex> = {
  // magic

  abilityPower: {
    id: "abilityPower",
    name: "Ability Power",
    abbr: ["AP"],
    color: "var(--color-sorcery)",
    description: "",
    group: "spells",
    icon: "lp:ap",
  },
  percentMagicPenetration: {
    id: "percentMagicPenetration",
    name: "Magic Penetration",
    abbr: ["MPEN", "Magic Pen"],
    color: "var(--color-mpen)",
    description: "",
    group: "spells",
    icon: "lp:mpen",
    unit: "%",
  },
  //
  healAndShieldPower: {
    id: "healAndShieldPower",
    name: "Heal & Shield Power",
    abbr: ["HSP"],
    color: "var(--color-enchanter)",
    description: "",
    group: "spells",
    icon: "lp:hsp",
    unit: "%",
  },
  //
  abilityHaste: {
    id: "abilityHaste",
    name: "Ability Haste",
    abbr: ["AH"],
    color: "var(--color-ah)",
    description: "",
    group: "spells",
    icon: "lp:ah",
  },

  // physical

  attackDamage: {
    id: "attackDamage",
    name: "Attack Damage",
    abbr: ["AD"],
    color: "var(--color-ad)",
    description: "",
    group: "physical",
    icon: "lp:ad",
  },
  attackSpeed: {
    id: "attackSpeed",
    name: "Attack Speed",
    abbr: ["AS", "Bonus AS"],
    color: "var(--color-as)",
    description: "",
    group: "physical",
    icon: "lp:as",
    unit: "%",
  },
  criticalStrikeChance: {
    id: "criticalStrikeChance",
    name: "Critical Chance",
    abbr: ["Crit", "Crit Chance"],
    color: "var(--color-domination)",
    description: "",
    group: "physical",
    icon: "lp:cs",
    unit: "%",
  },
  criticalStrikeDamage: {
    id: "criticalStrikeDamage",
    name: "Critical Damage",
    abbr: ["Crit Dmg"],
    color: "var(--color-fighter)",
    description: "",
    group: "physical",
    icon: "lp:crit-dmg",
  },
  //
  armorPenetration: {
    id: "armorPenetration",
    name: "Armor Penetration",
    abbr: ["APEN", "Armor Pen."],
    color: "var(--color-apen)",
    description: "",
    group: "physical",
    icon: "lp:armor-pen",
  },
  lethality: {
    id: "lethality",
    name: "Lethality",
    abbr: ["LTY", "Lethality"],
    color: "var(--color-apen)",
    description: "",
    group: "physical",
    icon: "lp:armor-pen",
  },
  lifesteal: {
    id: "lifesteal",
    name: "Lifesteal",
    abbr: ["LS", "Lifesteal"],
    color: "var(--color-domination)",
    description: "",
    group: "physical",
    icon: "lp:ls",
  },

  // basic

  health: {
    id: "health",
    name: "Health",
    abbr: ["HP", "Health"],
    color: "var(--color-resolve)",
    description: "",
    group: "basic",
    icon: "lp:health",
  },
  healthRegen: {
    id: "healthRegen",
    name: "Health Regen",
    abbr: ["HP/5", "HP ∕ 5"],
    color: "var(--color-resolve)",
    description: "",
    group: "basic",
    icon: "lp:hp",
    unit: "%",
  },
  mana: {
    id: "mana",
    name: "Mana",
    color: "var(--color-inspiration)",
    description: "",
    group: "basic",
    icon: "lp:mana",
  },
  manaRegen: {
    id: "manaRegen",
    name: "Mana Regen",
    abbr: ["MP ∕ 5", "Mana ∕ 5"],
    color: "var(--color-inspiration)",
    description: "",
    group: "basic",
    icon: "lp:mana-regen",
    unit: "%",
  },

  // defense

  armor: {
    id: "armor",
    name: "Armor",
    color: "var(--color-iron)",
    description: "",
    group: "defense",
    icon: "lp:armor",
  },
  magicResistance: {
    id: "magicResistance",
    name: "Magic Resist",
    abbr: ["MR"],
    color: "var(--color-mr)",
    description: "",
    group: "defense",
    icon: "lp:mr",
  },

  // utility

  percentMovespeed: {
    id: "percentMovespeed",
    name: "Movespeed",
    abbr: ["MS"],
    color: "var(--color-white-70)",
    description: "",
    group: "utility",
    icon: "lp:ms",
    unit: "%",
  },
  tenacity: {
    id: "tenacity",
    name: "Tenacity",
    color: "var(--color-platinum)",
    description: "",
    group: "utility",
    icon: "lp:tenacity",
  },
  //
  goldPer10: {
    id: "goldPer10",
    name: "Gold / 10",
    abbr: ["GP/10"],
    color: "var(--color-g)",
    description: "",
    group: "utility",
    icon: "lp:gold",
  },
  //
  omnivamp: {
    id: "omnivamp",
    name: "Omnivamp",
    abbr: ["Vamp", "Omnivamp"],
    color: "var(--color-vamp)",
    description: "",
    icon: "lp:vamp",
    unit: "%",
  },

  // champion

  flatMagicPenetration: {
    id: "flatMagicPenetration",
    name: "Flat Magic Penetration",
    abbr: ["MPEN", "Magic Pen."],
    color: "var(--color-mpen)",
    description: "",
    group: "champion",
    icon: "lp:mpen",
  },
  flatMovespeed: {
    id: "flatMovespeed",
    name: "Base Movespeed",
    abbr: ["MS"],
    color: "var(--color-white-70)",
    description: "",
    group: "champion",
    icon: "lp:ms",
  },
  //
  acquisitionRadius: {
    id: "acquisitionRadius",
    name: "Acquisition Radius",
    abbr: ["Acqusition"],
    description:
      "The range at which a unit acquires basic attack targets when a target unit is not specified by the player.",
    group: "champion",
    icon: "lp:acquisition-radius",
  },
  attackCastTime: {
    id: "attackCastTime",
    name: "Attack Cast Time",
    abbr: ["Cast Time"],
    description: "",
    group: "champion",
  },
  attackDelayOffset: {
    id: "attackDelayOffset",
    name: "Attack Delay Offset",
    abbr: ["Delay Offset"],
    description: "",
    group: "champion",
  },
  attackRange: {
    id: "attackRange",
    name: "Range",
    color: "var(--color-white-70)",
    description: "Range of the champion's basic attack.",
    group: "champion",
    icon: "lp:range",
  },
  attackSpeedRatio: {
    id: "attackSpeedRatio",
    name: "Attack Speed Ratio",
    abbr: ["AS Ratio"],
    description: "",
    group: "champion",
  },
  attackTotalTime: {
    id: "attackTotalTime",
    name: "Attack Total Time",
    abbr: ["Total Time"],
    description: "",
    group: "champion",
  },
  criticalStrikeDamageModifier: {
    id: "criticalStrikeDamageModifier",
    name: "Critical Strike Damage Modifier",
    abbr: ["Crit Modifier"],
    description: "",
    group: "champion",
    icon: "lp:cs",
    unit: "%",
  },
  gameplayRadius: {
    id: "gameplayRadius",
    name: "Gameplay Radius",
    abbr: ["Gameplay"],
    description: "Determines reach of both incoming and outgoing effects.",
    group: "champion",
    icon: "lp:radius",
  },
  pathingRadius: {
    id: "pathingRadius",
    name: "Pathing Radius",
    abbr: ["Pathing"],
    description:
      "The gameplay area a unit occupies for unit-collision and pathfinding logic.",
    group: "champion",
    icon: "lp:pathing",
  },
  selectionRadius: {
    id: "selectionRadius",
    name: "Selection Radius",
    abbr: ["Selection"],
    description: "The farthest selectable point from the unit's center point.",
    group: "champion",
    icon: "lp:range-center",
  },
}
