export default defineAppConfig({
  theme: {},
  icon: {
    mode: 'svg',
    class: 'text-[var(--color-bc)]',
    aliases: {
      'nuxt': 'logos:nuxt-icon',
      'search': 'teenyicons:search-outline',
      'add': 'teenyicons:add-outline',
      'add-sm': 'teenyicons:add-small-outline',
      'more': 'teenyicons:more-horizontal-outline',
      'tick': 'teenyicons:tick-outline',
      'tick-sm': 'teenyicons:tick-small-outline',
      'down': 'teenyicons:down-outline',
      'up': 'teenyicons:up-outline',
      'down-sm': 'teenyicons:down-small-outline',
      'up-sm': 'teenyicons:up-small-outline',
      'select': 'teenyicons:caret-vertical-small-outline',
      'at': 'teenyicons:at-outline',
      'riot': 'simple-icons:riotgames',
      'github': 'ph:github-logo',
      'x-sm': 'teenyicons:x-small-outline',
      'x': 'teenyicons:x-outline',
      'minus-sm': 'teenyicons:minus-small-outline',
      'and': 'mynaui:ampersand',
      'id-card': 'icon-park-twotone:id-card-v',
      'reset': 'mynaui:refresh',
      'gear': 'ph:gear-six',
      'shield': 'teenyicons:shield-tick-outline',
      'copy': 'teenyicons:layers-subtract-outline',
      'shuffle': 'qlementine-icons:shuffle-16',
      'folders': 'formkit:folder',
      'star': 'uiw:star-off',
      'infinity': 'solar:infinity-outline',
      'calc': 'teenyicons:calculator-outline',
      'filter': 'teenyicons:filter-outline',
      'heart': 'teenyicons:heart-outline',
      'x-folder': 'teenyicons:folder-x-outline',
      'add-folder': 'teenyicons:folder-plus-outline',
      'lines': 'teenyicons:align-text-justify-outline',
      'mail': 'fluent:mail-48-regular',
      'info': 'teenyicons:info-outline',
    },
  },
})
