/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/pages/about.vue')['default']
    App: typeof import('./src/pages/App.vue')['default']
    Browse: typeof import('./src/pages/browse.vue')['default']
    Build: typeof import('./src/pages/builds/build.vue')['default']
    BuildsTemplate: typeof import('./src/pages/builds/builds-template.vue')['default']
    BuildTemplate: typeof import('./src/pages/builds/buildTemplate.vue')['default']
    ChampionGrid: typeof import('./src/pages/champions/championGrid.vue')['default']
    Champions: typeof import('./src/pages/champions/champions.vue')['default']
    ChampionSidebar: typeof import('./src/pages/champions/championSidebar.vue')['default']
    copy: typeof import('./src/pages/items/itemGrid.vue')['default']
    Egg: typeof import('./src/pages/champions/egg.vue')['default']
    EggEmpty: typeof import('./src/pages/eggs/eggEmpty.vue')['default']
    Empty: typeof import('./src/pages/empty.vue')['default']
    Hi: typeof import('./src/pages/hi.vue')['default']
    Home: typeof import('./src/pages/home.vue')['default']
    Icons: typeof import('./src/pages/builds/icons.vue')['default']
    IRuneIconsPrecision: typeof import('~icons/rune-icons/precision')['default']
    ItemGrid: typeof import('./src/pages/items/itemGrid.vue')['default']
    Items: typeof import('./src/pages/items.vue')['default']
    IUiIconsLpup: typeof import('~icons/ui-icons/lpup')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Runes: typeof import('./src/pages/runes/runes.vue')['default']
    SearchBox: typeof import('./src/pages/searchBox.vue')['default']
    Settings: typeof import('./src/pages/settings.vue')['default']
    Template: typeof import('./src/pages/eggs/template.vue')['default']
    Titlebar: typeof import('./src/pages/components/titlebar.vue')['default']
  }
}
