shamefully-hoist: true
shellEmulator: true

trustPolicy: no-downgrade

overrides:
  chokidar: 3.5.3
  semver: 7.5.4

patchedDependencies:
  "@nuxt/icon@2.2.1": patches/@nuxt__icon@2.2.1.patch
  "@nuxt/ui@4.5.0": patches/@nuxt__ui@4.5.0.patch
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - re2
  - sharp
  - supabase
  - unrs-resolver
  - vue-demi
  - workerd
  - vue-chrts
