shamefullyHoist: false

shellEmulator: true

trustPolicy: no-downgrade
overrides:
  chokidar: 3.5.3
  semver: 7.5.4

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - maplibre-gl
  - re2
  - sharp
  - supabase
  - unrs-resolver
  - vue-demi
  - workerd
  - vue-chrts

