shamefullyHoist: false

shellEmulator: true

trustPolicy: no-downgrade
overrides:
  "@nuxt/ui>reka-ui": 2.9.5
  chokidar: 3.5.3
  reka-ui: $reka-ui
  semver: 7.5.4
  vaul-vue>reka-ui: 2.9.5
allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  esbuild: true
  maplibre-gl: true
  re2: true
  sharp: true
  supabase: true
  unrs-resolver: true
  vue-demi: true
  workerd: true
  vue-chrts: true
