/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'About': RouteRecordInfo<'About', '/about', Record<never, never>, Record<never, never>>,
    '/App': RouteRecordInfo<'/App', '/App', Record<never, never>, Record<never, never>>,
    '/champions/championAvatars': RouteRecordInfo<'/champions/championAvatars', '/champions/championAvatars', Record<never, never>, Record<never, never>>,
    'championGrid': RouteRecordInfo<'championGrid', '/champions/championGrid', Record<never, never>, Record<never, never>>,
    'Champions': RouteRecordInfo<'Champions', '/champions/champions', Record<never, never>, Record<never, never>>,
    'championSidebar': RouteRecordInfo<'championSidebar', '/champions/championSidebar', Record<never, never>, Record<never, never>>,
    '/champions/listChamps': RouteRecordInfo<'/champions/listChamps', '/champions/listChamps', Record<never, never>, Record<never, never>>,
    '/champions/selectedChamps': RouteRecordInfo<'/champions/selectedChamps', '/champions/selectedChamps', Record<never, never>, Record<never, never>>,
    '/components/clearButton': RouteRecordInfo<'/components/clearButton', '/components/clearButton', Record<never, never>, Record<never, never>>,
    '/components/colorPicker': RouteRecordInfo<'/components/colorPicker', '/components/colorPicker', Record<never, never>, Record<never, never>>,
    '/components/menu': RouteRecordInfo<'/components/menu', '/components/menu', Record<never, never>, Record<never, never>>,
    '/components/modal': RouteRecordInfo<'/components/modal', '/components/modal', Record<never, never>, Record<never, never>>,
    '/components/modalConfirm': RouteRecordInfo<'/components/modalConfirm', '/components/modalConfirm', Record<never, never>, Record<never, never>>,
    '/components/placeholder': RouteRecordInfo<'/components/placeholder', '/components/placeholder', Record<never, never>, Record<never, never>>,
    '/components/placeholder-outline': RouteRecordInfo<'/components/placeholder-outline', '/components/placeholder-outline', Record<never, never>, Record<never, never>>,
    '/components/pocketIcon': RouteRecordInfo<'/components/pocketIcon', '/components/pocketIcon', Record<never, never>, Record<never, never>>,
    '/components/quickSearch': RouteRecordInfo<'/components/quickSearch', '/components/quickSearch', Record<never, never>, Record<never, never>>,
    '/components/searchBox': RouteRecordInfo<'/components/searchBox', '/components/searchBox', Record<never, never>, Record<never, never>>,
    '/components/selectClass': RouteRecordInfo<'/components/selectClass', '/components/selectClass', Record<never, never>, Record<never, never>>,
    '/components/selectClassNew': RouteRecordInfo<'/components/selectClassNew', '/components/selectClassNew', Record<never, never>, Record<never, never>>,
    '/components/sort': RouteRecordInfo<'/components/sort', '/components/sort', Record<never, never>, Record<never, never>>,
    '/components/tabs': RouteRecordInfo<'/components/tabs', '/components/tabs', Record<never, never>, Record<never, never>>,
    '/components/titlebar': RouteRecordInfo<'/components/titlebar', '/components/titlebar', Record<never, never>, Record<never, never>>,
    '/empty': RouteRecordInfo<'/empty', '/empty', Record<never, never>, Record<never, never>>,
    '/hi': RouteRecordInfo<'/hi', '/hi', Record<never, never>, Record<never, never>>,
    'home': RouteRecordInfo<'home', '/home', Record<never, never>, Record<never, never>>,
    '/items': RouteRecordInfo<'/items', '/items', Record<never, never>, Record<never, never>>,
    '/items/filterPanel': RouteRecordInfo<'/items/filterPanel', '/items/filterPanel', Record<never, never>, Record<never, never>>,
    '/items/itemContextMenu': RouteRecordInfo<'/items/itemContextMenu', '/items/itemContextMenu', Record<never, never>, Record<never, never>>,
    'items': RouteRecordInfo<'items', '/items/items', Record<never, never>, Record<never, never>>,
    '/items/itemSets': RouteRecordInfo<'/items/itemSets', '/items/itemSets', Record<never, never>, Record<never, never>>,
    '/items/listItems': RouteRecordInfo<'/items/listItems', '/items/listItems', Record<never, never>, Record<never, never>>,
    '/items/popItem': RouteRecordInfo<'/items/popItem', '/items/popItem', Record<never, never>, Record<never, never>>,
    '/items/statFilters': RouteRecordInfo<'/items/statFilters', '/items/statFilters', Record<never, never>, Record<never, never>>,
    '/items/tierFilters': RouteRecordInfo<'/items/tierFilters', '/items/tierFilters', Record<never, never>, Record<never, never>>,
    'Champions': RouteRecordInfo<'Champions', '/likes', Record<never, never>, Record<never, never>>,
    'pocket': RouteRecordInfo<'pocket', '/pockets/pocket/:pocketKey', Record<never, never>, Record<never, never>>,
    '/pockets/export': RouteRecordInfo<'/pockets/export', '/pockets/export', Record<never, never>, Record<never, never>>,
    '/pockets/pocketChampions': RouteRecordInfo<'/pockets/pocketChampions', '/pockets/pocketChampions', Record<never, never>, Record<never, never>>,
    '/pockets/pocketForm': RouteRecordInfo<'/pockets/pocketForm', '/pockets/pocketForm', Record<never, never>, Record<never, never>>,
    '/pockets/pocketGrid': RouteRecordInfo<'/pockets/pocketGrid', '/pockets/pocketGrid', Record<never, never>, Record<never, never>>,
    '/pockets/pocketItems': RouteRecordInfo<'/pockets/pocketItems', '/pockets/pocketItems', Record<never, never>, Record<never, never>>,
    '/pockets/pocketMenu': RouteRecordInfo<'/pockets/pocketMenu', '/pockets/pocketMenu', Record<never, never>, Record<never, never>>,
    '/pockets/pocketRunes': RouteRecordInfo<'/pockets/pocketRunes', '/pockets/pocketRunes', Record<never, never>, Record<never, never>>,
    'pockets': RouteRecordInfo<'pockets', '/pockets/pockets', Record<never, never>, Record<never, never>>,
    '/pockets/pockets copy': RouteRecordInfo<'/pockets/pockets copy', '/pockets/pockets copy', Record<never, never>, Record<never, never>>,
    '/pockets/pockets1': RouteRecordInfo<'/pockets/pockets1', '/pockets/pockets1', Record<never, never>, Record<never, never>>,
    '/pockets/popPocket': RouteRecordInfo<'/pockets/popPocket', '/pockets/popPocket', Record<never, never>, Record<never, never>>,
    '/pockets/popPocket copy': RouteRecordInfo<'/pockets/popPocket copy', '/pockets/popPocket copy', Record<never, never>, Record<never, never>>,
    'trash': RouteRecordInfo<'trash', '/pockets/trash', Record<never, never>, Record<never, never>>,
    'trashPockets': RouteRecordInfo<'trashPockets', '/pockets/trashPockets', Record<never, never>, Record<never, never>>,
    '/runes/runeGrid': RouteRecordInfo<'/runes/runeGrid', '/runes/runeGrid', Record<never, never>, Record<never, never>>,
    '/runes/runeInfo': RouteRecordInfo<'/runes/runeInfo', '/runes/runeInfo', Record<never, never>, Record<never, never>>,
    '/runes/runePath': RouteRecordInfo<'/runes/runePath', '/runes/runePath', Record<never, never>, Record<never, never>>,
    '/runes/runePop': RouteRecordInfo<'/runes/runePop', '/runes/runePop', Record<never, never>, Record<never, never>>,
    'Runes': RouteRecordInfo<'Runes', '/runes/runes', Record<never, never>, Record<never, never>>,
    '/runes/runeSets': RouteRecordInfo<'/runes/runeSets', '/runes/runeSets', Record<never, never>, Record<never, never>>,
    '/runes/runeShards': RouteRecordInfo<'/runes/runeShards', '/runes/runeShards', Record<never, never>, Record<never, never>>,
    'Settings': RouteRecordInfo<'Settings', '/settings', Record<never, never>, Record<never, never>>,
    '/template': RouteRecordInfo<'/template', '/template', Record<never, never>, Record<never, never>>,
  }
}
