/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'About': RouteRecordInfo<'About', '/about', Record<never, never>, Record<never, never>>,
    '/App': RouteRecordInfo<'/App', '/App', Record<never, never>, Record<never, never>>,
    'Build': RouteRecordInfo<'Build', '/builds/build', Record<never, never>, Record<never, never>>,
    'championGrid': RouteRecordInfo<'championGrid', '/builds/buildChampions', Record<never, never>, Record<never, never>>,
    '/builds/buildItems': RouteRecordInfo<'/builds/buildItems', '/builds/buildItems', Record<never, never>, Record<never, never>>,
    '/builds/buildRunes': RouteRecordInfo<'/builds/buildRunes', '/builds/buildRunes', Record<never, never>, Record<never, never>>,
    '/builds/builds-template': RouteRecordInfo<'/builds/builds-template', '/builds/builds-template', Record<never, never>, Record<never, never>>,
    '/builds/buildTemplate': RouteRecordInfo<'/builds/buildTemplate', '/builds/buildTemplate', Record<never, never>, Record<never, never>>,
    '/builds/championAvatars': RouteRecordInfo<'/builds/championAvatars', '/builds/championAvatars', Record<never, never>, Record<never, never>>,
    '/builds/export': RouteRecordInfo<'/builds/export', '/builds/export', Record<never, never>, Record<never, never>>,
    'championGrid': RouteRecordInfo<'championGrid', '/champions/championGrid', Record<never, never>, Record<never, never>>,
    'Champions': RouteRecordInfo<'Champions', '/champions/champions', Record<never, never>, Record<never, never>>,
    'championSidebar': RouteRecordInfo<'championSidebar', '/champions/championSidebar', Record<never, never>, Record<never, never>>,
    '/champions/selectedChamps': RouteRecordInfo<'/champions/selectedChamps', '/champions/selectedChamps', Record<never, never>, Record<never, never>>,
    '/components/icons': RouteRecordInfo<'/components/icons', '/components/icons', Record<never, never>, Record<never, never>>,
    '/components/menu': RouteRecordInfo<'/components/menu', '/components/menu', Record<never, never>, Record<never, never>>,
    '/components/modal': RouteRecordInfo<'/components/modal', '/components/modal', Record<never, never>, Record<never, never>>,
    '/components/modalConfirm': RouteRecordInfo<'/components/modalConfirm', '/components/modalConfirm', Record<never, never>, Record<never, never>>,
    '/components/searchBox': RouteRecordInfo<'/components/searchBox', '/components/searchBox', Record<never, never>, Record<never, never>>,
    '/components/sort': RouteRecordInfo<'/components/sort', '/components/sort', Record<never, never>, Record<never, never>>,
    '/components/tabs': RouteRecordInfo<'/components/tabs', '/components/tabs', Record<never, never>, Record<never, never>>,
    '/components/titlebar': RouteRecordInfo<'/components/titlebar', '/components/titlebar', Record<never, never>, Record<never, never>>,
    '/empty': RouteRecordInfo<'/empty', '/empty', Record<never, never>, Record<never, never>>,
    '/hi': RouteRecordInfo<'/hi', '/hi', Record<never, never>, Record<never, never>>,
    'home': RouteRecordInfo<'home', '/home', Record<never, never>, Record<never, never>>,
    '/items': RouteRecordInfo<'/items', '/items', Record<never, never>, Record<never, never>>,
    '/items/itemContextMenu': RouteRecordInfo<'/items/itemContextMenu', '/items/itemContextMenu', Record<never, never>, Record<never, never>>,
    '/items/itemGrid': RouteRecordInfo<'/items/itemGrid', '/items/itemGrid', Record<never, never>, Record<never, never>>,
    '/items/itemPop': RouteRecordInfo<'/items/itemPop', '/items/itemPop', Record<never, never>, Record<never, never>>,
    'items': RouteRecordInfo<'items', '/items/items', Record<never, never>, Record<never, never>>,
    '/items/itemSets': RouteRecordInfo<'/items/itemSets', '/items/itemSets', Record<never, never>, Record<never, never>>,
    '/items/statFilters': RouteRecordInfo<'/items/statFilters', '/items/statFilters', Record<never, never>, Record<never, never>>,
    '/items/tierFilters': RouteRecordInfo<'/items/tierFilters', '/items/tierFilters', Record<never, never>, Record<never, never>>,
    '/runes/runeGrid': RouteRecordInfo<'/runes/runeGrid', '/runes/runeGrid', Record<never, never>, Record<never, never>>,
    '/runes/runeInfo': RouteRecordInfo<'/runes/runeInfo', '/runes/runeInfo', Record<never, never>, Record<never, never>>,
    '/runes/runePath': RouteRecordInfo<'/runes/runePath', '/runes/runePath', Record<never, never>, Record<never, never>>,
    '/runes/runePop': RouteRecordInfo<'/runes/runePop', '/runes/runePop', Record<never, never>, Record<never, never>>,
    'Runes': RouteRecordInfo<'Runes', '/runes/runes', Record<never, never>, Record<never, never>>,
    '/runes/runeSets': RouteRecordInfo<'/runes/runeSets', '/runes/runeSets', Record<never, never>, Record<never, never>>,
    '/runes/runeShards': RouteRecordInfo<'/runes/runeShards', '/runes/runeShards', Record<never, never>, Record<never, never>>,
    'Settings': RouteRecordInfo<'Settings', '/settings', Record<never, never>, Record<never, never>>,
    '/template': RouteRecordInfo<'/template', '/template', Record<never, never>, Record<never, never>>,
  }
}
