/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/App': RouteRecordInfo<'/App', '/App', Record<never, never>, Record<never, never>>,
    '/browse': RouteRecordInfo<'/browse', '/browse', Record<never, never>, Record<never, never>>,
    '/builds': RouteRecordInfo<'/builds', '/builds', Record<never, never>, Record<never, never>>,
    '/champions': RouteRecordInfo<'/champions', '/champions', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/items': RouteRecordInfo<'/items', '/items', Record<never, never>, Record<never, never>>,
    '/modules/ChampionInfo': RouteRecordInfo<'/modules/ChampionInfo', '/modules/ChampionInfo', Record<never, never>, Record<never, never>>,
    '/modules/ItemInfo': RouteRecordInfo<'/modules/ItemInfo', '/modules/ItemInfo', Record<never, never>, Record<never, never>>,
    '/modules/news': RouteRecordInfo<'/modules/news', '/modules/news', Record<never, never>, Record<never, never>>,
    '/runes': RouteRecordInfo<'/runes', '/runes', Record<never, never>, Record<never, never>>,
    '/searchBox': RouteRecordInfo<'/searchBox', '/searchBox', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
  }
}
