export const statTotalGold: ItemStat[] = [
  {
    id: 'total',
    displayName: 'Total Gold Cost',
    checked: false,
    shortName: 'Total',
    icon: '',
    class: '',
    bgClass: '',
    hoverClass: '',
  },
]
export const itemStats: ItemStat[] = [
  {
    id: 'abilityHaste',
    displayName: 'Ability Haste',
    checked: false,
    shortName: 'Cooldown_reduction_icon',
    icon: 'ah',
    class: '',
    bgClass: 'bg-inspiration text-white',
    hoverClass: 'hover:bg-inspiration-light/60',
  },
  {
    id: 'abilityPower',
    displayName: 'Ability Power',
    checked: false,
    shortName: 'AP',
    icon: 'ap',
    class: '',
    bgClass: 'bg-sorcery text-white',
    hoverClass: 'hover:bg-sorcery-light/60',
  },
  {
    id: 'armor',
    displayName: 'Armor',
    checked: false,
    shortName: 'ARMOR',
    icon: 'armor',
    class: '',
    bgClass: 'bg-precision text-white',
    hoverClass: 'hover:bg-precision-w600/60',
  },
  {
    id: 'armorPenetration',
    displayName: 'Armor Penetration',
    shortName: 'APEN',
    checked: false,
    icon: 'armor-pen',
    class: '',
    bgClass: 'bg-precision text-white',
    hoverClass: 'hover:bg-precision-w600/60',
  },
  {
    id: 'attackDamage',
    displayName: 'Attack Damage',
    checked: false,
    shortName: 'AD',
    icon: 'ad',
    class: '',
    bgClass: 'bg-precision text-white',
    hoverClass: 'hover:bg-precision-w600/60',
  },
  {
    id: 'attackSpeed',
    displayName: 'Attack Speed',
    checked: false,
    shortName: 'AS',
    icon: 'as',
    class: '',
    bgClass: 'bg-precision text-white',
    hoverClass: 'hover:bg-precision-w600/60',
  },
  {
    id: 'criticalStrikeChance',
    displayName: 'Critical Chance',
    checked: false,
    shortName: 'CRIT',
    icon: 'cs',
    class: '',
    bgClass: 'bg-domination text-white',
    hoverClass: 'hover:bg-domination-light/60',
  },
  {
    id: 'goldPer10',
    displayName: 'Gold per 10',
    shortName: 'GP/10',
    checked: false,
    icon: 'gold',
    class: '',
    bgClass: 'bg-precision text-white',
    hoverClass: 'hover:bg-precision-w600/60',
  },
  {
    id: 'healAndShieldPower',
    displayName: 'Heal & Shield Power',
    checked: false,
    shortName: 'HSP',
    icon: 'hsp',
    class: '',
    bgClass: 'bg-inspiration text-white',
    hoverClass: 'hover:bg-inspiration-light/60',
  },
  {
    id: 'health',
    displayName: 'Health',
    shortName: 'HP',
    checked: false,
    icon: 'health',
    class: '',
    bgClass: 'bg-resolve text-white',
    hoverClass: 'hover:bg-resolve-light/60',
  },
  {
    id: 'healthRegen',
    displayName: 'Health Regen',
    shortName: 'HP/5',
    checked: false,
    icon: 'hp',
    class: '',
    bgClass: 'bg-resolve text-white',
    hoverClass: 'hover:bg-resolve-light/60',
  },
  {
    id: 'lethality',
    displayName: 'Lethality',
    checked: false,
    shortName: 'LTY',
    icon: 'armor-pen',
    class: '',
    bgClass: 'bg-domination text-white',
    hoverClass: 'hover:bg-domination-light/60',
  },
  {
    id: 'lifesteal',
    displayName: 'Lifesteal',
    checked: false,
    shortName: 'LS',
    icon: 'ls',
    class: '',
    bgClass: 'bg-domination text-white',
    hoverClass: 'hover:bg-domination-light/60',
  },
  {
    id: 'percentMagicPenetration',
    displayName: 'Magic Penetration',
    shortName: 'MPEN',
    checked: false,
    icon: 'mpen',
    class: '',
    bgClass: 'Magic_penetration_icon',
    hoverClass: 'hover:bg-sorcery-light/60',
  },
  {
    id: 'flatMagicPenetration',
    displayName: 'Flat Magic Penetration',
    shortName: 'Flat MPEN',
    checked: false,
    icon: 'mpen',

    iconClass: '',
    class: '',
    bgClass: 'bg-sorcery text-white',
    hoverClass: 'hover:bg-sorcery-light/60',
  },
  {
    id: 'magicResistance',
    displayName: 'Magic Resist',
    checked: false,
    shortName: 'MR',
    icon: 'mr',
    class: '',
    bgClass: 'bg-sorcery text-white',
    hoverClass: 'hover:bg-sorcery-light/60',
  },
  {
    id: 'mana',
    displayName: 'Mana',
    checked: false,
    shortName: 'MANA',
    icon: 'mana',
    class: '',
    bgClass: 'mana',
    hoverClass: 'hover:bg-inspiration-light/60',
  },
  {
    id: 'manaRegen',
    displayName: 'Mana Regen',
    shortName: 'MP/5',
    checked: false,

    icon: 'mana-regen',
    class: '',
    bgClass: 'bg-inspiration text-white',
    hoverClass: 'hover:bg-inspiration-light/60',
  },

  {
    id: 'percentMovespeed',
    displayName: 'Movespeed',
    checked: false,
    shortName: 'MS',
    icon: 'ms',
    class: '',
    bgClass: 'bg-b2/60',
    hoverClass: 'hover:bg-b2/60',
  },

  {
    id: 'flatMovespeed',
    displayName: 'Base Movespeed',
    checked: false,
    shortName: 'Base MS',
    icon: 'ms',
    class: '',
    bgClass: 'bg-b2/60',
    hoverClass: 'hover:bg-b2/60',
  },

]