export const statTotalGold = [
  {
    id: 'total',
    displayName: 'Total Gold Cost',
    checked: false,
    shortName: 'Total',
    icon: '',
    class: '',
    bgClass: '',
  },
]
export const itemStats = [
  {
    id: 'abilityHaste',
    displayName: 'Ability Haste',
    checked: false,
    shortName: 'AH',
    icon: 'ah',
    class: '',
    color: '**:text-platinum',
    bgClass: 'bg-platinum text-white',
  },
  {
    id: 'abilityPower',
    displayName: 'Ability Power',
    checked: false,
    shortName: 'AP',
    icon: 'ap',
    class: '',
 color: '**:text-diamond',
    bgClass: 'bg-sorcery text-white',
  },
  {
    id: 'armor',
    displayName: 'Armor',
    checked: false,
    shortName: 'ARMOR',
    icon: 'armor',
    class: '',
 color: '**:text-precision',
    bgClass: 'bg-precision  **:!text-bc  !text-bc',
  },
  {
    id: 'armorPenetration',
    displayName: 'Armor Penetration',
    shortName: 'APEN',
    checked: false,
    icon: 'armor-pen',
    class: '',
 color: '**:text-fighter',
    bgClass: 'bg-fighter text-white',
  },
  {
    id: 'attackDamage',
    displayName: 'Attack Damage',
    checked: false,
    shortName: 'AD',
    icon: 'ad',
    class: '',
 color: '**:text-fighter',
    bgClass: 'bg-fighter text-white',
  },
  {
    id: 'attackSpeed',
    displayName: 'Attack Speed',
    checked: false,
    shortName: 'AS',
    icon: 'as',
    class: '',
 color: '**:text-precision',
    bgClass: 'bg-precision **:!text-bc  !text-bc',
  },
  {
    id: 'criticalStrikeChance',
    displayName: 'Critical Chance',
    checked: false,
    shortName: 'CRIT',
    icon: 'cs',
    class: '',
 color: '**:text-domination',
    bgClass: 'bg-domination text-white',
  },
  {
    id: 'goldPer10',
    displayName: 'Gold per 10',
    shortName: 'GP/10',
    checked: false,
    icon: 'gold',
    class: '',
 color: '**:text-precision',
    bgClass: 'bg-precision **:!text-bc  !text-bc',
  },
  {
    id: 'healAndShieldPower',
    displayName: 'Heal & Shield Power',
    checked: false,
    shortName: 'HSP',
    icon: 'hsp',
    class: '',
 color: '**:text-platinum',
    bgClass: 'bg-platinum text-white',
  },
  {
    id: 'health',
    displayName: 'Health',
    shortName: 'HP',
    checked: false,
    icon: 'health',
    class: '',
 color: '**:text-emerald',
    bgClass: 'bg-emerald text-white',
  },
  {
    id: 'healthRegen',
    displayName: 'Health Regen',
    shortName: 'HP/5',
    checked: false,
    icon: 'hp',
    class: '',
 color: '**:text-emerald',
    bgClass: 'bg-emerald text-white',
  },
  {
    id: 'lethality',
    displayName: 'Lethality',
    checked: false,
    shortName: 'LTY',
    icon: 'armor-pen',
    class: '',
 color: '**:text-domination',
    bgClass: 'bg-domination text-white',
  },
  {
    id: 'lifesteal',
    displayName: 'Lifesteal',
    checked: false,
    shortName: 'LS',
    icon: 'ls',
    class: '',
 color: '**:text-domination',
    bgClass: 'bg-domination text-white',
  },
  {
    id: 'percentMagicPenetration',
    displayName: 'Magic Penetration',
    shortName: 'MPEN',
    checked: false,
    icon: 'mpen',
    class: '',
 color: '**:text-diamond',
    bgClass: 'Magic_penetration_icon',
  },
  {
    id: 'flatMagicPenetration',
    displayName: 'Flat Magic Penetration',
    shortName: 'Flat MPEN',
    checked: false,
    icon: 'mpen',

    iconClass: '',
    class: '',
 color: '**:text-diamond',
    bgClass: 'bg-sorcery text-white',
  },
  {
    id: 'magicResistance',
    displayName: 'Magic Resist',
    checked: false,
    shortName: 'MR',
    icon: 'mr',
    class: '',
 color: '**:text-diamond',
    bgClass: 'bg-sorcery text-white',
  },
  {
    id: 'mana',
    displayName: 'Mana',
    checked: false,
    shortName: 'MANA',
    icon: 'mana',
    class: '',
 color: '**:text-platinum',
    bgClass: 'bg-platinum  text-white',
  },
  {
    id: 'manaRegen',
    displayName: 'Mana Regen',
    shortName: 'MP/5',
    checked: false,

    icon: 'mana-regen',
    class: '',
 color: '**:text-platinum',
    bgClass: 'bg-platinum text-white',
  },

  {
    id: 'percentMovespeed',
    displayName: 'Movespeed',
    checked: false,
    shortName: 'MS',
    icon: 'ms',
    class: '',
 color: '**:text-platinum',
    bgClass: 'bg-b2/60 **:!text-bc  !text-bc',
  },
  {
    id: 'flatMovespeed',
    displayName: 'Base Movespeed',
    checked: false,
    shortName: 'Base MS',
    icon: 'ms',
    class: '',
 color: '**:text-platinum',
    bgClass: 'bg-b2/60  **:!text-bc  !text-bc',
  },
  {
    id: 'criticalStrikeDamage',
    displayName: 'Critical Damage',
    checked: false,
    shortName: 'Crit Dmg',
    icon: 'crit-dmg',
    class: '',
 color: '**:text-domination',
    bgClass: 'bg-precision/60',
  },
  {
    id: 'tenacity',
    displayName: 'Tenacity',
    checked: false,
    shortName: 'Tenacity',
    icon: 'crit-dmg',
    class: '',
 color: '**:text-platinum',
    bgClass: 'bg-platinum/60',
  },

]