// Updated Patch 16.1 - 01/29/2026 04:27:02 PM CST
import type { Champion } from '#shared/types'

const champion: Champion = {
  id: 107,
  key: 'Rengar',
  name: 'Rengar',
  title: 'The Pridestalker',
  adaptiveType: 'Physical damage',
  attackType: 'Melee',
  patchLastChanged: '25.23',
  releaseDate: '2012-08-21',
  resource: 'Ferocity',
  abilities: [
    {
      key: 'P',
      name: 'Unseen Predator',
      affects: 'Self',
      blurb: 'Innate:  Rengar generates Ferocity when he casts a basic ability or uses  Savagery\'s empowered attack, which expires after a period out of combat. At max Ferocity, his next basic ability consumes them to become empowered with an additional effect, gain an extra cast, and briefly grant him  bonus movement speed.',
      icon: 'https://cdn.communitydragon.org/latest/champion/Rengar/ability-icon/p',
      notes: 'Rengar will not leap to targets already in his normal  basic attack range.\nWhile  grounded or  rooted, Rengar loses the enhanced  attack range from Unseen Predator.\nRengar will only leap to a target if his basic attack timer has been refreshed (if not so he will not automatically attempt to path towards his target, despite them being within leap range).\nOnly  Flash and  Hexflash instantly end Unseen Predator. Other effects (i.e  Teleport) will still cause the buff to linger upon leaving  brush.\nRengar can freely use any  abilities, summoner spells, or item actives while leaping.\nUsing a  dash or  blink ability will interrupt the leap.\nThe attack from the leap will:\nNot go off if the dash was interrupted.\nGo off at the end of the dash even if its normal destination is obstructed by boundaries he cannot cross (e.g. terrain,  The Hextech Ultimatum).\nGo off regardless of distance the enemy travels away from Rengar\'s original location.\nGo off even if Rengar loses  sight of the target.\nGo off but have no effect if the target dies or becomes  untargetable.\nWhen the attack goes off,  Savagery\'s empowered attack is consumed.\n Rapid Firecannon\'s and  Savagery\'s bonus ranges are lost after 0.25 seconds upon gaining Unseen Predator, and are re-gained after 0.25 seconds upon losing Unseen Predator.\nRengar has a secondary resource bar that indicates how much Ferocity he currently has as pips.\nFerocity generated by Unseen Predator has a purple color.\nFerocity generated by his other abilities has a white color.\nBonetooth Necklace uses different icons corresponding to the number of stacks acquired:\n1 Stack: \n2 Stacks: \n3 Stacks: \n4 Stacks: \n5 Stacks: \n6th Stack:  Head of Kha\'Zix',
      speed: '1450',
      targeting: 'Passive',
      targetRange: '50',
      effects: [
        {
          description: '<p class="ability-effect"><span class="ability-header">Innate:</span> Rengar generates 1 Ferocity upon casting a basic ability or using Savagery\'s first attack. At 4 Ferocity, his next basic ability consumes them all to become empowered with an additional effect and grant him an additional cast along with 30% / 40% / 50% (based on level) bonus movement speed for 1.5 seconds. All Ferocity is lost after 10 seconds of not dealing or taking damage, excluding damage dealt by persistent or proc effects.Reaching 4 Ferocity with Savagery or Bola Strike locks the empowered version of the ability from being cast for 0.1 seconds. Similarly, consuming all Ferocity with an empowered ability locks the unempowered version of the ability from being cast for 0.1 seconds if it is not already on cooldown, increased to 0.25 seconds for Battle Roar.</p>'
        },
        {
          description: '<p class="ability-effect"><span class="ability-header">Innate:</span> While in brush, Rengar gains Unseen Predator, which lingers for 0.35 seconds upon exiting brush. Unseen Predator is lost immediately if Rengar exits the brush using Flash or Hexflash.</p>'
        },
        {
          description: '<p class="ability-effect"><span class="ability-header">Unseen Predator:</span> Rengar\'s basic attacks have massively increased range and cause him to leap to the target\'s location, attacking the target upon arrival and landing closer than his normal melee range. At the start of the leap, Unseen Predator will generate 1 Ferocity if none of his current Ferocity was generated this way.Rengar can cast any of his abilities during the dash.</p>'
        },
        {
          description: '<p class="ability-effect"><span class="ability-header">Innate - Bonetooth Necklace:</span> Scoring a takedown against an enemy champion within 3 seconds of damaging them grants Rengar a Trophy, once per unique champion and up to 5. An additional Trophy is made available through the event The Hunt is On! with the Head of Kha\'Zix. Trophies grant bonus attack damage equal to 1% - 36% (based on Trophies) bonus AD.</p>'
        }
      ]
    },
    {
      key: 'Q',
      name: 'Savagery',
      affects: 'Self',
      blurb: 'Active:  Rengar gains  bonus attack speed for his next two  basic attacks. His next basic attack deals bonus physical damage and will  critically strike, dealing increased damage based on his  critical strike chance.',
      castTime: 'none',
      cooldown: '0.25',
      cost: '0',
      damageType: 'Physical damage',
      icon: 'https://cdn.communitydragon.org/latest/champion/Rengar/ability-icon/q',
      notes: 'Savagery deals  basic damage, but also triggers spell effects by also being tagged as  spell damage.\nThe  critical strike modifier scales up to 75% of the  critical damage champions usually have, based on Rengar\'s  critical strike chance.\nSavagery\'s empowered attack is not consumed against jungle plants.\nThe enhanced attack applies other  on-hit effects as well as  life steal as normal (the bonus damage cannot).\nCasting Savagery does not  break stealth.\nAgainst structures, the damage is calculated differently when the user has sources of  bonus critical damage. If the Basic attack damage against structures is:\nPhysical and  Infinity Edge is not equipped: Basic attack + Savagery bonus * 0.6.\nPhysical and  Infinity Edge is equipped: Basic attack + (Savagery bonus -  0.4 * AD) * 0.6. Infinity Edge\'s bonus is subtracted from the calculations.\nMagic and  Infinity Edge is not equipped: (Basic attack + Savagery bonus * 0.6) * 1.75. The damage is increased by the total critical damage modifier.\nMagic and  Infinity Edge is equipped: (Basic attack + (Savagery bonus -  0.4 * AD) * 0.6) * (1.75 +  0.4). Infinity Edge\'s bonus is subtracted from the calculations and the damage is increased by the total critical damage modifier.',
      spellEffects: 'Special',
      spellshieldable: 'True',
      targeting: 'Auto',
      effects: [
        {
          description: '<p class="ability-effect"><span class="ability-header">Active:</span> Rengar empowers his next two basic attacks within 3 seconds to gain 40% bonus attack speed. His first attack has an uncancellable windup, gains 25 bonus range, and deals bonus physical damage. The attack will critically strike for ((31.25% + 22.5%) critical strike chance + 30%) AD bonus physical damage. Against structures, Savagery\'s damage is reduced by 40% and can also critically strike.</p>',
          leveling: [
            {
              attribute: 'Bonus Physical Damage',
              modifiers: [
                {
                  values: '30 / 60 / 90 / 120 / 150'
                },
                {
                  tooltip: 'Scaling per rank:\n0 / 3.75 / 7.5 / 11.25 / 15% AD',
                  unit: '% AD',
                  values: '0 - 15'
                }
              ]
            }
          ]
        },
        {
          description: '<p class="ability-effect"><span class="ability-header">Ferocity Bonus:</span> Savagery\'s damage is modified to deal 30 - 235 (based on level) (+ 30% AD) bonus physical damage. Rengar gains 50% - 101% (based on level) bonus attack speed for 5 seconds.</p>'
        },
        {
          description: 'Savagery resets Rengar\'s basic attack timer.'
        }
      ]
    },
    {
      key: 'W',
      name: 'Battle Roar',
      affects: 'Self / Enemies',
      blurb: 'Passive:  Rengar stores grey health equal to a portion of damage taken within a brief moment.',
      castTime: 'none',
      cooldown: '0.25',
      cost: '0',
      damageType: 'Magic damage',
      effectRadius: '450',
      icon: 'https://cdn.communitydragon.org/latest/champion/Rengar/ability-icon/w',
      notes: 'Grey health will not be consumed upon casting Battle Roar despite visually appearing so. It will only ever expire after its duration ends.',
      spellEffects: 'spellaoe',
      spellshieldable: 'True',
      targeting: 'Auto',
      effects: [
        {
          description: '<p class="ability-effect"><span class="ability-header">Passive:</span> Rengar stores 50% of the post-mitigation damage he has taken in the last 1.5 seconds as grey health on his health bar, increased to 100% of damage taken from monsters.</p>'
        },
        {
          description: '<p class="ability-effect"><span class="ability-header">Active:</span> Rengar roars, dealing magic damage to nearby enemies and 65 - 130 (based on level) bonus magic damage to monsters, and consuming his grey health to heal for the same amount.</p>',
          leveling: [
            {
              attribute: 'Magic Damage',
              modifiers: [
                {
                  values: '50 / 80 / 110 / 140 / 170'
                },
                {
                  unit: '% AP',
                  values: '80'
                }
              ]
            }
          ]
        },
        {
          description: '<p class="ability-effect"><span class="ability-header">Ferocity Bonus:</span> Battle Roar\'s damage is modified to deal 50 - 220 (based on level) (+ 80% AP) magic damage. Rengar cleanses himself from all crowd control.</p>'
        }
      ]
    },
    {
      key: 'E',
      name: 'Bola Strike',
      width: '140',
      affects: 'Enemies',
      blurb: 'Active:  Rengar throws a bola in the target direction that deals  physical damage and briefly  slows the first enemy hit,  revealing them for a short time.',
      castTime: '0.25 / None',
      cooldown: '0.25',
      cost: '0',
      damageType: 'Physical damage',
      icon: 'https://cdn.communitydragon.org/latest/champion/Rengar/ability-icon/e',
      notes: 'If Rengar casts  Savagery and/or  Battle Roar during Bola Strike\'s cast time, he will buffer them and cast them when Bola Strike completes.\nThis ability will cast from wherever the caster is at the end of the cast time.\nBola Strike\'s end point will not move in relation to Rengar if he moves during the cast time.',
      projectile: 'TRUE',
      speed: '1500',
      spellEffects: 'spell',
      spellshieldable: 'True',
      targeting: 'Direction',
      targetRange: '1000',
      effects: [
        {
          description: '<p class="ability-effect"><span class="ability-header">Active:</span> Rengar throws a bola in the target direction that deals physical damage to the first enemy hit and slows them for 1.75 seconds, as well as revealing them for 2 seconds and granting sight of a 150-unit radius around them for the same duration.</p>',
          leveling: [
            {
              attribute: 'Physical Damage',
              modifiers: [
                {
                  values: '55 / 100 / 145 / 190 / 235'
                },
                {
                  unit: '% bonus AD',
                  values: '80'
                }
              ]
            },
            {
              attribute: 'Slow',
              modifiers: [
                {
                  unit: '%',
                  values: '30 / 45 / 60 / 75 / 90'
                }
              ]
            }
          ]
        },
        {
          description: '<p class="ability-effect"><span class="ability-header">Ferocity Bonus:</span> Bola Strike\'s damage is modified to deal 50 - 305 (based on level) (+ 80% bonus AD) physical damage. The target is rooted instead of slowed.</p>'
        }
      ]
    },
    {
      key: 'R',
      name: 'Thrill of the Hunt',
      affects: 'Enemies',
      blurb: 'Passive:  Rengar also gains  Unseen Predator while  camouflaged.',
      castTime: 'none',
      cooldown: '100 / 90 / 80',
      cost: '0',
      damageType: 'Physical damage',
      effectRadius: '2500 / 2750 / 3000 / 3250 / 3500',
      icon: 'https://cdn.communitydragon.org/latest/champion/Rengar/ability-icon/r',
      notes: 'Thrill of the Hunt\'s duration starts on-cast.\nThe armor reduction applies after the attack.\nIf the attack out of Thrill of the Hunt is prevented or blocked (e.g. by  knocking down Rengar when  leaping) then the effect will not be applied.\nThe  true sight reveal on the target stays until the leap finishes.\nRengar discerns a distinct  heart beat instead of the usual  true sight indicator. This indicator will be removed when out of range, but the target will remain revealed.\nUsing a basic attack  breaks the stealth at the end of the attack windup.\nThrill of the Hunt has an indicator that appears above the target(s) when Rengar is nearby. Some skins have a unique indicator.\n\n\n\n Headhunter\n\n\n\n Night Hunter\n\n\n\n Mecha\n\n\n\n Pretty Kitty\n\n\n\n Guardian of the Sands\n\n\n\n Sentinel\n\n\n\n Street Demons',
      spellEffects: 'Proc',
      spellshieldable: 'false',
      targeting: 'Auto',
      effects: [
        {
          description: '<p class="ability-effect"><span class="ability-header">Passive:</span> Rengar also gains Unseen Predator while camouflaged from any source.</p>'
        },
        {
          description: '<p class="ability-effect"><span class="ability-header">Active:</span> Rengar prowls for a duration, gaining bonus movement speed. After a 2-second delay, he also becomes camouflaged and gains Unseen Predator.</p>',
          leveling: [
            {
              attribute: 'Effect Duration',
              modifiers: [
                {
                  unit: ' seconds',
                  values: '12 / 16 / 20'
                }
              ]
            },
            {
              attribute: 'Bonus Movement Speed',
              modifiers: [
                {
                  unit: '%',
                  values: '40 / 50 / 60'
                }
              ]
            }
          ]
        },
        {
          description: 'During this time, Rengar will detect the nearest enemy champion in range, revealing and gaining sight of a 100-unit radius around them. Enemies detected are revealed for the remaining full duration.'
        },
        {
          description: 'The nearest detected enemy within 1600 range is also marked, alerting all of their allies within 1200 range about Rengar\'s presence.'
        },
        {
          description: 'Rengar\'s next basic attack within 125 range against any enemy or with Unseen Predator to the marked enemy deals 100% AD bonus physical damage, then inflicts armor reduction for 4 seconds.',
          leveling: [
            {
              attribute: 'Armor Reduction',
              modifiers: [
                {
                  values: '15 / 20 / 25'
                }
              ]
            }
          ]
        },
        {
          description: 'Attacking or casting abilities other than Savagery ends Thrill of the Hunt immediately.'
        }
      ]
    }
  ],
  attributeRatings: {
    abilityReliance: 30,
    control: 2,
    damage: 3,
    difficulty: 3,
    mobility: 2,
    toughness: 1,
    utility: 1
  },
  positions: [
    'Jungle',
    'Top'
  ],
  price: {
    blueEssence: 2400,
    rp: 880
  },
  roles: [
    'Assassin',
    'Diver',
    'Fighter'
  ],
  stats: {
    armor: 34,
    attackDamage: 68,
    attackRange: 125,
    attackSpeed: 0.7,
    hp: 590,
    hpRegen: 6,
    magicResist: 32,
    movespeed: 345,
    mp: 4
  },
  statsPerLevel: {
    armor: 4.2,
    attackDamage: 3,
    attackSpeed: 3,
    hp: 104,
    hpRegen: 0.5,
    magicResist: 2.1
  }
}
export default champion