export const regionIndex = {
  na1: 'North America',
  br1: 'Brazil',
  la1: 'Latin America North',
  la2: 'Latin America South',
  oc1: 'Oceania',
  kr: 'Korea',
  jp1: 'Japan',
  eun1: 'Europe Nordic & East',
  euw1: 'Europe West',
  tr1: 'Turkey',
  ru: 'Russia',
  ph2: 'Philippines',
  sg2: 'Singapore',
  th2: 'Thailand',
  tw2: 'Taiwan',
  vn2: 'Vietnam',
}
