import '~/assets/css/colors.css'

export const statTotalGold = [
  {
    id: 'total',
    name: 'Total Gold Cost',
    abbr: 'Total',
    icon: 'i-lol-',
  },
]
export const statIndex = [
  {
    id: 'abilityHaste',
    name: 'Ability Haste',
    abbr: 'AH',
    icon: 'i-lol-ah',
    color: 'var(--color-ah)',
  },
  {
    id: 'abilityPower',
    name: 'Ability Power',
    abbr: 'AP',
    icon: 'i-lol-ap',
    color: 'var(--color-ap)',
  },
  {
    id: 'armor',
    name: 'Armor',
    abbr: 'Armor',
    icon: 'i-lol-armor',
    color: 'var(--color-black-50)',
  },
  {
    id: 'armorPenetration',
    name: 'Armor Penetration',
    abbr: 'APEN',
    icon: 'i-lol-armor-pen',
    color: 'var(--color-apen)',
  },
  {
    id: 'attackDamage',
    name: 'Attack Damage',
    abbr: 'AD',
    icon: 'i-lol-ad',
    color: 'var(--color-ad)',
  },
  {
    id: 'attackSpeed',
    name: 'Attack Speed',
    abbr: 'AS',
    icon: 'i-lol-as',
    color: 'var(--color-as)',
  },
  {
    id: 'flatMovespeed',
    name: 'Base Movespeed',
    abbr: 'MS',
    icon: 'i-lol-ms',
    color: 'var(--color-white-70)',
  },
  {
    id: 'criticalStrikeChance',
    name: 'Critical Chance',
    abbr: 'CRIT',
    icon: 'i-lol-cs',
    color: 'var(--color-domination)',
  },
  {
    id: 'criticalStrikeDamage',
    name: 'Critical Damage',
    abbr: 'CRIT DMG',
    icon: 'i-lol-crit-dmg',
    color: 'var(--color-precision)',
  },
  {
    id: 'flatMagicPenetration',
    name: 'Flat Magic Penetration',
    abbr: 'MPEN',
    icon: 'i-lol-mpen',
    color: 'var(--color-master)',
  },
  {
    id: 'goldPer10',
    name: 'Gold / 10',
    abbr: 'GP/10',
    icon: 'i-lol-gold',
    color: 'var(--color-g)',
  },
  {
    id: 'healAndShieldPower',
    name: 'Heal & Shield Power',
    abbr: 'HSP',
    icon: 'i-lol-hsp',
    color: 'var(--color-hsp)',
  },
  {
    id: 'health',
    name: 'Health',
    abbr: 'HP',
    icon: 'i-lol-health',
    color: 'var(--color-hp)',
  },
  {
    id: 'healthRegen',
    name: 'Health Regen',
    abbr: 'HP/5',
    icon: 'i-lol-hp',
    color: 'var(--color-hp)',
  },
  {
    id: 'lethality',
    name: 'Lethality',
    abbr: 'LTY',
    icon: 'i-lol-armor-pen',
    color: 'var(--color-apen)',
  },
  {
    id: 'lifesteal',
    name: 'Lifesteal',
    abbr: 'LS',
    icon: 'i-lol-ls',
    color: 'var(--color-domination)',
  },
  {
    id: 'percentMagicPenetration',
    name: 'Magic Penetration',
    abbr: 'MPEN',
    icon: 'i-lol-mpen',
    color: 'var(--color-master)',
  },
  {
    id: 'magicResistance',
    name: 'Magic Resist',
    abbr: 'MR',
    icon: 'i-lol-mr',
    color: 'var(--color-mr)',
  },
  {
    id: 'mana',
    name: 'Mana',
    abbr: 'Mana',
    icon: 'i-lol-mana',
    color: 'var(--color-mana)',
  },
  {
    id: 'manaRegen',
    name: 'Mana Regen',
    abbr: 'MP/5',
    icon: 'i-lol-mana-regen',
    color: 'var(--color-mana)',
  },
  {
    id: 'percentMovespeed',
    name: 'Movespeed',
    abbr: 'MS',
    icon: 'i-lol-ms',
    color: 'var(--color-white-70)',
  },
  {
    id: 'omnivamp',
    name: 'Omnivamp',
    abbr: 'VAMP',
    icon: 'i-lol-vamp',
    color: 'var(--color-onhit)',
  },
  {
    id: 'tenacity',
    name: 'Tenacity',
    abbr: 'TENACITY',
    icon: 'i-lol-tenacity',
    color: 'var(--color-platinum)',
  },

  {
    id: 'attackSpeedRatio',
    name: 'Attack Speed Ratio',
    abbr: 'AS Ratio',
  },
  {
    name: 'Range',
    id: 'attackRange',
    icon: 'i-lol-range',
    abbr: 'Range',
    color: 'var(--color-white-70)',
  },
  {
    name: 'Movespeed',
    icon: 'i-lol-ms',
    id: 'movespeed',
    abbr: 'MS',
    color: 'var(--color-white-70)',
  },
  {
    group: 2,
    id: 'acquisitionRadius',
    name: 'Acquisition Radius',
    icon: 'i-lol-acquisition-radius',
    abbr: '',
  },
  {
    group: 2,
    id: 'selectionRadius',
    icon: 'i-lol-range-center',
    name: 'Selection Radius',
    abbr: '',
  },
  {
    group: 2,
    id: 'pathingRadius',
    name: 'Pathing Radius',
    icon: 'i-lol-pathing',
    abbr: '',
  },
  {
    group: 2,
    id: 'gameplayRadius',
    icon: 'i-lol-radius',
    name: 'Gameplay Radius',
    abbr: '',
  },
  {
    group: 2,
    id: 'criticalStrikeDamageModifier',
    name: 'Critical Strike Damage Modifier',
    abbr: '',
  },
  {
    group: 2,
    id: 'attackDelayOffset',
    name: 'Attack Delay Offset',
    abbr: '',
  },
  {
    group: 2,
    id: 'attackCastTime',
    name: 'Attack Cast Time',
    abbr: '',
  },
  {
    group: 2,
    id: 'attackTotalTime',
    name: 'Attack Total Time',
    abbr: '',
  },
]
