export const statTotalGold = [
  {
    id: 'total',
    name: 'Total Gold Cost',
    abbr: 'Total',
    longAbbr: '',
    description: '',
    icon: 'i-lol-',
  },
]
export const statIndex = [
  {
    id: 'abilityHaste',
    name: 'Ability Haste',
    abbr: 'AH',
    description: '',
    icon: 'i-lol-ah',
    color: 'var(--color-ah)',
  },
  {
    id: 'abilityPower',
    name: 'Ability Power',
    abbr: 'AP',
    description: '',
    icon: 'i-lol-ap',
    color: 'var(--color-sorcery)',
  },
  {
    id: 'armor',
    name: 'Armor',
    description: '',
    icon: 'i-lol-armor',
    color: 'var(--color-iron)',
  },
  {
    id: 'armorPenetration',
    name: 'Armor Penetration',
    abbr: 'APEN',
    longAbbr: 'Armor Pen.',
    description: '',
    icon: 'i-lol-armor-pen',
    color: 'var(--color-apen)',
  },
  {
    id: 'attackDamage',
    name: 'Attack Damage',
    abbr: 'AD',
    longAbbr: 'Atk. Dmg',
    description: '',
    icon: 'i-lol-ad',
    color: 'var(--color-ad)',
  },
  {
    id: 'attackSpeed',
    name: 'Attack Speed',
    abbr: 'AS',
    longAbbr: 'Atk. Speed',
    description: '',
    icon: 'i-lol-as',
    color: 'var(--color-as)',
  },
  {
    id: 'flatMovespeed',
    name: 'Base Movespeed',
    abbr: 'MS',
    longAbbr: 'Movespeed',
    description: '',
    icon: 'i-lol-ms',
    color: 'var(--color-white-70)',
  },
  {
    id: 'criticalStrikeChance',
    name: 'Critical Chance',
    abbr: 'Crit',
    longAbbr: 'Crit Chance',
    description: '',
    icon: 'i-lol-cs',
    color: 'var(--color-domination)',
  },
  {
    id: 'criticalStrikeDamage',
    name: 'Critical Damage',
    abbr: 'Crit Dmg',
    description: '',
    icon: 'i-lol-crit-dmg',
    color: 'var(--color-precision)',
  },
  {
    id: 'flatMagicPenetration',
    name: 'Flat Magic Penetration',
    abbr: 'MPEN',
    longAbbr: 'Magic Pen.',
    description: '',
    icon: 'i-lol-mpen',
    color: 'var(--color-master)',
  },
  {
    id: 'goldPer10',
    name: 'Gold / 10',
    abbr: 'GP/10',
    longAbbr: '',
    description: '',
    icon: 'i-lol-gold',
    color: 'var(--color-g)',
  },
  {
    id: 'healAndShieldPower',
    name: 'Heal & Shield Power',
    abbr: 'HSP',
    description: '',
    icon: 'i-lol-hsp',
    color: 'var(--color-enchanter)',
  },
  {
    id: 'health',
    name: 'Health',
    abbr: 'HP',
    longAbbr: 'Health',
    description: '',
    icon: 'i-lol-health',
    color: 'var(--color-resolve)',
  },
  {
    id: 'healthRegen',
    name: 'Health Regen',
    abbr: 'HP/5',
    longAbbr: 'HP Regen',
    description: '',
    icon: 'i-lol-hp',
    color: 'var(--color-resolve)',
  },
  {
    id: 'lethality',
    name: 'Lethality',
    abbr: 'LTY',
    longAbbr: 'Lethality',
    description: '',
    icon: 'i-lol-armor-pen',
    color: 'var(--color-apen)',
  },
  {
    id: 'lifesteal',
    name: 'Lifesteal',
    abbr: 'LS',
    longAbbr: 'Lifesteal',
    description: '',
    icon: 'i-lol-ls',
    color: 'var(--color-domination)',
  },
  {
    id: 'percentMagicPenetration',
    name: 'Magic Penetration',
    abbr: 'MPEN',
    longAbbr: 'Magic Pen',
    description: '',
    icon: 'i-lol-mpen',
    color: 'var(--color-master)',
  },
  {
    id: 'magicResistance',
    name: 'Magic Resist',
    abbr: 'MR',
    longAbbr: 'Magic Resist',
    description: '',
    icon: 'i-lol-mr',
    color: 'var(--color-mr)',
  },
  {
    id: 'mana',
    name: 'Mana',
    description: '',
    icon: 'i-lol-mana',
    color: 'var(--color-inspiration)',
  },
  {
    id: 'manaRegen',
    name: 'Mana Regen',
    abbr: 'MP/5',
    longAbbr: 'Mana Regen',
    description: '',
    icon: 'i-lol-mana-regen',
    color: 'var(--color-inspiration)',
  },
  {
    id: 'percentMovespeed',
    name: 'Movespeed',
    abbr: 'MS',
    longAbbr: 'Movespeed',
    description: '',
    icon: 'i-lol-ms',
    color: 'var(--color-white-70)',
  },
  {
    id: 'omnivamp',
    name: 'Omnivamp',
    abbr: 'Vamp',
    longAbbr: 'Omnivamp',
    description: '',
    icon: 'i-lol-vamp',
    color: 'var(--color-onhit)',
  },
  {
    id: 'tenacity',
    name: 'Tenacity',
    description: '',
    icon: 'i-lol-tenacity',
    color: 'var(--color-platinum)',
  },

  {
    id: 'attackSpeedRatio',
    name: 'Attack Speed Ratio',
    abbr: 'AS Ratio',
    description: '',
  },
  {
    name: 'Range',
    id: 'attackRange',
    icon: 'i-lol-range',
    color: 'var(--color-white-70)',
    description: 'Range of the champion\'s basic attack.'
  },
  {
    name: 'Movespeed',
    icon: 'i-lol-ms',
    id: 'movespeed',
    abbr: 'MS',
    longAbbr: 'Movespeed',
    description: '',
    color: 'var(--color-white-70)',
  },
  {
    id: 'acquisitionRadius',
    name: 'Acquisition Radius',
    icon: 'i-lol-acquisition-radius',
    abbr: 'Acq. Radius',
    description: 'The range at which a unit acquires basic attack targets when a target unit is not specified by the player.'
  },
  {
    id: 'selectionRadius',
    icon: 'i-lol-range-center',
    name: 'Selection Radius',
    abbr: 'Select Radius',
    description: 'The farthest selectable point from the unit\'s center point.',
  },
  {
    id: 'pathingRadius',
    name: 'Pathing Radius',
    icon: 'i-lol-pathing',
    abbr: 'Path Radius',
    description: 'The gameplay area a unit occupies for unit-collision and pathfinding logic.',
  },
  {
    id: 'gameplayRadius',
    icon: 'i-lol-radius',
    name: 'Gameplay Radius',
    abbr: 'Game Radius',
    description: 'Determines reach of both incoming and outgoing effects.',
  },
  {
    id: 'criticalStrikeDamageModifier',
    name: 'Critical Strike Damage Modifier',
    abbr: 'Crit Dmg Mod',
    description: '',
  },
  {
    id: 'attackDelayOffset',
    name: 'Attack Delay Offset',
    abbr: 'Atk. Delay',
    description: '',
  },
  {
    id: 'attackCastTime',
    name: 'Attack Cast Time',
    abbr: 'Atk. Cast',
    description: '',
  },
  {
    id: 'attackTotalTime',
    name: 'Attack Total Time',
    abbr: 'Atk. Total',
    description: '',
  },
]
