export const statTotalGold = [
  {
    id: 'total',
    name: 'Total Gold Cost',
    abbr: 'Total',
    description: '',
    icon: 'i-lol-',
  },
]
export const statIndex: Record<string, StatIndex> = {
  abilityHaste: {
    id: 'abilityHaste',
    name: 'Ability Haste',
    abbr: 'AH',
    color: 'var(--color-ah)',
    description: '',
    icon: 'i-lol-ah',
  },
  abilityPower: {
    id: 'abilityPower',
    name: 'Ability Power',
    abbr: 'AP',
    color: 'var(--color-sorcery)',
    description: '',
    icon: 'i-lol-ap',
  },
  acquisitionRadius: {
    id: 'acquisitionRadius',
    name: 'Acquisition Radius',
    abbr: 'Acqusition',
    description: 'The range at which a unit acquires basic attack targets when a target unit is not specified by the player.',
    icon: 'i-lol-acquisition-radius'
  },
  armor: {
    id: 'armor',
    name: 'Armor',
    color: 'var(--color-iron)',
    description: '',
    icon: 'i-lol-armor',
  },
  armorPenetration: {
    id: 'armorPenetration',
    name: 'Armor Penetration',
    abbr: 'APEN',
    color: 'var(--color-apen)',
    description: '',
    icon: 'i-lol-armor-pen',
    longAbbr: 'Armor Pen.',
  },
  attackCastTime: {
    id: 'attackCastTime',
    name: 'Attack Cast Time',
    abbr: 'Cast Time',
    description: '',
  },
  attackDamage: {
    id: 'attackDamage',
    name: 'Attack Damage',
    abbr: 'AD',
    color: 'var(--color-ad)',
    description: '',
    icon: 'i-lol-ad',
  },
  attackDelayOffset: {
    id: 'attackDelayOffset',
    name: 'Attack Delay Offset',
    abbr: 'Delay Offset',
    description: '',
  },
  attackRange: {
    id: 'attackRange',
    name: 'Range',
    color: 'var(--color-white-70)',
    description: 'Range of the champion\'s basic attack.',
    icon: 'i-lol-range',
  },
  attackSpeed: {
    id: 'attackSpeed',
    name: 'Attack Speed',
    abbr: 'AS',
    color: 'var(--color-as)',
    description: '',
    icon: 'i-lol-as',
    longAbbr: 'Bonus AS',
  },
  attackSpeedRatio: {
    id: 'attackSpeedRatio',
    name: 'Attack Speed Ratio',
    abbr: 'AS Ratio',
    description: '',
  },
  attackTotalTime: {
    id: 'attackTotalTime',
    name: 'Attack Total Time',
    abbr: 'Total Time',
    description: '',
  },
  criticalStrikeChance: {
    id: 'criticalStrikeChance',
    name: 'Critical Chance',
    abbr: 'Crit',
    color: 'var(--color-domination)',
    description: '',
    icon: 'i-lol-cs',
    longAbbr: 'Crit Chance',
  },
  criticalStrikeDamage: {
    id: 'criticalStrikeDamage',
    name: 'Critical Damage',
    abbr: 'Crit Dmg',
    color: 'var(--color-precision)',
    description: '',
    icon: 'i-lol-crit-dmg',
  },
  criticalStrikeDamageModifier: {
    id: 'criticalStrikeDamageModifier',
    name: 'Critical Strike Damage Modifier',
    abbr: 'Crit Modifier',
    description: '',
    icon: 'i-lol-cs',
  },
  flatMagicPenetration: {
    id: 'flatMagicPenetration',
    name: 'Flat Magic Penetration',
    abbr: 'MPEN',
    color: 'var(--color-master)',
    description: '',
    icon: 'i-lol-mpen',
    longAbbr: 'Magic Pen.',
  },
  flatMovespeed: {
    id: 'flatMovespeed',
    name: 'Base Movespeed',
    abbr: 'MS',
    color: 'var(--color-white-70)',
    description: '',
    icon: 'i-lol-ms',
    longAbbr: 'Movespeed',
  },
  gameplayRadius: {
    id: 'gameplayRadius',
    name: 'Gameplay Radius',
    abbr: 'Gameplay',
    description: 'Determines reach of both incoming and outgoing effects.',
    icon: 'i-lol-radius',
  },
  goldPer10: {
    id: 'goldPer10',
    name: 'Gold / 10',
    abbr: 'GP/10',
    color: 'var(--color-g)',
    description: '',
    icon: 'i-lol-gold',
    longAbbr: '',
  },
  healAndShieldPower: {
    id: 'healAndShieldPower',
    name: 'Heal & Shield Power',
    abbr: 'HSP',
    color: 'var(--color-enchanter)',
    description: '',
    icon: 'i-lol-hsp',
  },
  health: {
    id: 'health',
    name: 'Health',
    abbr: 'HP',
    color: 'var(--color-resolve)',
    description: '',
    icon: 'i-lol-health',
    longAbbr: 'Health',
  },
  healthRegen: {
    id: 'healthRegen',
    name: 'Health Regen',
    abbr: 'HP/5',
    color: 'var(--color-resolve)',
    description: '',
    icon: 'i-lol-hp',
    longAbbr: 'HP ∕ 5',
  },
  lethality: {
    id: 'lethality',
    name: 'Lethality',
    abbr: 'LTY',
    color: 'var(--color-apen)',
    description: '',
    icon: 'i-lol-armor-pen',
    longAbbr: 'Lethality',
  },
  lifesteal: {
    id: 'lifesteal',
    name: 'Lifesteal',
    abbr: 'LS',
    color: 'var(--color-domination)',
    description: '',
    icon: 'i-lol-ls',
    longAbbr: 'Lifesteal',
  },
  magicResistance: {
    id: 'magicResistance',
    name: 'Magic Resist',
    abbr: 'MR',
    color: 'var(--color-mr)',
    description: '',
    icon: 'i-lol-mr',
  },
  mana: {
    id: 'mana',
    name: 'Mana',
    color: 'var(--color-inspiration)',
    description: '',
    icon: 'i-lol-mana',
  },
  manaRegen: {
    id: 'manaRegen',
    name: 'Mana Regen',
    abbr: 'MP ∕ 5',
    color: 'var(--color-inspiration)',
    description: '',
    icon: 'i-lol-mana-regen',
    longAbbr: 'Mana ∕ 5',
  },
  movespeed: {
    id: 'movespeed',
    name: 'Movespeed',
    abbr: 'MS',
    color: 'var(--color-white-70)',
    description: '',
    icon: 'i-lol-ms',
    longAbbr: 'Movespeed',
  },
  omnivamp: {
    id: 'omnivamp',
    name: 'Omnivamp',
    abbr: 'Vamp',
    color: 'var(--color-onhit)',
    description: '',
    icon: 'i-lol-vamp',
    longAbbr: 'Omnivamp',
  },
  pathingRadius: {
    id: 'pathingRadius',
    name: 'Pathing Radius',
    abbr: 'Pathing',
    description: 'The gameplay area a unit occupies for unit-collision and pathfinding logic.',
    icon: 'i-lol-pathing',
  },
  percentMagicPenetration: {
    id: 'percentMagicPenetration',
    name: 'Magic Penetration',
    abbr: 'MPEN',
    color: 'var(--color-master)',
    description: '',
    icon: 'i-lol-mpen',
    longAbbr: 'Magic Pen',
  },
  percentMovespeed: {
    id: 'percentMovespeed',
    name: 'Movespeed',
    abbr: 'MS',
    color: 'var(--color-white-70)',
    description: '',
    icon: 'i-lol-ms',
  },
  selectionRadius: {
    id: 'selectionRadius',
    name: 'Selection Radius',
    abbr: 'Selection',
    description: 'The farthest selectable point from the unit\'s center point.',
    icon: 'i-lol-range-center',
  },
  tenacity: {
    id: 'tenacity',
    name: 'Tenacity',
    color: 'var(--color-platinum)',
    description: '',
    icon: 'i-lol-tenacity',
  },
}
