export default defineNuxtRouteMiddleware((to, from) => {
  const cs = useChampStore()
  const ts = useTempStore()
  const is = useItemStore()
  cs.champSearch = ''
  cs.champClassFilters = []
  cs.sortChampsAZ = ''
  cs.filterChampionClass = []
  cs.filterChampionTypes = null
  cs.filterFavoriteChamps = false
  is.sortItemsAZ = 0
  is.sortPrice = 0
  ts.catFilters = []
  ts.statFilters = []
  ts.viewFavoriteItems = false
  is.selectedItemSet = null
  is.pItemFilter.rank = ''
  is.pItemFilter.stats = []
  is.pItemFilter.tags = ''
})
