export const statTotalGold = [
  {
    id: 'total',
    displayName: 'Total Gold Cost',
    shortName: 'Total',
    icon: '',
    class: '',
    badge: '',
  },
]
export const itemStats = [
  {
    id: 'abilityHaste',
    displayName: 'Ability Haste',
    shortName: 'AH',
    icon: 'ah',
    class: '',
    color: '**:text-platinum',
    badge: 'bg-ah  **:!text-white  text-white',
  },
  {
    id: 'abilityPower',
    displayName: 'Ability Power',
    shortName: 'AP',
    icon: 'ap',
    class: '',
    color: '**:text-diamond',
    badge: 'bg-ap text-white  **:!text-white ',
  },
  {
    id: 'armor',
    displayName: 'Armor',
    shortName: 'ARMOR',
    icon: 'armor',
    class: '',
    color: '**:text-precision',
    badge: 'bg-armor  **:!text-white  !text-bc',
  },
  {
    id: 'armorPenetration',
    displayName: 'Armor Penetration',
    shortName: 'APEN',
    icon: 'armor-pen',
    class: '',
    color: '**:text-fighter',
    badge: 'bg-apen text-white  **:!text-white ',
  },
  {
    id: 'attackDamage',
    displayName: 'Attack Damage',
    shortName: 'AD',
    icon: 'ad',
    class: '',
    color: '**:text-fighter',
    badge: 'bg-ad text-white  **:!text-white ',
  },
  {
    id: 'attackSpeed',
    displayName: 'Attack Speed',
    shortName: 'AS',
    icon: 'as',
    class: '',
    color: '**:text-precision',
    badge: 'bg-as **:!text-white   !text-white',
  },
  {
    id: 'flatMovespeed',
    displayName: 'Base Movespeed',
    shortName: 'MS',
    icon: 'ms',
    class: '',
    color: '**:text-platinum',
    badge: 'bg-black-50  **:!text-white  text-white',
  },
  {
    id: 'criticalStrikeChance',
    displayName: 'Critical Chance',
    shortName: 'CRIT',
    icon: 'cs',
    class: '',
    color: '**:text-domination',
    badge: 'bg-domination  **:!text-white text-white',
  },
  {
    id: 'criticalStrikeDamage',
    displayName: 'Critical Damage',
    shortName: 'CRIT DMG',
    icon: 'crit-dmg',
    class: '',
    color: '**:text-domination',
    badge: 'bg-precision/60 **:!text-white text-white',
  },
  {
    id: 'flatMagicPenetration',
    displayName: 'Flat Magic Penetration',
    shortName: 'MPEN',
    icon: 'mpen',
    iconClass: '',
    class: '',
    color: '**:text-diamond',
    badge: 'bg-master **:!text-white  text-white',
  },
  {
    id: 'goldPer10',
    displayName: 'Gold / 10',
    shortName: 'GP/10',
    icon: 'gold',
    class: '',
    color: '**:text-precision',
    badge: 'bg-g  **:!text-white  !text-bc',
  },
  {
    id: 'healAndShieldPower',
    displayName: 'Heal & Shield Power',
    shortName: 'HSP',
    icon: 'hsp',
    class: '',
    color: '**:text-platinum',
    badge: 'bg-hsp  **:!text-white text-white',
  },
  {
    id: 'health',
    displayName: 'Health',
    shortName: 'HP',
    icon: 'health',
    class: '',
    color: '**:text-emerald',
    badge: 'bg-hp  **:!text-white text-white',
  },
  {
    id: 'healthRegen',
    displayName: 'Health Regen / 5',
    shortName: 'HP/5',
    icon: 'hp',
    class: '',
    color: '**:text-emerald',
    badge: 'bg-hp **:!text-white  text-white',
  },
  {
    id: 'lethality',
    displayName: 'Lethality',
    shortName: 'LTY',
    icon: 'armor-pen',
    class: '',
    color: '**:text-domination',
    badge: 'bg-apen **:!text-white  text-white',
  },
  {
    id: 'lifesteal',
    displayName: 'Lifesteal',
    shortName: 'LS',
    icon: 'ls',
    class: '',
    color: '**:text-domination',
    badge: 'bg-domination **:!text-white  text-white',
  },
  {
    id: 'percentMagicPenetration',
    displayName: 'Magic Penetration',
    shortName: 'MPEN',
    icon: 'mpen',
    class: '',
    color: '**:text-diamond',
    badge: 'bg-master  **:!text-white text-white',
  },
  {
    id: 'magicResistance',
    displayName: 'Magic Resist',
    shortName: 'MR',
    icon: 'mr',
    class: '',
    color: '**:text-diamond',
    badge: 'bg-mr **:!text-white text-white',
  },
  {
    id: 'mana',
    displayName: 'Mana',
    shortName: 'MANA',
    icon: 'mana',
    class: '',
    color: '**:text-platinum',
    badge: 'bg-mana **:!text-white   text-white',
  },
  {
    id: 'manaRegen',
    displayName: 'Mana Regen / 5',
    shortName: 'MP/5',
    icon: 'mana-regen',
    class: '',
    color: '**:text-platinum',
    badge: 'bg-mana **:!text-white  text-white',
  },
  {
    id: 'percentMovespeed',
    displayName: 'Movespeed',
    shortName: 'MS',
    icon: 'ms',
    class: '',
    color: '**:text-platinum',
    badge: 'bg-black-50 **:!text-white !text-white',
  },
  {
    id: 'omnivamp',
    displayName: 'Omnivamp',
    shortName: 'VAMP',
    icon: 'vamp',
    class: '',
    color: '**:text-platinum',
    badge: 'bg-onhit **:!text-white  text-white',
  },
  {
    id: 'tenacity',
    displayName: 'Tenacity',
    shortName: 'TENACITY',
    icon: 'tenacity',
    class: '',
    color: '**:text-platinum',
    badge: 'bg-platinum/60 **:!text-white  text-white',
  },
]


export const itemStatsMin = [
  {
    ids: 'abilityHaste',
    name: 'Ability Haste',
        icon: 'i-stats-ah',
    class: '',
      },
  {
    ids: 'abilityPower',
    name: 'Ability Power',
        icon: 'i-stats-ap',
    class: '',
      },
  {
    ids: 'armor',
    name: 'Armor',
        icon: 'i-stats-armor',
    class: '',
      },
  {
    ids: ['armorPenetration', 'lethality'],
    name: 'Armor Pen + Lethality',
        icon: 'i-stats-armor-pen',
    class: '',
      },
  {
    ids: 'attackDamage',
    name: 'Attack Damage',
        icon: 'i-stats-ad',
    class: '',
      },
  {
    ids: 'attackSpeed',
    name: 'Attack Speed',
        icon: 'i-stats-as',
    class: '',
      },
  {
    ids: ['flatMovespeed', 'percentMovespeed'],
    name: 'Movespeed',
        icon: 'i-stats-ms',
    class: '',
      },
  {
    ids: ['criticalStrikeChance', 'criticalStrikeDamage'],
    name: 'Crit Chance + Dmg',
        icon: 'i-stats-cs',
    class: '',
      },
  {
    ids: ['flatMagicPenetration', 'percentMagicPenetration'],
    name: 'Magic Penetration',
        icon: 'i-stats-mpen',
    iconClass: '',
    class: '',
      },
  {
    ids: 'healAndShieldPower',
    name: 'Heal & Shield Power',
        icon: 'i-stats-hsp',
    class: '',
      },
  {
    ids: 'health',
    name: 'Health',
        icon: 'i-stats-health',
    class: '',
      },
  {
    ids: 'healthRegen',
    name: 'Health Regen',
        icon: 'i-stats-hp',
    class: '!size-5.25',
      },
  {
    ids: 'lifesteal',
    name: 'Lifesteal',
        icon: 'i-stats-ls',
    class: '!size-5',
      },
  {
    ids: 'magicResistance',
    name: 'Magic Resist',
        icon: 'i-stats-mr',
    class: '',
      },
  {
    ids: 'mana',
    name: 'Mana',
        icon: 'i-stats-mana',
    class: '',
      },
  {
    ids: 'manaRegen',
    name: 'Mana Regen',
        icon: 'i-stats-mana-regen',
    class: '!size-5.25',
      }
]