const quotes = [
    "Braum! What are you doing over there?! Are you drunk?",
    "So, Braum. No shirt, huh? And I don't have pants. Yay, Freljord.",
    "A Crownguard and a mage? Wouldn't want to be her.",
    "Sylas? He hasn't changed. And my answer is still no.",
    "It's good to see Taric hasn't changed. And bad. It's both.",
    "Stay positive.",
    "Kat and Garen sitting in a tree~ And you better just be holding hands or I'm telling!",
    "I'm sure your wife forgives you for getting her soul taken by a remorseless creature of darkness!",
    "Ok.",
    "The darker the night, the brighter the stars",
    "I envy silence, for I must be loud!",
    "I fought a house once. I\'m pretty sure I won.",
    "Only two jokers in the deck and I get dealt you.",
    "Beauty fades. That is why it is beautiful.",
    "When I look to the mountain's peak, in my mind, I have already fallen. And so, I climb.",
    "Just leave everything to me. As usual.",
    "I'm used to this level of disappointment.",
    "I'm not your enemy, I am THE ENEMY",
    "You can sit on a throne, that doesn't make you a ruler. It only means you have an arse.",
    "THE DAYLIGHT, IT BURNS",
    "The only drinking problem I have is when I spill it",
    "Time flies like an arrow, fruit flies like banana ",
    "Put it on my tab, the names \'Pantheon\',with a P...\" -Aurelion Sol"
]