// Updated Patch 15.24.1 - 12/26/2025 07:04:14 PM CST

const ability: Ability = {
  key: 'P',
  name: 'Unseen Predator',
  affects: 'Self',
  blurb: 'Innate:  Rengar generates Ferocity when he casts a basic ability or uses  Savagery\'s empowered attack, which expires after a period out of combat. At max Ferocity, his next basic ability consumes them to become empowered with an additional effect, gain an extra cast, and briefly grant him  bonus movement speed.',
  effects: [
    {
      description: '<p class="ability-effect"><span class="ability-header">Innate:</span> Rengar generates 1 Ferocity upon casting a basic ability or using Savagery\'s first attack. At 4 Ferocity, his next basic ability consumes them all to become empowered with an additional effect and grant him an additional cast along with 30% / 40% / 50% (based on level) bonus movement speed for 1.5 seconds. All Ferocity is lost after 10 seconds of not dealing or taking damage, excluding damage dealt by persistent or proc effects.Reaching 4 Ferocity with Savagery or Bola Strike locks the empowered version of the ability from being cast for 0.1 seconds. Similarly, consuming all Ferocity with an empowered ability locks the unempowered version of the ability from being cast for 0.1 seconds if it is not already on cooldown, increased to 0.25 seconds for Battle Roar.</p>'
    },
    {
      description: '<p class="ability-effect"><span class="ability-header">Innate:</span> While in brush, Rengar gains Unseen Predator, which lingers for 0.35 seconds upon exiting brush. Unseen Predator is lost immediately if Rengar exits the brush using Flash or Hexflash.</p>'
    },
    {
      description: '<p class="ability-effect"><span class="ability-header">Unseen Predator:</span> Rengar\'s basic attacks have massively increased range and cause him to leap to the target\'s location, attacking the target upon arrival and landing closer than his normal melee range. At the start of the leap, Unseen Predator will generate 1 Ferocity if none of his current Ferocity was generated this way. Ferocity generated by Unseen Predator has a distinct color. Rengar can cast any of his abilities during the dash.</p>'
    },
    {
      description: '<p class="ability-effect"><span class="ability-header">Innate - Bonetooth Necklace:</span> Scoring a takedown against an enemy champion within 3 seconds of damaging them grants Rengar a Trophy, once per unique champion and up to 5. An additional Trophy is made available through the event The Hunt is On! with the Head of Kha\'Zix. Trophies grant bonus attack damage equal to 1% - 36% (based on Trophies) bonus AD.</p>'
    }
  ],
  icon: 'https://cdn.communitydragon.org/latest/champion/Rengar/ability-icon/p',
  notes: 'Rengar will not leap to targets already in his normal  basic attack range.\nWhile  grounded or  rooted, Rengar loses the enhanced  attack range from Unseen Predator.\nRengar will only leap to a target if his basic attack timer has been refreshed (if not so he will not automatically attempt to path towards his target, despite them being within leap range).\nOnly  Flash and  Hexflash instantly end Unseen Predator. Other effects (i.e  Teleport) will still cause the buff to linger upon leaving  brush.\nRengar can freely use any  abilities, summoner spells, or item actives while leaping.\nUsing a  dash or  blink ability will interrupt the leap.\nThe attack from the leap will:\nNot go off if the dash was interrupted.\nGo off at the end of the dash even if its normal destination is obstructed by boundaries he cannot cross (e.g. terrain,  The Hextech Ultimatum).\nGo off regardless of distance the enemy travels away from Rengar\'s original location.\nGo off even if Rengar loses  sight of the target.\nGo off but have no effect if the target dies or becomes  untargetable.\nWhen the attack goes off,  Savagery\'s empowered attack is consumed.\n Rapid Firecannon\'s and  Savagery\'s bonus ranges are lost after 0.25 seconds upon gaining Unseen Predator, and are re-gained after 0.25 seconds upon losing Unseen Predator.\nRengar has a resource bar that indicates how much Ferocity he currently has.\nBonetooth Necklace uses different icons corresponding to the number of stacks acquired:\n1 Stack: \n2 Stacks: \n3 Stacks: \n4 Stacks: \n5 Stacks: \n6th Stack:  Head of Kha\'Zix',
  speed: '1450',
  targeting: 'Passive',
  targetRange: '50'
}
export default ability
