export { default as TagsInput } from '/base/tags-input/TagsInput.vue'
export { default as TagsInputInput } from '/base/tags-input/TagsInputInput.vue'
export { default as TagsInputItem } from '/base/tags-input/TagsInputItem.vue'
export { default as TagsInputItemDelete } from '/base/tags-input/TagsInputItemDelete.vue'
export { default as TagsInputItemText } from '~/base/tags-input/TagsInputItemText.vue'
