const colors = [
  {
    champs: [
      'Aatrox',
      'Annie',
      'Darius',
      'Briar',
      'Katarina',
      'Jayce',
      'Leblanc',
      'MissFortune',
      'Mel',
      'LeeSin',
      'Ornn',
      'Naafiri',
      'Rakan',
      'Shaco',
      'Sett',
      'Sion',
      'Shyvana',
      'Swain',
      'Taliyah',
      'Tristana',
      'Vladimir',
      'TwistedFate',
      'Xayah',
      'MonkeyKing',
      'Yone',
      'Zed',
      'Ziggs',
      'Zyra',
      'Viktor',
    ],
    color: '--color-domination',
    text: '*:[&.ability-header]:text-domination',
  },
  {
    champs: [
      'Alistar',
      'Aphelios',
      'Belveth',
      'Caitlyn',
      'DrMundo',
      'Diana',
      'Evelynn',
      'Jax',
      'Kaisa',
      'Kennen',
      'Khazix',
      'Kassadin',
      'Lulu',
      'Malzahar',
      'Morgana',
      'Neeko',
      'RekSai',
      'Syndra',
      'Soraka',
      'Veigar',
      'Velkoz',
      'Vex',
      'Yuumi',
    ],
    color: '--color-sorcery',
    text: '*:[&.ability-header]:text-',
  },
  {
    champs: [
      'Ahri',
      'Ashe',
      'AurelionSol',
      'Anivia',
      'Ezreal',
      'Gwen',
      'Jinx',
      'Lissandra',
      'Maokai',
      'Nocturne',
      'Nunu',
      'Ryze',
      'Sejuani',
      'Talon',
      'Taric',
      'Sylas',
      'Sona',
      'Trundle',
      'Tryndamere',
      'Volibear',
      'Xerath',
      'Udyr',
      'Skarner',
      'Shen',
      'Janna',
    ],
    color: '--color-mana',
    text: '*:[&.ability-header]:text-mana',
  },
  {
    champs: [
      'Ekko',
      'Hecarim',
      'Karma',
      'Kalista',
      'Nami',
      'Mordekaiser',
      'Thresh',
      'Zilean',
      'Yorick',
      'Viego',
    ],
    color: '--color-ah',
    text: '*:[&.ability-header]:text-',
  },
  {
    champs: ['Akali', 'Singed', 'Twitch', 'Urgot', 'Warwick', 'Zac', 'Zeri'],
    color: '--color-hp',
    text: '*:[&.ability-header]:text-',
  },
  {
    champs: [
      'Akshan',
      'Bard',
      'Blitzcrank',
      'Azir',
      'Corki',
      'Camille',
      'Cassiopeia',
      'Garen',
      'Gangplank',
      'Graves',
      'Illaoi',
      'Jhin',
      'KSante',
      'JarvanIV',
      'Kayle',
      'Leona',
      'Lux',
      'MasterYi',
      'Nasus',
      'Olaf',
      'Nautilus',
      'Orianna',
      'Nilah',
      'Nidalee',
      'Qiyana',
      'Poppy',
      'Pantheon',
      'Rammus',
      'Rell',
      'Riven',
      'Rengar',
      'Renekton',
      'Samira',
      'Senna',
      'Sett',
      'Sivir',
      'Udyr',
      'XinZhao',
      'Xayah',
      'MonkeyKing',
    ],
    color: '--color-as',
    text: '*:[&.ability-header]:text-',
  },
  {
    champs: ['Brand', 'Milio', 'Nautilus'],
    color: '--color-ad',
    text: '*:[&.ability-header]:text-',
  },
  {
    champs: ['Irelia', 'Neeko', 'Seraphine', 'Vi'],
    color: '---color-onhit',
    text: '*:[&.ability-header]:text-',
  },
]

export function getColorByChampionKey(name?: string): string | undefined {
  if (!name)
    return undefined

  const entry = colors.find(group => group.champs.includes(name))
  return entry?.text
}
