// Updated Patch 15.24.1 - 12/26/2025 07:04:15 PM CST

export const abilityIdToName: Record<string, string> = {
  '1E': 'Molten Shield',
  '1P': 'Pyromania',
  '1Q': 'Disintegrate',
  '1R': 'Summon: Tibbers',
  '1W': 'Incinerate',
  '2E': 'Reckless Swing',
  '2P': 'Berserker Rage',
  '2Q': 'Undertow',
  '2R': 'Ragnarok',
  '2W': 'Tough It Out',
  '3E': 'Justice Punch',
  '3P': 'Colossal Smash',
  '3Q': 'Winds of War',
  '3R': 'Hero\'s Entrance',
  '3W': 'Shield of Durand',
  '4E': 'Stacked Deck',
  '4P': 'Loaded Dice',
  '4Q': 'Wild Cards',
  '4R': 'Destiny',
  '4W': 'Pick a Card',
  '5E': 'Audacious Charge',
  '5P': 'Determination',
  '5Q': 'Three Talon Strike',
  '5R': 'Crescent Guard',
  '5W': 'Wind Becomes Lightning',
  '6E': 'Disdain',
  '6P': 'Echoing Flames',
  '6Q': 'Corrosive Charge',
  '6R': 'Fear Beyond Death',
  '6W': 'Purge',
  '7E': 'Ethereal Chains',
  '7P': 'Mirror Image',
  '7Q': 'Sigil of Malice',
  '7R': 'Mimic',
  '7W': 'Distortion',
  '8E': 'Tides of Blood',
  '8P': 'Crimson Pact',
  '8Q': 'Transfusion',
  '8R': 'Hemoplague',
  '8W': 'Sanguine Pool',
  '9E': 'Reap',
  '9P': 'A Harmless Scarecrow',
  '9Q': 'Terrify',
  '9R': 'Crowstorm',
  '9W': 'Bountiful Harvest',
  '10E': 'Starfire Spellblade',
  '10P': 'Divine Ascent',
  '10Q': 'Radiant Blast',
  '10R': 'Divine Judgment',
  '10W': 'Celestial Blessing',
  '11E': 'Wuju Style',
  '11P': 'Double Strike',
  '11Q': 'Alpha Strike',
  '11R': 'Highlander',
  '11W': 'Meditate',
  '12E': 'Trample',
  '12P': 'Triumphant Roar',
  '12Q': 'Pulverize',
  '12R': 'Unbreakable Will',
  '12W': 'Headbutt',
  '13E': 'Spell Flux',
  '13P': 'Arcane Mastery',
  '13Q': 'Overload',
  '13R': 'Realm Warp',
  '13W': 'Rune Prison',
  '14E': 'Roar of the Slayer',
  '14P': 'Death Surge',
  '14Q': 'Decimating Smash',
  '14R': 'Unstoppable Onslaught',
  '14W': 'Soul Furnace',
  '15E': 'Spell Shield',
  '15P': 'Fleet of Foot',
  '15Q': 'Boomerang Blade',
  '15R': 'On the Hunt',
  '15W': 'Ricochet',
  '16E': 'Equinox',
  '16P': 'Salvation',
  '16Q': 'Starcall',
  '16R': 'Wish',
  '16W': 'Astral Infusion',
  '17E': 'Toxic Shot',
  '17P': 'Guerrilla Warfare',
  '17Q': 'Blinding Dart',
  '17R': 'Noxious Trap',
  '17W': 'Move Quick',
  '18E': 'Explosive Charge',
  '18P': 'Draw a Bead',
  '18Q': 'Rapid Fire',
  '18R': 'Buster Shot',
  '18W': 'Rocket Jump',
  '19E': 'Primal Howl',
  '19P': 'Eternal Hunger',
  '19Q': 'Jaws of the Beast',
  '19R': 'Infinite Duress',
  '19W': 'Blood Hunt',
  '20E': 'Snowball Barrage',
  '20P': 'Call of the Freljord',
  '20Q': 'Consume',
  '20R': 'Absolute Zero',
  '20W': 'Biggest Snowball Ever!',
  '21E': 'Make It Rain',
  '21P': 'Love Tap',
  '21Q': 'Double Up',
  '21R': 'Bullet Time',
  '21W': 'Strut',
  '22E': 'Hawkshot',
  '22P': 'Frost Shot',
  '22Q': 'Ranger\'s Focus',
  '22R': 'Enchanted Crystal Arrow',
  '22W': 'Volley',
  '23E': 'Spinning Slash',
  '23P': 'Battle Fury',
  '23Q': 'Bloodlust',
  '23R': 'Undying Rage',
  '23W': 'Mocking Shout',
  '24E': 'Counter Strike',
  '24P': 'Relentless Assault',
  '24Q': 'Leap Strike',
  '24R': 'Grandmaster-at-Arms',
  '24W': 'Empower',
  '25E': 'Black Shield',
  '25P': 'Soul Siphon',
  '25Q': 'Dark Binding',
  '25R': 'Soul Shackles',
  '25W': 'Tormented Shadow',
  '26E': 'Time Warp',
  '26P': 'Time in a Bottle',
  '26Q': 'Time Bomb',
  '26R': 'Chronoshift',
  '26W': 'Rewind',
  '27E': 'Fling',
  '27P': 'Noxious Slipstream',
  '27Q': 'Poison Trail',
  '27R': 'Insanity Potion',
  '27W': 'Mega Adhesive',
  '28E': 'Empowered Whiplash',
  '28P': 'Demon Shade',
  '28Q': 'Hate Spike',
  '28R': 'Last Caress',
  '28W': 'Allure',
  '29E': 'Contaminate',
  '29P': 'Deadly Venom',
  '29Q': 'Ambush',
  '29R': 'Spray and Pray',
  '29W': 'Venom Cask',
  '30E': 'Defile',
  '30P': 'Death Defied',
  '30Q': 'Lay Waste',
  '30R': 'Requiem',
  '30W': 'Wall of Pain',
  '31E': 'Vorpal Spikes',
  '31P': 'Carnivore',
  '31Q': 'Rupture',
  '31R': 'Feast',
  '31W': 'Feral Scream',
  '32E': 'Tantrum',
  '32P': 'Cursed Touch',
  '32Q': 'Bandage Toss',
  '32R': 'Curse of the Sad Mummy',
  '32W': 'Despair',
  '33E': 'Frenzying Taunt',
  '33P': 'Spiked Shell',
  '33Q': 'Powerball',
  '33R': 'Soaring Slam',
  '33W': 'Defensive Ball Curl',
  '34E': 'Frostbite',
  '34P': 'Rebirth',
  '34Q': 'Flash Frost',
  '34R': 'Glacial Storm',
  '34W': 'Crystallize',
  '35E': 'Two-Shiv Poison',
  '35P': 'Backstab',
  '35Q': 'Deceive',
  '35R': 'Hallucinate',
  '35W': 'Jack in the Box',
  '36E': 'Blunt Force Trauma',
  '36P': 'Goes Where He Pleases',
  '36Q': 'Infected Bonesaw',
  '36R': 'Maximum Dosage',
  '36W': 'Heart Zapper',
  '37E': 'Song of Celerity',
  '37P': 'Power Chord',
  '37Q': 'Hymn of Valor',
  '37R': 'Crescendo',
  '37W': 'Aria of Perseverance',
  '38E': 'Force Pulse',
  '38P': 'Void Stone',
  '38Q': 'Null Sphere',
  '38R': 'Riftwalk',
  '38W': 'Nether Blade',
  '39E': 'Flawless Duet',
  '39P': 'Ionian Fervor',
  '39Q': 'Bladesurge',
  '39R': 'Vanguard\'s Edge',
  '39W': 'Defiant Dance',
  '40E': 'Eye of the Storm',
  '40P': 'Tailwind',
  '40Q': 'Howling Gale',
  '40R': 'Monsoon',
  '40W': 'Zephyr',
  '41E': 'Powder Keg',
  '41P': 'Trial by Fire',
  '41Q': 'Parrrley',
  '41R': 'Cannon Barrage',
  '41W': 'Remove Scurvy',
  '42E': 'Gatling Gun',
  '42P': 'Hextech Munitions',
  '42Q': 'Phosphorus Bomb',
  '42R': 'Missile Barrage',
  '42W': 'Valkyrie',
  '43E': 'Defiance',
  '43P': 'Gathering Fire',
  '43Q': 'Soulflare',
  '43R': 'Mantra',
  '43W': 'Renewal',
  '44E': 'Dazzle',
  '44P': 'Bravado',
  '44Q': 'Starlight\'s Touch',
  '44R': 'Cosmic Radiance',
  '44W': 'Bastion',
  '45E': 'Event Horizon',
  '45P': 'Phenomenal Evil Power',
  '45Q': 'Baleful Strike',
  '45R': 'Primordial Burst',
  '45W': 'Dark Matter',
  '48E': 'Pillar of Ice',
  '48P': 'King\'s Tribute',
  '48Q': 'Chomp',
  '48R': 'Subjugate',
  '48W': 'Frozen Domain',
  '50E': 'Nevermove',
  '50P': 'Ravenous Flock',
  '50Q': 'Death\'s Hand',
  '50R': 'Demonflare',
  '50W': 'Vision of Empire',
  '51E': '90 Caliber Net',
  '51P': 'Headshot',
  '51Q': 'Piltover Peacemaker',
  '51R': 'Ace in the Hole',
  '51W': 'Yordle Snap Trap',
  '53E': 'Power Fist',
  '53P': 'Mana Barrier',
  '53Q': 'Rocket Grab',
  '53R': 'Static Field',
  '53W': 'Overdrive',
  '54E': 'Ground Slam',
  '54P': 'Granite Shield',
  '54Q': 'Seismic Shard',
  '54R': 'Unstoppable Force',
  '54W': 'Thunderclap',
  '55E': 'Shunpo',
  '55P': 'Voracity',
  '55Q': 'Bouncing Blade',
  '55R': 'Death Lotus',
  '55W': 'Preparation',
  '56E': 'Unspeakable Horror',
  '56P': 'Umbra Blades',
  '56Q': 'Duskbringer',
  '56R': 'Paranoia',
  '56W': 'Shroud of Darkness',
  '57E': 'Sapling Toss',
  '57P': 'Sap Magic',
  '57Q': 'Bramble Smash',
  '57R': 'Nature\'s Grasp',
  '57W': 'Twisted Advance',
  '58E': 'Slice and Dice',
  '58P': 'Reign of Anger',
  '58Q': 'Cull the Meek',
  '58R': 'Dominus',
  '58W': 'Ruthless Predator',
  '59E': 'Demacian Standard',
  '59P': 'Martial Cadence',
  '59Q': 'Dragon Strike',
  '59R': 'Cataclysm',
  '59W': 'Golden Aegis',
  '60E': 'Rappel',
  '60P': 'Spider Queen',
  '60Q': 'Venomous Bite',
  '60R': 'Spider Form / Human Form',
  '60W': 'Skittering Frenzy',
  '61E': 'Command: Protect',
  '61P': 'Clockwork Windup',
  '61Q': 'Command: Attack',
  '61R': 'Command: Shockwave',
  '61W': 'Command: Dissonance',
  '62E': 'Nimbus Strike',
  '62P': 'Stone Skin',
  '62Q': 'Crushing Blow',
  '62R': 'Cyclone',
  '62W': 'Warrior Trickster',
  '63E': 'Conflagration',
  '63P': 'Blaze',
  '63Q': 'Sear',
  '63R': 'Pyroclasm',
  '63W': 'Pillar of Flame',
  '64E': 'Cripple',
  '64P': 'Flurry',
  '64Q': 'Resonating Strike',
  '64R': 'Dragon\'s Rage',
  '64W': 'Iron Will',
  '67E': 'Condemn',
  '67P': 'Night Hunter',
  '67Q': 'Tumble',
  '67R': 'Final Hour',
  '67W': 'Silver Bolts',
  '68E': 'Electro Harpoon',
  '68P': 'Junkyard Titan',
  '68Q': 'Flamespitter',
  '68R': 'The Equalizer',
  '68W': 'Scrap Shield',
  '69E': 'Twin Fang',
  '69P': 'Serpentine Grace',
  '69Q': 'Noxious Blast',
  '69R': 'Petrifying Gaze',
  '69W': 'Miasma',
  '72E': 'Ixtal\'s Impact',
  '72P': 'Threads of Vibration',
  '72Q': 'Upheaval',
  '72R': 'Impale',
  '72W': 'Seismic Bastion',
  '74E': 'CH-3X Lightning Grenade',
  '74P': 'Hextech Affinity',
  '74Q': 'H-28Q Apex Turret',
  '74R': 'UPGRADE!!!',
  '74W': 'Hextech Rocket Swarm',
  '75E': 'Spirit Fire',
  '75P': 'Soul Eater',
  '75Q': 'Siphoning Strike',
  '75R': 'Fury of the Sands',
  '75W': 'Wither',
  '76E': 'Swipe',
  '76P': 'Prowl',
  '76Q': 'Takedown',
  '76R': 'Aspect of the Cougar',
  '76W': 'Pounce',
  '77E': 'Blazing Stampede',
  '77P': 'Bridge Between',
  '77Q': 'Wilding Claw',
  '77R': 'Wingborne Storm',
  '77W': 'Iron Mantle',
  '78E': 'Heroic Charge',
  '78P': 'Iron Ambassador',
  '78Q': 'Hammer Shock',
  '78R': 'Keeper\'s Verdict',
  '78W': 'Steadfast Presence',
  '79E': 'Body Slam',
  '79P': 'Happy Hour',
  '79Q': 'Barrel Roll',
  '79R': 'Explosive Cask',
  '79W': 'Drunken Rage',
  '80E': 'Aegis Assault',
  '80P': 'Mortal Will',
  '80Q': 'Comet Spear',
  '80R': 'Grand Starfall',
  '80W': 'Shield Vault',
  '81E': 'Arcane Shift',
  '81P': 'Rising Spell Force',
  '81Q': 'Mystic Shot',
  '81R': 'Trueshot Barrage',
  '81W': 'Essence Flux',
  '82E': 'Death\'s Grasp',
  '82P': 'Darkness Rise',
  '82Q': 'Obliterate',
  '82R': 'Realm of Death',
  '82W': 'Indestructible',
  '83E': 'Mourning Mist',
  '83P': 'Shepherd of Souls',
  '83Q': 'Awakening',
  '83R': 'Eulogy of the Isles',
  '83W': 'Dark Procession',
  '84E': 'Shuriken Flip',
  '84P': 'Assassin\'s Mark',
  '84Q': 'Five Point Strike',
  '84R': 'Perfect Execution',
  '84W': 'Twilight Shroud',
  '85E': 'Lightning Rush',
  '85P': 'Mark of the Storm',
  '85Q': 'Thundering Shuriken',
  '85R': 'Slicing Maelstrom',
  '85W': 'Electrical Surge',
  '86E': 'Judgment',
  '86P': 'Perseverance',
  '86Q': 'Decisive Strike',
  '86R': 'Demacian Justice',
  '86W': 'Courage',
  '89E': 'Zenith Blade',
  '89P': 'Sunlight',
  '89Q': 'Shield of Daybreak',
  '89R': 'Solar Flare',
  '89W': 'Eclipse',
  '90E': 'Malefic Visions',
  '90P': 'Void Shift',
  '90Q': 'Call of the Void',
  '90R': 'Nether Grasp',
  '90W': 'Void Swarm',
  '91E': 'Assassin\'s Path',
  '91P': 'Blade\'s End',
  '91Q': 'Noxian Diplomacy',
  '91R': 'Shadow Assault',
  '91W': 'Rake',
  '92E': 'Valor',
  '92P': 'Runic Blade',
  '92Q': 'Broken Wings',
  '92R': 'Wind Slash',
  '92W': 'Ki Burst',
  '96E': 'Void Ooze',
  '96P': 'Icathian Surprise',
  '96Q': 'Caustic Spittle',
  '96R': 'Living Artillery',
  '96W': 'Bio-Arcane Barrage',
  '98E': 'Shadow Dash',
  '98P': 'Ki Barrier',
  '98Q': 'Twilight Assault',
  '98R': 'Stand United',
  '98W': 'Spirit\'s Refuge',
  '99E': 'Lucent Singularity',
  '99P': 'Illumination',
  '99Q': 'Light Binding',
  '99R': 'Final Spark',
  '99W': 'Prismatic Barrier',
  '101E': 'Shocking Orb',
  '101P': 'Mana Surge',
  '101Q': 'Arcanopulse',
  '101R': 'Rite of the Arcane',
  '101W': 'Eye of Destruction',
  '102E': 'Flame Breath',
  '102P': 'Fury of the Dragonborn',
  '102Q': 'Twin Bite',
  '102R': 'Dragon\'s Descent',
  '102W': 'Burnout',
  '103E': 'Charm',
  '103P': 'Essence Theft',
  '103Q': 'Orb of Deception',
  '103R': 'Spirit Rush',
  '103W': 'Fox-Fire',
  '104E': 'Quickdraw',
  '104P': 'New Destiny',
  '104Q': 'End of the Line',
  '104R': 'Collateral Damage',
  '104W': 'Smoke Screen',
  '105E': 'Trickster',
  '105P': 'Nimble Fighter',
  '105Q': 'Urchin Strike',
  '105R': 'Chum the Waters',
  '105W': 'Seastone Trident',
  '106E': 'Sky Splitter',
  '106P': 'The Relentless Storm',
  '106Q': 'Thundering Smash',
  '106R': 'Stormbringer',
  '106W': 'Frenzied Maul',
  '107E': 'Bola Strike',
  '107P': 'Unseen Predator',
  '107Q': 'Savagery',
  '107R': 'Thrill of the Hunt',
  '107W': 'Battle Roar',
  '110E': 'Hail of Arrows',
  '110P': 'Living Vengeance',
  '110Q': 'Piercing Arrow',
  '110R': 'Chain of Corruption',
  '110W': 'Blighted Quiver',
  '111E': 'Riptide',
  '111P': 'Staggering Blow',
  '111Q': 'Dredge Line',
  '111R': 'Depth Charge',
  '111W': 'Titan\'s Wrath',
  '112E': 'Hextech Ray',
  '112P': 'Glorious Evolution',
  '112Q': 'Siphon Power',
  '112R': 'Arcane Storm',
  '112W': 'Gravity Field',
  '113E': 'Permafrost',
  '113P': 'Fury of the North',
  '113Q': 'Arctic Assault',
  '113R': 'Glacial Prison',
  '113W': 'Winter\'s Wrath',
  '114E': 'Bladework',
  '114P': 'Duelist\'s Dance',
  '114Q': 'Lunge',
  '114R': 'Grand Challenge',
  '114W': 'Riposte',
  '115E': 'Hexplosive Minefield',
  '115P': 'Short Fuse',
  '115Q': 'Bouncing Bomb',
  '115R': 'Mega Inferno Bomb',
  '115W': 'Satchel Charge',
  '117E': 'Help, Pix!',
  '117P': 'Pix, Faerie Companion',
  '117Q': 'Glitterlance',
  '117R': 'Wild Growth',
  '117W': 'Whimsy',
  '119E': 'Stand Aside',
  '119P': 'League of Draven',
  '119Q': 'Spinning Axe',
  '119R': 'Whirling Death',
  '119W': 'Blood Rush',
  '120E': 'Devastating Charge',
  '120P': 'Warpath',
  '120Q': 'Rampage',
  '120R': 'Onslaught of Shadows',
  '120W': 'Spirit of Dread',
  '121E': 'Evolved Wings',
  '121P': 'Unseen Threat',
  '121Q': 'Evolved Reaper Claws',
  '121R': 'Evolved Adaptive Cloaking',
  '121W': 'Evolved Spike Racks',
  '122E': 'Apprehend',
  '122P': 'Hemorrhage',
  '122Q': 'Decimate',
  '122R': 'Noxian Guillotine',
  '122W': 'Crippling Strike',
  '126E': 'Acceleration Gate',
  '126P': 'Hextech Capacitor',
  '126Q': 'Shock Blast',
  '126R': 'Transform Mercury Hammer',
  '126W': 'Hyper Charge',
  '127E': 'Glacial Path',
  '127P': 'Iceborn Subjugation',
  '127Q': 'Ice Shard',
  '127R': 'Frozen Tomb',
  '127W': 'Ring of Frost',
  '131E': 'Lunar Rush',
  '131P': 'Moonsilver Blade',
  '131Q': 'Crescent Strike',
  '131R': 'Moonfall',
  '131W': 'Pale Cascade',
  '133E': 'Vault',
  '133P': 'Harrier',
  '133Q': 'Blinding Assault',
  '133R': 'Skystrike',
  '133W': 'Heightened Senses',
  '134E': 'Scatter the Weak',
  '134P': 'Transcendent',
  '134Q': 'Dark Sphere',
  '134R': 'Unleashed Power',
  '134W': 'Force of Will',
  '136E': 'Singularity',
  '136P': 'Cosmic Creator',
  '136Q': 'Breath of Light',
  '136R': 'The Skies Descend',
  '136W': 'Astral Flight',
  '141E': 'Shadow Step',
  '141P': 'The Darkin Scythe',
  '141Q': 'Reaping Slash',
  '141R': 'Umbral Trespass',
  '141W': 'Blade\'s Reach',
  '142E': 'Sleepy Trouble Bubble',
  '142P': 'More Sparkles!',
  '142Q': 'Paddle Star!',
  '142R': 'Portal Jump',
  '142W': 'Spell Thief',
  '143E': 'Grasping Roots',
  '143P': 'Garden of Thorns',
  '143Q': 'Deadly Spines',
  '143R': 'Stranglethorns',
  '143W': 'Rampant Growth',
  '145E': 'Supercharge',
  '145P': 'Second Skin',
  '145Q': 'Icathian Rain',
  '145R': 'Killer Instinct',
  '145W': 'Void Seeker',
  '147E': 'Beat Drop',
  '147P': 'Stage Presence',
  '147Q': 'High Note',
  '147R': 'Encore',
  '147W': 'Surround Sound',
  '150E': 'Crunch',
  '150P': 'Rage Gene',
  '150Q': 'Boulder Toss',
  '150R': 'GNAR!',
  '150W': 'Wallop',
  '154E': 'Elastic Slingshot',
  '154P': 'Cell Division',
  '154Q': 'Stretching Strikes',
  '154R': 'Let\'s Bounce!',
  '154W': 'Unstable Matter',
  '157E': 'Sweeping Blade',
  '157P': 'Way of the Wanderer',
  '157Q': 'Steel Tempest',
  '157R': 'Last Breath',
  '157W': 'Wind Wall',
  '161E': 'Tectonic Disruption',
  '161P': 'Organic Deconstruction',
  '161Q': 'Plasma Fission',
  '161R': 'Life Form Disintegration Ray',
  '161W': 'Void Rift',
  '163E': 'Unraveled Earth',
  '163P': 'Rock Surfing',
  '163Q': 'Threaded Volley',
  '163R': 'Weaver\'s Wall',
  '163W': 'Seismic Shove',
  '164E': 'Wall Dive',
  '164P': 'Adaptive Defenses',
  '164Q': 'Precision Protocol',
  '164R': 'The Hextech Ultimatum',
  '164W': 'Tactical Sweep',
  '166E': 'Heroic Swing',
  '166P': 'Dirty Fighting',
  '166Q': 'Avengerang',
  '166R': 'Comeuppance',
  '166W': 'Going Rogue',
  '200E': 'Royal Maelstrom',
  '200P': 'Death in Lavender',
  '200Q': 'Void Surge',
  '200R': 'Endless Banquet',
  '200W': 'Above and Below',
  '201E': 'Unbreakable',
  '201P': 'Concussive Blows',
  '201Q': 'Winter\'s Bite',
  '201R': 'Glacial Fissure',
  '201W': 'Stand Behind Me',
  '202E': 'Captive Audience',
  '202P': 'Whisper',
  '202Q': 'Dancing Grenade',
  '202R': 'Curtain Call',
  '202W': 'Deadly Flourish',
  '203E': 'Mounting Dread',
  '203P': 'Mark of the Kindred',
  '203Q': 'Dance of Arrows',
  '203R': 'Lamb\'s Respite',
  '203W': 'Wolf\'s Frenzy',
  '221E': 'Spark Surge',
  '221P': 'Living Battery',
  '221Q': 'Burst Fire',
  '221R': 'Lightning Crash',
  '221W': 'Ultrashock Laser',
  '222E': 'Flame Chompers!',
  '222P': 'Get Excited!',
  '222Q': 'Switcheroo!',
  '222R': 'Super Mega Death Rocket!',
  '222W': 'Zap!',
  '223E': 'Thick Skin',
  '223P': 'An Acquired Taste',
  '223Q': 'Tongue Lash',
  '223R': 'Regurgitate',
  '223W': 'Abyssal Dive',
  '233E': 'Chilling Scream',
  '233P': 'Crimson Curse',
  '233Q': 'Head Rush',
  '233R': 'Certain Death',
  '233W': 'Snack Attack',
  '234E': 'Harrowed Path',
  '234P': 'Sovereign\'s Domination',
  '234Q': 'Blade of the Ruined King',
  '234R': 'Heartbreaker',
  '234W': 'Spectral Maw',
  '235E': 'Curse of the Black Mist',
  '235P': 'Absolution',
  '235Q': 'Piercing Darkness',
  '235R': 'Dawning Shadow',
  '235W': 'Last Embrace',
  '236E': 'Relentless Pursuit',
  '236P': 'Lightslinger',
  '236Q': 'Piercing Light',
  '236R': 'The Culling',
  '236W': 'Ardent Blaze',
  '238E': 'Shadow Slash',
  '238P': 'Contempt for the Weak',
  '238Q': 'Razor Shuriken',
  '238R': 'Death Mark',
  '238W': 'Living Shadow',
  '240E': 'Dismounted Jousting',
  '240P': 'Dismounted Skaarl the Cowardly Lizard',
  '240Q': 'Pocket Pistol',
  '240R': 'Dismounted Chaaaaaaaarge!!!',
  '240W': 'Violent Tendencies',
  '245E': 'Phase Dive',
  '245P': 'Z-Drive Resonance',
  '245Q': 'Timewinder',
  '245R': 'Chronobreak',
  '245W': 'Parallel Convergence',
  '246E': 'Audacity',
  '246P': 'Royal Privilege',
  '246Q': 'Elemental Wrath',
  '246R': 'Supreme Display of Talent',
  '246W': 'Terrashape',
  '254E': 'Relentless Force',
  '254P': 'Blast Shield',
  '254Q': 'Vault Breaker',
  '254R': 'Cease and Desist',
  '254W': 'Denting Blows',
  '266E': 'Umbral Dash',
  '266P': 'Deathbringer Stance',
  '266Q': 'The Darkin Blade',
  '266R': 'World Ender',
  '266W': 'Infernal Chains',
  '267E': 'Tidecaller\'s Blessing',
  '267P': 'Surging Tides',
  '267Q': 'Aqua Prison',
  '267R': 'Tidal Wave',
  '267W': 'Ebb and Flow',
  '268E': 'Shifting Sands',
  '268P': 'Shurima\'s Legacy',
  '268Q': 'Conquering Sands',
  '268R': 'Emperor\'s Divide',
  '268W': 'Arise!',
  '350E': 'Zoomies',
  '350P': 'Feline Friendship',
  '350Q': 'Prowling Projectile',
  '350R': 'Final Chapter',
  '350W': 'You and Me!',
  '360E': 'Wild Rush',
  '360P': 'Daredevil Impulse',
  '360Q': 'Flair',
  '360R': 'Inferno Trigger',
  '360W': 'Blade Whirl',
  '412E': 'Flay',
  '412P': 'Damnation',
  '412Q': 'Death Sentence',
  '412R': 'The Box',
  '412W': 'Dark Passage',
  '420E': 'Test of Spirit',
  '420P': 'Prophet of an Elder God',
  '420Q': 'Tentacle Smash',
  '420R': 'Leap of Faith',
  '420W': 'Harsh Lesson',
  '421E': 'Tunnel',
  '421P': 'Fury of the Xer\'Sai',
  '421Q': 'Prey Seeker',
  '421R': 'Void Rush',
  '421W': 'Unburrow',
  '427E': 'Triggerseed',
  '427P': 'Friend of the Forest',
  '427Q': 'Rootcaller',
  '427R': 'Daisy!',
  '427W': 'Brushmaker',
  '429E': 'Rend',
  '429P': 'Martial Poise',
  '429Q': 'Pierce',
  '429R': 'Fate\'s Call',
  '429W': 'Sentinel',
  '432E': 'Magical Journey',
  '432P': 'Traveler\'s Call',
  '432Q': 'Cosmic Binding',
  '432R': 'Tempered Fate',
  '432W': 'Caretaker\'s Shrine',
  '497E': 'Battle Dance',
  '497P': 'Fey Feathers',
  '497Q': 'Gleaming Quill',
  '497R': 'The Quickness',
  '497W': 'Grand Entrance',
  '498E': 'Bladecaller',
  '498P': 'Clean Cuts',
  '498Q': 'Double Daggers',
  '498R': 'Featherstorm',
  '498W': 'Deadly Plumage',
  '516E': 'Searing Charge',
  '516P': 'Living Forge',
  '516Q': 'Volcanic Rupture',
  '516R': 'Call of the Forge God',
  '516W': 'Bellows Breath',
  '517E': 'Abduct',
  '517P': 'Petricite Burst',
  '517Q': 'Chain Lash',
  '517R': 'Hijack',
  '517W': 'Kingslayer',
  '518E': 'Tangle-Barbs',
  '518P': 'Inherent Glamour',
  '518Q': 'Blooming Burst',
  '518R': 'Pop Blossom',
  '518W': 'Shapesplitter',
  '523E': 'Weapon Queue System',
  '523P': 'Crescendum',
  '523Q': 'Sentry',
  '523R': 'Moonlight Vigil',
  '523W': 'Phase',
  '526E': 'Full Tilt',
  '526P': 'Break the Mold',
  '526Q': 'Shattering Strike',
  '526R': 'Magnet Storm',
  '526W': 'Ferromancy: Mount Up',
  '555E': 'Phantom Undertow',
  '555P': 'Gift of the Drowned Ones',
  '555Q': 'Bone Skewer',
  '555R': 'Death from Below',
  '555W': 'Ghostwater Dive',
  '711E': 'Looming Darkness',
  '711P': 'Doom \'n Gloom',
  '711Q': 'Mistral Bolt',
  '711R': 'Shadow Surge',
  '711W': 'Personal Space',
  '777E': 'Soul Unbound',
  '777P': 'Way of the Hunter',
  '777Q': 'Mortal Steel',
  '777R': 'Fate Sealed',
  '777W': 'Spirit Cleave',
  '799E': 'Lacerate',
  '799P': 'Drakehound\'s Step',
  '799Q': 'Sundering Slam',
  '799R': 'Public Execution',
  '799W': 'Repudiation',
  '800E': 'Solar Snare',
  '800P': 'Searing Brilliance',
  '800Q': 'Radiant Volley',
  '800R': 'Golden Eclipse',
  '800W': 'Rebuttal',
  '804E': 'Untouchable Shadow',
  '804P': 'Vow of the First Lands',
  '804Q': 'Cultivation of Spirit',
  '804R': 'Transcend One\'s Self',
  '804W': 'Arc of Ruin',
  '875E': 'Facebreaker',
  '875P': 'Pit Grit',
  '875Q': 'Knuckle Down',
  '875R': 'The Show Stopper',
  '875W': 'Haymaker',
  '876E': 'Swirlseed',
  '876P': 'Dream-Laden Bough',
  '876Q': 'Blooming Blows',
  '876R': 'Lilting Lullaby',
  '876W': 'Watch Out! Eep!',
  '887E': 'Skip \'n Slash',
  '887P': 'A Thousand Cuts',
  '887Q': 'Snip Snip!',
  '887R': 'Needlework',
  '887W': 'Hallowed Mist',
  '888E': 'Loyalty Program',
  '888P': 'Leverage',
  '888Q': 'Handshake',
  '888R': 'Hostile Takeover',
  '888W': 'Bailout',
  '893E': 'The Weirding',
  '893P': 'Spirit Abjuration',
  '893Q': 'Twofold Hex',
  '893R': 'Between Worlds',
  '893W': 'Across the Veil',
  '895E': 'Slipstream',
  '895P': 'Joy Unending',
  '895Q': 'Formless Blade',
  '895R': 'Apotheosis',
  '895W': 'Jubilant Veil',
  '897E': 'Footwork',
  '897P': 'Dauntless Instinct',
  '897Q': 'Ntofo Strikes',
  '897R': 'All Out',
  '897W': 'Path Maker',
  '901E': 'Flap, Flap, Flap',
  '901P': 'Dragon Practice',
  '901Q': 'Super Scorcher Breath',
  '901R': 'MMOOOMMMM!',
  '901W': 'Achooo!',
  '902E': 'Warm Hugs',
  '902P': 'Fired Up!',
  '902Q': 'Ultra Mega Fire Kick',
  '902R': 'Breath of Life',
  '902W': 'Cozy Campfire',
  '904E': 'Aureate Rush',
  '904P': 'Cultivation of War',
  '904Q': 'The Darkin Glaive',
  '904R': 'Grim Deliverance',
  '904W': 'Dreaded Return',
  '910E': 'Crushing Maw',
  '910P': 'Signature of the Visionary',
  '910Q': 'Molten Fissure',
  '910R': 'Wash Brush',
  '910W': 'Stirring Lights',
  '950E': 'Eviscerate',
  '950P': 'We Are More',
  '950Q': 'Darkin Daggers',
  '950R': 'Hounds\' Pursuit',
  '950W': 'The Call of the Pack'
}