import { iconSetQuartzLight, themeQuartz } from 'ag-grid-community'

export const pocketTheme = themeQuartz.withPart(iconSetQuartzLight).withParams({
  // oddRowBackgroundColor: 'var(--p2) / 60%',
  sidePanelBorder: true,
  // chromeBackgroundColor: "#654D4D",
  widgetContainerHorizontalPadding: 9,
  widgetContainerVerticalPadding: 5,
  backgroundColor: 'transparent',
  borderColor: 'transparent',
  borderRadius: '0.7rem',
  cellHorizontalPadding: 6,
  cellTextColor: 'var(--bc)',
  checkboxCheckedBackgroundColor: 'var(--neutral)/0.8',
  checkboxCheckedBorderColor: 'var(--neutral)',
  checkboxCheckedShapeColor: 'var(--p0)',
  checkboxIndeterminateBackgroundColor: '#1C3043',
  checkboxIndeterminateBorderColor: '#1F3A4F',
  checkboxIndeterminateShapeColor: 'var(--p0)',
  checkboxUncheckedBackgroundColor: 'transparent',
  checkboxUncheckedBorderColor: 'var(--neutral)',
  columnBorder: false,
  columnHoverColor: 'color-mix(in oklch, var(--p2) 30%, transparent)',
  fontFamily: 'var(--font-sans), system ui',
  fontSize: '12px',
  headerBackgroundColor: 'transparent',
  headerFontWeight: 500,
  headerTextColor: 'var(--bc)/0.8',
  headerVerticalPaddingScale: 0.6,
  rangeSelectionBorderStyle: 'none',
  rowBorder: true,
  rowHoverColor: 'transparent',
  rowVerticalPaddingScale: 1.1,
  selectCellBorder: true,
  selectedRowBackgroundColor: 'transparent',
  tooltipBackgroundColor: 'var(--neutral)',
  tooltipBorder: false,
  tooltipTextColor: 'var(--nc)',
  wrapperBorder: false,
  wrapperBorderRadius: '0.7rem',
})
