/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
<<<<<<< HEAD
<<<<<<< HEAD
=======
    ' pushArray': typeof import('./utils/ pushArray.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    ' pushArray': typeof import('./utils/ pushArray.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
    About: typeof import('./pages/About.vue')['default']
    Accordion: typeof import('./components/base/accordion/Accordion.vue')['default']
    AccordionContent: typeof import('./components/base/accordion/AccordionContent.vue')['default']
    AccordionItem: typeof import('./components/base/accordion/AccordionItem.vue')['default']
    AccordionTrigger: typeof import('./components/base/accordion/AccordionTrigger.vue')['default']
    AccountSettings: typeof import('./components/settings/AccountSettings.vue')['default']
    AppearanceSettings: typeof import('./components/settings/AppearanceSettings.vue')['default']
    Archive: typeof import('./pages/Archive.vue')['default']
    Avatar: typeof import('./components/base/avatar/Avatar.vue')['default']
    AvatarFallback: typeof import('./components/base/avatar/AvatarFallback.vue')['default']
    AvatarImage: typeof import('./components/base/avatar/AvatarImage.vue')['default']
    Badge: typeof import('./components/base/badge/Badge.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    BarChart: typeof import('./components/base/chart-bar/BarChart.vue')['default']
<<<<<<< HEAD
=======
    BooleanDisplay: typeof import('./components/layout/utility/BooleanDisplay.vue')['default']
>>>>>>> fcc65b9c (update 38 files and delete 54 files)
    BottomSvg: typeof import('./components/ui/role/BottomSvg.vue')['default']
=======
    BooleanDisplay: typeof import('./components/layout/utility/BooleanDisplay.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    BarChart: typeof import('./components/base/chart-bar/BarChart.vue')['default']
    BooleanDisplay: typeof import('./components/layout/utility/BooleanDisplay.vue')['default']
    BottomSvg: typeof import('./components/ui/role/BottomSvg.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    BarChart: typeof import('./components/base/chart-bar/BarChart.vue')['default']
    BooleanDisplay: typeof import('./components/app/ui/utility/BooleanDisplay.vue')['default']
    BottomSvg: typeof import('./components/ui/role/BottomSvg.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
    BooleanDisplay: typeof import('./components/layout/utility/BooleanDisplay.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    BarChart: typeof import('./components/base/chart-bar/BarChart.vue')['default']
    BooleanDisplay: typeof import('./components/layout/utility/BooleanDisplay.vue')['default']
    BottomSvg: typeof import('./components/ui/role/BottomSvg.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
    Button: typeof import('./components/base/button/Button.vue')['default']
    Calculator: typeof import('./pages/Calculator.vue')['default']
    Card: typeof import('./components/base/card/Card.vue')['default']
    CardBack: typeof import('./components/pocket/pocket-cards/CardBack.vue')['default']
    CardChampion: typeof import('./components/pocket/pocket-cards/CardChampion.vue')['default']
    CardContent: typeof import('./components/base/card/CardContent.vue')['default']
    CardDescription: typeof import('./components/base/card/CardDescription.vue')['default']
    CardDrawer: typeof import('./components/drawer/CardDrawer.vue')['default']
    CardFooter: typeof import('./components/base/card/CardFooter.vue')['default']
    CardGlare: typeof import('./components/pocket/pocket-cards/CardGlare.vue')['default']
    CardHeader: typeof import('./components/base/card/CardHeader.vue')['default']
    CardItems: typeof import('./components/pocket/pocket-cards/CardItems.vue')['default']
    CardKeystone: typeof import('./components/pocket/pocket-cards/CardKeystone.vue')['default']
    CardRuneset: typeof import('./components/pocket/pocket-cards/CardRuneset.vue')['default']
    CardShards: typeof import('./components/pocket/pocket-cards/CardShards.vue')['default']
    CardShine: typeof import('./components/pocket/pocket-cards/CardShine.vue')['default']
    CardSpells: typeof import('./components/pocket/pocket-cards/CardSpells.vue')['default']
    CardTitle: typeof import('./components/base/card/CardTitle.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    ChampBar: typeof import('./components/home/ChampBar.vue')['default']
    Champion: typeof import('./components/pocket/champions/Champion.vue')['default']
=======
>>>>>>> f5f00c30 (update components.d.ts)
=======
    ChampBar: typeof import('./components/home/ChampBar.vue')['default']
    Champion: typeof import('./components/pocket/champions/Champion.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    ChampBar: typeof import('./components/home/ChampBar.vue')['default']
    ChampDonut: typeof import('./components/home/RoleDonut.vue')['default']
    Champion: typeof import('./components/pocket/champions/Champion.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
>>>>>>> f5f00c30 (update components.d.ts)
=======
    ChampBar: typeof import('./components/home/ChampBar.vue')['default']
    Champion: typeof import('./components/pocket/champions/Champion.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
    ChampionAbilities: typeof import('./components/pocket/champions/ChampionAbilities.vue')['default']
    ChampionList: typeof import('./components/pocket/champions/ChampionList.vue')['default']
    Champions: typeof import('./pages/Champions.vue')['default']
    ChampionSidebar: typeof import('./components/pocket/champions/ChampionSidebar.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
>>>>>>> 58212a1a (update 38 files and delete 54 files)
    ChampTabs: typeof import('./components/home/ChampTabs.vue')['default']
    ChartCrosshair: typeof import('./components/base/chart/ChartCrosshair.vue')['default']
    ChartLegend: typeof import('./components/base/chart/ChartLegend.vue')['default']
    ChartSingleTooltip: typeof import('./components/base/chart/ChartSingleTooltip.vue')['default']
    ChartTooltip: typeof import('./components/base/chart/ChartTooltip.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> f5f00c30 (update components.d.ts)
=======
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
=======
>>>>>>> 18878a61 (update 38 files and delete 54 files)
=======
>>>>>>> 90299573 (update 38 files and delete 54 files)
    ChampTabs: typeof import('./components/home/ChampTabs.vue')['default']
    ChartCrosshair: typeof import('./components/base/chart/ChartCrosshair.vue')['default']
    ChartLegend: typeof import('./components/base/chart/ChartLegend.vue')['default']
    ChartSingleTooltip: typeof import('./components/base/chart/ChartSingleTooltip.vue')['default']
    ChartTooltip: typeof import('./components/base/chart/ChartTooltip.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 90299573 (update 38 files and delete 54 files)
=======
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
>>>>>>> 18878a61 (update 38 files and delete 54 files)
=======
>>>>>>> f5f00c30 (update components.d.ts)
=======
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
>>>>>>> 90299573 (update 38 files and delete 54 files)
    Checkbox: typeof import('./components/base/checkbox/Checkbox.vue')['default']
    CmOptionItems: typeof import('./components/menu/options/cm-option-items.vue')['default']
    CmOptionName: typeof import('./components/menu/options/cm-option-name.vue')['default']
    CmOptionNotes: typeof import('./components/menu/options/cm-option-notes.vue')['default']
    CmOptionRunes: typeof import('./components/menu/options/cm-option-runes.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    Collapse: typeof import('./components/ui/Collapse.vue')['default']
    Collapse: typeof import('./components/ui/Collapse.vue')['default']
    Collapse: typeof import('./components/ui/Collapse.vue')['default']
    Collapse: typeof import('./components/ui/Collapse.vue')['default']
    Collapsible: typeof import('./components/base/collapsible/Collapsible.vue')['default']
    CollapsibleContent: typeof import('./components/base/collapsible/CollapsibleContent.vue')['default']
    CollapsibleTrigger: typeof import('./components/base/collapsible/CollapsibleTrigger.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
    ColorPicker: typeof import('./components/utility/ColorPicker.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> f5f00c30 (update components.d.ts)
    Collapse: typeof import('./components/layout/Collapse.vue')['default']
    Collapsible: typeof import('./components/base/collapsible/Collapsible.vue')['default']
    CollapsibleContent: typeof import('./components/base/collapsible/CollapsibleContent.vue')['default']
    CollapsibleTrigger: typeof import('./components/base/collapsible/CollapsibleTrigger.vue')['default']
    ColorPicker: typeof import('./components/layout/utility/color-picker.vue')['default']
<<<<<<< HEAD
>>>>>>> f5f00c30 (update components.d.ts)
=======
    Collapse: typeof import('./components/ui/Collapse.vue')['default']
    Collapsible: typeof import('./components/base/collapsible/Collapsible.vue')['default']
    CollapsibleContent: typeof import('./components/base/collapsible/CollapsibleContent.vue')['default']
    CollapsibleTrigger: typeof import('./components/base/collapsible/CollapsibleTrigger.vue')['default']
    ColorPicker: typeof import('./components/utility/ColorPicker.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    ColorPicker: typeof import('./components/utility/ColorPicker.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
=======
    Collapse: typeof import('./components/ui/Collapse.vue')['default']
    Collapsible: typeof import('./components/base/collapsible/Collapsible.vue')['default']
    CollapsibleContent: typeof import('./components/base/collapsible/CollapsibleContent.vue')['default']
    CollapsibleTrigger: typeof import('./components/base/collapsible/CollapsibleTrigger.vue')['default']
    ColorPicker: typeof import('./components/utility/ColorPicker.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
    ColorPicker: typeof import('./components/utility/ColorPicker.vue')['default']
>>>>>>> 18878a61 (update 38 files and delete 54 files)
=======
>>>>>>> f5f00c30 (update components.d.ts)
=======
    Collapse: typeof import('./components/ui/Collapse.vue')['default']
    Collapsible: typeof import('./components/base/collapsible/Collapsible.vue')['default']
    CollapsibleContent: typeof import('./components/base/collapsible/CollapsibleContent.vue')['default']
    CollapsibleTrigger: typeof import('./components/base/collapsible/CollapsibleTrigger.vue')['default']
    ColorPicker: typeof import('./components/utility/ColorPicker.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    ColorPicker: typeof import('./components/utility/ColorPicker.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
=======
    ColorPicker: typeof import('./components/layout/utility/color-picker.vue')['default']
>>>>>>> 3de7f5b3 (update components.d.ts)
=======
    ColorPicker: typeof import('./components/utility/ColorPicker.vue')['default']
>>>>>>> 2c930845 (update 38 files and delete 54 files)
    ColumnTools: typeof import('./components/table/panels/ColumnTools.vue')['default']
    Command: typeof import('./components/command/Command.vue')['default']
    CommandDialog: typeof import('./components/base/command/CommandDialog.vue')['default']
    CommandEmpty: typeof import('./components/base/command/CommandEmpty.vue')['default']
    CommandGroup: typeof import('./components/base/command/CommandGroup.vue')['default']
    CommandInput: typeof import('./components/base/command/CommandInput.vue')['default']
    CommandItem: typeof import('./components/base/command/CommandItem.vue')['default']
    CommandList: typeof import('./components/base/command/CommandList.vue')['default']
    CommandRoot: typeof import('./components/base/command/CommandRoot.vue')['default']
    CommandSeparator: typeof import('./components/base/command/CommandSeparator.vue')['default']
    CommandShortcut: typeof import('./components/base/command/CommandShortcut.vue')['default']
    ContextMenu: typeof import('./components/base/context-menu/ContextMenu.vue')['default']
    ContextMenuCheckboxItem: typeof import('./components/base/context-menu/ContextMenuCheckboxItem.vue')['default']
    ContextMenuContent: typeof import('./components/base/context-menu/ContextMenuContent.vue')['default']
    ContextMenuGroup: typeof import('./components/base/context-menu/ContextMenuGroup.vue')['default']
    ContextMenuItem: typeof import('./components/base/context-menu/ContextMenuItem.vue')['default']
    ContextMenuLabel: typeof import('./components/base/context-menu/ContextMenuLabel.vue')['default']
    ContextMenuPortal: typeof import('./components/base/context-menu/ContextMenuPortal.vue')['default']
    ContextMenuRadioGroup: typeof import('./components/base/context-menu/ContextMenuRadioGroup.vue')['default']
    ContextMenuRadioItem: typeof import('./components/base/context-menu/ContextMenuRadioItem.vue')['default']
    ContextMenuSeparator: typeof import('./components/base/context-menu/ContextMenuSeparator.vue')['default']
    ContextMenuShortcut: typeof import('./components/base/context-menu/ContextMenuShortcut.vue')['default']
    ContextMenuSub: typeof import('./components/base/context-menu/ContextMenuSub.vue')['default']
    ContextMenuSubContent: typeof import('./components/base/context-menu/ContextMenuSubContent.vue')['default']
    ContextMenuSubTrigger: typeof import('./components/base/context-menu/ContextMenuSubTrigger.vue')['default']
    ContextMenuTrigger: typeof import('./components/base/context-menu/ContextMenuTrigger.vue')['default']
    copy: typeof import('./components/menu/dropdown/dd-itemset copy.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    CreateIcon: typeof import('./components/utility/CreateIcon.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
    CreateIcon: typeof import('./components/layout/utility/create-icon.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    CreateIcon: typeof import('./components/utility/CreateIcon.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    CreateIcon: typeof import('./components/utility/CreateIcon.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
=======
    CreateIcon: typeof import('./components/utility/CreateIcon.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
    CreateIcon: typeof import('./components/utility/CreateIcon.vue')['default']
>>>>>>> 18878a61 (update 38 files and delete 54 files)
=======
    CreateIcon: typeof import('./components/layout/utility/create-icon.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    CreateIcon: typeof import('./components/utility/CreateIcon.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    CreateIcon: typeof import('./components/utility/CreateIcon.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
=======
    CreateIcon: typeof import('./components/layout/utility/create-icon.vue')['default']
>>>>>>> 3de7f5b3 (update components.d.ts)
=======
    CreateIcon: typeof import('./components/utility/CreateIcon.vue')['default']
>>>>>>> 2c930845 (update 38 files and delete 54 files)
    DashboardItems: typeof import('./components/pocket/dashboard/DashboardItems.vue')['default']
    DashboardOverview: typeof import('./components/pocket/dashboard/DashboardOverview.vue')['default']
    DashboardRunes: typeof import('./components/pocket/dashboard/DashboardRunes.vue')['default']
    DashboardSidebar: typeof import('./components/pocket/dashboard/DashboardSidebar.vue')['default']
    DashboardSpells: typeof import('./components/pocket/dashboard/DashboardSpells.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    Data: typeof import('./components/settings/data.vue')['default']
    DdCheckbox: typeof import('./components/menu/dropdown/dd-checkbox.vue')['default']
    DdItemset: typeof import('./components/menu/dropdown/dd-itemset.vue')['default']
=======
=======
    Data: typeof import('./components/settings/data.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
    DdCheckbox: typeof import('./components/menu/dropdown/dd-checkbox.vue')['default']
    DdItemset: typeof import('./components/menu/dropdown/dd-itemset.vue')['default']
    'DdItemset copy': typeof import('./components/menu/dropdown/dd-itemset copy.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    DdCheckbox: typeof import('./components/menu/dropdown/dd-checkbox.vue')['default']
    DdItemset: typeof import('./components/menu/dropdown/dd-itemset.vue')['default']
    'DdItemset copy': typeof import('./components/menu/dropdown/dd-itemset copy.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
    DdSelect: typeof import('./components/menu/dropdown/dd-select.vue')['default']
    DdSetType: typeof import('./components/menu/dropdown/dd-set-type.vue')['default']
    Dialog: typeof import('./components/base/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./components/base/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./components/base/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./components/base/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./components/base/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./components/base/dialog/DialogHeader.vue')['default']
    DialogScrollContent: typeof import('./components/base/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./components/base/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./components/base/dialog/DialogTrigger.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    DisplayCard: typeof import('./components/ui/DisplayCard.vue')['default']
    DividerStart: typeof import('./components/utility/DividerStart.vue')['default']
    DonutChart: typeof import('./components/base/chart-donut/DonutChart.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
    DisplayCard: typeof import('./components/layout/DisplayCard.vue')['default']
    DividerStart: typeof import('./components/layout/utility/DividerStart.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    DisplayCard: typeof import('./components/ui/DisplayCard.vue')['default']
    DividerStart: typeof import('./components/utility/DividerStart.vue')['default']
    DonutChart: typeof import('./components/base/chart-donut/DonutChart.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    DisplayCard: typeof import('./components/ui/DisplayCard.vue')['default']
    DividerStart: typeof import('./components/utility/DividerStart.vue')['default']
    DonutChart: typeof import('./components/base/chart-donut/DonutChart.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
=======
    DisplayCard: typeof import('./components/ui/DisplayCard.vue')['default']
    DividerStart: typeof import('./components/utility/DividerStart.vue')['default']
    DonutChart: typeof import('./components/base/chart-donut/DonutChart.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
    DisplayCard: typeof import('./components/ui/DisplayCard.vue')['default']
    DividerStart: typeof import('./components/utility/DividerStart.vue')['default']
    DonutChart: typeof import('./components/base/chart-donut/DonutChart.vue')['default']
>>>>>>> 18878a61 (update 38 files and delete 54 files)
=======
    DisplayCard: typeof import('./components/layout/DisplayCard.vue')['default']
    DividerStart: typeof import('./components/layout/utility/DividerStart.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    DisplayCard: typeof import('./components/ui/DisplayCard.vue')['default']
    DividerStart: typeof import('./components/utility/DividerStart.vue')['default']
    DonutChart: typeof import('./components/base/chart-donut/DonutChart.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    DisplayCard: typeof import('./components/ui/DisplayCard.vue')['default']
    DividerStart: typeof import('./components/utility/DividerStart.vue')['default']
    DonutChart: typeof import('./components/base/chart-donut/DonutChart.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
    Drawer: typeof import('./components/drawer/Drawer.vue')['default']
    DrawerContent: typeof import('./components/base/drawer/DrawerContent.vue')['default']
    DrawerDescription: typeof import('./components/base/drawer/DrawerDescription.vue')['default']
    DrawerFooter: typeof import('./components/base/drawer/DrawerFooter.vue')['default']
    DrawerHeader: typeof import('./components/base/drawer/DrawerHeader.vue')['default']
    DrawerOverlay: typeof import('./components/base/drawer/DrawerOverlay.vue')['default']
    DrawerRoot: typeof import('./components/base/drawer/DrawerRoot.vue')['default']
    DrawerTitle: typeof import('./components/base/drawer/DrawerTitle.vue')['default']
    Dropdown: typeof import('./components/menu/Dropdown.vue')['default']
    DropdownMenu: typeof import('./components/base/dropdown-menu/DropdownMenu.vue')['default']
    DropdownMenuCheckboxItem: typeof import('./components/base/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    DropdownMenuContent: typeof import('./components/base/dropdown-menu/DropdownMenuContent.vue')['default']
    DropdownMenuGroup: typeof import('./components/base/dropdown-menu/DropdownMenuGroup.vue')['default']
    DropdownMenuItem: typeof import('./components/base/dropdown-menu/DropdownMenuItem.vue')['default']
    DropdownMenuLabel: typeof import('./components/base/dropdown-menu/DropdownMenuLabel.vue')['default']
    DropdownMenuRadioGroup: typeof import('./components/base/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    DropdownMenuRadioItem: typeof import('./components/base/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    DropdownMenuSeparator: typeof import('./components/base/dropdown-menu/DropdownMenuSeparator.vue')['default']
    DropdownMenuShortcut: typeof import('./components/base/dropdown-menu/DropdownMenuShortcut.vue')['default']
    DropdownMenuSub: typeof import('./components/base/dropdown-menu/DropdownMenuSub.vue')['default']
    DropdownMenuSubContent: typeof import('./components/base/dropdown-menu/DropdownMenuSubContent.vue')['default']
    DropdownMenuSubTrigger: typeof import('./components/base/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    DropdownMenuTrigger: typeof import('./components/base/dropdown-menu/DropdownMenuTrigger.vue')['default']
    Eraser: typeof import('./components/buttons/Eraser.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    ErrorMessage: typeof import('./components/utility/ErrorMessage.vue')['default']
    ExpandIndicator: typeof import('./components/utility/ExpandIndicator.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
    ErrorMessage: typeof import('./components/layout/utility/ErrorMessage.vue')['default']
    ExpandIndicator: typeof import('./components/layout/utility/ExpandIndicator.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    ErrorMessage: typeof import('./components/utility/ErrorMessage.vue')['default']
    ExpandIndicator: typeof import('./components/utility/ExpandIndicator.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    ErrorMessage: typeof import('./components/utility/ErrorMessage.vue')['default']
    ExpandIndicator: typeof import('./components/utility/ExpandIndicator.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
=======
    ErrorMessage: typeof import('./components/utility/ErrorMessage.vue')['default']
    ExpandIndicator: typeof import('./components/utility/ExpandIndicator.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
    ErrorMessage: typeof import('./components/utility/ErrorMessage.vue')['default']
    ExpandIndicator: typeof import('./components/utility/ExpandIndicator.vue')['default']
>>>>>>> 18878a61 (update 38 files and delete 54 files)
=======
    ErrorMessage: typeof import('./components/layout/utility/ErrorMessage.vue')['default']
    ExpandIndicator: typeof import('./components/layout/utility/ExpandIndicator.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    ErrorMessage: typeof import('./components/utility/ErrorMessage.vue')['default']
    ExpandIndicator: typeof import('./components/utility/ExpandIndicator.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    ErrorMessage: typeof import('./components/utility/ErrorMessage.vue')['default']
    ExpandIndicator: typeof import('./components/utility/ExpandIndicator.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
    Export: typeof import('./components/buttons/Export.vue')['default']
    Favorites: typeof import('./pages/Favorites.vue')['default']
    FilterButton: typeof import('./components/buttons/FilterButton.vue')['default']
    FilterPanel: typeof import('./components/pocket/items/panels/FilterPanel.vue')['default']
    GeneralSettings: typeof import('./components/settings/GeneralSettings.vue')['default']
    GridChampions: typeof import('./components/table/GridChampions.vue')['default']
    GridCheckbox: typeof import('./components/table/GridCheckbox.vue')['default']
    GridCheckboxHeader: typeof import('./components/table/GridCheckboxHeader.vue')['default']
    GridDate: typeof import('./components/table/GridDate.vue')['default']
    GridItems: typeof import('./components/table/GridItems.vue')['default']
    GridName: typeof import('./components/table/GridName.vue')['default']
    GridNotes: typeof import('./components/table/GridNotes.vue')['default']
    GridRunes: typeof import('./components/table/GridRunes.vue')['default']
    GridTags: typeof import('./components/table/GridTags.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    Grow: typeof import('./components/utility/Grow.vue')['default']
    HeaderCard: typeof import('./components/ui/HeaderCard.vue')['default']
    Grow: typeof import('./components/utility/Grow.vue')['default']
    HeaderCard: typeof import('./components/ui/HeaderCard.vue')['default']
<<<<<<< HEAD
    Grow: typeof import('./components/utility/Grow.vue')['default']
    HeaderCard: typeof import('./components/ui/HeaderCard.vue')['default']
=======
    Grow: typeof import('./components/layout/utility/Grow.vue')['default']
    HeaderCard: typeof import('./components/layout/HeaderCard.vue')['default']
>>>>>>> 3de7f5b3 (update components.d.ts)
=======
    Grow: typeof import('./components/utility/Grow.vue')['default']
    HeaderCard: typeof import('./components/ui/HeaderCard.vue')['default']
>>>>>>> 2c930845 (update 38 files and delete 54 files)
    HeartIcons: typeof import('./components/buttons/HeartIcons.vue')['default']
    Hide: typeof import('./components/utility/Hide.vue')['default']
    History: typeof import('./components/app/History.vue')['default']
    Hide: typeof import('./components/utility/Hide.vue')['default']
    History: typeof import('./components/app/History.vue')['default']
    Home: typeof import('./pages/Home.vue')['default']
    HotkeySettings: typeof import('./components/settings/HotkeySettings.vue')['default']
    HvPocket: typeof import('./components/menu/hover/hv-pocket.vue')['default']
    Icon: typeof import('~icons/ic/on')['default']
    IconPicker: typeof import('./components/pocket/ui/IconPicker.vue')['default']
    IconRenderer: typeof import('./components/table/IconRenderer.vue')['default']
    InfoCard: typeof import('./components/ui/InfoCard.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
=======
    Grow: typeof import('./components/layout/utility/Grow.vue')['default']
    HeaderCard: typeof import('./components/layout/HeaderCard.vue')['default']
=======
    Grow: typeof import('./components/utility/Grow.vue')['default']
    HeaderCard: typeof import('./components/ui/HeaderCard.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    Grow: typeof import('./components/utility/Grow.vue')['default']
    HeaderCard: typeof import('./components/ui/HeaderCard.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
    HeartIcons: typeof import('./components/buttons/HeartIcons.vue')['default']
    Hide: typeof import('./components/utility/Hide.vue')['default']
    History: typeof import('./components/app/History.vue')['default']
    Home: typeof import('./pages/Home.vue')['default']
    HotkeySettings: typeof import('./components/settings/HotkeySettings.vue')['default']
    HvPocket: typeof import('./components/menu/hover/hv-pocket.vue')['default']
    Icon: typeof import('~icons/ic/on')['default']
    IconPicker: typeof import('./components/pocket/ui/IconPicker.vue')['default']
    IconRenderer: typeof import('./components/table/IconRenderer.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
    InfoCard: typeof import('./components/layout/InfoCard.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    InfoCard: typeof import('./components/ui/InfoCard.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    InfoCard: typeof import('./components/ui/InfoCard.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
=======
    InfoCard: typeof import('./components/ui/InfoCard.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
    InfoCard: typeof import('./components/ui/InfoCard.vue')['default']
>>>>>>> 18878a61 (update 38 files and delete 54 files)
=======
    Grow: typeof import('./components/layout/utility/Grow.vue')['default']
    HeaderCard: typeof import('./components/layout/HeaderCard.vue')['default']
=======
    Grow: typeof import('./components/utility/Grow.vue')['default']
    HeaderCard: typeof import('./components/ui/HeaderCard.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
>>>>>>> 90299573 (update 38 files and delete 54 files)
    HeartIcons: typeof import('./components/buttons/HeartIcons.vue')['default']
    Hide: typeof import('./components/utility/Hide.vue')['default']
    History: typeof import('./components/app/History.vue')['default']
    Hide: typeof import('./components/utility/Hide.vue')['default']
    History: typeof import('./components/app/History.vue')['default']
    Home: typeof import('./pages/Home.vue')['default']
    HotkeySettings: typeof import('./components/settings/HotkeySettings.vue')['default']
    HvPocket: typeof import('./components/menu/hover/hv-pocket.vue')['default']
    IconPicker: typeof import('./components/pocket/ui/IconPicker.vue')['default']
    IconRenderer: typeof import('./components/table/IconRenderer.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    InfoCard: typeof import('./components/layout/InfoCard.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    InfoCard: typeof import('./components/ui/InfoCard.vue')['default']
<<<<<<< HEAD
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    InfoCard: typeof import('./components/ui/InfoCard.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
=======
    InfoCard: typeof import('./components/layout/InfoCard.vue')['default']
>>>>>>> 3de7f5b3 (update components.d.ts)
=======
    InfoCard: typeof import('./components/ui/InfoCard.vue')['default']
>>>>>>> 2c930845 (update 38 files and delete 54 files)
    Input: typeof import('./components/base/input/Input.vue')['default']
    InputEditable: typeof import('./components/inputs/InputEditable.vue')['default']
    InputResizable: typeof import('./components/inputs/InputResizable.vue')['default']
    Item: typeof import('./components/pocket/items/Item.vue')['default']
    ItemList: typeof import('./components/pocket/items/ItemList.vue')['default']
    ItemPop: typeof import('./components/pocket/items/ItemPop.vue')['default']
    Items: typeof import('./pages/Items.vue')['default']
    ItemSetItems: typeof import('./components/pocket/items/ItemSetItems.vue')['default']
    ItemsetModel: typeof import('./components/pocket/items/ItemsetModel.vue')['default']
    ItemSets: typeof import('./components/pocket/items/ItemSets.vue')['default']
    ItemSlot: typeof import('./components/pocket/items/ItemSlot.vue')['default']
    ItemSlotSearch: typeof import('./components/pocket/items/ItemSlotSearch.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    JungleSvg: typeof import('./components/ui/role/JungleSvg.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
    JungleSvg: typeof import('./components/ui/role/JungleSvg.vue')['default']
    Keystone: typeof import('./components/pocket/runes/Keystone.vue')['default']
    Label: typeof import('./components/base/label/Label.vue')['default']
    Layout2: typeof import('./components/app/page-layouts/Layout2.vue')['default']
    Layout3: typeof import('./components/app/page-layouts/Layout3.vue')['default']
    LayoutSpacer: typeof import('./components/utility/LayoutSpacer.vue')['default']
<<<<<<< HEAD
    Layout2: typeof import('./components/app/page-layouts/Layout2.vue')['default']
    Layout3: typeof import('./components/app/page-layouts/Layout3.vue')['default']
    LayoutSpacer: typeof import('./components/utility/LayoutSpacer.vue')['default']
=======
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
    LgChampion: typeof import('./components/pocket/champions/lgChampion.vue')['default']
    LoadImg: typeof import('./components/placeholders/LoadImg.vue')['default']
    LoadRune: typeof import('./components/placeholders/LoadRune.vue')['default']
    MainMenubar: typeof import('./components/menubar/MainMenubar.vue')['default']
    MainSidebarFooter: typeof import('./components/sidebar/MainSidebarFooter.vue')['default']
<<<<<<< HEAD
    MatchCard: typeof import('./components/home/MatchCard.vue')['default']
=======
=======
    JungleSvg: typeof import('./components/ui/role/JungleSvg.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    JungleSvg: typeof import('./components/ui/role/JungleSvg.vue')['default']
>>>>>>> 18878a61 (update 38 files and delete 54 files)
    Keystone: typeof import('./components/pocket/runes/Keystone.vue')['default']
    Label: typeof import('./components/base/label/Label.vue')['default']
    Layout2: typeof import('./components/app/page-layouts/Layout2.vue')['default']
    Layout3: typeof import('./components/app/page-layouts/Layout3.vue')['default']
    LayoutSpacer: typeof import('./components/utility/LayoutSpacer.vue')['default']
    Layout2: typeof import('./components/app/page-layouts/Layout2.vue')['default']
    Layout3: typeof import('./components/app/page-layouts/Layout3.vue')['default']
    LayoutSpacer: typeof import('./components/utility/LayoutSpacer.vue')['default']
    LgChampion: typeof import('./components/pocket/champions/lgChampion.vue')['default']
    LoadImg: typeof import('./components/placeholders/LoadImg.vue')['default']
    LoadRune: typeof import('./components/placeholders/LoadRune.vue')['default']
    MainMenubar: typeof import('./components/menubar/MainMenubar.vue')['default']
    MainSidebarFooter: typeof import('./components/sidebar/MainSidebarFooter.vue')['default']
<<<<<<< HEAD
    MainSidebarHeader: typeof import('./components/layout/sidebar/MainSidebarHeader.vue')['default']
<<<<<<< HEAD
>>>>>>> f5f00c30 (update components.d.ts)
=======
=======
<<<<<<< HEAD
=======
    MainSidebarHeader: typeof import('./components/layout/sidebar/MainSidebarHeader.vue')['default']
>>>>>>> fcc65b9c (update 38 files and delete 54 files)
>>>>>>> 2c930845 (update 38 files and delete 54 files)
    MatchCard: typeof import('./components/home/MatchCard.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    MainSidebarHeader: typeof import('./components/sidebar/SidebarAccount.vue')['default']
    MatchCard: typeof import('./components/home/MatchCard.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
=======
    JungleSvg: typeof import('./components/ui/role/JungleSvg.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    JungleSvg: typeof import('./components/ui/role/JungleSvg.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
    Keystone: typeof import('./components/pocket/runes/Keystone.vue')['default']
    Label: typeof import('./components/base/label/Label.vue')['default']
    Layout2: typeof import('./components/app/page-layouts/Layout2.vue')['default']
    Layout3: typeof import('./components/app/page-layouts/Layout3.vue')['default']
    LayoutSpacer: typeof import('./components/utility/LayoutSpacer.vue')['default']
    Layout2: typeof import('./components/app/page-layouts/Layout2.vue')['default']
    Layout3: typeof import('./components/app/page-layouts/Layout3.vue')['default']
    LayoutSpacer: typeof import('./components/utility/LayoutSpacer.vue')['default']
    LgChampion: typeof import('./components/pocket/champions/lgChampion.vue')['default']
    LoadImg: typeof import('./components/placeholders/LoadImg.vue')['default']
    LoadRune: typeof import('./components/placeholders/LoadRune.vue')['default']
    MainMenubar: typeof import('./components/menubar/MainMenubar.vue')['default']
    MainSidebarFooter: typeof import('./components/sidebar/MainSidebarFooter.vue')['default']
    MainSidebarHeader: typeof import('./components/layout/sidebar/MainSidebarHeader.vue')['default']
<<<<<<< HEAD
>>>>>>> f5f00c30 (update components.d.ts)
=======
    MatchCard: typeof import('./components/home/MatchCard.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
    Menubar: typeof import('./components/base/menubar/Menubar.vue')['default']
    MenubarCheckboxItem: typeof import('./components/base/menubar/MenubarCheckboxItem.vue')['default']
    MenubarContent: typeof import('./components/base/menubar/MenubarContent.vue')['default']
    MenubarGroup: typeof import('./components/base/menubar/MenubarGroup.vue')['default']
    MenubarItem: typeof import('./components/base/menubar/MenubarItem.vue')['default']
    MenubarLabel: typeof import('./components/base/menubar/MenubarLabel.vue')['default']
    MenubarMenu: typeof import('./components/base/menubar/MenubarMenu.vue')['default']
    MenubarRadioGroup: typeof import('./components/base/menubar/MenubarRadioGroup.vue')['default']
    MenubarRadioItem: typeof import('./components/base/menubar/MenubarRadioItem.vue')['default']
    MenubarSeparator: typeof import('./components/base/menubar/MenubarSeparator.vue')['default']
    MenubarShortcut: typeof import('./components/base/menubar/MenubarShortcut.vue')['default']
    MenubarSub: typeof import('./components/base/menubar/MenubarSub.vue')['default']
    MenubarSubContent: typeof import('./components/base/menubar/MenubarSubContent.vue')['default']
    MenubarSubTrigger: typeof import('./components/base/menubar/MenubarSubTrigger.vue')['default']
    MenubarTrigger: typeof import('./components/base/menubar/MenubarTrigger.vue')['default']
    MenuItemButton: typeof import('./components/buttons/MenuItemButton.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    MidSvg: typeof import('./components/ui/role/MidSvg.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> f5f00c30 (update components.d.ts)
=======
    MidSvg: typeof import('./components/ui/role/MidSvg.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    MidSvg: typeof import('./components/ui/role/MidSvg.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
=======
    MidSvg: typeof import('./components/ui/role/MidSvg.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
    MidSvg: typeof import('./components/ui/role/MidSvg.vue')['default']
>>>>>>> 18878a61 (update 38 files and delete 54 files)
=======
>>>>>>> f5f00c30 (update components.d.ts)
=======
    MidSvg: typeof import('./components/ui/role/MidSvg.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    MidSvg: typeof import('./components/ui/role/MidSvg.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
    Modal: typeof import('./components/command/Modal.vue')['default']
    Motion: typeof import('@oku-ui/motion')['Motion']
    MotionPresence: typeof import('@oku-ui/motion')['MotionPresence']
    MoveButton: typeof import('./components/buttons/MoveButton.vue')['default']
    NavigationMenu: typeof import('./components/base/navigation-menu/NavigationMenu.vue')['default']
    NavigationMenuContent: typeof import('./components/base/navigation-menu/NavigationMenuContent.vue')['default']
    NavigationMenuIndicator: typeof import('./components/base/navigation-menu/NavigationMenuIndicator.vue')['default']
    NavigationMenuItem: typeof import('./components/base/navigation-menu/NavigationMenuItem.vue')['default']
    NavigationMenuLink: typeof import('./components/base/navigation-menu/NavigationMenuLink.vue')['default']
    NavigationMenuList: typeof import('./components/base/navigation-menu/NavigationMenuList.vue')['default']
    NavigationMenuTrigger: typeof import('./components/base/navigation-menu/NavigationMenuTrigger.vue')['default']
    NavigationMenuViewport: typeof import('./components/base/navigation-menu/NavigationMenuViewport.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    News: typeof import('./components/menubar/News.vue')['default']
    PageLayout: typeof import('./components/app/page-layouts/PageLayout.vue')['default']
    PageNav: typeof import('./components/app/page-layouts/PageNav.vue')['default']
    News: typeof import('./components/menubar/News.vue')['default']
    PageLayout: typeof import('./components/app/page-layouts/PageLayout.vue')['default']
    PageNav: typeof import('./components/app/page-layouts/PageNav.vue')['default']
    News: typeof import('./components/menubar/News.vue')['default']
    PageLayout: typeof import('./components/app/page-layouts/PageLayout.vue')['default']
    PageNav: typeof import('./components/app/page-layouts/PageNav.vue')['default']
    News: typeof import('./components/menubar/News.vue')['default']
    PageLayout: typeof import('./components/app/page-layouts/PageLayout.vue')['default']
    PageNav: typeof import('./components/app/page-layouts/PageNav.vue')['default']
    Placeholder: typeof import('./components/placeholders/placeholder.vue')['default']
    PlayerCard: typeof import('./components/home/PlayerCard.vue')['default']
    PlayerMatches: typeof import('./components/home/PlayerMatches.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> f5f00c30 (update components.d.ts)
    PageLayout: typeof import('./components/layout/page-layouts/PageLayout.vue')['default']
    PageNav: typeof import('./components/layout/page-layouts/PageNav.vue')['default']
    Placeholder: typeof import('./components/placeholders/placeholder.vue')['default']
    PlayerCard: typeof import('./components/home/PlayerCard.vue')['default']
<<<<<<< HEAD
>>>>>>> f5f00c30 (update components.d.ts)
=======
    News: typeof import('./components/menubar/News.vue')['default']
    PageLayout: typeof import('./components/app/page-layouts/PageLayout.vue')['default']
    PageNav: typeof import('./components/app/page-layouts/PageNav.vue')['default']
    Placeholder: typeof import('./components/placeholders/placeholder.vue')['default']
    PlayerCard: typeof import('./components/home/PlayerCard.vue')['default']
    PlayerMatches: typeof import('./components/home/PlayerMatches.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    PlayerMatches: typeof import('./components/home/PlayerMatches.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
=======
    News: typeof import('./components/menubar/News.vue')['default']
    PageLayout: typeof import('./components/app/page-layouts/PageLayout.vue')['default']
    PageNav: typeof import('./components/app/page-layouts/PageNav.vue')['default']
    Placeholder: typeof import('./components/placeholders/placeholder.vue')['default']
    PlayerCard: typeof import('./components/home/PlayerCard.vue')['default']
    PlayerMatches: typeof import('./components/home/PlayerMatches.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
    PlayerMatches: typeof import('./components/home/PlayerMatches.vue')['default']
>>>>>>> 18878a61 (update 38 files and delete 54 files)
=======
>>>>>>> f5f00c30 (update components.d.ts)
=======
    News: typeof import('./components/menubar/News.vue')['default']
    PageLayout: typeof import('./components/app/page-layouts/PageLayout.vue')['default']
    PageNav: typeof import('./components/app/page-layouts/PageNav.vue')['default']
    Placeholder: typeof import('./components/placeholders/placeholder.vue')['default']
    PlayerCard: typeof import('./components/home/PlayerCard.vue')['default']
    PlayerMatches: typeof import('./components/home/PlayerMatches.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    PlayerMatches: typeof import('./components/home/PlayerMatches.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
    Pocket: typeof import('./components/pocket/Pocket.vue')['default']
    PocketCard: typeof import('./components/pocket/pocket-cards/PocketCard.vue')['default']
    PocketCards: typeof import('./pages/PocketCards.vue')['default']
    PocketChampions: typeof import('./components/pocket/champions/PocketChampions.vue')['default']
    PocketDashboard: typeof import('./components/pocket/dashboard/PocketDashboard.vue')['default']
    PocketDrawer: typeof import('./components/drawer/PocketDrawer.vue')['default']
    PocketGrid: typeof import('./components/table/PocketGrid.vue')['default']
    PocketGrid: typeof import('./components/table/PocketGrid.vue')['default']
    PocketIcon: typeof import('./components/pocket/ui/PocketIcon.vue')['default']
    PocketItems: typeof import('./components/pocket/items/PocketItems.vue')['default']
    PocketMenu: typeof import('./components/menu/PocketMenu.vue')['default']
    PocketModal: typeof import('./components/drawer/PocketModal.vue')['default']
    PocketPreview: typeof import('./components/pocket/ui/PocketPreview.vue')['default']
    PocketRunes: typeof import('./components/pocket/runes/PocketRunes.vue')['default']
    PocketTables: typeof import('./pages/PocketTables.vue')['default']
    Popover: typeof import('./components/base/popover/Popover.vue')['default']
    PopoverContent: typeof import('./components/base/popover/PopoverContent.vue')['default']
    PopoverTrigger: typeof import('./components/base/popover/PopoverTrigger.vue')['default']
    pushArray: typeof import('./utils/ pushArray.vue')['default']
    QuickSearch: typeof import('./components/inputs/QuickSearch.vue')['default']
    RankCard: typeof import('./components/home/RankCard.vue')['default']
    ResetStore: typeof import('./utils/resetStore.vue')['default']
    ResizableHandle: typeof import('./components/base/resizable/ResizableHandle.vue')['default']
    ResizablePanelGroup: typeof import('./components/base/resizable/ResizablePanelGroup.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    ResizeHandle: typeof import('./components/utility/ResizeHandle.vue')['default']
    ResizeHandle: typeof import('./components/utility/ResizeHandle.vue')['default']
    ResizeHandle: typeof import('./components/utility/ResizeHandle.vue')['default']
    ResizeHandle: typeof import('./components/utility/ResizeHandle.vue')['default']
    Resources: typeof import('./components/home/Resources.vue')['default']
    RoleDonut: typeof import('./components/home/RoleDonut.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
    ResizeHandle: typeof import('./components/layout/utility/ResizeHandle.vue')['default']
    Resources: typeof import('./components/home/Resources.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    ResizeHandle: typeof import('./components/utility/ResizeHandle.vue')['default']
    Resources: typeof import('./components/home/Resources.vue')['default']
    RoleDonut: typeof import('./components/home/RoleDonut.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    RoleDonut: typeof import('./components/home/RoleDonut.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
=======
    ResizeHandle: typeof import('./components/utility/ResizeHandle.vue')['default']
    Resources: typeof import('./components/home/Resources.vue')['default']
    RoleDonut: typeof import('./components/home/RoleDonut.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
    RoleDonut: typeof import('./components/home/RoleDonut.vue')['default']
>>>>>>> 18878a61 (update 38 files and delete 54 files)
=======
    ResizeHandle: typeof import('./components/layout/utility/ResizeHandle.vue')['default']
    Resources: typeof import('./components/home/Resources.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    ResizeHandle: typeof import('./components/utility/ResizeHandle.vue')['default']
    Resources: typeof import('./components/home/Resources.vue')['default']
    RoleDonut: typeof import('./components/home/RoleDonut.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    RoleDonut: typeof import('./components/home/RoleDonut.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuneInfo: typeof import('./components/pocket/runes/RuneInfo.vue')['default']
    RunePop: typeof import('./components/pocket/runes/RunePop.vue')['default']
    Runes: typeof import('./pages/Runes.vue')['default']
    RuneSelect: typeof import('./components/pocket/runes/RuneSelect.vue')['default']
    RuneSets: typeof import('./components/pocket/runes/RuneSets.vue')['default']
    RuneShards: typeof import('./components/pocket/runes/RuneShards.vue')['default']
    ScrollArea: typeof import('./components/base/scroll-area/ScrollArea.vue')['default']
    ScrollBar: typeof import('./components/base/scroll-area/ScrollBar.vue')['default']
    SearchBox: typeof import('./components/inputs/SearchBox.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    SearchButton: typeof import('./components/menubar/SearchButton.vue')['default']
    SearchButton: typeof import('./components/menubar/SearchButton.vue')['default']
    SearchButton: typeof import('./components/menubar/SearchButton.vue')['default']
    SearchButton: typeof import('./components/menubar/SearchButton.vue')['default']
    SelectedChampions: typeof import('./components/pocket/champions/SelectedChampions.vue')['default']
    Separator: typeof import('./components/base/separator/Separator.vue')['default']
    Settings: typeof import('./pages/Settings.vue')['default']
    SettingsDropdown: typeof import('./components/menubar/SettingsDropdown.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> f5f00c30 (update components.d.ts)
    SearchButton: typeof import('./components/layout/ui/SearchButton.vue')['default']
    SelectedChampions: typeof import('./components/pocket/champions/SelectedChampions.vue')['default']
    Separator: typeof import('./components/base/separator/Separator.vue')['default']
    Settings: typeof import('./pages/Settings.vue')['default']
    SettingsDropdown: typeof import('./components/layout/ui/SettingsDropdown.vue')['default']
<<<<<<< HEAD
>>>>>>> f5f00c30 (update components.d.ts)
=======
    SearchButton: typeof import('./components/menubar/SearchButton.vue')['default']
    SelectedChampions: typeof import('./components/pocket/champions/SelectedChampions.vue')['default']
    Separator: typeof import('./components/base/separator/Separator.vue')['default']
    Settings: typeof import('./pages/Settings.vue')['default']
    SettingsDropdown: typeof import('./components/menubar/SettingsDropdown.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    SettingsDropdown: typeof import('./components/menubar/SettingsDropdown.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
=======
    SearchButton: typeof import('./components/menubar/SearchButton.vue')['default']
    SelectedChampions: typeof import('./components/pocket/champions/SelectedChampions.vue')['default']
    Separator: typeof import('./components/base/separator/Separator.vue')['default']
    Settings: typeof import('./pages/Settings.vue')['default']
    SettingsDropdown: typeof import('./components/menubar/SettingsDropdown.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
    SettingsDropdown: typeof import('./components/menubar/SettingsDropdown.vue')['default']
>>>>>>> 18878a61 (update 38 files and delete 54 files)
=======
>>>>>>> f5f00c30 (update components.d.ts)
=======
    SearchButton: typeof import('./components/menubar/SearchButton.vue')['default']
    SelectedChampions: typeof import('./components/pocket/champions/SelectedChampions.vue')['default']
    Separator: typeof import('./components/base/separator/Separator.vue')['default']
    Settings: typeof import('./pages/Settings.vue')['default']
    SettingsDropdown: typeof import('./components/menubar/SettingsDropdown.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    SettingsDropdown: typeof import('./components/menubar/SettingsDropdown.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
    ShadowedPlaceholder: typeof import('./components/placeholders/ShadowedPlaceholder.vue')['default']
    Sheet: typeof import('./components/base/sheet/Sheet.vue')['default']
    SheetClose: typeof import('./components/base/sheet/SheetClose.vue')['default']
    SheetContent: typeof import('./components/base/sheet/SheetContent.vue')['default']
    SheetDescription: typeof import('./components/base/sheet/SheetDescription.vue')['default']
    SheetFooter: typeof import('./components/base/sheet/SheetFooter.vue')['default']
    SheetHeader: typeof import('./components/base/sheet/SheetHeader.vue')['default']
    SheetTitle: typeof import('./components/base/sheet/SheetTitle.vue')['default']
    SheetTrigger: typeof import('./components/base/sheet/SheetTrigger.vue')['default']
    Shortcut: typeof import('./components/buttons/Shortcut.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    Shortkey: typeof import('./components/utility/Shortkey.vue')['default']
    Shortkeys: typeof import('./components/app/Shortkeys.vue')['default']
    Shortkey: typeof import('./components/utility/Shortkey.vue')['default']
    Shortkeys: typeof import('./components/app/Shortkeys.vue')['default']
    Shortkey: typeof import('./components/utility/Shortkey.vue')['default']
    Shortkeys: typeof import('./components/app/Shortkeys.vue')['default']
    Shortkey: typeof import('./components/utility/Shortkey.vue')['default']
    Shortkeys: typeof import('./components/app/Shortkeys.vue')['default']
    Sidebar: typeof import('./components/base/sidebar/Sidebar.vue')['default']
    SidebarAccount: typeof import('./components/sidebar/SidebarAccount.vue')['default']
    SidebarBrowse: typeof import('./components/sidebar/SidebarBrowse.vue')['default']
    SidebarAccount: typeof import('./components/sidebar/SidebarAccount.vue')['default']
    SidebarBrowse: typeof import('./components/sidebar/SidebarBrowse.vue')['default']
    SidebarContent: typeof import('./components/base/sidebar/SidebarContent.vue')['default']
    SidebarElse: typeof import('./components/sidebar/SidebarElse.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
    Shortkey: typeof import('./components/layout/utility/Shortkey.vue')['default']
    Shortkeys: typeof import('./components/layout/app/Shortkeys.vue')['default']
=======
    Shortkey: typeof import('./components/utility/Shortkey.vue')['default']
    Shortkeys: typeof import('./components/app/Shortkeys.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    Shortkey: typeof import('./components/utility/Shortkey.vue')['default']
    Shortkeys: typeof import('./components/app/Shortkeys.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
    Sidebar: typeof import('./components/base/sidebar/Sidebar.vue')['default']
    SidebarAccount: typeof import('./components/sidebar/SidebarAccount.vue')['default']
    SidebarBrowse: typeof import('./components/sidebar/SidebarBrowse.vue')['default']
    SidebarContent: typeof import('./components/base/sidebar/SidebarContent.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
    SidebarElse: typeof import('./components/layout/sidebar/SidebarElse.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    SidebarElse: typeof import('./components/sidebar/SidebarElse.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    SidebarElse: typeof import('./components/sidebar/SidebarElse.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
=======
    SidebarElse: typeof import('./components/sidebar/SidebarElse.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
    SidebarElse: typeof import('./components/sidebar/SidebarElse.vue')['default']
>>>>>>> 18878a61 (update 38 files and delete 54 files)
=======
    Shortkey: typeof import('./components/layout/utility/Shortkey.vue')['default']
    Shortkeys: typeof import('./components/layout/app/Shortkeys.vue')['default']
=======
    Shortkey: typeof import('./components/utility/Shortkey.vue')['default']
    Shortkeys: typeof import('./components/app/Shortkeys.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
    Sidebar: typeof import('./components/base/sidebar/Sidebar.vue')['default']
    SidebarAccount: typeof import('./components/sidebar/SidebarAccount.vue')['default']
    SidebarBrowse: typeof import('./components/sidebar/SidebarBrowse.vue')['default']
    SidebarContent: typeof import('./components/base/sidebar/SidebarContent.vue')['default']
<<<<<<< HEAD
    SidebarElse: typeof import('./components/layout/sidebar/SidebarElse.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    SidebarElse: typeof import('./components/sidebar/SidebarElse.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    SidebarElse: typeof import('./components/sidebar/SidebarElse.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
    SidebarFooter: typeof import('./components/base/sidebar/SidebarFooter.vue')['default']
    SidebarGroup: typeof import('./components/base/sidebar/SidebarGroup.vue')['default']
    SidebarGroupAction: typeof import('./components/base/sidebar/SidebarGroupAction.vue')['default']
    SidebarGroupContent: typeof import('./components/base/sidebar/SidebarGroupContent.vue')['default']
    SidebarGroupLabel: typeof import('./components/base/sidebar/SidebarGroupLabel.vue')['default']
    SidebarHeader: typeof import('./components/base/sidebar/SidebarHeader.vue')['default']
    SidebarInput: typeof import('./components/base/sidebar/SidebarInput.vue')['default']
    SidebarInset: typeof import('./components/base/sidebar/SidebarInset.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    SidebarLink: typeof import('./components/sidebar/SidebarLink.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
    SidebarLink: typeof import('./components/layout/sidebar/SidebarLink.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    SidebarLink: typeof import('./components/sidebar/SidebarLink.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    SidebarLink: typeof import('./components/sidebar/SidebarLink.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
=======
    SidebarLink: typeof import('./components/sidebar/SidebarLink.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
    SidebarLink: typeof import('./components/sidebar/SidebarLink.vue')['default']
>>>>>>> 18878a61 (update 38 files and delete 54 files)
=======
    SidebarLink: typeof import('./components/layout/sidebar/SidebarLink.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    SidebarLink: typeof import('./components/sidebar/SidebarLink.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    SidebarLink: typeof import('./components/sidebar/SidebarLink.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
    SidebarMenu: typeof import('./components/base/sidebar/SidebarMenu.vue')['default']
    SidebarMenuAction: typeof import('./components/base/sidebar/SidebarMenuAction.vue')['default']
    SidebarMenuBadge: typeof import('./components/base/sidebar/SidebarMenuBadge.vue')['default']
    SidebarMenuButton: typeof import('./components/base/sidebar/SidebarMenuButton.vue')['default']
    SidebarMenuButtonChild: typeof import('./components/base/sidebar/SidebarMenuButtonChild.vue')['default']
    SidebarMenuItem: typeof import('./components/base/sidebar/SidebarMenuItem.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    SidebarMenuLoves: typeof import('./components/sidebar/SidebarMenuLoves.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
    SidebarMenuLoves: typeof import('./components/layout/sidebar/SidebarMenuLoves.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    SidebarMenuLoves: typeof import('./components/sidebar/SidebarMenuLoves.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    SidebarMenuLoves: typeof import('./components/sidebar/SidebarMenuLoves.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
=======
    SidebarMenuLoves: typeof import('./components/sidebar/SidebarMenuLoves.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
    SidebarMenuLoves: typeof import('./components/sidebar/SidebarMenuLoves.vue')['default']
>>>>>>> 18878a61 (update 38 files and delete 54 files)
=======
    SidebarMenuLoves: typeof import('./components/layout/sidebar/SidebarMenuLoves.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    SidebarMenuLoves: typeof import('./components/sidebar/SidebarMenuLoves.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    SidebarMenuLoves: typeof import('./components/sidebar/SidebarMenuLoves.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
    SidebarMenuSkeleton: typeof import('./components/base/sidebar/SidebarMenuSkeleton.vue')['default']
    SidebarMenuSub: typeof import('./components/base/sidebar/SidebarMenuSub.vue')['default']
    SidebarMenuSubButton: typeof import('./components/base/sidebar/SidebarMenuSubButton.vue')['default']
    SidebarMenuSubItem: typeof import('./components/base/sidebar/SidebarMenuSubItem.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    SidebarPocketDisplays: typeof import('./components/sidebar/SidebarPocketDisplays.vue')['default']
    SidebarPockets: typeof import('./components/sidebar/SidebarPockets.vue')['default']
    SidebarPocketUtilities: typeof import('./components/sidebar/SidebarPocketUtilities.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
    SidebarPocketDisplays: typeof import('./components/layout/sidebar/SidebarPocketDisplays.vue')['default']
    SidebarPockets: typeof import('./components/layout/sidebar/SidebarPockets.vue')['default']
    SidebarPocketUtilities: typeof import('./components/layout/sidebar/SidebarPocketUtilities.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    SidebarPocketDisplays: typeof import('./components/sidebar/SidebarPocketDisplays.vue')['default']
    SidebarPockets: typeof import('./components/sidebar/SidebarPockets.vue')['default']
    SidebarPocketUtilities: typeof import('./components/sidebar/SidebarPocketUtilities.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    SidebarPocketDisplays: typeof import('./components/sidebar/SidebarPocketDisplays.vue')['default']
    SidebarPockets: typeof import('./components/sidebar/SidebarPockets.vue')['default']
    SidebarPocketUtilities: typeof import('./components/sidebar/SidebarPocketUtilities.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
=======
    SidebarPocketDisplays: typeof import('./components/sidebar/SidebarPocketDisplays.vue')['default']
    SidebarPockets: typeof import('./components/sidebar/SidebarPockets.vue')['default']
    SidebarPocketUtilities: typeof import('./components/sidebar/SidebarPocketUtilities.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
    SidebarPocketDisplays: typeof import('./components/sidebar/SidebarPocketDisplays.vue')['default']
    SidebarPockets: typeof import('./components/sidebar/SidebarPockets.vue')['default']
    SidebarPocketUtilities: typeof import('./components/sidebar/SidebarPocketUtilities.vue')['default']
>>>>>>> 18878a61 (update 38 files and delete 54 files)
=======
    SidebarPocketDisplays: typeof import('./components/layout/sidebar/SidebarPocketDisplays.vue')['default']
    SidebarPockets: typeof import('./components/layout/sidebar/SidebarPockets.vue')['default']
    SidebarPocketUtilities: typeof import('./components/layout/sidebar/SidebarPocketUtilities.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    SidebarPocketDisplays: typeof import('./components/sidebar/SidebarPocketDisplays.vue')['default']
    SidebarPockets: typeof import('./components/sidebar/SidebarPockets.vue')['default']
    SidebarPocketUtilities: typeof import('./components/sidebar/SidebarPocketUtilities.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    SidebarPocketDisplays: typeof import('./components/sidebar/SidebarPocketDisplays.vue')['default']
    SidebarPockets: typeof import('./components/sidebar/SidebarPockets.vue')['default']
    SidebarPocketUtilities: typeof import('./components/sidebar/SidebarPocketUtilities.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
    SidebarProvider: typeof import('./components/base/sidebar/SidebarProvider.vue')['default']
    SidebarRail: typeof import('./components/base/sidebar/SidebarRail.vue')['default']
    SidebarSeparator: typeof import('./components/base/sidebar/SidebarSeparator.vue')['default']
    SidebarTrigger: typeof import('./components/base/sidebar/SidebarTrigger.vue')['default']
    Skeleton: typeof import('./components/base/skeleton/Skeleton.vue')['default']
    SlideMenu: typeof import('./components/menu/SlideMenu.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    SmallLogo: typeof import('./components/ui/SmallLogo.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
    SmallLogo: typeof import('./components/layout/ui/SmallLogo.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    SmallLogo: typeof import('./components/ui/SmallLogo.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    SmallLogo: typeof import('./components/ui/SmallLogo.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
=======
    SmallLogo: typeof import('./components/ui/SmallLogo.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
    SmallLogo: typeof import('./components/ui/SmallLogo.vue')['default']
>>>>>>> 18878a61 (update 38 files and delete 54 files)
=======
    SmallLogo: typeof import('./components/layout/ui/SmallLogo.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    SmallLogo: typeof import('./components/ui/SmallLogo.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    SmallLogo: typeof import('./components/ui/SmallLogo.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
    SmItem: typeof import('./components/pocket/items/smItem.vue')['default']
    Sonner: typeof import('./components/base/sonner/Sonner.vue')['default']
    SpellPicker: typeof import('./components/pocket/spells/SpellPicker.vue')['default']
    Spells: typeof import('./pages/Spells.vue')['default']
    StatFilters: typeof import('./components/pocket/items/panels/StatFilters.vue')['default']
    StorageSettings: typeof import('./components/settings/StorageSettings.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    SupportSvg: typeof import('./components/ui/role/SupportSvg.vue')['default']
    Switch: typeof import('./components/base/switch/Switch.vue')['default']
=======
>>>>>>> f5f00c30 (update components.d.ts)
=======
    SupportSvg: typeof import('./components/ui/role/SupportSvg.vue')['default']
    Switch: typeof import('./components/base/switch/Switch.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    Support: typeof import('./components/ui/role/support.vue')['default']
    SupportSvg: typeof import('./components/ui/role/SupportSvg.vue')['default']
    Switch: typeof import('./components/base/switch/Switch.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
>>>>>>> f5f00c30 (update components.d.ts)
=======
    SupportSvg: typeof import('./components/ui/role/SupportSvg.vue')['default']
    Switch: typeof import('./components/base/switch/Switch.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
    TabHandle: typeof import('./components/base/resizable/tab-handle.vue')['default']
    TableSearch: typeof import('./components/table/TableSearch.vue')['default']
    TableSearch: typeof import('./components/table/TableSearch.vue')['default']
    Tabs: typeof import('./components/base/tabs/Tabs.vue')['default']
    TabsContent: typeof import('./components/base/tabs/TabsContent.vue')['default']
    TabsList: typeof import('./components/base/tabs/TabsList.vue')['default']
    TabsTrigger: typeof import('./components/base/tabs/TabsTrigger.vue')['default']
    TagsInput: typeof import('./components/base/tags-input/TagsInput.vue')['default']
    TagsInputInput: typeof import('./components/base/tags-input/TagsInputInput.vue')['default']
    TagsInputItem: typeof import('./components/base/tags-input/TagsInputItem.vue')['default']
    TagsInputItemDelete: typeof import('./components/base/tags-input/TagsInputItemDelete.vue')['default']
    TagsInputItemText: typeof import('./components/base/tags-input/TagsInputItemText.vue')['default']
    Target: typeof import('./components/placeholders/Target.vue')['default']
    TextureOutline: typeof import('./components/placeholders/TextureOutline.vue')['default']
    Thing: typeof import('./components/pocket/pocket-cards/thing.vue')['default']
    TierFilters: typeof import('./components/pocket/items/panels/TierFilters.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    Toasted: typeof import('./components/utility/toasted.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
    Toasted: typeof import('./components/layout/utility/toasted.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    Toasted: typeof import('./components/utility/toasted.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    Toasted: typeof import('./components/utility/toasted.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
=======
    Toasted: typeof import('./components/utility/toasted.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
    Toasted: typeof import('./components/utility/toasted.vue')['default']
>>>>>>> 18878a61 (update 38 files and delete 54 files)
=======
    Toasted: typeof import('./components/layout/utility/toasted.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    Toasted: typeof import('./components/utility/toasted.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    Toasted: typeof import('./components/utility/toasted.vue')['default']
>>>>>>> 90299573 (update 38 files and delete 54 files)
    ToggleButton: typeof import('./components/buttons/ToggleButton.vue')['default']
    ToggleStateButton: typeof import('./components/buttons/ToggleStateButton.vue')['default']
    Tooltip: typeof import('./components/menu/Tooltip.vue')['default']
    TooltipContent: typeof import('./components/base/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./components/base/tooltip/TooltipProvider.vue')['default']
    TooltipRoot: typeof import('./components/base/tooltip/TooltipRoot.vue')['default']
    TooltipTrigger: typeof import('./components/base/tooltip/TooltipTrigger.vue')['default']
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    TopSvg: typeof import('./components/ui/role/TopSvg.vue')['default']
    TopSvg: typeof import('./components/ui/role/TopSvg.vue')['default']
<<<<<<< HEAD
    TopSvg: typeof import('./components/ui/role/TopSvg.vue')['default']
    Trash: typeof import('./pages/Trash.vue')['default']
=======
=======
    TopSvg: typeof import('./components/ui/role/TopSvg.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
    TopSvg: typeof import('./components/ui/role/TopSvg.vue')['default']
>>>>>>> 58212a1a (update 38 files and delete 54 files)
=======
>>>>>>> 90299573 (update 38 files and delete 54 files)
    Trash: typeof import('./pages/Trash.vue')['default']
    WindowButtonCircles: typeof import('./components/layout/ui/WindowButtonCircles.vue')['default']
    WindowButtons: typeof import('./components/layout/ui/WindowButtons.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
=======
    TopSvg: typeof import('./components/ui/role/TopSvg.vue')['default']
    Trash: typeof import('./pages/Trash.vue')['default']
>>>>>>> 12d6db59 (update 38 files and delete 54 files)
=======
    Trash: typeof import('./pages/Trash.vue')['default']
    WindowButtonCircles: typeof import('./components/layout/ui/WindowButtonCircles.vue')['default']
    WindowButtons: typeof import('./components/layout/ui/WindowButtons.vue')['default']
>>>>>>> f5f00c30 (update components.d.ts)
  }
}
